### ISSUE TITLE
Siri cannot change LED color.

### ISSUE THREAD

**Issue by jeanofthedead** [bwp91/homebridge-govee#1]
I am able to control power on/off by using Siri on my iPhone and HomePods, but requests such "turn x light RED" do not work. I can change LED color through the Home app just fine, though.
...
iPhone XR, HomePods, Homebridge on RPi3B+.
...
Homebridge 1.2.2
...
homebridge-govee v1.0.2
...
Logs do not show my Govee requests.

**Comment by bwp91** [comment]
Hi, I will look into this and get back to you.
Sorry it’s taken a few days to initially reply!

**Comment by bwp91** [comment]
I have made some improvements to the connection so please try v1.1.1 and it should get this working.
If not, a couple of other things to try are:
* Turning on "Debug Logging" and "Request & Response Logging" in the plugin settings to see if any errors are shown in the logs
* Deleting the device from the Govee app, unplugging it for about 30 minutes, and then reconnecting it to the Govee app.

**Comment by jeanofthedead** [comment]
Thanks so much! I’ll test it out some more.

**Comment by bwp91** [comment]
The other thing i'd recommend is to read the things i have written on the main page of this plugin:

https://github.com/bwp91/homebridge-govee

especially the ⚠️ parts!
