### ISSUE TITLE
H6138 Device is not currently supported

### ISSUE THREAD

**Issue by AfricanHipp0** [bwp91/homebridge-govee#103]
### What issue do you have? Please be as thorough and explicit as possible.
```

[Govee] is not currently supported, do create a Github issue with the following info:
{"device":"B5:1F:A4:C1:38:58:4F:5D","deviceName":"Study","model":"H6138","httpInfo":{"device":"B5:1F:A4:C1:38:58:4F:5D","sku":"H6138","spec":"","versionHard":"1.00.01","versionSoft":"1.07.02","deviceName":"Study","deviceExt":{"deviceSettings":"{\"address\":\"A4:C1:38:58:4F:5D\",\"bleName\":\"ihoment_H6138_4F5D\",\"ic\":0,\"sku\":\"H6138\",\"device\":\"B5:1F:A4:C1:38:58:4F:5D\",\"deviceName\":\"Study\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.07.02\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}
```

### Details of your setup.
**Do you use Homebridge (with config-ui?) or HOOBS?** 
* Homebridge

**Which version of Homebridge/HOOBS do you have?**
* Homebridge  v1.3.4 

**Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?**
* homebridge-govee v4.4.1 

**Which Govee devices do you have that are causing issues? Please include product models if applicable.**
* Govee LED Strip H6138 which is practically the same as H6139 I thought?

Thanks!

**Comment by bwp91** [comment]
Literally doing this right now!

**Comment by AfricanHipp0** [comment]
Legend! Let me know if you need me to test anything for you! Sorry about the Pull request ignore anything from me, I was just having a play around

If you also want to hit me up on Discord for easier communication, feel free to do so! AfricanHipp0#2731

**Comment by bwp91** [comment]
If you update to 4.4.2-beta.4, the device should appear. Have you gotten the bluetooth working for different models?

The PR was correct, I wondered why you then closed it!

**Comment by AfricanHipp0** [comment]
Can confirm both my H6138 controllers are connecting to Homebridge! You legend

Ah sorry about that! I thought I f**ked it up, and didn't want to congest you with rubbish PR!

**Comment by bwp91** [comment]
Ah good!

> Govee LED Strip H6138 which is practically the same as H6139 I thought?

Probably are, I really don't know how there can be so many different models and how they can all _really_ be different. I'm adding the bluetooth only models on a case by case basis. It's slightly more exciting than scrolling through the app looking looking for ones I have missed!
