### ISSUE TITLE
Adding support to H6102 request

### ISSUE THREAD

**Issue by Gaflee** [bwp91/homebridge-govee#106]
* **Please explain your feature request in a one or two sentences.**

Could be possible for you to add support to "H6102" a Bluetooth led strip.

* **Is your feature request related to a problem? Please describe.**

no

* **Any particular Govee devices that this relates to?**

H6102

* **Anything else?**

no.. ur cool

**Comment by bwp91** [comment]
Hi @Gaflee 

Please install test version of the plugin, v4.6.1-beta.0.

Instructions on how to install the beta version here:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Once you've configured the device in the config, the accessory should then appear in Homebridge!
