### ISSUE TITLE
Please add support for H5082 

### ISSUE THREAD

**Issue by rekirk82** [bwp91/homebridge-govee#107]
### What issue do you have? Please be as thorough and explicit as possible.

Recieving this error while trying to use Govee H5082 devices

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

config-ui

* Which version of Homebridge/HOOBS do you have?

homebridge 1.3.4

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee v4.7.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H5082 dual plug smart plugs

### Please paste any relevant logs below.

[Dual Smart Plug #4] is not currently supported, do create a Github issue with the following info:

```json
{
   "device":"DA:F6:9C:04:A0:08:F9:F9",
   "deviceName":"Dual Smart Plug #4",
   "model":"H5082",
   "httpInfo":{
      "device":"DA:F6:9C:04:A0:08:F9:F9",
      "sku":"H5082",
      "spec":"0",
      "versionHard":"1.02.00",
      "versionSoft":"1.00.09",
      "deviceName":"Dual Smart Plug #4",
      "deviceExt":{
         "deviceSettings":"{"wifiName":"IoT_all_the_things_2G","address":"9C:04:A0:08:F9:FA","bleName":"ihoment_H5082_F9FA","topic":"GD/7ba3f046bb1189803d2526173e5d93d7","wifiMac":"9C:04:A0:08:F9:F9","pactType":1,"pactCode":1,"wifiSoftVersion":"1.00.09","wifiHardVersion":"1.02.00","ic":0,"secretCode":"wqa0AvGnyAo=","subDevices":{"sub_0":{"name":"Outlet 2"},"sub_1":{"name":"Outlet 1"}},"sku":"H5082","device":"DA:F6:9C:04:A0:08:F9:F9","deviceName":"Dual Smart Plug #4","versionHard":"1.02.00","versionSoft":"1.00.09"}",
         "lastDeviceData":"{"online":false}",
         "extResources":"{"skuUrl":"","headOnImg":"","headOffImg":"","ext":"","ic":0}"
      },
      "pactType":1,
      "pactCode":1,
      "goodsType":50
   },
   "isAPIDevice":false
}
```

**Comment by bwp91** [comment]
Hi @rekirk82 

Could I message you on Discord with regards to implementing this device type?
https://discord.gg/cMGhNtZ3tW

I have not yet implemented this type of device (dual outlet) into the plugin so I'm gonna need a lot more info compared to a typical light strip.

**Comment by rekirk82** [comment]
Sure. I’d really to utilize these new plugs with homebridge. Invite link to discord is not expired.

**Comment by bwp91** [comment]
Can you try this link for the main homebridge discord server?
https://discord.gg/bHjKNkN

**Comment by rekirk82** [comment]
Guess the problem was that I wasn’t logged into discord on my phone. I’ve joined both groups. Lmk what you need from me.

**Comment by bwp91** [comment]
I have sent you a dm on discord
