### ISSUE TITLE
Request for support of Govee Bluetooth Temp & Humidity Sensor - H5072

### ISSUE THREAD

**Issue by SemoTech** [bwp91/homebridge-govee#109]
* **Please explain your feature request in a one or two sentences.**

If possible, please add support for the **Govee Bluetooth Temp & Humidity Sensor Model H5072**

Currently using the H5072 device with the "[homebridge-plugin-govee](https://github.com/asednev/homebridge-plugin-govee#readme)", but was hoping to not have to use two separate plugins, and consolidate.  Especially since your plugin pulls the devices straight from my Govee account. 

If not possible, at least how does one suppress the warnings from the logs?

* **Here is the log from the plugin - Used Login U/P and API Key to get device automatically!**
```
[Govee] Disabling BLE client as no enabled devices configured.
[Govee] [Govee Temp & Humidity] is not currently supported, do create a Github issue with the following info:
{"device":"CE:40:A5:D2:F7:AC:18:2E","deviceName":"Govee Temp & Humidity","model":"H5072","httpInfo":{"device":"CE:40:A5:D2:F7:AC:18:2E","sku":"H5072","spec":"","versionHard":"1.00.01","versionSoft":"1.01.00","deviceName":"Govee Temp & Humidity","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":false,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":false,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":80,\"wifiLevel\":0,\"bleName\":\"GVH5072_146E\",\"address\":\"A5:D2:F7:AC:18:2E\",\"secretCode\":\"86F0310BDC268741\",\"sku\":\"H5072\",\"device\":\"CE:40:A5:D2:F7:AC:18:2E\",\"deviceName\":\"Govee Temp & Humidity\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.01.00\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}
```

* **Any particular Govee devices that this relates to?**
Govee Bluetooth Temp & Humidity Sensor - Model H5072

* **Anything else?**
Just a thank you, in advance :-)

**Comment by bwp91** [comment]
Hi @SemoTech 

These bluetooth-only temp/humidity sensors don't provide any data from govee http and so the plugin can't do anything with them.

You can update to beta version 4.7.1-beta.1 and this will remove the logging about the unsupported device.

The other plugin reads the data directly from the device via bluetooth, something this plugin does not do for any device.

**Comment by SemoTech** [comment]
Hi @bwp91 and thanks for the info.  Is there any reason your plugin can't also do the same thing (read directly from the device) as the other one? Just curious. Meantime I have just updated to the new v4.8.0, and that cleaned up the logs.  Thanks again.

**Comment by bwp91** [comment]
Bluetooth implementation is tricky and is not my strong point.
Anything to do would be effectively copying the code from the other plugin which is something I don’t want to do.

**Comment by SemoTech** [comment]
Gotcha Ben, makes sense.  Appreciate the explanation.  I'll keep running with both plugins.
