### ISSUE TITLE
Strange warning during plugin installation

### ISSUE THREAD

**Issue by SemoTech** [bwp91/homebridge-govee#110]
### What issue do you have? Please be as thorough and explicit as possible.
Hello, I got a strange warning message while installing the plugin.  Should this be of concern?
Thanks. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
  -> Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
-> v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
-> Raspberry Pi
-> Node.js = v14.17.6
-> NPM = v6.14.15

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
->  homebridge-govee v4.8.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
None, this is about an installation log warning. 

* Relevant Screenshot is below:

![2021-08-28_12-07-43](https://user-images.githubusercontent.com/1452100/131783669-44a9cd3b-bed2-4044-9788-a11f023a973a.png)

**Comment by bwp91** [comment]
This is nothing to worry about, anyone who installs the plugin will see this, and can be ignored!

**Comment by SemoTech** [comment]
> This is nothing to worry about, anyone who installs the plugin will see this, and can be ignored!

Sounds good Ben, just making sure :-) Thank you.
