### ISSUE TITLE
Please add H6147 Bluetooth LED strip support :)

### ISSUE THREAD

**Issue by JSpielz** [bwp91/homebridge-govee#111]
### What issue do you have? Please be as thorough and explicit as possible.

Homebridge throws an error saying my Govee light is not compatible and requests I submit it to this Github. Logs are below. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1) Homebridge UI-X (homebridge-config-ui-x v4.41.2)

* Which version of Homebridge/HOOBS do you have?

This is what it says in homebridge: "Up To Date v1.3.4"

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

I am running homebridge on MacOS Monterey Beta 6 (latest), npm 6.14.15 (latest), node v14.17.6 (latest)

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee v4.8.0. I just installed it.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6147 Bluetooth LED strips. 

### Please paste any relevant logs below.

```

Starting to advertise 'Homebridge ECBC 3611' using bonjour-hap backend!
[9/5/2021, 2:12:30 AM] Homebridge v1.3.4 (Homebridge ECBC) is running on port 51022.
[9/5/2021, 2:12:31 AM] [Govee] Disabling BLE client as no enabled devices configured.
[9/5/2021, 2:12:31 AM] [Govee] [Room] is not currently supported, do create a Github issue with the following info:
{"device":"E0:F1:A4:C1:38:C3:05:68","deviceName":"Room","model":"H6147","httpInfo":{"device":"E0:F1:A4:C1:38:C3:05:68","sku":"H6147","spec":"","versionHard":"1.00.01","versionSoft":"1.06.04","deviceName":"Room","deviceExt":{"deviceSettings":"{\"address\":\"A4:C1:38:C3:05:68\",\"bleName\":\"ihoment_H6147_0568\",\"pactType\":1,\"pactCode\":1,\"ic\":60,\"sku\":\"H6147\",\"device\":\"E0:F1:A4:C1:38:C3:05:68\",\"deviceName\":\"Room\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.06.04\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/c9f204ccc5a54ff52abd7c648d365f73-add_list_type_device_6147.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png\",\"ext\":\"\",\"ic\":60}"},"pactType":1,"pactCode":1,"goodsType":13},"isAPIDevice":false}
[9/5/2021, 2:12:31 AM] [Govee] ✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91

```

**Comment by bwp91** [comment]
Hi, I've added this model to the list of supported devices in v4.9.0 of the plugin :)
