### ISSUE TITLE
Please add support for H5053 Temp/Humidity Sensors

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-govee#112]
* **Please explain your feature request in a one or two sentences.**
Please add support for H5053 Temp/Humidity Sensors

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**
H5053

* **Anything else?**
Error from Homebridge:

[9/5/2021, 6:54:17 PM] [Govee] [Attic 2] is not currently supported, do create a Github issue with the following info:
{"device":"7ca6b01a1a91030361","deviceName":"Attic 2","model":"H5053","httpInfo":{"device":"7ca6b01a1a91030361","sku":"H5053","spec":"","versionHard":"1.00.01","versionSoft":"1.00.07","deviceName":"Attic 2","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":true,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":true,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":90,\"wifiLevel\":0,\"header\":\"3\",\"gatewayVersionHard\":\"1.00.00\",\"gatewayVersionSoft\":\"1.01.08\",\"sku\":\"H5053\",\"device\":\"7ca6b01a1a91030361\",\"deviceName\":\"Attic 2\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.00.07\"}","lastDeviceData":"{\"online\":true,\"gwonline\":true,\"tem\":3955,\"hum\":2456,\"lastTime\":1630893180000,\"avgDayTem\":3955,\"avgDayHum\":2456}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/40a92d402e7eff4c685a056a86ef8342-add_list_type_device_5053.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}

[9/5/2021, 6:54:17 PM] [Govee] [Garage 2] is not currently supported, do create a Github issue with the following info:
{"device":"7ca6b01a1a91030350","deviceName":"Garage 2","model":"H5053","httpInfo":{"device":"7ca6b01a1a91030350","sku":"H5053","spec":"","versionHard":"1.00.01","versionSoft":"1.00.07","deviceName":"Garage 2","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":true,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":true,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":90,\"wifiLevel\":0,\"header\":\"2\",\"gatewayVersionHard\":\"1.00.00\",\"gatewayVersionSoft\":\"1.01.08\",\"sku\":\"H5053\",\"device\":\"7ca6b01a1a91030350\",\"deviceName\":\"Garage 2\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.00.07\"}","lastDeviceData":"{\"online\":true,\"gwonline\":true,\"tem\":2973,\"hum\":3882,\"lastTime\":1630893180000,\"avgDayTem\":2973,\"avgDayHum\":3882}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/40a92d402e7eff4c685a056a86ef8342-add_list_type_device_5053.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}

[9/5/2021, 6:54:17 PM] [Govee] [Master Bedroom 2] is not currently supported, do create a Github issue with the following info:
{"device":"7ca6b01a1a91030055","deviceName":"Master Bedroom 2","model":"H5053","httpInfo":{"device":"7ca6b01a1a91030055","sku":"H5053","spec":"","versionHard":"1.00.01","versionSoft":"1.00.07","deviceName":"Master Bedroom 2","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":true,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":true,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":90,\"wifiLevel\":0,\"header\":\"1\",\"gatewayVersionHard\":\"1.00.00\",\"gatewayVersionSoft\":\"1.01.08\",\"sku\":\"H5053\",\"device\":\"7ca6b01a1a91030055\",\"deviceName\":\"Master Bedroom 2\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.00.07\"}","lastDeviceData":"{\"online\":true,\"gwonline\":true,\"tem\":2594,\"hum\":4235,\"lastTime\":1630893240000,\"avgDayTem\":2594,\"avgDayHum\":4235}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/40a92d402e7eff4c685a056a86ef8342-add_list_type_device_5053.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}

**Comment by bwp91** [comment]
Hi,

Can you install the beta version of the plugin, 4.9.1-beta.0? Once installed and restarted, these sensors should appear in Homebridge!
