### ISSUE TITLE
Report “off” when device is offline.

### ISSUE THREAD

**Issue by jackl5** [bwp91/homebridge-govee#117]
A quick feature request, when a device is offline, can this be reported as “off”? 

I have 2 sets of LED strips powered by my TV, these show as “on”, even when the TV is powered off.

thanks!

**Comment by bwp91** [comment]
Hi @jackl5 

Please install the beta version of the plugin, currently 4.10.1-beta.2.
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

You can see a new "Offline As Off" setting in the "optional settings" section of the configuration. Tick this box and restart the plugin.

Your devices that are reported as offline should then show as off in homekit. The status may up to a minute to update after the tv turning off, as the plugin needs to wait for the offline status to be reported by Govee.

Hope this helps!

**Comment by jackl5** [comment]
Hi @bwp91,

This works perfectly! Thank you for adding that so quickly!
