### ISSUE TITLE
Thermometer & Hydrometer not updating

### ISSUE THREAD

**Issue by tvqam** [bwp91/homebridge-govee#118]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
UI-X

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
4.10.0
Just started using this feature.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Hydrometer &Thermometer 
Model 5075

I have 6 of these devices and none of them are displaying the correct temperature or humidity.
I am able to look in the Govee App and try to compare the data history to what is being displayed in HomeKit, but none of data sets match.. at least for the previous 24 hours anyway.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @tvqam 

The H5075 and a number of similar models only refresh their data I think when connected to the Govee app. The plugin does not use bluetooth to get the latest data for these models.

You will need to use this plugin:
https://www.npmjs.com/package/homebridge-plugin-govee

**Comment by tvqam** [comment]
Thanks for getting back to me.
That makes sense now. 
I was using your recommended plugin but thought it'd be neater to have all Govee devices under the one plugin.
I appreciate your work.
Thanks again
