### ISSUE TITLE
Custom Colors as Scenes button?

### ISSUE THREAD

**Issue by WBWBW** [bwp91/homebridge-govee#119]
Thanks for bringing this plugin to homebridge. It’s been working great and I am using it with a Glide right now as a potential replacement to the buggy Lifx Beam. 

I am wondering if it’s possible to “call” a color mode with a particular color pattern that’s been saved under ‘my color’?

I am able to set DIY scenes as per the guide, and the ‘Color Mode’ also appear in the Eve app, but the DIY scenes are dynamic . The colour mode works but only sets the last used color. 

Am I missing something or is that not available at the moment?

**Comment by bwp91** [comment]
Hi @WBWBW 

The purpose of the “Colour Mode” button is simply to revert back from any set scene/music mode/diy back to the previous colour.

You can create HomeKit scenes to select any colour you’d like.

When you mention “colour pattern”, what do you mean by this? different colours along the same strip? Is this not considered a DIY?

**Comment by WBWBW** [comment]
Yes I meant different colors at the same time. I’ll look again at the DIY but it seems those scenes are all “dynamic” and have some animation in the scene setting. Whereas the one under “Colour” are fixed without animation.

**Comment by bwp91** [comment]
Could you do me a favour, put the plugin into debug mode from the plugin settings, and then use the govee app to turn the strip into some “segment” colour (make sure strip is connected via wifi rather than bluetooth if it supports it).

The logs should show an incoming message when you change to such a segmented colour.

Can you post the logs here that appear?

Thanks

**Comment by WBWBW** [comment]
Turns out the AWS code does appear. I missed it first because it doesn’t appear when just changing to “colour” but once you’ve saved some pattern and select one of those pattern it does show up in the logs.

**Comment by bwp91** [comment]
If you install the beta version of the plugin, I have added more fields to add a code to, the are called “Segmented”… “Segmented 2”… etc
