### ISSUE TITLE
Support turning on Mode for Govee Smart LED Lightbar

### ISSUE THREAD

**Issue by bezibaerchen** [bwp91/homebridge-govee#120]
Govee Smart LED Lightbar is properly found by plugin and can be turned on and off. Device offers different modes.

It is related to device Govee Smart LED Lightbar.  In Govee Home there are different modes:
Music, Video, Color, Scene and DIY.

It would be great if either one of the modes can be selected or plugin would turn on device in particular mode.
Currently device always is in color mode when turned on. However, as it is sort of an ambilight thing especially movie mode would be appreciated.

**Comment by bwp91** [comment]
Hi, is this a bluetooth or wifi device?

**Comment by bezibaerchen** [comment]
> Hi, is this a bluetooth or wifi device?

Both Bluetooth and WiFi.

https://de.govee.com/products/flow-pro-light-bar

**Comment by bezibaerchen** [comment]
> Hi, is this a bluetooth or wifi device?

Both Bluetooth and WiFi.

https://de.govee.com/products/flow-pro-light-bar

**Comment by bwp91** [comment]
If you have your govee username and password in the config you should be able to take advantage of this:

https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

**Comment by bezibaerchen** [comment]
> If you have your govee username and password in the config you should be able to take advantage of this:
> 
> https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

I am dumb, sorry. I thought I need to bluetooth code but if I read it correctly it can be either bluetooth OR WiFi. I will give that a try, thanks mate.

Greetings,

Ben (not trolling you, that's my name as well :-) )

**Comment by bezibaerchen** [comment]
Unfortunately I don't see a yellow entry as announced when switching mode.
What I get is:

```
[9/23/2021, 4:39:44 PM] [Govee] [Flow Pro Wohnzimmer] [AWS] message event [GD/70f37b92f045fb10bd93fa5ce6ca0511 {"msg":{"transaction":"v_1632407983967316","data":{"command":["MwUAAABkADIAAAAAAAAAAAAAAGA=","qgUBAAAAAAAAAAAAAAAAAAAAAK4="]},"accountTopic":"GA\/c2bdf9071ec5a9cf7e01ebc650a3440a","type":1,"cmdVersion":0,"cmd":"ptReal"}}].
[9/23/2021, 4:39:44 PM] [Govee] [Flow Pro Wohnzimmer] [AWS] receiving update [{"transaction":"v_1632407983967316","data":{"command":["MwUAAABkADIAAAAAAAAAAAAAAGA=","qgUBAAAAAAAAAAAAAAAAAAAAAK4="]},"accountTopic":"GA/c2bdf9071ec5a9cf7e01ebc650a3440a","type":1,"cmdVersion":0,"cmd":"ptReal","source":"AWS"}].
```

**Comment by bwp91** [comment]
Yes, the AWS codes will work over wifi and let you mimic most modes that the govee app provides.

Just be aware that if you setup an AWS code and get the plugin to set to this mode, the device must not be connected to your phone via bluetooth at the time, i think with some models if the bluetooth is connected then the wifi is disconnected!

**Comment by bwp91** [comment]
Do you have plugin debug mode turned on in the plugin settings?

**Comment by bezibaerchen** [comment]
> Yes, the AWS codes will work over wifi and let you mimic most modes that the govee app provides.
> 
> Just be aware that if you setup an AWS code and get the plugin to set to this mode, the device must not be connected to your phone via bluetooth at the time, i think with some models if the bluetooth is connected then the wifi is disconnected!

That is mainly if me and my phone is not around. I use an automation to turn device on when TV is turned on.

**Comment by bezibaerchen** [comment]
> Do you have plugin debug mode turned on in the plugin settings?

I ticked "Debug Logging" in Optional settings yes. And restarted Homebridge. Prior to that change I didn't see those lines.

**Comment by bwp91** [comment]
I don't know why the code didn't appear for you in this case. It won't appear if you already have the code in the config, which perhaps isn't the case here? Anyway the code you need for the scene from your logs above is:

```
MwUAAABkADIAAAAAAAAAAAAAAGA=,qgUBAAAAAAAAAAAAAAAAAAAAAK4=||ptReal||
```

**Comment by bezibaerchen** [comment]
For whatever reason code appeared at one point. However, the code seems to work, at least when checking in the app.
Will give it a final live try later tonight. Thanks a lot mate for swift reply and especially solution.

I will confirm laterst tomorrow if that did the trick. I already married with a scene and added to my automation in Homekit.

**Comment by bezibaerchen** [comment]
So tetsted successfully and it's working fine. Again thanks a lot for guidance mate.
