### ISSUE TITLE
Govee Heater H7130 Implementation

### ISSUE THREAD

**Issue by tjridge** [bwp91/homebridge-govee#121]
Please add support for new heater :)

**Comment by bwp91** [comment]
Hi @tjridge thanks for this, since it’s not an already implemented device it would require some work (which i would explain) between me and you.

If you have your username and password in the config does it appear in the log as an unsupported device?

**Comment by tjridge** [comment]
It does show up as an unsupported device.

**Comment by bwp91** [comment]
can you copy and paste the whole log message?

**Comment by tjridge** [comment]
[Heater] is not currently supported, do create a Github issue with the following info:
{"device":"31:CF:D4:AD:XX:XX:XX:XX","deviceName":"Heater","model":"H7130","httpInfo":{"device":"31:CF:D4:AD:XX:XX:XX:XX","sku":"H7130","spec":"","versionHard":"1.02.00","versionSoft":"1.00.08","deviceName":"Heater","deviceExt":{"deviceSettings":"{\"wifiName\":\"XXXX\",\"address\":\"XXXXXX\",\"bleName\":\"ihoment_H7130_2D7F\",\"topic\":\"GD/7eb8973b8a263d5e6a121c9d9c5d9611\",\"wifiMac\":\"D4:AD:FC:04:2D:7E\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.08\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"NnADXCcBAg0=\",\"sku\":\"H7130\",\"device\":\"31:CF:D4:AD:FC:04:2D:7E\",\"deviceName\":\"Heater\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.08\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/bb9c445b65b0583235546c40e7a2c8ef-add_list_type_device_7130.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":60},"isAPIDevice":false}

**Comment by bwp91** [comment]
Could we message on discord? Since this is a totally new device type for the plugin I will need a fair amount of extra information.

https://discord.gg/cMGhNtZ3tW

**Comment by tjridge** [comment]
Just updated the plug-in and it now shows up in my home. It shows up as unsupported and I have no control options.

**Comment by natistir** [comment]
I am having this issue as well. I can provide any and all info to get this up and running. Thanks!

**Comment by mbelkin** [comment]
Any chance this could be picked up again? <3

**Comment by bwp91** [comment]
> Any chance this could be picked up again? <3

Heater is already supported by the plugin :)

**Comment by mbelkin** [comment]
I wasn't able to get it working (doesn't show up under accessories). Also the device ID said it should be 20 something characters but all I have is a 17 char MAC address. Are you sure this specific heater is supported?

**Comment by bwp91** [comment]
Does anyone with a govee heater also own a govee temperature sensor?
