### ISSUE TITLE
Support  for H61270

### ISSUE THREAD

**Issue by jg506** [bwp91/homebridge-govee#123]
### What issue do you have? Please be as thorough and explicit as possible.

Support for unsupported LED strip [Govee] [H6170_D5AF] is not currently supported, do create a Github issue with the following info:
{"device":"7A:4A:A4:C1:38:21:D5:XX,"deviceName":"H6170_D5AF","model":"H6170","httpInfo":{"device":"7A:4A:A4:C1:38:21:D5:XX","sku":"H6170","spec":"","versionHard":"1.00.01","versionSoft":"1.00.03","deviceName":"H6170_D5AF","deviceExt":{"deviceSettings":"{\"bleName\":\"ihoment_H6170_D5AF\",\"pactType\":2,\"pactCode\":1,\"ic\":0,\"sku\":\"H6170\",\"device\":\"7A:4A:A4:C1:38:21:D5:AF\",\"deviceName\":\"H6170_D5AF\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.00.03\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5323ebc5a2a80e8328c9b994fa2d63e3-add_list_type_device_6170.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/b062901f0c6263cab2ee939c66c46424-new_light_title_eaves_rgb_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/4b1a91316faebe523e645a0a895c476e-new_light_title_eaves_off.png\",\"ext\":\"\",\"ic\":0}"},"pactType":2,"pactCode":1,"goodsType":2},"isAPIDevice":false}

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

* Which version of Homebridge/HOOBS do you have?

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @jg506 

I've just released v4.13.0 which includes support for the H6170.

Since this device is bluetooth only, the plugin can only push updates to the device, it cannot obtain the latest status.

**Comment by jg506** [comment]
Working perfect! super fast response (by the device, and by the maintainer!) Had to manually add it, which was self explanatory by the logs.
