### ISSUE TITLE
I Can’t add a Bluetooth controlled RGB strip, Model H613C

### ISSUE THREAD

**Issue by PierreOlivier-M** [bwp91/homebridge-govee#124]
### What issue do you have? Please be as thorough and explicit as possible.
i am trying to setup homebridge-govee plugin to control my light strip over bluetooth, model H613C, and when i checked the logs it says i should create an issue because my device is not supported

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

Homebridge v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry, Node.js v14.8.0, npm v6.14

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

V4.13.1, it is my first time using this plugin

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Model H613C
H613C_D570

RGB Basic light strip
### Please paste any relevant logs below.

```

[06/10/2021, 02:36:54] [Govee] Initializing Govee platform...
[06/10/2021, 02:36:54] [Govee] Initialising plugin v4.13.1 | Node v14.18.0 | HB v1.3.4...

[06/10/2021, 02:36:54] [Govee] Plugin initialised. Setting up accessories....

[06/10/2021, 02:36:56] [Govee] [H613C_D570] is not currently supported, do create a Github issue with the following info:
{"device":"4F:26:7C:A6:B0:5F:D5:70","deviceName":"H613C_D570","model":"H613C","httpInfo":{"device":"4F:26:7C:A6:B0:5F:D5:70","sku":"H613C","spec":"","versionHard":"2.01.01","versionSoft":"2.04.00","deviceName":"H613C_D570","deviceExt":{"deviceSettings":"{\"address\":\"7C:A6:B0:5F:D5:70\",\"bleName\":\"GBK_H613C_D570\",\"pactType\":10,\"pactCode\":1,\"ic\":0,\"sku\":\"H613C\",\"device\":\"4F:26:7C:A6:B0:5F:D5:70\",\"deviceName\":\"H613C_D570\",\"versionHard\":\"2.01.01\",\"versionSoft\":\"2.04.00\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/bbfa1b98a970733c443e142b86535af1-add_list_type_device_613bc.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png\",\"ext\":\"\",\"ic\":0}"},"pactType":10,"pactCode":1,"goodsType":39},"isAPIDevice":false}

```

**Comment by bwp91** [comment]
Hi @PierreOlivier-M 

If you update to beta version 4.13.2-beta.0, this device should be available in the home app,

**Comment by bwp91** [comment]
Since this is a bluetooth only device, you will need to add it to the configuration marking the 'Enable BLE Control' and also following any instructions you might need at

https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control

**Comment by bwp91** [comment]
Also, you will need to understand that the plugin can only **send** commands to the device, i mean the plugin cant obtain current status

**Comment by PierreOlivier-M** [comment]
Thanks i'm going to try to update to the beta 
and yes i already turned bluetooth control mode on and added Mac address
