### ISSUE TITLE
Disabling BLE client as Cannot find module '@abandonware/bluetooth-hci-socket'

### ISSUE THREAD

**Issue by HomebridgeX** [bwp91/homebridge-govee#125]
### What issue do you have? Please be as thorough and explicit as possible.

After the start of my homebridge, I get this error:

Disabling BLE client as Cannot find module '@abandonware/bluetooth-hci-socket'
Require stack:
- /usr/local/lib/node_modules/homebridge-govee/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridgeRequire stack:.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge

* Which version of Homebridge/HOOBS do you have?
1.3.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 3 Model B Rev 1.2
Node.js: 14.18.0
NPM: 8.0.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
4.13.1

**Comment by bwp91** [comment]
Hi @HomebridgeX 

Can you run this command in a homebridge terminal and show me the output?

`sudo npm i -g homebridge-govee@latest`

**Comment by HomebridgeX** [comment]
Hi @bwp91 ,


$ sudo npm i -g homebridge-govee@latest

added 32 packages, removed 7 packages, changed 99 packages, and audited 132 packages in 2m

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by bwp91** [comment]
And do you still have the same issue when the plugin loads?

**Comment by HomebridgeX** [comment]
It works perfect again, your‘re the best. Thank you!

**Comment by bwp91** [comment]
excellent!
