### ISSUE TITLE
Govee H5074 device is not supported

### ISSUE THREAD

**Issue by carldunniii** [bwp91/homebridge-govee#126]
### What issue do you have? Please be as thorough and explicit as possible.
I have placed the Govee H5074 inside the return A/C duct but the Homebridge plugin is saying it is not supported.  Error below.  I have successfully gotten the H5075 devices to report to Homebridge. 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge

* Which version of Homebridge/HOOBS do you have?
1.3.5

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v4.13.1 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Govee H5074

### Please paste any relevant logs below.

```
[10/12/2021, 2:25:28 PM] [Govee] [Furnace Out] is not currently supported, do create a Github issue with the following info:
{"device":"97:5A:E3:5E:CC:90:10:A2","deviceName":"Furnace Out","model":"H5074","httpInfo":{"device":"97:5A:E3:5E:CC:90:10:A2","sku":"H5074","spec":"","versionHard":"1.00.01","versionSoft":"1.01.00","deviceName":"Furnace Out","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":false,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":false,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":100,\"wifiLevel\":0,\"bleName\":\"Govee_H5074_10A2\",\"address\":\"E3:5E:CC:90:10:A2\",\"sku\":\"H5074\",\"device\":\"97:5A:E3:5E:CC:90:10:A2\",\"deviceName\":\"Furnace Out\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.01.00\"}","lastDeviceData":"{\"online\":false,\"tem\":1300,\"hum\":8350,\"lastTime\":1631846820000,\"avgDayTem\":1300,\"avgDayHum\":8350}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}
[10/12/2021, 2:25:28 PM] [Govee] [Furnace In] is not currently supported, do create a Github issue with the following info:
{"device":"6D:D5:E3:5E:CC:70:50:59","deviceName":"Furnace In","model":"H5074","httpInfo":{"device":"6D:D5:E3:5E:CC:70:50:59","sku":"H5074","spec":"","versionHard":"1.00.01","versionSoft":"1.01.00","deviceName":"Furnace In","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":false,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":false,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":99,\"wifiLevel\":0,\"bleName\":\"Govee_H5074_5059\",\"address\":\"E3:5E:CC:70:50:59\",\"sku\":\"H5074\",\"device\":\"6D:D5:E3:5E:CC:70:50:59\",\"deviceName\":\"Furnace In\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.01.00\"}","lastDeviceData":"{\"online\":false,\"tem\":2190,\"hum\":5480,\"lastTime\":1631845080000,\"avgDayTem\":2190,\"avgDayHum\":5480}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}
```

**Comment by bwp91** [comment]
Hi @carldunniii 

If you update to the beta version of the plugin, currently v4.13.2-beta.3, your H5074 devices should be added to Homebridge.

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Just to make you aware that this plugin doesn't use bluetooth to query these sensors for the most up to date readings. The plugin uses the data provided from the Govee cloud. For sensors that don't have wifi capability, the cloud data may not be up to date and so neither will the readings shown by Homebridge.

You may find that the other homebridge plugin, homebridge-plugin-govee, works better for your devices as this plugin uses bluetooth to obtain the latest data directly from the sensor.
