### ISSUE TITLE
Govee Humidifier H7141 Implementation

### ISSUE THREAD

**Issue by dineelbathina** [bwp91/homebridge-govee#127]
### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

* Which version of Homebridge/HOOBS do you have?

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by dineelbathina** [comment]
{"device":"1C:2B:9C:04:A0:94:0B:A3","deviceName":"Smart Humidifier","model":"H7141","httpInfo":{"device":"1C:2B:9C:04:A0:94:0B:A3","sku":"H7141","spec":"","versionHard":"1.02.00","versionSoft":"1.00.13","deviceName":"Smart Humidifier","deviceExt":{"deviceSettings":"{\"wifiName\":\"@Badboys5G\",\"address\":\"9C:04:A0:94:0B:A4\",\"bleName\":\"ihoment_H7141_0BA4\",\"topic\":\"GD/78b076060392e92cb395b6a7090ac9e0\",\"wifiMac\":\"9C:04:A0:94:0B:A3\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.13\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"YVZwCnJRXFU=\",\"waterShortageOnOff\":1,\"sku\":\"H7141\",\"device\":\"1C:2B:9C:04:A0:94:0B:A3\",\"deviceName\":\"Smart Humidifier\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.13\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/9665fd8703926801c0b62ff03bd25f6e-add_list_type_device_7141.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":61},"isAPIDevice":false}

**Comment by bwp91** [comment]
Hi @dineelbathina 

Thanks for this!

Could we message on discord? Since this is a totally new device type for the plugin I will need a fair amount of extra information.

https://discord.gg/cMGhNtZ3tW
