### ISSUE TITLE
Enter an AWS Code (from Logs) ?

### ISSUE THREAD

**Issue by Stonie70** [bwp91/homebridge-govee#129]
Hi, I want to ad a DIY to the Wifi Lightstrip in homebridge.govee, where do I get the AWS Code from Logs ?
Thanks for your help !
![18-10-_2021_18-51-19](https://user-images.githubusercontent.com/90376181/137774578-6868dd67-8319-4388-b1b8-3a05ded9483b.jpg)

**Comment by bwp91** [comment]
Hi @Stonie70 

Details for obtaining the AWS code can be seen in this wiki article:

https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

If you need anything clarified feel free to ask!
