### ISSUE TITLE
H6141 Brightness issue

### ISSUE THREAD

**Issue by ecoen66** [bwp91/homebridge-govee#13]
I'm using an H6141.  At 100% brightness in the Govee app (iOS), Apple Home shows 39% brightness.  If I try to set the brightness above 39% in Apple Home, homebridge logs the following error:
"[Govee] [Cabinet lights] could not be updated and its status will be reverted soon. Error: Request failed with status code 400."

Setting it to something less than 39% in Apple Home does reduce the brightness in the Govee app.  I can move it up and down within the range of 0 - 39%.
...

**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge
...

Which version of Homebridge/HOOBS do you have?
Version 1.1.6
...

Which version of this plugin (homebridge-govee) do you have?
homebridge-govee v2.0.7. 
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**

**_This was after bumping the brightness in Apple Home to 50-something percent..._**

[Govee] [getDevices()] HTTP Response:
{
  "data": {
    "devices": [
      {
        "device": "2E:39:A4:C1:38:E2:C8:8F",
        "model": "H6141",
        "deviceName": "Cabinet Lights",
        "controllable": true,
        "retrievable": true,
        "supportCmds": [
          "turn",
          "brightness",
          "color",
          "colorTem"
        ]
      }
    ]
  },
  "message": "Success",
  "code": 200
}
[10/30/2020, 2:22:20 PM] [Govee] [1] devices loaded from your Govee account.
[10/30/2020, 2:22:20 PM] [Govee] Govee setup complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!
[10/30/2020, 2:22:20 PM] [Govee] Note: 'Request & Response Logging' is not advised for long-term use.
[10/30/2020, 2:22:20 PM] [Insteon Local Platform] Internet is on at 100%
[10/30/2020, 2:22:20 PM] [Belkin WeMo] Online: Deck Lights [841826000000D5AC]
[10/30/2020, 2:22:20 PM] [Govee] [getDevice()] HTTP Response:
{
  "data": {
    "device": "2E:39:A4:C1:38:E2:C8:8F",
    "model": "H6141",
    "properties": [
      {
        "online": true
      },
      {
        "powerState": "on"
      },
      {
        "brightness": 69
      },
      {
        "color": {
          "r": 255,
          "b": 196,
          "g": 226
        }
      }
    ]
  },
  "message": "Success",
  "code": 200
}

[10/30/2020, 2:23:22 PM] [Govee] [updateDevice()] HTTP Request. This message is yellow for clarity:
{
  "device": "2E:39:A4:C1:38:E2:C8:8F",
  "model": "H6141",
  "cmd": {
    "name": "brightness",
    "value": 127
  }
}
[10/30/2020, 2:23:22 PM] [Govee] [Cabinet lights] could not be updated and its status will be reverted soon. Error: Request failed with status code 400.
[10/30/2020, 2:23:36 PM] [Govee] [getDevices()] HTTP Response:
{
  "data": {
    "devices": [
      {
        "device": "2E:39:A4:C1:38:E2:C8:8F",
        "model": "H6141",
        "deviceName": "Cabinet Lights",
        "controllable": true,
        "retrievable": true,
        "supportCmds": [
          "turn",
          "brightness",
          "color",
          "colorTem"
        ]
      }
    ]
  },
  "message": "Success",
  "code": 200
}
...

**Comment by bwp91** [comment]
Thank you for this. And this should be fixed in the just released v2.0.8 :)

**Comment by ecoen66** [comment]
All good now!  Thanks!
