### ISSUE TITLE
Support for H7060 Floodlights

### ISSUE THREAD

**Issue by adammiarka** [bwp91/homebridge-govee#130]
* **Please explain your feature request in a one or two sentences.**
Would like to have the H7060 Floodlights added for control

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Govee devices that this relates to?**
H7060

* **Anything else?**
Hopefully this is supported by the Govee API.

**Comment by bwp91** [comment]
Hi @adammiarka 
The H7060 isn’t (currently) supported by the API.
Is this a bluetooth device? wifi? both?

**Comment by adammiarka** [comment]
Darn.  Was hoping it could be supported.   The device supports both bluetooth and wifi.

**Comment by bwp91** [comment]
What platform are you running homebridge on?

**Comment by bwp91** [comment]
I ask because it may be possible to control your lights via bluetooth

**Comment by adammiarka** [comment]
So you're saying there's a chance?  Woohoo!  Let me know what information you would need.

**Comment by bwp91** [comment]
Yes this is why i asked what platform you are running homebridge on… 🙂

**Comment by adammiarka** [comment]
Oops...it's been a long week.  🙃 

Running on a Synology DS218+ via Docker.   HomeBridge version 1.3.5

**Comment by bwp91** [comment]
I don’t know if homebridge/node would have permission/access to some bluetooth module that your platform has? maybe worth a try?

start by adding your govee username and password to the config, unless you have done this already?

**Comment by adammiarka** [comment]
Yes, I've already setup the Govee plugin with username/pass/API key.   Currently using it with the new Immersion strip leds.

**Comment by bwp91** [comment]
Ah so do you have a message in the logs when you start homebridge with your “unsupported” H7060?

**Comment by adammiarka** [comment]
Yes.  

```
[10/22/2021, 11:36:02 AM] [Govee] [H7060_1767] is not currently supported, do create a Github issue with the following info:
{"device":"2D:A7:CA:30:39:39:17:67","deviceName":"H7060_1767","model":"H7060","httpInfo":{"device":"2D:A7:CA:30:39:39:17:67","sku":"H7060","spec":"","versionHard":"3.01.01","versionSoft":"1.00.05","deviceName":"H7060_1767","deviceExt":{"deviceSettings":"{\"wifiName\":\"Oedipus\",\"address\":\"CA:30:39:39:17:67\",\"bleName\":\"Govee_H7060_1767\",\"topic\":\"GD/9fa916172538426188ab43013756ac3b\",\"wifiMac\":\"D4:AD:FC:04:DE:60\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"2.00.04\",\"wifiHardVersion\":\"1.02.00\",\"ic\":4,\"secretCode\":\"a57KMDk5F2c=\",\"sku\":\"H7060\",\"device\":\"2D:A7:CA:30:39:39:17:67\",\"deviceName\":\"H7060_1767\",\"versionHard\":\"3.01.01\",\"versionSoft\":\"1.00.05\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/6e19099c2ac3e92f5b0c3f8ffe88fd78-add_list_type_device_7060.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/150fbfc847e474034e3e351ac7f079cb-new_light_title_7060_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/41564cd6fc6cc32c3a525afb3de5f1f6-new_light_title_7060_off.png\",\"ext\":\"\",\"ic\":4}"},"pactType":1,"pactCode":1,"goodsType":76},"isAPIDevice":false}
```

**Comment by bwp91** [comment]
Can you update to the beta version of the plugin, 4.15.1-beta.2

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

You will also need to add an entry for this device in the config, with id `2D:A7:CA:30:39:39:17:67` with the "Enable BLE Control" ticked... 

restart the plugin and you can test whether the bluetooth control works

**Comment by adammiarka** [comment]
Updated to the latest beta.   Used the device ID, and added the Bluetooth address of the floodlights.   Shows up in HomeKit now and can control it.  Great success!  😀 

There are four floodlights that came with the kit and each one can be controlled separately for color, brightness, etc.   Hopefully when Govee adds to their API you can take advantage of it.   

Thanks again for the quick turn around!

**Comment by bwp91** [comment]
So the one H7060 device is actually split into 4 lights?

**Comment by adammiarka** [comment]
Yes.   This one https://www.amazon.com/Govee-Floodlights-2700-6500K-Landscape-Waterproof/dp/B09FXH4YLG/

**Comment by bwp91** [comment]
The current state of the plugin, there is no way that the plugin could control each light separately.

The closest thing I could recommend for the moment is the the “scene” functionality:

https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

**Comment by adammiarka** [comment]
Thanks!  I'll try that out when I have time.   Was just thankful to be able to turn on/off the flood lights via HomeKit automation.   They keep their state when turned on an off so I can always adjust in the Govee app if needed.

**Comment by bwp91** [comment]
The H7060 model is now supported by the Govee API and with the beta version of the plugin you will be able to control this device without depending on bluetooth control.

**Comment by adammiarka** [comment]
Thanks!  Is there a way to tell that the lights are using the API instead of Bluetooth?  Or does the switch happen automatically?

**Comment by bwp91** [comment]
With debug logging on, you can see which commands are being sent via which method.

The plugin will initially attempt bluetooth for supported commands, otherwise if bluetooth fails or it’s an unsupported command then the plugin will revert to the API
