### ISSUE TITLE
Device has been reported [Offline]

### ISSUE THREAD

**Issue by nur1442** [bwp91/homebridge-govee#131]
### What issue do you have? Please be as thorough and explicit as possible.

My Govee plugin has stopped controlling my LED light strip. It was working fine but now will not control them. The log file is just showing _25/10/2021, 14:22:49 HOOBS Govee WARNING [TV Backlights] has been reported [offline]._
Control is working fine on my local wifi network using the Govee IOS app. I have reapplied the API Key with no change.
If I change the power status or brightness via the IOS Home app, I do see it in the hoops logs. I've enabled debugging and see the following line: _[TV Backlights] has been reported [offline] via API, so update may or may not be successful._

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

HOOBS 4.0.110
Homebridge 1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi with Node version 14.18.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

4.15.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

LED Light Strip H6159_D912

### Please paste any relevant logs below.

```
25/10/2021, 14:47:44HOOBSGoveeInitialising plugin v4.15.0 | Node v14.18.1 | HB v1.3.4 | HOOBS v4...
25/10/2021, 14:47:44HOOBSGoveePlugin initialised. Setting up accessories....
25/10/2021, 14:47:46HOOBSGoveeWARNINGDisabling BLE client as no enabled devices configured.
25/10/2021, 14:47:46HOOBSGovee[TV Backlights] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableAWS":"no","enableBT":"no","logging":"debug"}.
25/10/2021, 14:47:46HOOBSGovee[TV Backlights] initialised with id [78:65:A4:C1:38:5F:D9:12].
25/10/2021, 14:47:46HOOBSGovee✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
25/10/2021, 14:47:47HOOBSGovee[TV Backlights] [AWS] connected event.
25/10/2021, 14:47:47HOOBSGovee[TV Backlights] [API] receiving update [{"source":"API","online":"false","powerState":"off","brightness":25,"color":{"r":249,"b":6,"g":6}}].
25/10/2021, 14:47:47HOOBSGoveeWARNING[TV Backlights] has been reported [offline].
25/10/2021, 14:48:02HOOBSGovee[TV Backlights] [API] receiving update [{"source":"API","online":"false","powerState":"off","brightness":25,"color":{"r":249,"b":6,"g":6}}].
25/10/2021, 14:48:17HOOBSGovee[TV Backlights] [API] receiving update [{"source":"API","online":"false","powerState":"off","brightness":25,"color":{"r":249,"b":6,"g":6}}].
25/10/2021, 14:48:19HOOBSGovee[TV Backlights] has been reported [offline] via API, so update may or may not be successful.
25/10/2021, 14:48:19HOOBSGovee[TV Backlights] [AWS] sending update {"msg":{"accountTopic":"GA/adfa891c2a87fe0265bfacb30c83d6c9","cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1635169699942000","type":1}}.
25/10/2021, 14:48:19HOOBSGovee[TV Backlights] [API] sending update {"name":"turn","value":"on"}.
25/10/2021, 14:48:20HOOBSGovee[TV Backlights] [AWS] message event [GD/2848ccbbf61486e0397f5032126480ac {"msg":{"accountTopic":"GA/adfa891c2a87fe0265bfacb30c83d6c9","cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1635169699942000","type":1}}].
25/10/2021, 14:48:20HOOBSGovee[TV Backlights] [AWS] receiving update [{"accountTopic":"GA/adfa891c2a87fe0265bfacb30c83d6c9","cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1635169699942000","type":1,"source":"AWS"}].
25/10/2021, 14:48:20HOOBSGovee[TV Backlights] current state [on].
25/10/2021, 14:48:20HOOBSGovee[TV Backlights] [AWS] message event [GD/2848ccbbf61486e0397f5032126480ac {"msg":{"transaction":"o_1635169700409","type":1,"cmd":"turn","data":{"val":1},"accountTopic":"GA/adfa891c2a87fe0265bfacb30c83d6c9"}}].
25/10/2021, 14:48:20HOOBSGovee[TV Backlights] [AWS] receiving update [{"transaction":"o_1635169700409","type":1,"cmd":"turn","data":{"val":1},"accountTopic":"GA/adfa891c2a87fe0265bfacb30c83d6c9","source":"AWS"}].
25/10/2021, 14:48:20HOOBSGovee[TV Backlights] current state [on].```

**Comment by bwp91** [comment]
The plugin will mark the device as offline when reported offline by the govee server.

The plugin will always attempt to send a command to the device even when offline, the extra logging is just to make the user aware that govee has reported the device offline.

This can happen when the device is disconnected from wifi. You may still be able to control the device from the govee app via bluetooth instead of wifi. Have you tried using the govee app with bluetooth disabled to control the device?

Another thing that may get the device online again is unplugging and plugging back in.

Is your device bluetooth too? did you know the plugin can control certain functions using bluetooth? depending on which platform you are running homebridge on.
