### ISSUE TITLE
Govee H61A0 - Neon LED Rope Lights HOOBS support

### ISSUE THREAD

**Issue by CadLiara** [bwp91/homebridge-govee#133]
* **Please explain your feature request in a one or two sentences.**

Currently doesn't show as a supported device. Can this be added to be able to expose it to Homekit?

* **Is your feature request related to a problem? Please describe.**

No

* **Any particular Govee devices that this relates to?**

Govee H61A0 Neon LED Rope Lights

* **Anything else?**

Nothing but a thank you for the work and support.

**Comment by bwp91** [comment]
Hi @CadLiara can you update to the beta version of the plugin, v4.15.1-beta.4.

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version#hoobs-4

You should also add an entry for this light in the "light devices" section of the plugin configuration, with the device id as shown in the hoobs log. You should tick the "enable ble control" option.

The plugin will attempt to control your H61A0 via bluetooth. The Govee API does not currently support this model for cloud control, however I imagine it will do at some point as it is a wifi + bluetooth device. Until then, the plugin will need to use bluetooth to control the device.

**Comment by bwp91** [comment]
The H61A0 model is now supported by the Govee API and with the beta version of the plugin you will be able to control this device without depending on bluetooth control.
