### ISSUE TITLE
Device Not Supported

### ISSUE THREAD

**Issue by mslawson** [bwp91/homebridge-govee#134]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

4.0.98

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

HOOBS Box 

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

4.15.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H613A

### Please paste any relevant logs below.

```
10/30/2021, 8:51:47 PMGovee BridgeGoveeWARNING[Cabinet Left] is not currently supported, do create a Github issue with the following info:
{"device":"D8:18:7C:A6:B0:5F:F4:27","deviceName":"Cabinet Left","model":"H613A","httpInfo":{"device":"D8:18:7C:A6:B0:5F:F4:27","sku":"H613A","spec":"","versionHard":"2.01.01","versionSoft":"2.03.11","deviceName":"Cabinet Left","deviceExt":{"deviceSettings":"{\"bleName\":\"GBK_H613A_F427\",\"pactType\":10,\"pactCode\":1,\"ic\":0,\"sku\":\"H613A\",\"device\":\"D8:18:7C:A6:B0:5F:F4:27\",\"deviceName\":\"Cabinet Left\",\"versionHard\":\"2.01.01\",\"versionSoft\":\"2.03.11\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/b6edf57d9c0782c59a4b6bf8b00d9d8d-add_list_type_device_613abcf.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png\",\"ext\":\"\",\"ic\":0}"},"pactType":10,"pactCode":1,"goodsType":39},"isAPIDevice":false}
```

**Comment by bwp91** [comment]
Hi @mslawson this model should appear as a device in the latest version of the plugin 4.16.0.

Bear in mind since this is a bluetooth-only device you will need to configure it via the plugin settings, you may also need to install some extra packages for the bluetooth control to work. More info at

https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control

Thanks!
