### ISSUE TITLE
Additional support

### ISSUE THREAD

**Issue by Gotcha182** [bwp91/homebridge-govee#136]
* **Please explain your feature request in a one or two sentences.**

Support for h617c rgbic lights

* **Is your feature request related to a problem? Please describe.**

Cannot set up at this time

* **Any particular Govee devices that this relates to?**

H617c

* **Anything else?**

**Comment by bwp91** [comment]
Hi @Gotcha182 this model should appear as a device in the beta version of the plugin 4.16.1-beta.0.

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Bear in mind since this is a bluetooth-only device you will need to configure it via the plugin settings, you may also need to install some extra packages for the bluetooth control to work. More info at

https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control

Thanks!

**Comment by Gotcha182** [comment]
Thank you for the assistance in getting the beta added. Bluetooth is seeming to be a challenge as well as the device id. Where can this be located as the Mac id seems to not be what is needed. Is this the Bluetooth id that is being referred to?

**Comment by bwp91** [comment]
The device id for the config can be found in the homebridge log when the plug-in starts, it will list the devices in your account.

In the config, enter the device ID and tick the Enable BLE Control box. You can try leaving the bluetooth address field blank as the plugin can usually get the bluetooth address.

**Comment by Gotcha182** [comment]
I still cannot seem to get the device id when running on the pi4. It initializes then disables http for some reason and then disables the plug in as no devices found

**Comment by bwp91** [comment]
Can you paste the homebridge logs here? Have you put your govee username and password into the config?

**Comment by Gotcha182** [comment]
Changing the username to the email as opposed to the what I will call the nickname solved it! Thanks!!!

**Comment by Gotcha182** [comment]
Thanks for the wonderful plug-in!

**Comment by bwp91** [comment]
Is the bluetooth working? Maybe i will change the text to “govee email” instead of “govee username”

**Comment by Gotcha182** [comment]
It seems to be? I will have to double check more when I get home. I was able to remote into my pi to set up config so it certainly seems all is good when changing to email
