### ISSUE TITLE
Device not supported

### ISSUE THREAD

**Issue by yangqi** [bwp91/homebridge-govee#137]
* **Please explain your feature request in a one or two sentences.**
`
[Thermometer 1] is not currently supported, do create a Github issue with the following info:
{"device":"21:26:35:32:39:D2:FA:FC","deviceName":"Thermometer 1","model":"H5100","httpInfo":{"device":"21:26:35:32:39:D2:FA:FC","sku":"H5100","spec":"","versionHard":"3.01.01","versionSoft":"1.00.10","deviceName":"Thermometer 1","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":false,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":false,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":100,\"wifiLevel\":0,\"bleName\":\"GVH5100_2621\",\"address\":\"D2:39:32:35:26:21\",\"gatewayId\":120765,\"gatewayInfo\":{\"index\":1,\"device\":\"66:16:C1:32:32:36:2B:70\",\"sku\":\"H5151\",\"topic\":\"GD/0d16e3fc4505d4f671f15735197b4056\"},\"sku\":\"H5100\",\"device\":\"21:26:35:32:39:D2:FA:FC\",\"deviceName\":\"Thermometer 1\",\"versionHard\":\"3.01.01\",\"versionSoft\":\"1.00.10\"}","lastDeviceData":"{\"online\":false,\"tem\":2090,\"hum\":5370,\"lastTime\":1635885418000,\"avgDayTem\":2090,\"avgDayHum\":5370}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/093658cd203f2b31b7ebbe860b14bf4b-add_list_type_device_5100.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":66},"isAPIDevice":false}
`

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**
This is a new Thermo Hygrometer H5100

* **Anything else?**

**Comment by bwp91** [comment]
Hi @yangqi please install the beta version of the plugin, v4.16.1-beta.1.

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

This device should then appear in Homebridge :)

**Comment by yangqi** [comment]
Thank you, that did the trick.
