### ISSUE TITLE
Problem when upgrading Node.js to 16.31

### ISSUE THREAD

**Issue by Subivan1** [bwp91/homebridge-govee#138]
### I have upgrade node as recommended by a number of plugins, but then i get an error message in the log and the bluetooth devices don't work. When I set Node.js back to 14.81 everything works again but I get warning messages for plugins that want me to update Node.js

Is there a solution that allows me to keep all the plugins satisfied?

Thanks.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
* I use Homebridge UI-X running Govee on a child bridge.

* Which version of Homebridge/HOOBS do you have?
* homebridge-config-ui-x v4.41.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
* Raspberry PI 3
* Node version causes the problem in the plugin when I upgrade to 16.13 from 14.81
* npm -version 8.1.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee v4.17.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Bluetooth lights h6127

### Please paste any relevant logs below.
relevant section of log showing error message.
<
[**Govee**] _Disabling BLE client as The module '/usr/local/lib/node_modules/homebridge-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).was compiled against a different Node.js version using.
```_

**Comment by bwp91** [comment]
Yes, you can run these terminal commands to uninstall and reinstall the plugin...

```
sudo npm uninstall -g homebridge-govee
```

```
sudo npm install -g homebridge-govee
```

This will simply reinstall the plugin without losing any configuration or accessory cache.

**Comment by Subivan1** [comment]
Excellent, thanks very much.

**Comment by Subivan1** [comment]
solution worked perfectly
