### ISSUE TITLE
H5001 support

### ISSUE THREAD

**Issue by maxtaunton** [bwp91/homebridge-govee#14]
**Please explain your feature request in one sentence.**
Can you please add model h5001 (Smart light switch)

**Is your feature request related to a problem? Please describe.**
Yes I got to be a tester for the smart light switch but I want to be able to control it with hoobs / HomeKit
**Any particular Govee devices that this relates to?**
Yes model H5001 the smart light switch

**Anything else?**
No

**Comment by bwp91** [comment]
Hi, 
Unless anything has changed with the govee api, i am still under the impression this model is not supported. 
It’s something completely out of my control, and Govee are the ones that control which models are supported!

**Comment by bwp91** [comment]
Gonna close this.
If you have some sort of updated API document which states support for the H5001 then let me know :)

**Comment by bwp91** [comment]
Support for H5001 is available with the new update v2.4.0.
