### ISSUE TITLE
Calibrate hygrometer

### ISSUE THREAD

**Issue by Captain-Greybeard** [bwp91/homebridge-govee#140]
I have a H5075 which I have calibrated in the govee app but the plugin shows about 1% more in homekit.

**Comment by bwp91** [comment]
The H5075 is a bluetooth-only sensor device and this plugin does not use bluetooth connect to these sensors to read the most up-to-date information.

This plugin uses the information retrieved from the Govee cloud, meaning that the data may be old if the sensor has not synced with your phone.

For these bluetooth-only sensors I always recommend using the other Govee plugin, homebridge-plugin-govee.

See for more info:

https://github.com/bwp91/homebridge-govee/wiki/Supported-Devices#thermo-hygrometer-sensors-wi-fi

**Comment by Captain-Greybeard** [comment]
Great thanks for the help, I wasn't aware that there was another plugin.
