### ISSUE TITLE
H613D Support

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-govee#141]
* **Please explain your feature request in a one or two sentences.**
[Bedroom] is not currently supported, do create a Github issue with the following info:

* **Is your feature request related to a problem? Please describe.**
H613D

* **Any particular Govee devices that this relates to?**

* **Anything else?**
{"device":"BA:33:7C:A6:B0:5F:CC:78","deviceName":"Bedroom","model":"H613D","httpInfo":{"groupId":0,"device":"BA:33:7C:A6:B0:5F:CC:78","sku":"H613D","spec":"","versionHard":"2.01.01","versionSoft":"2.02.04","deviceName":"Bedroom","deviceExt":{"deviceSettings":"{\"bleName\":\"GBK_H613D_CC78\",\"pactType\":10,\"pactCode\":1,\"ic\":0,\"sku\":\"H613D\",\"device\":\"BA:33:7C:A6:B0:5F:CC:78\",\"deviceName\":\"Bedroom\",\"versionHard\":\"2.01.01\",\"versionSoft\":\"2.02.04\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/9afd5f5903facff0db3955ba6fd90ebe-add_list_type_device_613de.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfr

**Comment by bwp91** [comment]
Hi @ahlawdev  this model should appear as a device in the beta version of the plugin 4.17.1-beta.4.

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Bear in mind since this is a bluetooth-only device you will need to configure it via the plugin settings, you may also need to install some extra packages for the bluetooth control to work. More info at

https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control

Thanks!

**Comment by ghost** [comment]
Got it working! Thank you for your work.

**Comment by bwp91** [comment]
Hi @aahlw 

Are you still using your H613D with this plugin? Are you able to successfully change the colour and colour temperature from the Home app?

**Comment by ghost** [comment]
Hey, 

Sorry, I'm not using the Homebridge altogether. I can set it up again and try if you are willing to wait.

**Comment by bwp91** [comment]
If it’s not too much trouble, i would be really interested to know if the colour is working with this device when controlllrd from home app.

Thanks for getting back to me, and no rush :)

**Comment by ghost** [comment]
Hey,

Sorry for taking long to get back but I was able to set up Homebridge again. Color and temperature do not change when done via the Home app. I also used the latest beta version (v4.27.1-beta.2)
