### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by aafayed** [bwp91/homebridge-govee#142]
### What issue do you have? Please be as thorough and explicit as possible.
I currently have homebridge-govee v4.12.2. Everytime I try to update, I get the following error:
![image](https://user-images.githubusercontent.com/94153877/141400770-6472a677-6d71-4de2-b620-a1b3f9357509.png)

Not sure what is wrong, but I do notice when homebridge starts that I get the following message:
![image](https://user-images.githubusercontent.com/94153877/141401031-4f641197-4e21-4f49-9876-e9635ae3ab48.png)

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which ![image](https://user-images.githubusercontent.com/94153877/141401756-8507889f-f697-4d11-9536-fd6f974791a4.png) of Homebridge/HOOBS do you have?

Homebridge v1.3.4 (Homebridge A118)
 
* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Windows 10 on HyperV, Node.js v16.13.0 

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee v4.12.2

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

No issues with the devices. I just can't update the plugin version

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @aafayed 

Did you recently update to node v16? How did you do this on your windows system?

**Comment by aafayed** [comment]
Hi Ben @bwp91 , Yes, I did. The way it happened is that I noticed that the plugin had an update. When I tried to update, an error message came out saying that I need to first update my Node.js to the latest version. I followed the instructions associated with the platform I'm using for homebridge at:
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10-Using-Hyper-V

So I opened a terminal in homebridge and executed the command sudo hb-service update-node.
I then went back to update the plugin (after restarting the server), and this is when I started to have the error I reported. Since that time, I tried to uninstall the plugin so that I install it again. However, even when I try to uninstall or even install a previous version, I get the same error. The things i, the light I'm using with the plugin works just fine. So it seems that the plugin is still working correctly. It just does not want to update.

**Comment by bwp91** [comment]
The node update is quite tricky to do correctly, when i get to my laptop in a minute i will type out the necessary terminal commands in an order to make sure everything gets working again

**Comment by aafayed** [comment]
Thanks, @bwp91 for being so helpful. I'm looking forward to it.

**Comment by bwp91** [comment]
1. Downgrade node to 14.18.1
    ```
    sudo hb-service update-node 14.18.1
    ```
2. Update npm to the latest version 8
    ```
    sudo npm i -g npm
    ```
3. Uninstall govee plugin
    ```
    sudo npm uninstall -g homebridge-govee
    ```
4. Update node to 16.13.0
    ```
    sudo hb-service update-node 16.13.0
    ```
5. Re-update npm to the latest version 8
    ```
    sudo npm i -g npm
    ```
6. Reinstall govee plugin
    ```
    sudo npm i -g homebridge-govee
    ```

If at any point any of the commands fails, please let me know with the output here! But this *should* get everything working again.

**Comment by aafayed** [comment]
Thanks you so much, @bwp91 . The steps you described worked very well. The only issue I faced is that the command:
sudo npm uninstall -g homebridge-govee did not uninstall the plugin. I got the message below:
![image](https://user-images.githubusercontent.com/94153877/141519974-8dd994ef-593f-483f-b818-a1e234ee0b42.png)
but when I restart homebridge and check the plugins, I can still see it installed. So I went ahead and used the homebridge interface instead of the terminal to uninstall, which worked.
After reinstalling the plugin, though, I saw the following message:
![image](https://user-images.githubusercontent.com/94153877/141520172-5d183dcc-b8f7-4926-876c-1173949e3f8f.png)

However, I went ahead and updated homebridge to the latest version, which got rid of that message.

The only message left that I don't know what to do with is:
![image](https://user-images.githubusercontent.com/94153877/141520292-9cdd623f-4cab-4d64-b24f-1fbe0fec858b.png)

I don't know how serious it is. Other than that, everything seems to be working well and the plugin is now at the latest version of v4.17.0.

**Comment by bwp91** [comment]
I’ve never seen that bluetooth warning message. Do you use bluetooth at all to control the devices?

**Comment by aafayed** [comment]
The particular Govee LED light strip I have can be controlled through BT or WIFI. It only uses BT if the phone is in a close proximity (and BT of the phone is turned on), otherwise it uses WIFI. So maybe the plugin is just disabling the BT feature? I'm not sure.

**Comment by bwp91** [comment]
First just want to check everything seems okay with your homebridge instance and all the updates, everything seems like how it was before?

**Comment by aafayed** [comment]
So far, everything seems to be normal. It may take a day or two until I notice anything weird. I will keep you posted though if I see anything. Thank you so much for your help.

**Comment by bwp91** [comment]
Ah, the bluetooth warning message may be because your homebridge instance doesn’t have access to a bluetooth module?

**Comment by aafayed** [comment]
That is possible too. Honestly, it doesn't bother me. I hate BT anyway :) The range never works from the basement to the other floors :)
