### ISSUE TITLE
Error while updating from 4.17 -> 4.18

### ISSUE THREAD

**Issue by Nils89** [bwp91/homebridge-govee#146]
### What issue do you have? Please be as thorough and explicit as possible.
I got this error while updating from 4.17 -> 4.18:

TypeError: Class extends value undefine
d
is not a constructor or null
at Object.<anonymous>(/usr/local/1
ib/node modules/npm/node modules/socks-
proxy-agent/dist/agent.js:114:44)
at Module. compile (node: internal/m
odules/cjs/loader:1101:14)
at Object.Module.
extensions.
.jS
(n
ode:internal/modules/cjs/loader:1153:10

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

1.3.6

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi
Node: 16.13.0
NPM: 8.1.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Currently on 4.17.0

**Comment by bwp91** [comment]
Hi @Nils89 

Please follow the steps here:

https://github.com/bwp91/homebridge-govee/issues/142#issuecomment-967276355

This should get everything working again!

**Comment by Nils89** [comment]
Thank you very much :)
