### ISSUE TITLE
H6117 39% Brightness issue

### ISSUE THREAD

**Issue by Captainscarlet22** [bwp91/homebridge-govee#15]
**What issue do you have? Please be as thorough and explicit as possible.**
I have the H6117 model and the brightness sticks to 39% in HomeKit. Even though I know the lights are @ 100%. Moving to 100% in HomeKit will stay for a few seconds and then go back to 39%. I suspect it's the same issue as some of the other models. 
...

**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge
...

Which version of Homebridge/HOOBS do you have?
1.1.6
...

Which version of this plugin (homebridge-govee) do you have?
2.1.0-0
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.
[11/14/2020, 4:38:04 PM] [Govee] [getDevice()] HTTP Response:
{
  "data": {
    "device": "3C:50:A4:C1:38:39:06:70",
    "model": "H6117",
    "properties": [
      {
        "online": true
      },
      {
        "powerState": "on"
      },
      {
        "brightness": 100
      },
      {
        "color": {
          "r": 0,
          "b": 255,
          "g": 0
        }
      }
    ]
  },
  "message": "Success",
  "code": 200
}
[11/14/2020, 4:38:08 PM] [Govee] [updateDevice()] HTTP Request. This message is yellow for clarity:
{
  "device": "3C:50:A4:C1:38:39:06:70",
  "model": "H6117",
  "cmd": {
    "name": "brightness",
    "value": 254
  }
}
[11/14/2020, 4:38:08 PM] [Govee] [Zoey’s led lights] could not be updated and its status will revert soon - Request failed with status code 400.
...

**Comment by bwp91** [comment]
Hi @Captainscarlet22 
Thanks for reporting this.
I see you are already on a beta version, please update to the newest beta v2.1.0-3 and this should be fixed :)

**Comment by Captainscarlet22** [comment]
Thank you!!! Works perfect!!!!! That was quick! :)
