### ISSUE TITLE
Bluetooth state powered off

### ISSUE THREAD

**Issue by jogoyo** [bwp91/homebridge-govee#150]
### What issue do you have? Please be as thorough and explicit as possible.
The Govee plugin is unable to scan for Bluetooth devices due to: [Govee] [noble] stateChange: poweredOff when Homebridge boots up. Anytime I try to control the lights, it reverts to API because Bluetooth is not in correct state.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
1.3.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
In a Docker container running on an Unraid host. The host detects my Bluetooth dongle as:
Bus 001 Device 018: | ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode) and Unraid loads the proper drivers.

Node.js v16.13 & Npm v8.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v4.18

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6159

### Please paste any relevant logs below.
```
[11/26/2021, 12:00:15 PM] [Govee] Bluetooth hardware and packages found successfully.
[11/26/2021, 12:00:16 PM] [Govee] [Bed Lights] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H6159].
[11/26/2021, 12:00:16 PM] [Govee] [Bed Lights] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableAWS":"no","enableBT":"yes","logging":"debug"}.
[11/26/2021, 12:00:16 PM] [Govee] [Bed Lights] initialised with id [xxx].
[11/26/2021, 12:00:16 PM] [Govee] ✓ Setup complete. Have time to give this plugin a review? http://bit.ly/hb-govee-review
[11/26/2021, 12:00:16 PM] [Govee] [noble] stateChange: poweredOff.
[11/26/2021, 12:06:46 PM] [Govee] [Bed Lights] reverting to API as BLE adapter not in correct state [poweredOff] at BluetoothLED.updateDevice (/homebridge/node_modules/homebridge-govee/lib/connection/ble.js:126:13).
```

**Comment by bwp91** [comment]
Hi @jogoyo 

The package that this plugin uses to communicate with the devices is called [noble](https://github.com/abandonware/noble).

In your case it is reporting to the plugin that the bluetooth adapter is turned off, and so in turn the plugin is skipping the bluetooth communication and reverting to the api.

You’re lucky in a sense that your device supports the API otherwise would be uncontrollable.

However the issue seems to be that the noble is reporting the bluetooth status as powered off - however i’m assuming that you have it powered on since i guess you have checked this.

Perhaps it is a software/hardware issue maybe running in a container? i’m not sure as i have never tested the bluetooth capability with other systems.

**Comment by jogoyo** [comment]
I'm unsure what you mean by powered on. It's plugged into a rear USB 3.0 slot of my server. So I assume it's powered on... Is there a command in the container I need to run to "enable" it? Thanks for the help!

**Comment by bwp91** [comment]
The prerequisites for noble can be found [here](https://github.com/abandonware/noble#prerequisites)... I am not familiar at all with how to get this working with unraid/docker.

This noble package provides the plugin with the current state of the bluetooth adapter, which can be

- unknown
- resetting
- unsupported
- unauthorized
- poweredOff
- poweredOn

The plugin can only scan and send commands when noble reports the adapter in `poweredOn` state. If your dongle is plugged into the usb then yes it sounds like noble *should* be reporting this as `poweredOn`, however for some reason noble thinks it is in `poweredOff` state.

Is your container running with the `--network=host` option?
