### ISSUE TITLE
BLE

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-govee#151]
### What issue do you have? Please be as thorough and explicit as possible.

Error about BLE control 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

1.3.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Hoobs box (PI 3+)

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

4.18.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6159

### Please paste any relevant logs below.

```

[27/11/2021.
08:14:181 [Goveel Disabli
ng BLE client
as
ENODEV.
No such devic
e
a GoveePlatform.pluginSetup(/usr/l
ocal/lib/node
modules/homebridge-govee
/lib/index.is:342:18).
[27/11/2021.
08:14:191 [Govee] [Letto]
if you notice
any flickering when
cha
nging the brightness/colour,
let me kn
Ow
on
Discord/Github with model
number
[H61591.
[27/11/2021,
08:14:191 [Govee] [Letto]
initialising
with options
{
adaptivel
ightingShift"
•Or
.
"brightnessstep"
•1
"di
sableAws"
, "no"
g".
,
enableBT": "no"
, "loggin
"standard"}
[27/11/2021,
08:14:191
[Govee] [Lettol
initialised with id (7E:7:A4:C1:38:2
2: C7:1F1.
[27/11/2021, 08:14:19] [Govee] [Ingres
so] if you
notice
any flickering when
changing the brightness/colour,
let me
know on
Discord/Github with model
num
ber [H61591.
[27/11/2021
08:14:191 [Govee] [Ingres
sol initialising
with options
{"
adapti
veLightingshift"
•0
"brightnessStep":1,
"disableAWS"
"no"
"enableBI": "no" ,
"10g
ging"
"standard"}
[27/11/2021
08:14:191 [Goveel [Ingres
so] initialised with id [8E:3F:A4:C1:3

```

**Comment by Stetocasa** [comment]
![image](https://user-images.githubusercontent.com/70729310/143672304-d236e6fd-8315-4df1-b523-40e2b64b0a61.jpeg)

**Comment by bwp91** [comment]
You may need to install the `pi-bluetooth` package on your raspberry pi:

```
sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev pi-bluetooth
```
