### ISSUE TITLE
Plugs No Longer Showing Up In Homekit

### ISSUE THREAD

**Issue by tjridge** [bwp91/homebridge-govee#152]
### What issue do you have? Please be as thorough and explicit as possible.

- Plugs are no longer showing up in homekit 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

-HOOBS

* Which version of Homebridge/HOOBS do you have?

- 4.0.104

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

-4.18

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Dual and single WiFi plugs 

```

```

**Comment by bwp91** [comment]
Hi,

Can you restart the govee bridge and paste here all the logs from the plugin setting up?

**Comment by bwp91** [comment]
On a side note, i would also recommend updating to the latest version of hoobs (v4.1). If it’s not showing as an update in the hoobs ui, you can use a terminal to ssh into the box and run this command:

```
curl -sk https://dl.hoobs.org/fix | sudo bash - 
```
