### ISSUE TITLE
Air Purifier not supported?

### ISSUE THREAD

**Issue by Jayva2002** [bwp91/homebridge-govee#154]
### What issue do you have? Please be as thorough and explicit as possible.
Air purifiers reported as not supported during start.  Both model H7122 and H7121.  Supported devices indicates both are supported.  Change log also indicates on/off support for these models.  Does Bluetooth need to be enalbe for these devices?

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
I use (1) Homebirdge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.3.8 (HAP v0.9.7) 

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
MACOS; NPM 8.0.0; Node 14.15.4

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v4.18.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H7122 and H7121 - reported in logs as not supported? 

### Please paste any relevant logs below.

[12/6/2021, 10:24:38 AM] [Govee] Disabling BLE client as no enabled devices configured.
[12/6/2021, 10:24:38 AM] [Govee] [LR Air] is not currently supported, do create a Github issue with the following info:
{"device":"25:F7:D4:AD:FC:05:62:12","deviceName":"LR Air","model":"H7122","httpInfo":{"groupId":0,"device":"25:F7:D4:AD:FC:05:62:12","sku":"H7122","spec":"","versionHard":"1.02.00","versionSoft":"1.00.07","deviceName":"LR Air","deviceExt":{"deviceSettings":"{\"wifiName\":\"*****\",\"address\":\"D4:AD:FC:05:62:13\",\"bleName\":\"ihoment_H7122_6213\",\"topic\":\"GD/c559905a5b4719e5805cce7f6b424668\",\"wifiMac\":\"D4:AD:FC:05:62:12\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.07\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"NFJTAgIBA1Y=\",\"filterExpireOnOff\":1,\"sku\":\"H7122\",\"device\":\"25:F7:D4:AD:FC:05:62:12\",\"deviceName\":\"LR Air\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.07\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/cff9b6cc1a82569bca75e4f4cc659466-add_list_type_device_7122.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":79},"isAPIDevice":false}
[12/6/2021, 10:24:38 AM] [Govee] [LR Corner Lamp] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableAWS":"no","enableBT":"no","logging":"standard"}.
[12/6/2021, 10:24:38 AM] [Govee] [LR Corner Lamp] initialised with id [69:DD:D5:31:30:30:3E:7E].
[12/6/2021, 10:24:38 AM] [Govee] [BR AirPurifier] is not currently supported, do create a Github issue with the following info:
{"device":"7E:67:9C:04:A0:95:33:FF","deviceName":"BR AirPurifier","model":"H7121","httpInfo":{"groupId":0,"device":"7E:67:9C:04:A0:95:33:FF","sku":"H7121","spec":"","versionHard":"1.02.00","versionSoft":"1.00.20","deviceName":"BR AirPurifier","deviceExt":{"deviceSettings":"{\"wifiName\":\"****\",\"address\":\"9C:04:A0:95:34:00\",\"bleName\":\"ihoment_H7121_3400\",\"topic\":\"GD/a26ee8be3dd817aee920f4e1ba884941\",\"wifiMac\":\"9C:04:A0:95:33:FF\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.20\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"OAhRWANRD1E=\",\"filterExpireOnOff\":1,\"sku\":\"H7121\",\"device\":\"7E:67:9C:04:A0:95:33:FF\",\"deviceName\":\"BR AirPurifier\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.20\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/96e6e357d8b360781c9c4564469c4c4a-add_list_type_device_7121.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":72},"isAPIDevice":false}
```

```

**Comment by bwp91** [comment]
Hi @Jayva2002 

Please update to the beta version of the plugin. I’ve gotten a bit ahead of myself with updating the wiki before releasing the new version of the plugin!

**Comment by bwp91** [comment]
Currently only on/off is supported. You’re the first person I know with the purifier.

If you’re happy to work with me I can try to implement other features of the purifier,

**Comment by Jayva2002** [comment]
Thanks.  That was quick!  Happy Holidays

**Comment by Jayva2002** [comment]
Sure, what ever you need.  I really only need the on/off functions, as I just like to turn everything off when I leave the house.  I am not that tech savoy, but happy to help support a developer anyway I can.

-Jay

**Comment by bwp91** [comment]
Could we message on discord? I find it a lot easier and simpler on there

https://discord.gg/cMGhNtZ3tW
