### ISSUE TITLE
LightStrip for Car, in HomeKit 

### ISSUE THREAD

**Issue by heberlej** [bwp91/homebridge-govee#155]
* **Please explain your feature request in a one or two sentences.**
It would be nice to set an Automation when iPhone connecting to CarPlay or certain events trigger as notification to change color and Brightness of these strips. :) 

* **Is your feature request related to a problem? Please describe.**
I don´t hink so. 

* **Any particular Govee devices that this relates to?**
H6114_163E

* **Anything else?**
The Log of HOOBS 

{"device":"3A:6A:A4:C1:38:AA:16:3E","deviceName":"H6114_163E","model":"H6114","httpInfo":{"groupId":0,"device":"3A:6A:A4:C1:38:AA:16:3E","sku":"H6114","spec":"","versionHard":"1.00.01","versionSoft":"1.01.23","deviceName":"H6114_163E","deviceExt":{"deviceSettings":"{\"bleName\":\"ihoment_H6114_163E\",\"ic\":0,\"sku\":\"H6114\",\"device\":\"3A:6A:A4:C1:38:AA:16:3E\",\"deviceName\":\"H6114_163E\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.01.23\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/ef7972abc611efa3a4d26ba8c65f70cf-add_list_type_device_6114.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/2d3f45685089d2e76927a6345b61ade1-new_light_title_car_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7200c733005cb1be318b3c630af1d0c9-new_light_title_car_off.png\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}

Thanks in Advance ``

**Comment by bwp91** [comment]
Hi @TCHNLVR-HJ

If you update to the beta version of the plugin, this device should be supported.

Instructions for hoobs:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version#hoobs-4

You will need to add a configuration entry for your lights with the device id and explicitly enabling bluetooth control.

Let me know if you have any difficulty as sometimes a couple of extra things need to be installed to enable bluetooth in general.
