### ISSUE TITLE
Resolution of temperature only 0.5 accuracy ? in Home app? H5179

### ISSUE THREAD

**Issue by alegend2k** [bwp91/homebridge-govee#156]
Im using the above sensor and home app shows only .5 degrees whereas EVE shows .1 degree temperature accuracy.
Is this a normal behavior?
Im on IOS 15.1.1 and using Homebridge 1.38 on Synology via Docker

Thx for info on this.

**Comment by bwp91** [comment]
Hi @alegend2k 

Yes this is normal for the Home app. The plugin updates the current temperature value with a 0.1 degree accuracy, this is why the Eve app is able to show this degree, but the Home app rounds to the nearest 0.5 degrees.

Not sure why it does this!

**Comment by alegend2k** [comment]
ah ok perfect! 
thx for info on this!!!
