### ISSUE TITLE
No API yet for this accessory, but a heads-up

### ISSUE THREAD

**Issue by tjb1013** [bwp91/homebridge-govee#157]
###### I understand that this device is not supported yet, adding this issue just to get it on a "look for" list.

{"device":"E4:80:A4:C1:38:CB:1B:D1","deviceName":"Bedroom Thermometer","model":"H5174","httpInfo":{"groupId":0,"device":"E4:80:A4:C1:38:CB:1B:D1","sku":"H5174","spec":"","versionHard":"1.00.01","versionSoft":"1.00.02","deviceName":"Bedroom Thermometer","deviceExt":{"lastDeviceData":"{\"online\":false,\"tem\":1240,\"hum\":5670,\"lastTime\":1639167960000}","deviceSettings":"{\"battery\":100,\"humMax\":10000,\"temCali\":0,\"humMin\":0,\"address\":\"A4:C1:38:CB:1B:D1\",\"temMax\":6000,\"humCali\":0,\"temWarning\":false,\"bleName\":\"GVH5174_1BD1\",\"temMin\":-2000,\"humWarning\":false,\"deviceName\":\"Bedroom Thermometer\"}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/51892cfa7af72d45ff8ced6f49d620c2-add_list_type_device_h5174.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":8},"isAPIDevice":false}

**Comment by tjb1013** [comment]
Oops not a wifi device ... nm

**Comment by bwp91** [comment]
Are you running homebridge on a raspberry pi?

**Comment by tjb1013** [comment]
Yes, sorry:

## What issue do you have? Please be as thorough and explicit as possible.

Temperature sensor not supported in API. Model H5174

## Details of your setup.

##### Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?

homebridge-config-ui-x v4.41.3 

##### Which version of Homebridge/HOOBS do you have?
Homebridge v1.3.8

##### Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi
Node.js v14.18.2
NPM v6.14.15

##### Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee v4.19.0

##### Which Govee devices do you have that are causing issues? Please include product models if applicable.
H5174 - reported in logs as not supported?

##### Please paste any relevant logs below.
Repeat from above:

[Bedroom Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"E4:80:A4:C1:38:CB:1B:D1","deviceName":"Bedroom Thermometer","model":"H5174","httpInfo":{"groupId":0,"device":"E4:80:A4:C1:38:CB:1B:D1","sku":"H5174","spec":"","versionHard":"1.00.01","versionSoft":"1.00.02","deviceName":"Bedroom Thermometer","deviceExt":{"lastDeviceData":"{\"online\":false,\"tem\":1390,\"hum\":4980,\"lastTime\":1639168140000}","deviceSettings":"{\"battery\":100,\"humMax\":10000,\"temCali\":0,\"humMin\":0,\"address\":\"A4:C1:38:CB:1B:D1\",\"temMax\":6000,\"humCali\":0,\"temWarning\":false,\"bleName\":\"GVH5174_1BD1\",\"temMin\":-2000,\"humWarning\":false,\"deviceName\":\"Bedroom Thermometer\"}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/51892cfa7af72d45ff8ced6f49d620c2-add_list_type_device_h5174.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":8},"isAPIDevice":false}

**Comment by bwp91** [comment]
You may have success with this plugin? It uses the raspberry pi bluetooth to scan for nearby sensors and reads the data.
https://github.com/asednev/homebridge-plugin-govee

I know H5174 isn't officially on that plugin's supported list, but, it may work in the same way as other similar models.

**Comment by tjb1013** [comment]
That worked! Thanks for the tip.

**Comment by bwp91** [comment]
Oh good! and the sensor readings are accurate?
I think the dev of that plugin would be interested to know your model is working with the plugin
