### ISSUE TITLE
H6181 timeout

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-govee#158]
### What issue do you have? Please be as thorough and explicit as possible.

Led strip H6181 recognized from the plug-in but not work the control ON/OFF

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI

* Which version of Homebridge/HOOBS do you have?

1.3.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Hoobs box (PI 3+)

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Last

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6181

```

[11/12/2021, 21:46:00] [Govee] [Strisc
ia Led Scrivania] could not be updated
as
timeout of 8 seconds exceeded.

```
 This is my config:
```

name": "Govee",
            "username": "xxxxxx",
            "password": "xxxxxxx!",
            "apiKey": "4169ac97-ce21-xxxxxxx77cb",
            "lightDevices": [
                {
                    "label": "Striscia LED",
                    "deviceId": "6F:9E:A4:C1:38:D1:3E:22",
                    "enableBT": true
                },
                {
                    "label": "Led Scrivania",
                    "deviceId": "53:71:A4:C1:38:51:BE:53",
                    "enableBT": true
                }
            ],
            "platform": "Govee"
        },

```
No relevant info from debug mode

**Comment by Stetocasa** [comment]
![image](https://user-images.githubusercontent.com/70729310/145692664-d50f889e-7652-47b9-a922-aa88b8d4e582.jpeg)

**Comment by Stetocasa** [comment]
@bwp91

**Comment by bwp91** [comment]
Hi @Stetocasa 

Please show logs from debug mode when trying to control this device.
