### ISSUE TITLE
Bluetooth address incorrect

### ISSUE THREAD

**Issue by DerGenus** [bwp91/homebridge-govee#159]
First of all, thanks for the plugin.

I came across a little inconvenience.
My Govee LED Strips ( H6102 & H6127 ) where recognised and I got them integrated with my pre-existing Apple HomeKit.
The trouble began when I tried to control the Strips. The Homebridge Log reported a timeout every time I tried to do anything with the lights. After finding the debug option in Homebridge and trying a couple of things I found the problem. The predetermined bluetooth Address (or "customAddress" in the config) was incorrect. The Debug showed a bluetooth device with a different bluetooth Address but the ihoment name, which I knew was the name of the Lightstrip controller. Everything worked after I changed the address to the one I found in the logs.
If I remember correctly the "add light" dialog said something about older devices not having the right bluetooth address. 
It would be awesome if you could add a short text on how to get the right bluetooth address.

**Comment by bwp91** [comment]
Hi @DerGenus 

So did you get your lights working in the end? The debug of showing addresses found in the log is very new and the idea was to help to discover the real address of such devices.

I will add to the wiki some instructions of how to find the bluetooth address.

But primarily just wanted to make sure you got your lights working via bluetooth?

**Comment by DerGenus** [comment]
Lights are working great, better than I was expecting. 👍
Thanks for the quick response.

**Comment by bwp91** [comment]
I made a heading for the section!
https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control#finding-the-bluetooth-address

Would you be able to go into detail about how you found the correct bluetooth address? I’ll be happy to made edits but it would be great to get first hand instructions 😊

**Comment by DerGenus** [comment]
Sorry for the late response.
The following steps assume that the unresponsive Lights were setup following the guide on GitHub and show up in the homebridge interface and the Apple HomeKit app.
To find the "correct" bluetooth address you have to enable the debug log option in the govee plugin settings.
After enabling the setting and restarting homebridge try to change the state of a connected govee light (for example: try turning on the unresponsive LED light strip). The log will show all bluetooth devices in range (log entries are marked with [noble] followed by the bluetooth address and a identifying name).
The tricky part ist finding the right entry. My Govee Light Strip H6102 showed up as [ihoment_H6102_A7F8]. A quick internet search confirmed the relation to my govee light strip. Copy the bluetooth address and paste it in the light setup dialog in the govee plugin settings. After that restart homebridge and everything should word flawlessly. Just verified these steps by nuking my homebridge install and setting it up again while following the setup guide here on GitHub.
Hope this helps. I will try to respond as quick as possible if you have further questions.

**Comment by bwp91** [comment]
Thanks for that, I made a couple of edits but I think it's clear how to find the address.

https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control#finding-the-bluetooth-address

I've also added a link to this section in the plugin settings screen:

<img width="690" alt="Screenshot 2021-12-16 at 14 10 36" src="https://user-images.githubusercontent.com/43026681/146387480-0890b6cd-bad7-4f3e-bb88-a3580aa4d0fe.png">
