### ISSUE TITLE
"personal requests" mandatory to turn on/off/change colour after recent plugin update?

### ISSUE THREAD

**Issue by roninniagara** [bwp91/homebridge-govee#161]
First off: thank you for this plugin! It's fantastic.

I recently updated the plugin - the device still works through the home app. As do the scenes.

But now through any homepod it's THE ONLY device giving me a "you have to turn on personal requests" issue out of every device in the house. It only started after updating. Nothing else changed except that.

Any help appreciated. Thanks!

**Comment by bwp91** [comment]
Hi @roninniagara 

I don't own a HomePod so I was unaware of this 'personal requests' feature. However I am unsure why it is saying this. Do you have the HomePod setup as a HomeKit home hub?

I don't think I have made any changes to the plugin that could cause this... could it have started with another event like updating the software on the HomeHub?

**Comment by roninniagara** [comment]
> Hi @roninniagara
> 
> I don't own a HomePod so I was unaware of this 'personal requests' feature. However I am unsure why it is saying this. Do you have the HomePod setup as a HomeKit home hub?
> 
> I don't think I have made any changes to the plugin that could cause this... could it have started with another event like updating the software on the HomeHub?

I have an apple tv 4k as my hub. then 7 homepods around the house.

Found out the issue. I had named the lights "Front deck lights" - but when I renamed them to "Front Deck LED" it worked. strange.

Thank you for the reply and also for the hard work on the plugin!
