### ISSUE TITLE
Govee H613E

### ISSUE THREAD

**Issue by Dsopinka** [bwp91/homebridge-govee#162]
* **Please explain your feature request in a one or two sentences.**
* Would love to see these RGB strips for homebridge

* **Is your feature request related to a problem? Please describe.**
No problem

* **Any particular Govee devices that this relates to?**
H613E

* **Anything else?**
Imagine
![577E874E-2BD6-41BD-83B2-328ECA3F7D17](https://user-images.githubusercontent.com/96312744/146593267-8a4dca9d-de8b-4bdc-a0c1-c338c373651f.png)

**Comment by bwp91** [comment]
Hi @Dsopinka 

If you update to the beta version of the plugin this device should be added to your homebridge.

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by Dsopinka** [comment]
Hey thanks for the response. Getting unknown error when trying to access that link and the beta link on your page.

Image attached.

Thanks,
David![image](https://user-images.githubusercontent.com/96312744/146629362-cc27560f-3a29-4452-9193-9355e8c1cd6e.png)

**Comment by bwp91** [comment]
Can you try again? in a different browser?
