### ISSUE TITLE
Support for B5041102 thermometer?

### ISSUE THREAD

**Issue by daversion** [bwp91/homebridge-govee#166]
* **Please explain your feature request in a one or two sentences.**
Hi. I was wondering if the above mentioned model of thermometer is supported. I didn't see it in the list. It appears to be a wi-fi thermometer.
https://www.amazon.com/dp/B0834SNGQW/

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

* **Anything else?**
Nope. Thanks.

**Comment by bwp91** [comment]
Hi @daversion 

Since it's a wifi model, there shouldn't be a reason why it couldn't be implemented into the plugin.

Do you own this device already?

**Comment by daversion** [comment]
Hi. I don’t but was considering picking one up if it had some plugin support. If I can help your efforts (and vice versa) I can pick one up and report back if it works. I’m not clear if you need to do anything to enable the model number or if it may already work with the existing plugin protocols.

**Comment by bwp91** [comment]
I don't know if this model would work straight off, as it's effectively a hub with multiple subdevices rather than the existing supported single wifi device.

However with a bit of debug logging which I would guide you what I needed, there's no reason why I wouldn't be able to implement it into the plugin.

**Comment by daversion** [comment]
Thanks. When I end up picking one up I'll add a comment or create a new ticket. They went off sale yesterday.

**Comment by bwp91** [comment]
Cool, I will close this issue for now, if you manage to get this device then feel free to reopen this or create a new issue!
