### ISSUE TITLE
H5101 not updating and offline

### ISSUE THREAD

**Issue by jmlumpkin** [bwp91/homebridge-govee#168]
### What issue do you have? Please be as thorough and explicit as possible.

H5101 was able to get all stats automatically at first, but now only seems to ever update battery percentage. So it does see the device on Bluetooth and updates, but not temp and humidity data. I was actually amazed to see it work out of the box, but then appears that it won't update just those parameters, but does see the devices, as it updates battery. It does show that the devices are offline in the settings, but the log shows battery updates. As I look through though, they don't change much. The log just notes device being reported offline. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI. This is on Ubuntu with a USB Bluetooth connector. Bluetooth is working and seeing devices.

* Which version of Homebridge/HOOBS do you have?

Homebridge 1.3.8.

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Ubuntu

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

4.20.2. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H5101

### Please paste any relevant logs below.

```
No logs showed errors beyond what's reported above.
```

**Comment by jmlumpkin** [comment]
While testing this some, I noticed the devices hadn't synced to the Govee app either (although it said it had). When refreshing there, they also have the right data in HomeKit. So it seems like it's not "waking up" the devices to read, unless I am missing something.

**Comment by bwp91** [comment]
Hi @jmlumpkin 

Can you enable plugin debug logging and show me some of the logs that appear from the polling that happens every 15 seconds?

**Comment by jmlumpkin** [comment]
Hi @bwp91 

Sorry about that - It didn't have anything really (and I was on phone sending this in, which doesn't let you copy logs well). 

`[12/29/2021, 6:40:56 PM] [Govee] [Small Bin] [HTTP] receiving update [{"source":"HTTP","battery":94,"temperature":1880,"humidity":5110,"online":false}].
[12/29/2021, 6:40:56 PM] [Govee] [Large Bin] [HTTP] receiving update [{"source":"HTTP","battery":99,"temperature":1880,"humidity":3270,"online":false}].
[12/29/2021, 6:40:56 PM] [Govee] [Garage] [HTTP] receiving update [{"source":"HTTP","battery":89,"temperature":1560,"humidity":4770,"online":false}].
[12/29/2021, 6:40:56 PM] [Govee] [Office] [HTTP] receiving update [{"source":"HTTP","battery":94,"temperature":1980,"humidity":4620,"online":false}].
[12/29/2021, 6:40:56 PM] [Govee] [Playroom] [API] receiving update [{"source":"API","online":true,"powerState":"off","brightness":100,"color":{"r":255,"b":0,"g":0}}].`

It seems to get a new temp if I sync in the Govee app, versus talking to these through bluetooth. I assumed it auto-found them, but wondering it its because it found them through the API? Do I need to hide those, and add manually though Bluetooth setup/config?

**Comment by bwp91** [comment]
This plugin doesn’t communicate with sensors via bluetooth, it uses the cloud data to update the values.

From the logs you can see why the plugin is marking the device offline, since govee is (incorrectly?) reporting the device as offline.

There is another govee plugin that communicates via bluetooth to these sensors, you may have more luck with that one. I don’t think your model is stated as supported, but it might still work, worth a try.

https://www.npmjs.com/package/homebridge-plugin-govee

This plugin automatically scans for govee sensors and reads the data periodically.

Try it and let me know if it works!

**Comment by jmlumpkin** [comment]
Is there a way to then 'hide' these sensors from this plugin?

**Comment by bwp91** [comment]
Yes, you can use the config with the device id to hide it from this plugin.

**Comment by bwp91** [comment]
Out of interest, are all your devices connected to wifi? Or do they connect to some govee gateway device? And if so, is this connected to wifi?

**Comment by jmlumpkin** [comment]
Only my lights (which is where I got started with this plugin). These little H1501's are bluetooth only. They sync with the phone, and then that is copied to the Govee cloud. I am assuming you then read from the 'cloud' API and end up getting those values. It would be awesome if this could talk directly through bluetooth (like that other plugin you shared above). The devices themsevles do advertise openly through Bluetooth, and I can see them through the bluetooth connector on my server (that this instance of HomeBridge is on)

**Comment by jmlumpkin** [comment]
(Sorry, clicked the wrong button)

**Comment by bwp91** [comment]
Does the other plugin work with them?

**Comment by jmlumpkin** [comment]
Yes, the other plugin found them an added them right away. I don't mind using the other one, thought it would be cool to have it all in one place. 

I never 'set up' the H1501 in this plugin, so they auto-added. I can't seem to figure out how to 'hide' them, and accidentally managed to delete this plugin in the process.

**Comment by jmlumpkin** [comment]
Was also thinking that if this didn't support the Bluetooth devices, and you would know which devices those are, potentially hiding them automatically, or at least not auto adding them? I can't enable your plugin (for lights) until I can remove the others (unless you ended up adding support for devices like this)

**Comment by bwp91** [comment]
In fact in the last version of the plugin, I went ahead and auto removed all the ble only sensors that this plugin doesn't support :)

https://github.com/bwp91/homebridge-govee/blob/latest/CHANGELOG.md#removed

**Comment by jmlumpkin** [comment]
I'll re-enable, as I've updated to that. What is expected behavior? When I disabled earlier for some reason I thought it still showed the other devices.

**Comment by bwp91** [comment]
It will skip these models, and also remove the accessory that this plugin creates if it exists (it won't have any effect on the accessory created by the other plugin)

**Comment by jmlumpkin** [comment]
Marking as closed. Other plugin works as expected, as does this. I do really like your plugin!
