### ISSUE TITLE
Support for H6196_FF89

### ISSUE THREAD

**Issue by CliffPeeples** [bwp91/homebridge-govee#169]
Homebridge UI X v1.39, all plugins up to date: 

[H6196_FF89] is not currently supported, do create a Github issue with the following info:
{"device":"66:C9:A4:C1:38:34:FF:89","deviceName":"H6196_FF89","model":"H6196","httpInfo":{"groupId":0,"device":"66:C9:A4:C1:38:34:FF:89","sku":"H6196","spec":"","versionHard":"1.00.01","versionSoft":"1.04.00","deviceName":"H6196_FF89","deviceExt":{"deviceSettings":"{\"address\":\"A4:C1:38:34:FF:89\",\"bleName\":\"ihoment_H6196_FF89\",\"pactType\":2,\"pactCode\":1,\"ic\":0,\"sku\":\"H6196\",\"device\":\"66:C9:A4:C1:38:34:FF:89\",\"deviceName\":\"H6196_FF89\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.04.00\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"http://s3.amazonaws.com/govee-public/sku-img/78d395fdbdc19b8c8252a61247078ce0-add_list_type_device_6196.png\",\"headOnImg\":\"http://s3.amazonaws.com/govee-public/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"http://s3.amazonaws.com/govee-public/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png\",\"ext\":\"\",\"ic\":0}"},"pactType":2,"pactCode":1,"goodsType":2},"isAPIDevice":false}

**Comment by bwp91** [comment]
Hi @CliffPeeples 

Please update to the beta version of the plugin I've just published, v4.20.4-beta.0.

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version#homebridge-ui

This should enable support for this H6196.

Thanks!

**Comment by bwp91** [comment]
In fact I have just released v4.21.0 of the plugin which includes support for this device!
