### ISSUE TITLE
Support for new Govee TV Lights

### ISSUE THREAD

**Issue by jeanofthedead** [bwp91/homebridge-govee#17]
* **Please explain your feature request in a one or two sentences.**
Could you add support for the H6199 model of TV backlights? Thanks!

**Comment by bwp91** [comment]
Hi @jeanofthedead 
Unfortunately this model is not supported by the Govee API that this plugin uses. There is a fixed device list that the plugin is limited to.
It might be worth you asking Govee directly to support this model, and maybe in a future version of the API I would be able to support the device in this plugin.
Thanks!

**Comment by jeanofthedead** [comment]
Good to know- I appreciate it!

**Comment by bwp91** [comment]
Support for H6199 is available with the new update v2.4.0.
