### ISSUE TITLE
Cannot update or uninstall

### ISSUE THREAD

**Issue by dgeisler-sys** [bwp91/homebridge-govee#170]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have? 1.3.9 ui 4.41.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
16.1 npm 8.3

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
8.1

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

all

### Please paste any relevant logs below.
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-govee
npm ERR! dest /usr/local/lib/node_modules/.homebridge-govee-4xHIsKEi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-govee' -> '/usr/local/lib/node_modules/.homebridge-govee-4xHIsKEi'

```

```

**Comment by bwp91** [comment]
Hi @dgeisler-sys 

Please run the following commands in the homebridge terminal:

1. Delete the current plugin files
    ```
    sudo rm -rf /usr/local/lib/node_modules/homebridge-govee
    ```
2. Install the plugin again
    ```
    sudo npm i -g homebridge-govee
    ```

This should get everything working again

**Comment by dgeisler-sys** [comment]
It did! Thanks for your help
