### ISSUE TITLE
plugin not working after update 

### ISSUE THREAD

**Issue by tjridge** [bwp91/homebridge-govee#173]
After recent update, none of the devices are responding to commands from HomeKit. 

* Do you use Homebridge (with config-ui?) or HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

4.0.104

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

4.22.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

All

### Please paste any relevant logs below.
No logs available

**Comment by bwp91** [comment]
Hi @tjridge 

Please can you post the startup logs from the plugin? 

And logs that appear when you try to control a device?

Which models do you own? It's helpful for me to know which models you have.

Thanks!
