### ISSUE TITLE
Can't control my Govee Light Strip H6127

### ISSUE THREAD

**Issue by Superduperduu04** [bwp91/homebridge-govee#174]
### What issue do you have? Please be as thorough and explicit as possible.
I can't control my Light Strip. A Light is added to my Homekit and I can control it and the plugin log shows the actions, but it belongs not to my Light Strip.
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Hoobs

* Which version of Homebridge/HOOBS do you have?
Hoobs 4.1.20
Homebridge 1.3.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi
Node Version 16.13.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
New installation of 4.23.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6127

### Please paste any relevant logs below.

```
3.1.2022, 14:55:36HOOBSGoveeInitialising plugin v4.23.0 | Node v16.13.1 | HB v1.3.8 | HAPNodeJS v0.9.7 | HOOBS v4...
3.1.2022, 14:55:36HOOBSGoveePlugin initialised. Setting up accessories....
3.1.2022, 14:55:38HOOBSGoveeLogin successful.
3.1.2022, 14:55:39HOOBSGovee[LED Stripe] initialising with options {"adaptiveLightingShift":0,"bluetooth":"disabled","brightnessStep":1,"logging":"debug"}.
3.1.2022, 14:55:39HOOBSGovee[LED Stripe] initialised with id [*****].
3.1.2022, 14:55:41HOOBSGovee✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
```
How can I change the "bluetooth: disabled"? I enabled BLE Control in the plugin settings

**Comment by bwp91** [comment]
Hi,

You will need to create an entry in the “Light Devices” section of the config, all you need to enter is a label for the device, the device id which you have masked out above, and tick the “Enable BLE Control” option, then click save

**Comment by Superduperduu04** [comment]
Yeah, i know - i already did but it doesn't work.🤔

**Comment by bwp91** [comment]
Have you also followed these extra instructions here?

https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control#raspberry-pihomebridge-rpi-imagehoobs-box

**Comment by Superduperduu04** [comment]
Yes, this is what i get from the terminal
``
hoobs@hoobs:~ $ sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev pi-bluetooth
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libudev-dev is already the newest version (241-7~deb10u8+rpi1).
bluetooth is already the newest version (5.50-1.2~deb10u2+rpt1).
bluez is already the newest version (5.50-1.2~deb10u2+rpt1).
libbluetooth-dev is already the newest version (5.50-1.2~deb10u2+rpt1).
pi-bluetooth is already the newest version (0.1.18).
The following packages were automatically installed and are no longer required:
  libbrotli1 nodejs-doc
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hoobs@hoobs:~ $ sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
``

I also added the Bluetooth address in the settings...

**Comment by bwp91** [comment]
Can you turn on debug logging in the plugin settings, then show me all the logs from the plugin loading after restart?

There should be some extra log lines about the state of the bluetooth.

**Comment by Superduperduu04** [comment]
I already turned debug logging on - it's the same as above

```
3.1.2022, 16:09:45HOOBSGoveeInitialising plugin v4.23.0 | Node v16.13.1 | HB v1.3.8 | HAPNodeJS v0.9.7 | HOOBS v4...
3.1.2022, 16:09:45HOOBSGoveePlugin initialised. Setting up accessories....
3.1.2022, 16:09:46HOOBSGoveeLogin successful.
3.1.2022, 16:09:50HOOBSGovee[LED Stripe] initialising with options {"adaptiveLightingShift":0,"bluetooth":"disabled","brightnessStep":1,"logging":"debug"}.
3.1.2022, 16:09:50HOOBSGovee[LED Stripe] initialised with id [AA:99:41:EB:B3:64:2C:A3].
3.1.2022, 16:09:53HOOBSGovee✓ Setup complete. Want to see this plugin in your own language? Let me know!
```

The name of the Device, which is added,  is not the same I configured in the settings:

```
3.1.2022, 16:14:37HOOBSGovee[LED Stripe] current state [on].
3.1.2022, 16:14:39HOOBSGovee[LED Stripe] current state [off].
```

**Comment by bwp91** [comment]
Can you show me the advanced config for govee? i mean the json text.

Can be found at the bottom of the config screen, clicking on Advanced.

Remember to remove your govee username and password!

**Comment by Superduperduu04** [comment]
```json
{
    "username": "***",
    "password": "***",
    "name": "Govee",
    "controlInterval": 500,
    "refreshTime": 15,
    "apiKey": "removed",
    "platform": "Govee",
    "debug": true,
    "lightDevices": [
        {
            "label": "LED Streifen Decke",
            "deviceId": "AA:99:41:EB:B3:64:2C:A3",
            "enableBT": true,
            "customAddress": "A4:C1:38:CC:3E:F1",
            "overrideLogging": "debug"
        }
    ]
}
```

**Comment by bwp91** [comment]
How did you find that this is the ble address of the device? `a4:C1:38:CC:3E:F1`

**Comment by bwp91** [comment]
There is nothing in the logs about the state of the bluetooth hardware packages. There should be some logging either way, whether it’s all okay, or whether there is something wrong.

The fact there is no logging at all is concerning me 🤔

**Comment by Superduperduu04** [comment]
> How did you find that this is the ble address of the device? `a4:C1:38:CC:3E:F1`

I listed all bluetooth devices that the Pi can find and searched for the "[ihoment_HXXXX_XXXX]" like you described. but it doesn't show in the logging - i searched it seperately in the terminal

**Comment by Superduperduu04** [comment]
> There is nothing in the logs about the state of the bluetooth hardware packages. There should be some logging either way, whether it’s all okay, or whether there is something wrong.
> 
> The fact there is no logging at all is concerning me 🤔

yes, i don't know, maybe i did something wrong with the installation for the bluetooth... Should happen something after i put "sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)" in the terminal line or is there no response?

**Comment by bwp91** [comment]
Would you be happy to delete the plugin and bridge? and start again?

Which raspberry pi model do you have?

**Comment by Superduperduu04** [comment]
I have some other plugins installed and would not completely reset my Bridge or pi.... Is it enough to add another Bridge to my Hoobs, where only the govee plugin is installed?

I think I have the Raspberry Pi 3

**Comment by bwp91** [comment]
> I have some other plugins installed and would not completely reset my Bridge or pi.... Is it enough to add another Bridge to my Hoobs, where only the govee plugin is installed?

Ah yes in this case just uninstall the govee plugin and reinstall it. it would be worth taking the opportunity to put it in it's own bridge. It's recommended to do this for stability.

**Comment by Superduperduu04** [comment]
I have added a new Bridge to my Hoobs and installed only the govee plugin. I added my email, the API and the Device ID ang now got this from my log:

```
3.1.2022, 17:44:31GoveeConfiguration change
3.1.2022, 17:44:41GoveeFEHLER[31mThe plugin "homebridge-govee" requires a Homebridge version of ^1.3.9 which does not satisfy the current Homebridge version of 1.3.8. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
3.1.2022, 17:44:41GoveeLoaded plugin 'homebridge-govee'
3.1.2022, 17:44:41GoveeLoading 1 platforms...
3.1.2022, 17:44:41GoveeGoveeInitialising plugin v4.23.0 | Node v16.13.1 | HB v1.3.8 | HAPNodeJS v0.9.7 | HOOBS v4...
3.1.2022, 17:44:41GoveeGoveePlugin initialised. Setting up accessories....
3.1.2022, 17:44:41GoveeBridge is running on port 51836.
3.1.2022, 17:44:44GoveeGoveeBluetooth hardware and packages found successfully.
3.1.2022, 17:44:44GoveeGovee[LED Stripe] has been added to Homebridge.
3.1.2022, 17:44:44GoveeGovee[LED Stripe] initialising with options {"adaptiveLightingShift":0,"bluetooth":"enabled","brightnessStep":1,"logging":"standard"}.
3.1.2022, 17:44:44GoveeGovee[LED Stripe] initialised with id [AA:99:41:EB:B3:64:2C:A3].
3.1.2022, 17:44:46GoveeGovee✓ Setup complete. Have time to give this plugin a review? http://bit.ly/hb-govee-review
3.1.2022, 17:45:03GoveeFEHLER[Govee ABE6@Brightness] The write handler for the characteristic 'Brightness' on the accessory 'LED Stripe' was slow to respond!
3.1.2022, 17:45:03GoveeFEHLER[Govee ABE6@On] The write handler for the characteristic 'On' on the accessory 'LED Stripe' was slow to respond!
3.1.2022, 17:45:08GoveeGoveeWARNUNG[LED Stripe] could not be updated as BLE took too long at BluetoothLED.updateDevice (/var/lib/hoobs/govee/node_modules/homebridge-govee/lib/connection/ble.js:165:15).
3.1.2022, 17:45:08GoveeGoveeWARNUNG[LED Stripe] could not be updated as BLE took too long at BluetoothLED.updateDevice (/var/lib/hoobs/govee/node_modules/homebridge-govee/lib/connection/ble.js:165:15).
```

Does this helps you?

**Comment by bwp91** [comment]
This is _better_. Can you turn on debug logging and try turning on/off again?

**Comment by Superduperduu04** [comment]
I did and the Log shows the Scan - I added the Bluetooth Address and saved it and now it works :) I really don't know why it was not working on the other bridge but now it's all perfect. Thank you very much for your helping! 👍

**Comment by bwp91** [comment]
Great! Glad it’s working :)

**Comment by Superduperduu04** [comment]
Now I'm working on the Custom Scenes and DIY Modes 💯

**Comment by bwp91** [comment]
> Now I'm working on the Custom Scenes and DIY Modes 💯

Since your device is bluetooth only, the AWS codes won’t work. So you’ll have to stick to the existing known bluetooth codes. Unless your tech enough to go sniffing for your own 😊

**Comment by bwp91** [comment]
And in fact since the device is bluetooth only, you don’t need your API key in the config. This is needed just for wifi devices!

**Comment by Superduperduu04** [comment]
Yeah, I try it with the existing Codes.💪🏼
Ah okay thanks.

**Comment by bwp91** [comment]
In fact I found some updated docs this evening, i need to update the wiki 

https://github.com/egold555/Govee-Reverse-Engineering

**Comment by Superduperduu04** [comment]
Oh nice, I will have a look.
I was trying a little bit with the Codes and now says my log this: 
```
3.1.2022, 19:57:32GoveeLoaded plugin 'homebridge-govee'
3.1.2022, 19:57:32GoveeLoading 1 platforms...
3.1.2022, 19:57:32GoveeGoveeInitialising plugin v4.23.0 | Node v16.13.1 | HB v1.3.8 | HAPNodeJS v0.9.7 | HOOBS v4...
3.1.2022, 19:57:32GoveeGoveePlugin initialised. Setting up accessories....
3.1.2022, 19:57:32GoveeBridge is running on port 51836.
3.1.2022, 19:57:38GoveeGoveeWARNUNGDisabling HTTP client as Your account is abnormal, please contact customer service. at connectionHTTP.login (/var/lib/hoobs/govee/node_modules/homebridge-govee/lib/connection/http.js:58:15).
3.1.2022, 19:57:38GoveeGoveeWARNUNGDisabling API client as API key not provided.
3.1.2022, 19:57:38GoveeGoveeBluetooth hardware and packages found successfully.
3.1.2022, 19:57:38GoveeGoveeWARNUNG***** Disabling plugin. *****
3.1.2022, 19:57:38GoveeGoveeWARNUNG***** No devices found to initialise. *****
```

Did I broke it? :D

**Comment by bwp91** [comment]
https://github.com/bwp91/homebridge-govee/issues/172#issuecomment-1003500396

**Comment by Superduperduu04** [comment]
> [#172 (comment)](https://github.com/bwp91/homebridge-govee/issues/172#issuecomment-1003500396)

oh okay - yes i tested a little bit too much :D 
I will wait till tomorrow - thanks again :)
