### ISSUE TITLE
Latest Govee v4.23.0 not working on HOOBs

### ISSUE THREAD

**Issue by BukriChod** [bwp91/homebridge-govee#175]
### What issue do you have? Please be as thorough and explicit as possible.

updated latest version of Govee via HOOBs (v4.23.0) and keep getting the following error: 

HOOBS: ERROR[31mThe plugin "homebridge-govee" requires a Homebridge version of ^1.3.9 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBs

* Which version of Homebridge/HOOBS do you have?

HOOBS 4.0.110

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Pi3

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Yes - since the latest update as of 5 hours ago

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Govee H619A (hardware version 2.01.02, firmware 2.05.21)
Govee H6199 (hardware version 3.02.01, firmware 1.08.12)

### Please paste any relevant logs below.

```

03/01/2022, 14:52:19HOOBSERROR[31mThe plugin "homebridge-govee" requires a Homebridge version of ^1.3.9 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
03/01/2022, 14:52:19HOOBSLoaded plugin 'homebridge-govee'
03/01/2022, 14:52:21HOOBSGoveeWARNING***** Disabling plugin. *****

```

**Comment by bwp91** [comment]
Hi @BukriChod 

Can you show me the next line of the log? 

This shouldn’t be the reason why the plugin is disabling.

In fact this message has no effect on the functionality at all, it is just a warning.

**Comment by bwp91** [comment]
I believe a new version of hoobs will be released tomorrow with the updated version of homebridge. 

you can simply ignore this red message.

**Comment by BukriChod** [comment]
Hi Ben,

Here is the log after I rebooted the HOOBs:

```
03/01/2022, 15:07:18WARNINGdevice reboot command received
03/01/2022, 15:07:18HOOBS stopping
03/01/2022, 15:07:39hub is running on port 80
03/01/2022, 15:07:41HOOBS starting
03/01/2022, 15:07:48HOOBSLoaded plugin 'homebridge-dyson-pure-cool'
03/01/2022, 15:07:48HOOBSERROR[31mThe plugin "homebridge-govee" requires a Homebridge version of ^1.3.9 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
03/01/2022, 15:07:50HOOBSLoaded plugin 'homebridge-govee'
03/01/2022, 15:07:54HOOBSLoaded plugin 'homebridge-lifx'
03/01/2022, 15:08:11HOOBSLoaded plugin 'homebridge-lifx-lan-client'
03/01/2022, 15:08:15HOOBSLoaded plugin 'homebridge-ring'
03/01/2022, 15:08:15HOOBSLoaded plugin 'homebridge-yalesmarthomealarm'
03/01/2022, 15:08:15HOOBSLoading 5 platforms...
03/01/2022, 15:08:15HOOBSLIFxFetching LIFx devices.
03/01/2022, 15:08:16HOOBSGoveeWARNING***** Disabling plugin. *****
```

After this it just loads my lights and Ring devices. No reference to any of the 2 Govee devices currently running via the Govee App. 

Appreciate your help!

**Comment by bwp91** [comment]
I notice that you are still running HOOBS 4.0.110.

I think it would be a good idea to update to HOOBS 4.1. It's much more stable and _could_ be the reason the plugin isn't loading.

This doc link may help:
https://support.hoobs.org/topics/61c9e100dcf29f5e39f034fb/61c9e133dcf29f5e39f03535

**Comment by BukriChod** [comment]
Hi Ben, the doc link to force the upgrade and rebuild did the trick! All working absolutely seamlessly now, I'm very pleased! 

Thanks again for your support!
