### ISSUE TITLE
Govee Plugin 4.23.0 on Hoobs 4.1.20

### ISSUE THREAD

**Issue by Praktiker** [bwp91/homebridge-govee#176]
### What issue do you have? Please be as thorough and explicit as possible.
Setup of plugin was done as in the manual. Device appears in HomeKit but switching on/off does not work.
Log says Bluetooth is disabled, but I checked the box in Config: see screenshot.
Also I followed the instruction to install software for bluetooth on the PI.
Haven't figured out the Bluetooth address, is it really necessary?

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
3

* Which version of Homebridge/HOOBS do you have?
4.1.20
Node: 16.13.1
Homebridge 1.3.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry pi3

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v4.23.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6126

### Please paste any relevant logs below.

4.1.2022, 02:05:55HOOBSGoveeInitialising plugin v4.23.0 | Node v16.13.1 | HB v1.3.8 | HAPNodeJS v0.9.7 | HOOBS v4...
4.1.2022, 02:05:56HOOBSGoveePlugin initialised. Setting up accessories....
4.1.2022, 02:06:03HOOBSGoveeLogin successful.
4.1.2022, 02:06:12HOOBSGovee[Gewitter] initialising with options {"adaptiveLightingShift":0,"bluetooth":"disabled","brightnessStep":1,"logging":"debug"}.
4.1.2022, 02:06:12HOOBSGovee[Gewitter] initialised with id [7F:27:.....].
4.1.2022, 02:06:14HOOBSGovee✓ Setup complete. Check out my other Homebridge plugins! https://github.com/bwp91
```

```
![Bildschirmfoto 2022-01-04 um 02 10 48](https://user-images.githubusercontent.com/16985470/147996760-2266af9d-fc61-48ea-9a1e-b8199e89859c.png)

**Comment by bwp91** [comment]
Can you try reinstalling the plugin?

**Comment by Homekitdude** [comment]
Got mine on Homekit, but when the lights turn on with my evening automation, they turn blue even though they are set to a warm tone. Anyone know how to solve that?

**Comment by Praktiker** [comment]
Hi, I upgraded to the newest version and also reinstalled the plugin. The log says that it switches the light on or off, if I klick in HOOBS on the device as it should, but nothing happens. So I think it is the bluetooth part which is not working.
As I said, I followed your info on setting it up on my PI, but couldn't figure out the bluetooth address. Maybe that is the problem (does not appear in Log as described in your info , debug on btw.).
regards. BTW Lights do not react to the Alexa skill either...

**Comment by bwp91** [comment]
Hi,

Are you able to show all the logs from plugin setup? Thanks

**Comment by Praktiker** [comment]
9.1.2022, 13:21:53HOOBSGoveeInitialising plugin v4.24.0 | Node v16.13.1 | HB v1.3.9 | HAPNodeJS v0.9.8 | HOOBS v4...
9.1.2022, 13:21:54HOOBSGoveePlugin initialised. Setting up accessories....
9.1.2022, 13:22:12HOOBSGoveeLogin successful.
9.1.2022, 13:22:25HOOBSGovee[Lettherebelight] initialising with options {"adaptiveLightingShift":0,"bluetooth":"disabled","brightnessStep":1,"logging":"debug"}.
9.1.2022, 13:22:25HOOBSGovee[Lettherebelight] initialised with id [7F:27:…………].
9.1.2022, 13:22:29HOOBSGovee✓ Setup complete. Check out my other Homebridge plugins! https://github.com/bwp91
9.1.2022, 13:23:10HOOBSGovee[Lettherebelight] current state [on].

Interesting, that it says bluetooth "disabled" though it is enabled in the config. Also see here:
  "lightDevices": [
        {
            "enableBT": true,
            "label": "Lettherebelight",
            "deviceId": "7F:27:......"
        }
    ],
    "debug": true

**Comment by bwp91** [comment]
Could you access the hoobs terminal and run this command and show me the output?

`service hciuart status`

**Comment by Praktiker** [comment]
hoobs@hoobs:~ $ service hciuart status
● hciuart.service - Configure Bluetooth Modems connected by UART
   Loaded: loaded (/lib/systemd/system/hciuart.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2022-01-09 05:52:07 MST; 1h 35min ago
  Process: 330 ExecStart=/usr/bin/btuart (code=exited, status=0/SUCCESS)
 Main PID: 608 (hciattach)
    Tasks: 1 (limit: 2059)
   CGroup: /system.slice/hciuart.service
           └─608 /usr/bin/hciattach /dev/serial1 bcm43xx 3000000 flow - b8:27:eb:22:0e:81

Jan 09 05:51:58 hoobs systemd[1]: Starting Configure Bluetooth Modems connected by UART...
Jan 09 05:52:07 hoobs btuart[330]: bcm43xx_init
Jan 09 05:52:07 hoobs btuart[330]: Flash firmware /lib/firmware/brcm/BCM4345C0.hcd
Jan 09 05:52:07 hoobs btuart[330]: Set BDADDR UART: b8:27:eb:22:0e:81
Jan 09 05:52:07 hoobs btuart[330]: Set Controller UART speed to 3000000 bit/s
Jan 09 05:52:07 hoobs btuart[330]: Device setup complete
Jan 09 05:52:07 hoobs systemd[1]: Started Configure Bluetooth Modems connected by UART.
hoobs@hoobs:~ $

**Comment by bwp91** [comment]
And now can you restart the plugin and show me the logs?

**Comment by Praktiker** [comment]
9.1.2022, 15:30:17 HOOBS [ DEBUG ] Shutting down
9.1.2022, 15:30:17 HOOBS HOOBS stopping
9.1.2022, 15:30:22 HOOBS [ DEBUG ] Stopped
9.1.2022, 15:30:39 Hub hub is running on port 80
9.1.2022, 15:30:40 Hub HOOBS starting

9.1.2022, 15:30:52 HOOBS Loaded plugin 'homebridge-govee'
9.1.2022, 15:30:52 HOOBS [ DEBUG ] Registering platform 'homebridge-govee.Govee'

9.1.2022, 15:31:12 HOOBS Govee Initialising plugin v4.24.0 | Node v16.13.1 | HB v1.3.9 | HAPNodeJS v0.9.8 | HOOBS v4...

9.1.2022, 15:31:13 HOOBS Govee Plugin initialised. Setting up accessories....

9.1.2022, 15:31:19 HOOBS Govee Login successful.

9.1.2022, 15:31:34 HOOBS Govee [Lettherebelight] initialising with options {"adaptiveLightingShift":0,"bluetooth":"disabled","brightnessStep":1,"logging":"debug"}.
9.1.2022, 15:31:34 HOOBS Govee [Lettherebelight] initialised with id [7F:27:........].

9.1.2022, 15:31:39 HOOBS Govee ✓ Setup complete. Want to see this plugin in your own language? Let me know!

**Comment by bwp91** [comment]
I am really confused. The plugin on startup should either log that the bluetooth is properly setup, or, give a warning message with the reason for failure.
In your case it’s not doing either. But there is obviously an issue since the plugin is marking the bluetooth for the device as “disabled” even though you have it configured as enabled, the plugin will override this if it encounters an issue.

**Comment by bwp91** [comment]
Can you run these commands from the terminal:

```
sudo apt remove pi-bluetooth bluez bluez-firmware
```
and enter y when prompted.

If it doesn’t work, show me the output, otherwise then run this command:

```
sudo apt install pi-bluetooth
```

and enter y when prompted.

**Comment by bwp91** [comment]
If all is well, then fully restart the raspberry pi and show me the plugin logs from startup :)

**Comment by Praktiker** [comment]
Ok will do. I am home in about 30 minutes.

**Comment by bwp91** [comment]
If you haven't done anything yet, try updating the plugin to v4.25.0.

I have fixed a couple of bugs that I found trying to get to the bottom of this. It hasn't suddenly made the bluetooth work properly, but the logging much more clearly explains that the bluetooth is being disabled and if you try to control the device it will fail.

The error is `ERR_DLOPEN_FAILED`. I now need to take a look at how to fix this message!

**Comment by bwp91** [comment]
Closing this in favour of #185 please add further comments to this new issue,

I assume that once you update the plugin you will see this same error.

Thanks!

**Comment by Praktiker** [comment]
9.1.2022, 18:30:01 Hub [ WARNING ] device reboot command received
9.1.2022, 18:30:01 Hub [ DEBUG ] Shutting down
9.1.2022, 18:30:01 Hub HOOBS stopping
9.1.2022, 18:30:06 Hub [ DEBUG ] Stopped
9.1.2022, 18:30:23 Hub hub is running on port 80
9.1.2022, 18:30:24 Hub HOOBS starting

9.1.2022, 18:30:35 HOOBS Loaded plugin 'homebridge-govee'
9.1.2022, 18:30:35 HOOBS [ DEBUG ] Registering platform 'homebridge-govee.Govee'

9.1.2022, 18:30:57 HOOBS Govee Initialising plugin v4.25.0 | Node v16.13.1 | HB v1.3.9 | HAPNodeJS v0.9.8 | HOOBS v4...

9.1.2022, 18:30:58 HOOBS Govee Plugin initialised. Setting up accessories....

9.1.2022, 18:31:00 HOOBS Govee Login successful.

9.1.2022, 18:31:17 HOOBS Govee [ WARNING ] Disabling BLE client as ERR_DLOPEN_FAILED.
9.1.2022, 18:31:17 HOOBS Govee [Lettherebelight] initialising with options {"adaptiveLightingShift":0,"bluetooth":"disabled","brightnessStep":1,"logging":"debug"}.
9.1.2022, 18:31:17 HOOBS Govee [Lettherebelight] initialised with id [7F:27:.......].
9.1.2022, 18:31:18 HOOBS Bridge is running on port 51826.
9.1.2022, 18:31:19 HOOBS Govee ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW
regards...

**Comment by bwp91** [comment]
Can we message on Discord?

https://discord.gg/cMGhNtZ3tW

**Comment by Praktiker** [comment]
Yes, never used it before though...

**Comment by Praktiker** [comment]
I am Praktiker btw.
