### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by bauerx-hub** [bwp91/homebridge-govee#18]
### What issue do you have? Please be as thorough and explicit as possible.
Im using the Homebridge-Govee, but im getting the error 400 when using my TV-Strip #6104 over 39%. 
It seems like 39% in HomeKit is 100% in Govee - so when I go over 39% it just gives up. 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Im using Homebridge - installed directly and NOT through HOOBS

* Which version of Homebridge/HOOBS do you have?

To be honest, im not sure what version it is other than its through MacBook Pro. 

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
I just downloaded and installed it - so it would be the latest id think - homebridge-govee v2.2.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
#4106 - tv strip with camera (Govee ofcourse)

### Please paste any relevant logs below.

[12/1/2020, 3:28:02 PM] [Govee] [TV Baggrund] could not be updated and its status will revert soon - Request failed with status code 400.

I hope you have enough to help me. I would really like for it to match the 100% . Other than that, great work!! I can't believe I FINALLY managed to Govee into other places than just Alexa!! 
```

```

**Comment by bwp91** [comment]
Hi @bauerx-hub please update to v2.2.1 and this should fix the brightness issue :)
Thanks for this report.

**Comment by bauerx-hub** [comment]
Hey! 

Thanks for the quick reply! 

When im on the homebridge it doesn't look like I can update it? Is there a way to force the update?
- Sorry if im asking obvious questions. Im kind of a noob to homebridge :D

**Comment by bwp91** [comment]
A button to update should appear on the Plugins page of the UI:

<img width="300" alt="Screenshot 2020-12-01 at 15 00 59 1" src="https://user-images.githubusercontent.com/43026681/100757438-4a7af980-33e6-11eb-865a-060035faaccc.png">

There is a command to force an update but it differs depending on the platform you are running Homebridge on.

Probably worth waiting for the update to appear in Homebridge, it might take a few minutes

**Comment by bauerx-hub** [comment]
Hi Again! 

The update button didn't show up for some reason - I did manage to use the time-stamp on the right side, and just choose the latest version instead of going back! 
It works all great now!! Thank you so much. 
Ill be donating so you can buy yourself a beer my great man. This is awesome! Good work!

**Comment by bwp91** [comment]
Ah excellent glad it's working for you :) thank you
