### ISSUE TITLE
Device supports 'colorwc'

### ISSUE THREAD

**Issue by SimonLawson70** [bwp91/homebridge-govee#180]
Got this in the log of v4.23.0

[Window Lightstrip] device supports 'colorwc' command, let me know on Github with model number [H619A].

**Comment by bwp91** [comment]
Hi @SimonLawson70 

Thanks for this. I've made some changes and released to v4.23.1.

You should find that colour and colour temperature updates might be slightly faster now!

**Comment by bwp91** [comment]
Gonna close this, any issues please let me know!
