### ISSUE TITLE
[H6199] device supports 'colorwc'

### ISSUE THREAD

**Issue by mwhuss** [bwp91/homebridge-govee#181]
```
[1/3/2022, 3:22:24 PM] [Govee] [TV] device supports 'colorwc' command, let me know on Github with model number [H6199].
```

**Comment by mwhuss** [comment]
This is for `homebridge-govee v4.23.1`

**Comment by bwp91** [comment]
Thanks for reporting this! If you update to the beta version 4.23.2-beta.3, you may find that changing colour works a bit better (quicker) and perhaps the light may not flicker if it was slightly before when changing colour.

Any new issues let me know! thanks

**Comment by bwp91** [comment]
Gonna close this, any issues please let me know!
