### ISSUE TITLE
[H6054] device support colorwc

### ISSUE THREAD

**Issue by bezibaerchen** [bwp91/homebridge-govee#183]
[1/7/2022, 7:35:45 AM] [Govee] [Flow Pro Wohnzimmer] device supports 'colorwc' command, let me know on Github with model number [H6054].

homebridge-govee v4.23.1

**Comment by bwp91** [comment]
Thanks for reporting this! If you update to the beta version 4.23.2-beta.3, you may find that changing colour works a bit better (quicker) and perhaps the light may not flicker if it was slightly before when changing colour.

Any new issues let me know! thanks
