### ISSUE TITLE
`ERR_DLOPEN_FAILED` bluetooth error

### ISSUE THREAD

**Issue by bwp91** [bwp91/homebridge-govee#185]
Anyone experiencing this error please message me on discord and I can explain a solution

https://discord.gg/cMGhNtZ3tW

**Comment by IceDarius** [comment]
> Hi, the link expired, I'm experiencing this issue, can you post the workaround?

**Comment by ghost** [comment]
That is not how ANY of this works.

Discord is a walled garden that makes critical info inaccessible to billions of people.

If you dont want to share solutions to problems in open source projects, dont make these open from the beginning

(hello fedi)

**Comment by teh-hippo** [comment]
I'm getting this error again.  What was the solution @bwp91?

**Comment by bwp91** [comment]
You need to uninstall and reinstall the plugin. 
If you do this without restarting homebridge after uninstalling, then this won’t affect your accessories.
you can restart after installing the plugin again
