### ISSUE TITLE
Govee Immersion Light kit -  H605B - Video Mode

### ISSUE THREAD

**Issue by Mattchill** [bwp91/homebridge-govee#186]
in your recent update, i noticed you added
"Added two custom scene options called 'Video Mode' for video mode scenes"

after updating i have not figured out how to add the Scene for Video Mode.

i found your instructions for Finding an AWS code. but when i change modes with the Govee app (with Bluetooth turned off on my phone) the homebridge log doesn't note any changes. the homebridge log only logs changes made within the Apple Home App.

how can i add the video mode to Homebridge

Thank you for any help you can provide.

**Comment by bwp91** [comment]
Hi @Mattchill 

Have you enabled debug logging in the plugin settings and restarted?

Is this a bluetooth and wifi device? I mean it is possible to change to video mode with bluetooth turned off so it goes over wifi? 

It _may_ use a command I haven’t seen, so with debug logging turned on, see if any AWS messages come into the log when you change to video mode.

**Comment by vavelsky** [comment]
I think I have the similar issue and made a duplicated issue here https://github.com/bwp91/homebridge-govee/issues/576
