### ISSUE TITLE
Support for Govee Indoor/Outdoor Hygrometer (B5178)

### ISSUE THREAD

**Issue by philliml74** [bwp91/homebridge-govee#187]
* **Please explain your feature request in a one or two sentences.**
Adding support for the Govee Indoor/Outdoor Hygrometer B5178

* **Is your feature request related to a problem? Please describe.**
Additional support for a device.

* **Any particular Govee devices that this relates to?**
Govee B5178
https://www.amazon.com/Govee-Bluetooth-Humidity-Temperature-Sensor/dp/B0872ZPQSJ

* **Anything else?**
the logs of home bridge provide the following information:
[11/01/2022, 23:07:25] [Govee] [Common Area Thermomete] is not currently supported, do create a Github issue with the following info:
{"device":"D9:E8:A4:C1:38:E4:1C:48","deviceName":"Common Area Thermomete","model":"B5178","httpInfo":{"groupId":1648963,"device":"D9:E8:A4:C1:38:E4:1C:48","sku":"B5178","spec":"","versionHard":"1.00.01","versionSoft":"1.00.08","deviceName":"Common Area Thermomete","deviceExt":{"lastDeviceData":"{\"tem\":2220,\"hum\":4080,\"lastTime\":1637981700000}","deviceSettings":"{\"ic\":0,\"ic_sub_1\":0,\"address\":\"A4:C1:38:E4:1C:48\",\"temWarning\":false,\"wifiLevel\":0,\"humMax\":10000,\"groupOrder\":0,\"fahOpen\":false,\"gatewayId\":0,\"humMin\":0,\"pactCode\":0,\"netWarning\":false,\"groupRole\":1,\"battery\":100,\"temMax\":6000,\"humWarning\":false,\"temMin\":-2000,\"pactType\":0,\"temCali\":0,\"ic_sub_2\":0,\"bleName\":\"B51781C48\",\"header\":0,\"humCali\":0,\"uploadRate\":0,\"deviceName\":\"Common Area Thermomete\"}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/img/4c860fe1586d072171b1f12a63059e1c-add_list_type_device_b5178_1.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":14},"isAPIDevice":false}
[11/01/2022, 23:07:25] [Govee] [Outdoor Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"D9:E8:A4:C1:38:E4:1C:48_1","deviceName":"Outdoor Thermometer","model":"B5178","httpInfo":{"groupId":0,"device":"D9:E8:A4:C1:38:E4:1C:48_1","sku":"B5178","spec":"","versionHard":"1.00.00","versionSoft":"1.00.00","deviceName":"Outdoor Thermometer","deviceExt":{"lastDeviceData":"{\"tem\":350,\"hum\":7600,\"lastTime\":1640125920000}","deviceSettings":"{\"ic\":0,\"pDevice\":\"D9:E8:A4:C1:38:E4:1C:48\",\"ic_sub_1\":0,\"address\":\"A4:C1:38:E4:1C:48\",\"temWarning\":false,\"wifiLevel\":0,\"humMax\":10000,\"groupOrder\":1,\"fahOpen\":false,\"gatewayId\":0,\"humMin\":0,\"pactCode\":0,\"netWarning\":false,\"groupRole\":2,\"battery\":89,\"temMax\":6000,\"humWarning\":false,\"temMin\":-2000,\"pactType\":0,\"temCali\":0,\"ic_sub_2\":0,\"bleName\":\"B51781C48\",\"header\":0,\"humCali\":0,\"uploadRate\":0,\"deviceName\":\"Outdoor Thermometer\"}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/img/e57571028831ecb45811f1ef23022d6b-add_list_type_device_b5178_2.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":14},"isAPIDevice":false}

**Comment by bwp91** [comment]
Hi @philliml74 

Is this a wifi device? Or bluetooth only?

**Comment by philliml74** [comment]
@bwp91 This is a bluetooth only device.

**Comment by bwp91** [comment]
Since it's bluetooth only, you may find that the other govee plugin works - have you tried homebridge-plugin-govee? 

This is a plugin for bluetooth-only govee sensors.

**Comment by philliml74** [comment]
I will try it out to see if it provides the info.  But if memory services, it only provides one out of the 2 temperature entries.
