### ISSUE TITLE
Govee H6178 Light notification

### ISSUE THREAD

**Issue by mikepick** [bwp91/homebridge-govee#189]
### What issue do you have? Please be as thorough and explicit as possible.

When starting Homebridge, the plugin reports: [Govee] [ xxx ] is not currently supported, do create a Github issue with the following info.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X, on a Raspberry Pi 3B+.

* Which version of Homebridge/HOOBS do you have?

1.3.9

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 3B+
Node.js Version v14.18.3
Npm Version v8.3.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee v4.26.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H617A, H6178

### Please paste any relevant logs below.

```
[13/01/2022, 18:51:54] [Govee] [Ezra Room] is not currently supported, do create a Github issue with the following info:
{"device":"41:D9:D8:30:39:37:38:1F","deviceName":"Ezra Room","model":"H617A","httpInfo":{"groupId":0,"device":"41:D9:D8:30:39:37:38:1F","sku":"H617A","spec":"","versionHard":"3.01.01","versionSoft":"3.02.21","deviceName":"Ezra Room","deviceExt":{"deviceSettings":"{\"address\":\"D8:30:39:37:38:1F\",\"bleName\":\"Govee_H617A_381F\",\"pactType\":10,\"pactCode\":1,\"ic\":15,\"secretCode\":\"Hzg3OTDYYXo=\",\"sku\":\"H617A\",\"device\":\"41:D9:D8:30:39:37:38:1F\",\"deviceName\":\"Ezra Room\",\"versionHard\":\"3.01.01\",\"versionSoft\":\"3.02.21\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/cc868a2def84fe0c9139d68b44544272-add_list_type_device_617ac.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png\",\"ext\":\"\",\"ic\":15}"},"pactType":10,"pactCode":1,"goodsType":73},"isAPIDevice":false}

[13/01/2022, 18:51:54] [Govee] [TV lights] is not currently supported, do create a Github issue with the following info:
{"device":"65:63:C4:32:32:36:09:6B","deviceName":"TV lights","model":"H6178","httpInfo":{"groupId":0,"device":"65:63:C4:32:32:36:09:6B","sku":"H6178","spec":"","versionHard":"3.01.01","versionSoft":"2.01.13","deviceName":"TV lights","deviceExt":{"deviceSettings":"{\"bleName\":\"Govee_H6178_096B\",\"pactType\":10,\"pactCode\":2,\"ic\":0,\"sku\":\"H6178\",\"device\":\"65:63:C4:32:32:36:09:6B\",\"deviceName\":\"TV lights\",\"versionHard\":\"3.01.01\",\"versionSoft\":\"2.01.13\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/3465654f0c451772945eaa7e4ab20ad3-add_list_type_device_6178.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/eed1b442fc5d3aaa28563ded4284e057-new_light_title_6160_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/cb48afdb8618c2ddfd8fe16673336af0-new_light_title_6160_off.png\",\"ext\":\"\",\"ic\":0}"},"pactType":10,"pactCode":2,"goodsType":78},"isAPIDevice":false}
```

**Comment by bwp91** [comment]
Hi @mikepick 

I've just published a beta version of the plugin which should support both these models.
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Since these models are bluetooth only, you may need to install some extra packages to enable the bluetooth on your pi (assuming you haven't already)
https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control#raspberry-pihomebridge-rpi-imagehoobs-box-raspbian

Thanks!

**Comment by mikepick** [comment]
Thanks Ben for the quick response! It does seem to be working now with the H6178 lights, if a bit creaky.

(I seem to remember that Wifi / Bluetooth don't play well together on the 3B+, so not sure how much that affects things.)

On / off works at least. Color changes don't seem to work, FWIW, the logs report:

```
[14/01/2022, 16:56:22] [Govee] [H6178_096B] current colour [rgb 93 255 13].
[14/01/2022, 16:56:42] [Govee] [noble] Peripheral already connected at Peripheral.connect (/usr/lib/node_modules/homebridge-govee/node_modules/@abandonware/noble/lib/peripheral.js:47:26).
```

It's not a big deal, but cool to have working at least for on / off. Thanks for your work on the plugin! Because it's available, I've ordered Govee outlets as well.
