### ISSUE TITLE
Color Changing Not Working on H605B

### ISSUE THREAD

**Issue by iSteve-O** [bwp91/homebridge-govee#190]
### What issue do you have? Please be as thorough and explicit as possible.

I have 2 tv backlight sets, the H6199, & the H605B with the added bars, but color changing is only working for the H6199. 

When I ask Siri to change the color of the H605B she says “Hmm. That’s not a supported feature” but changes the color of the H6199 perfectly when I ask her to. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

Latest

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi (4)

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Latest (not beta)

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H605B

### Please paste any relevant logs below.

```

```

**Comment by iSteve-O** [comment]
I updated to the beta and the color changing seems to be working now (Siri no longer says not supported) but I am getting this message in the log so I wanted to let you know… H605B immersion strip w/bars

<device supports 'colorwc' command. let me know on Github with model number H605B>

**Comment by bwp91** [comment]
New version of the plugin will use this new code for sending colour updates via AWS. You may find it's a little faster and also this log message won't appear anymore.

**Comment by iSteve-O** [comment]
Thank you so much. This set is working great now. I really appreciate it.
