### ISSUE TITLE
device supports 'colorwc' command, let me know on Github with model number [H6058].

### ISSUE THREAD

**Issue by AlexKusnezov** [bwp91/homebridge-govee#191]
Hey Guys, got this message after updating to 4.26.0

```
device supports 'colorwc' command, let me know on Github with model number [H6058].
```

**Comment by bwp91** [comment]
Hi @AlexKusnezov 

Thanks for this. If you wanted to update to the beta version of the plugin, you may see some colour change improvements (ie faster).

And this message should be hidden from now on!

**Comment by iSteve-O** [comment]
I got this too, only the model of mine is H605B. I left a reply to my issue post about color changing not working but that’s resolved. Thanks for your work!

**Comment by bwp91** [comment]
Thanks for reporting this. Please update to the new version of the plugin!
