### ISSUE TITLE
Is there a way to change features other than the colors for lights?

### ISSUE THREAD

**Issue by ashishgururani** [bwp91/homebridge-govee#192]
For the RGB lights that have Wifi and bluetooth, there is usually a music mode where the lights respond to the music playing. I want to say "party mode" and have the music mode turn on. I only see options to change the colors on homebridge. Is it possible to change other features such as the music mode?

**Comment by bwp91** [comment]
Hi @ashishgururani 

Please see
https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

It should be pretty self-explanatory but if you need any further help do let me know!
