### ISSUE TITLE
Does the plugin cache a login token for account logins?

### ISSUE THREAD

**Issue by ianchesal** [bwp91/homebridge-govee#193]
I ended up getting locked out of my Govee account for 24 hours because the plugin queried the account with my username and password more than 30 times in a 24 hour period. I'm not certain if that's due to a mis-configuration on my part with respect to the plugin or if the plugin truly does do a new login every time it queries your account for data.

Is there cached auth token if the plugin is doing username+password data fetches from the account and not using the API key?

If there's no caching, Govee informed me they rate limit account logins to 30/day before they lock the account for 24 hours which makes the default query time of the plugin one that'll get you rate limited pretty quickly.

Might have been I messed up the plugin config at first and that caused more account logins than expected so I thought I'd check here with you on that. PEBKAC? :)

**Comment by bwp91** [comment]
Hi @ianchesal 

The plugin only performs a login when it initialises. It caches the auth token for future queries until the plugin restarts again.

Sounds like you may have restarted the plugin over 30 times... it's handy to know their limit is 30 as I didn't know this myself.

Hope this helps!

**Comment by ianchesal** [comment]
Awesome. Then it was entirely PEBKAC. Thanks!
