### ISSUE TITLE
BLE Devices not working 

### ISSUE THREAD

**Issue by pullupnshowout** [bwp91/homebridge-govee#198]
### What issue do you have? Please be as thorough and explicit as possible.
Hey, I connected my Govee acc to your plugin and it connected as stated with the terminal, i also put in my API key and it detects both of my Bluetooth lights, but it says " will not be added to Homebridge unless configured and Bluetooth enabled in config." and i look through the configs but i didn't see anything to enable Bluetooth

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
* Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
* homebridge-config-ui-x v4.42.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
* Windows and Version 8.1.2 for NPM

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
* First time user with homebridge-config-ui-x v4.42.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
* Govee Model Numver H6125

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @pullupnshowout 

Please see this link for more info about adding bluetooth only lights:
https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control#plugin-setup

You basically need to use the device id show in the log to create a config entry for your light in the “light devices” section and ticking the “enable ble control” option.
