### ISSUE TITLE
Saw this entry on the log for my lamp (Lyra)

### ISSUE THREAD

**Issue by Cmejia** [bwp91/homebridge-govee#199]
[LyraLamp] device supports 'colorwc' command, let me know on Github with model number [H6072].

**Comment by bwp91** [comment]
Hi @Cmejia 

Thanks for this. Are you able to update to the beta version (4.27.1-beta.2) of the plugin and let me know if colour change is still working for your device? Thanks

**Comment by Cmejia** [comment]
Just updated to 4.27.1-beta.2 and the colour change from Home app works properly. Thanks for the follow up.

**Comment by bwp91** [comment]
Great, thanks!
