### ISSUE TITLE
Home app does does not show if device is on or off. 

### ISSUE THREAD

**Issue by velazpablo** [bwp91/homebridge-govee#2]
Home app does not show whether the device is on or off. Color changes do not work properly, as well as the brightness percentage.

**Homebridge version:**
Homebridge 1.2.2

**Homebridge Govee version:**
homebridge-govee v1.0.3

...
No logs showing when making changes to the device.

**Comment by bwp91** [comment]
Hi.
You can on logging in the plugin settings -> optional -> “Debug Logging”.
Sounds like nothing is working for you 😅
Which model device do you have? and does it have a reliable connection to wifi? 
Thanks

**Comment by velazpablo** [comment]
Wow, forgot the debug logging 😄. So I'm running a Raspberry Pi Zero W, everything else seems to be working fine and the network is stable.

**Comment by bwp91** [comment]
I meant, does your led light have a stable internet connection? is it setup with wifi?

**Comment by bwp91** [comment]
> The only thing that does not update is when I make changes to my LED strip from my Google Home (like turning it off or on).

The plugin checks for "external" changes every thirty seconds, so if you change your LED via google home, whilst it won't update instantly, it should within 30 seconds/one minute.
