### ISSUE TITLE
Add support for new device (H7111)

### ISSUE THREAD

**Issue by tjridge** [bwp91/homebridge-govee#200]
Addition of Smart Air Circulator Fan (H7111)

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
4.1.22

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
4.27.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H7111

### Please paste any relevant logs below.
"device":"18:2D:D4:AD:FC:35:EF:E2","deviceName":"Smart Fan","model":"H7111",
```

```

**Comment by bwp91** [comment]
Hi @tjridge if you update to the beta version 4.27.1-beta.4 then this device model should be recognised and added as a fan. On/off may already work. But other features I will need the 'codes' for I believe you helped me with another accessory type before?

**Comment by tjridge** [comment]
Here is the info from the log: 

Smart Fan is not currently supported, do create a Github issue with the following info:
{"device":"18:2D:D4:AD:FC:35:EF:E2","deviceName":"Smart Fan","model":"H7111","httpInfo":{"groupId":0,"device":"18:2D:D4:AD:FC:35:EF:E2","sku":"H7111","spec":"","versionHard":"1.02.00","versionSoft":"1.00.18","deviceName":"Smart Fan","deviceExt":{"deviceSettings":"{\"wifiName\":\"XXXXXXX\",\"address\":\"D4:AD:FC:35:EF:E3\",\"bleName\":\"ihoment_H7111_EFE3\",\"topic\":\"GD/deb82762ea5405750873565a3dd8b6cd\",\"wifiMac\":\"D4:AD:FC:35:EF:E2\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.18\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"TFSrNEqj2hg=\",\"sku\":\"H7111\",\"device\":\"18:2D:D4:AD:FC:35:EF:E2\",\"deviceName\":\"Smart Fan\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.18\"}","lastDeviceData":"{\"online\":false}","extResources":"

**Comment by bwp91** [comment]
Did you update to the beta version?

**Comment by tjridge** [comment]
Yes. It is now showing up in the Home app with the option to turn it on and off, but nothing happens when sending the commands.

**Comment by bwp91** [comment]
I will need the codes that appear in the homebridge log, like we did with the other accessory, to be able to implement the functions of this device.

**Comment by tjridge** [comment]
Sorry, can you refresh my memory as to where I can find the info you need?

**Comment by bwp91** [comment]
Of course,

So with bluetooth disabled on your phone (if the device supports bluetooth), you can perform certain functions to control the fan.

Each time you do for each function (on, off, low speed, medium speed, etc), a code will appear in the homebridge log.

I need to know a list of these codes with which function they correspond to.

for example

turn on: %%%
turn off: %%%
high speed: %%%
oscillate on:

etc. I’m not entirely sure what features the fan has but these above would be the main ones

**Comment by tjridge** [comment]
This is all I get: 
WARNING[Smart Fan] New/Unknown scene code received: [qhAAAAAAAAAAAAAAAAAAAAAAALo=].
[Smart Fan] [AWS] message event [{"msg":{"transaction":"v_1643985907451926","data":{"command":["qhAAAAAAAAAAAAAAAAAAAAAAALo="]},"type":1,"cmdVersion":0,"cmd":"ptReal"}}].
9:45:07 AMGoveeGovee[Smart Fan] [AWS] receiving update [{"transaction":"v_1643985907451926","data":{"command":]

**Comment by bwp91** [comment]
There should appear one code everytime you do something in the govee app

**Comment by tjridge** [comment]
[AWS] message event [{"msg":{"transaction":"v_1644006781964726","data":{"command":["qhAAAAAAAAAAAAAAAAAAAAAAALo="]},"type":1,"cmdVersion":0,"cmd":"ptReal"}}].
2/4/2022, 3:33:02 PMGoveeGovee[Smart Fan] [AWS] receiving update [{"transaction":"v_1644006781964726","data":{"command":["qhAAAAAAAAAAAAAAAAAAAAAAALo="]},"type":1,"cmdVersion":0,"cmd":"ptReal","source":"AWS"}].
Smart Fan] [AWS] message event [{"msg":{"transaction":"v_1644006835250150","data":{"command":["Mx8BAQAAAAAAAAAAAAAAAAAAACw="]},"type":1,"cmdVersion":0,"cmd":"ptReal"}}].
2/4/2022, 3:33:55 PMGoveeGovee[Smart Fan] [AWS] receiving update [{"transaction":"v_1644006835250150","data":{"command":["Mx8BAQAAAAAAAAAAAAAAAAAAACw="]},"type":1,"cmdVersion":0,"cmd":"ptReal","source":"AWS"}].
2/4/2022, 3:33:55 PMGoveeGoveeWARNING[Smart Fan] New/Unknown scene code received: [Mx8BAQAAAAAAAAAAAAAAAAAAACw=].
2/4/2022, 3:33:57 PMGoveeGovee[Smart Fan] [AWS] message event [{"msg":{"transaction":"v_1644006837188191","data":{"command":["MwEAAAAAAAAAAAAAAAAAAAAAADI="]},"type":1,"cmdVersion":0,"cmd":"ptReal"}}].
2/4/2022, 3:33:57 PMGoveeGovee[Smart Fan] [AWS] receiving update [{"transaction":"v_1644006837188191","data":{"command":["MwEAAAAAAAAAAAAAAAAAAAAAADI="]},"type":1,"cmdVersion":0,"cmd":"ptReal","source":"AWS"}].
2/4/2022, 3:33:57 PMGoveeGoveeWARNING[Smart Fan] New/Unknown scene code received: [MwEAAAAAAAAAAAAAAAAAAAAAADI=].
2/4/2022, 3:33:57 PMGoveeGovee[Smart Fan] [AWS] message event [{"msg":{"transaction":"v_1644006837333201","data":{"command":["qhAAAAAAAAAAAAAAAAAAAAAAALo="]},"type":1,"cmdVersion":0,"cmd":"ptReal"}}].
2/4/2022, 3:33:57 PMGoveeGovee[Smart Fan] [AWS] receiving update [{"transaction":"v_1644006837333201","data":{"command":["qhAAAAAAAAAAAAAAAAAAAAAAALo="]},"type":1,"cmdVersion":0,"cmd":"ptReal","source":"AWS"}].
2/4/2022, 3:33:57 PMGoveeGoveeWARNING[Smart Fan] New/Unknown scene code received: [qhAAAAAAAAAAAAAAAAAAAAAAALo=].

**Comment by bwp91** [comment]
Yea but i also need to know what you did in the govee app and which code corresponds to what you did
