### ISSUE TITLE
BLE using AWS even with AWS disabled

### ISSUE THREAD

**Issue by Z3r0CooLE** [bwp91/homebridge-govee#202]
### What issue do you have? Please be as thorough and explicit as possible.
I have a govee strip that is BLE only, it shows up in my logs, I copied the ID to the config and enabled BLE control; I even enabled the 'disable AWS' option. However when attempting to control the device, Homebridge log says 'not sending AWS update as not available or enabled' with no indication it attempted to connect to the device view BLE.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
v1.4.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Ubuntu 20.04LTS headless
node v16.13.2
npm v8.1.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v4.27.0
this is my first attempt as using the plugin

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6126

### Please paste any relevant logs below.

```
[Govee] Login successful.
[Govee] [Desk Under Lighting] has been added to Homebridge.
[Govee] Bluetooth hardware and packages found successfully.
[Govee] [Desk Under Lighting] initialising with options {"adaptiveLightingShift":0,"bluetooth":"enabled","brightnessStep":1,"logging":"debug"}.
[Govee] [Desk Under Lighting] initialised with id [6D:52:A4:C1:38:17:D9:F7] [H6126].
[Govee] [noble] stateChange: poweredOn.
[Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91 from the UK!
# send a command to the device
[Govee] [Desk Under Lighting] not sending AWS update as not available or enabled.
```

**Comment by bwp91** [comment]
Hi @Z3r0CooLE 

Were there no messages after this in the log about attempting via bluetooth? What exactly were you trying to do?

**Comment by Z3r0CooLE** [comment]
@bwp91 I included all log lines related to the plugin in the post and will update if new ones come up, but it never even attempts a bluetooth connection.
I'm using a Gigabyte GC-WBAX210 PCIE card as my bluetooth 5.2 LE adapter on Ubuntu 20.04LTS headless.
I've updated the machine to the latest mainline kernel and installed supported drivers.
I've installed a slew of Linux CLI Bluetooth tools and services and I can turn the adapter on/off, scan for devices and trust devices. For some reason every tool I've used fails to connect to devices even though I can scan, find, trust and get info from them so it could be related to this issue.
But in the homebridge logs the plugin claims it found and configured BT hardware and software appropriately.. Just the line saying it won't bother with AWS as I set it to disabled since the strip is BT only. I also don't get anything back form the Govee api when polling devices... not sure if it only shows WiFi enabled devices, but it seems like it should still know I have the device registered to my account.. The Mac address does get returned in HB logs though, and I have that set in the config, so I guess whatever makes the device discoverable must be working.. but yea, no errors in the logs even with debug logs on for the plugin and device.

**Comment by sYkx** [comment]
Hey, I have the exact same Issue, also on Ubuntu - but I’m using an Intel NUC with onboard Bluetooth and it tells me everything is fine and it found everything bluetooth related, api is also connected but I get the same message: „Not sending AWS update …“

I disabled AWS and enabled BLE in the Settings.

**Comment by Z3r0CooLE** [comment]
@sYkx thanks for sharing, I was 50/50 on whether this was an issue with my specific network card which provides my server Bluetooth. But if your machine had Bluetooth built in and works as intended aside from the plugin using it, this must be related to the plugin. Are you running headless or desktop?

**Comment by sYkx** [comment]
@Z3r0CooLE headless - the same version as you, 20.04 LTS

**Comment by bwp91** [comment]
Can anyone install the beta version of the plugin to see if this has improved anything?

Thanks!
