### ISSUE TITLE
Support for H613B

### ISSUE THREAD

**Issue by jbheuschen** [bwp91/homebridge-govee#205]
Hey, first of all thanks for your work on this great plugin! Do you think it would be possible to add support for the H613B RGB Strip?

`[04/02/2022, 18:41:55] [Govee] [H613B_82F5] is not currently supported, do create a Github issue with the following info:
{"device":"3A:38:D4:AD:FC:0B:82:F5","deviceName":"H613B_82F5","model":"H613B","httpInfo":{"groupId":0,"device":"3A:38:D4:AD:FC:0B:82:F5","sku":"H613B","spec":"","versionHard":"2.01.01","versionSoft":"2.04.00","deviceName":"H613B_82F5","deviceExt":{"deviceSettings":"{\"address\":\"D4:AD:FC:0B:82:F5\",\"bleName\":\"GBK_H613B_82F5\",\"pactType\":10,\"pactCode\":1,\"ic\":0,\"sku\":\"H613B\",\"device\":\"3A:38:D4:AD:FC:0B:82:F5\",\"deviceName\":\"H613B_82F5\",\"versionHard\":\"2.01.01\",\"versionSoft\":\"2.04.00\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/bbfa1b98a970733c443e142b86535af1-add_list_type_device_613bc.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png\",\"ext\":\"\",\"ic\":0}"},"pactType":10,"pactCode":1,"goodsType":39},"isAPIDevice":false} `

Thanks a lot in advance!

**Comment by bwp91** [comment]
Hi @jbheuschen 

If you update to the beta version of the plugin, this device should show as supported!

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Thanks!

**Comment by jbheuschen** [comment]
Hey @bwp91, thanks a lot for your really fast answer! The strip is now being recognized properly and showing up, it's basically working, too. However, there are two things that might need a bit of fine-tuning:

- The brightness slider is a bit off, the strip basically reaches full brightness when the Home-slider passes 40%. I had a look at the debug logs and if I interpret them correctly, the code being sent at 40% is about `100` (see below for logs). Based on that, I guess - correct me if I'm missing out on something at this point - that instead of ranging from `0 - 255`, this strip seems to use a range of `0 - 100` for its brightness.
  `[08/02/2022, 19:36:29] [Govee] [H613B_82F5] [BLE] sending update {4: 102}.
[08/02/2022, 19:36:29] [Govee] [H613B_82F5] current brightness [40%].`
- Switching colors doesn't seem to work. I don't really have a clue yet on what's going wrong here but I'm definitely going to try to find out. Based on the fact that color changes appear normally in the debug logs (see below) and that there seem to be protocol differences for the brightness, too, I wouldn't wonder if this is some simple protocol difference as well.
`[08/02/2022, 19:52:01] [Govee] [H613B_82F5] has been reported [connected] via BLE.
[08/02/2022, 19:52:02] [Govee] [H613B_82F5] [BLE] sending update {5: [2,255,136,67]}.
[08/02/2022, 19:52:02] [Govee] [H613B_82F5] current colour [rgb 255 136 67].
[08/02/2022, 19:52:12] [Govee] [H613B_82F5] has been reported [disconnected] via BLE.`

If there is anything I can do/try/test, just let me know! In the meantime, I'll also try to further investigate this issue myself. Thanks in advance for your help!

**Comment by jbheuschen** [comment]
As to the colors, I found out that H613B seems to use `0x0D` instead of `0x02` as a signal for manual mode. I forked and added a temporary workaround by adding a check for the model and using `0x0D` instead, and it works as intended.

**Comment by bwp91** [comment]
Please make a pull request!

**Comment by bwp91** [comment]
Thanks so much for the PR and taking the time to notice this different code. Hopefully it will also help other users in the future!

Could you update to the beta version I have just released, 4.28.1-beta.3.

It includes the colour code changes for your model, and also should fix the brightness issue you were experiencing too.

**Comment by jbheuschen** [comment]
Thanks, both the brightness and color are working properly now! Haven't noticed any other problems so far.

**Comment by bwp91** [comment]
Ah good news! Nice to have a success case with this plugin recently!
