### ISSUE TITLE
Device Request: Doorbell

### ISSUE THREAD

**Issue by squishycat92** [bwp91/homebridge-govee#206]
Hey,

I think that this is a really great plugin, and it seems like it currently supports a lot of Govee devices! However, I noticed that the Govee audio-only doorbell (H7205) does not currently seem supported. Would it be possible to add this device into Homebridge using this plugin (perhaps with the added functionality of two-way talk, chime, etc.)? 

The attached info is:
`{"device":"34:20:03:18:72:92","deviceName":"Doorbell","model":"H7205","httpInfo":{"groupId":0,"device":"34:20:03:18:72:92","sku":"H7205","spec":"","versionHard":"1.0.00","versionSoft":"1.0.00","deviceName":"Doorbell","deviceExt":{"deviceSettings":"{\"promptLanguage\":1,\"mac\":\"34:20:03:18:72:92\",\"wifiName\":\"Hong Family\",\"battery\":72,\"voiceGrads\":70,\"bindTime\":1641513365340,\"wifiVersionHard\":\"1.00.01\",\"wifiVersionSoft\":\"1.00.04\",\"sku\":\"H7205\",\"device\":\"34:20:03:18:72:92\",\"deviceName\":\"Doorbell\",\"versionHard\":\"1.0.00\",\"versionSoft\":\"1.0.00\"}","lastDeviceData":"{\"online\":false,\"lastTime\":1643941458383,\"unread\":1,\"isConnected\":true}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}`

Thank you very much!

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
