### ISSUE TITLE
'colorwc' Command Warning

### ISSUE THREAD

**Issue by mrlightison** [bwp91/homebridge-govee#207]
### What issue do you have? Please be as thorough and explicit as possible.

Error Code for Neon Light Strip

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

HOOBS 4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

HOOBS Box

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

4.28.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Model number [H61A0]

### Please paste any relevant logs below.

```
2/6/2022, 5:45:30 PMGovee BridgeGoveeWARNING[Backsplash Lights 1] device supports 'colorwc' command, let me know on Github with model number [H61A0].
```

**Comment by bwp91** [comment]
Hi @mrlightison 

Thanks for this, are you able to update to the beta version of the plugin and let me know if colour change is still working from the home app?

Instructions for HOOBS here:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version#hoobs-4

Thanks!

**Comment by mrlightison** [comment]
Hi there—as far as I can tell, everything looks good in beta. Thanks!
