### ISSUE TITLE
can't setup scenes

### ISSUE THREAD

**Issue by ideea** [bwp91/homebridge-govee#209]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/318955/153468641-dfb8151a-0ced-4ec8-9325-909d286ef032.png">

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

homebridge ui-ux

* Which version of Homebridge/HOOBS do you have?

latests

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

raspberry pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

latest

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

tv backlight

### Please paste any relevant logs below.

```
<img width="726" alt="image" src="https://user-images.githubusercontent.com/318955/153468743-a1168b75-b485-41d2-87de-dbb1457d160e.png">
 here's the image, im not able to see setting. in description it says that these options are available if something was ticked or no, I don't see them in config as well.
```

**Comment by bwp91** [comment]
Hi @ideea 

The options will appear once you have added a 'Label' and the 'Device ID' into the fields you can see in the config.

**Comment by ideea** [comment]
@bwp91 thank you :D

**Comment by alikhodrali** [comment]
> 

I have both fields filled in and still nothing is showing up in my case, unfortunately. Any help would be greatly appreciated!
