### ISSUE TITLE
Error installing adapter

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-govee#21]
Installing this on iobroker i get the following error:
Using homebridge 1.1.2

`Info: Can not get current GitHub commit, we remember master branch only. Status: 422 (No commit found for SHA: master)
install https://github.com/bwp91/homebridge-govee/tarball/master
NPM version: 6.14.6
npm install https://github.com/bwp91/homebridge-govee/tarball/master --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code E404
npm ERR! 404 Not Found - GET https://codeload.github.com/bwp91/homebridge-govee/legacy.tar.gz/masternpm ERR! 404 npm ERR! 404  'https://github.com/bwp91/homebridge-govee/tarball/master' is not in the npm registry.npm ERR! 404 Your package name is not valid, because npm ERR! 404  1. name can only contain URL-friendly charactersnpm ERR! 404 npm ERR! 404 Note that you can also install from anpm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-12-04T14_03_00_957Z-debug.log
ERROR: host.raspberrypi2 Cannot install https://github.com/bwp91/homebridge-govee/tarball/master: 1
ERROR: process exited with code 25`

**Comment by bwp91** [comment]
Hi, I have never used iobroker so my knowledge is limited.
How do you install a homebridge plugin through iobroker?
Are you using the latest versions of everything?

**Comment by ghost** [comment]
because this plugin (2.3.0) needs node >14 and i have node 12, i use the plugin homebridge-govee@2.0.10 now.
I installed it at the console. But i cannot see it anywhere or there is no tree entry.

**Comment by bwp91** [comment]
v2.3.0 of the plugin will work with node v12 if you have the opportunity to ‘install anyway’.
The logs in your original message show that the script that is trying to install the plugin is looking for a `master` branch of the plugin, which does not exist. The branch it needs to install is called `latest`.
Which command did you use to install it via the terminal?
Could be that ioBroker needs the plugin installed in a specific location?
I am willing to try and help, but, as I said my knowledge of ioBroker is zero 😅

**Comment by ghost** [comment]
my command is:
sudo npm install homebridge-govee@2.3.0 -g

updated this successful on the commandline.

I got a key from govee and inserted it in the homebridge config like this:
{
  "platform": "Govee",
  "name": "Govee",
  "apiKey": "xx6b9096-xxxx-xxxx-9705-b892c268eexx"
}

the path is: /opt/iobroker/node_modules

if it helps, logfile:

All Libraries installed/updated
ham.0 | 2020-12-04 17:19:47.734 | info | (4388) Install/Update homebridge-govee
ham.0 | 2020-12-04 17:19:47.732 | info | (4388) Install/Update the following Libraries: homebridge-govee
ham.0 | 2020-12-04 17:19:47.701 | info | (4388) starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.ham, node: v12.20.0, js-controller: 3.1.6
ham.0 | 2020-12-04 17:19:45.430 | info | (25848) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ham.0 | 2020-12-04 17:19:45.428 | info | (25848) terminating
ham.0 | 2020-12-04 17:19:45.420 | info | (25848) cleaned everything up...
ham.0 | 2020-12-04 17:19:45.417 | info | (25848) Got terminate signal TERMINATE_YOURSELF

**Comment by bwp91** [comment]
This command `sudo npm install homebridge-govee@2.3.0 -g` will install the plugin globally, most likely in a different location. To revert this, you can use the command:

```
sudo npm uninstall homebridge-govee -g
```

And then `cd` to the `/opt/iobroker/` folder and run:

```
sudo npm install homebridge-govee@2.3.0
```

This will install the plugin in the `/opt/iobroker/` directory. This should work so long as this is the directory that the plugin needs to be installed in to be visible to ioBroker.

**Comment by ghost** [comment]
now i got this error:
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for homebridge-govee@2.3.0: wanted: {"homebridge":"^1.1.0","node":"^14.15.1"} (current: {"node":"12.20.0","npm":"6.14.8"})
npm ERR! notsup Not compatible with your version of node/npm: homebridge-govee@2.3.0
npm ERR! notsup Not compatible with your version of node/npm: homebridge-govee@2.3.0
npm ERR! notsup Required: {"homebridge":"^1.1.0","node":"^14.15.1"}
npm ERR! notsup Actual:   {"npm":"6.14.8","node":"12.20.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-04T18_56_57_429Z-debug.log
pi@raspberrypi2:/opt/iobroker $

**Comment by bwp91** [comment]
Can you upgrade your versions of homebridge and node?

**Comment by ghost** [comment]
no, i cannot update the node, cause some other adapters could be instable. The bridge is already the newest version 1.1.2.
The log is still ok and loads with homebridge-govee@2.2.0 but there is no tree and datapoint with ham.0

**Comment by bwp91** [comment]
Do ioBroker have support you can ask? This is not really an issue with my plugin, rather the way that it's required to be installed by them, which I don't know.

**Comment by ghost** [comment]
thanks so far, i´ll give it a try 👍

**Comment by ghost** [comment]
Hi,
it is not necessary to install the plugin via console. At first install the homebridge accessory manager.
In this instance go to the configuration side and fill in "homebridge-govee@2.3.0" at npm module field.
Then edit the configuration file and fill in everything you need for your adapter.

**Comment by bwp91** [comment]
Have you been able to do this?

**Comment by ghost** [comment]
yes

**Comment by bwp91** [comment]
Ah great, and it's all working?

**Comment by ghost** [comment]
Yes, it depends on what i have configured in the config-file.

**Comment by bwp91** [comment]
Ah excellent glad you've it working. It'll mark this issue as complete, but in the meantime if you have any further questions do let me know. Please remember that my knowledge of iobroker is zero so I won't be able to offer support for things specific to this. But support for this plugin indeed yes.

**Comment by bwp91** [comment]
Hi @TCRW 

You managed to install this plugin within ioBroker right?

Could you be of any assistance here:

https://github.com/bwp91/homebridge-govee/issues/69

TIA
