### ISSUE TITLE
H6159 - Color issue

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-govee#210]
Ben, my both devices Led wifi/BT H6159 had an issue about color change.
My trigger ask to switch on light with Blue color, but when my sensor is triggered the light on on white and just after few second goin in the right color.
I discovered that the first color is the default color that are reported into Govee app 
![image](https://user-images.githubusercontent.com/70729310/153496684-ac68003b-cd5e-4911-96b5-23a8ea5df02e.jpeg)

I already changed in Govee app the  color in blue, but after some days the app come back to this white.

Second issue, when I trigger light off, the light turn off but after some seconds return on again to turn off definitely 

I have last version of HB and your plug-in

**Comment by bwp91** [comment]
Hi @Stetocasa 

Can you put the plugin in debug logging mode, then restart the govee bridge. Then use the govee app (with bluetooth disabled) and change the colour of the lights to green.

And show me here everything that appears in the homebridge log? There should be some `incoming AWS` messages.

Also do you have the plugin setup to control these lights via bluetooth too?

**Comment by Stetocasa** [comment]
![image](https://user-images.githubusercontent.com/70729310/153755967-bfccf309-2275-4bb5-8ce2-9f526113f092.jpeg)

I confirm that the plug-in is correctly setup to use BLE

**Comment by bwp91** [comment]
Can you try updating to plugin beta version 4.28.1-beta.5 and see if this improves the colour change ie not turning to white for a few seconds?

**Comment by Stetocasa** [comment]
Done. But nothing changed

**Comment by bwp91** [comment]
Can you try unchecking the enable BLE option for your light to see if this makes it better?

**Comment by Stetocasa** [comment]
> Can you try unchecking the enable BLE option for your light to see if this makes it better?

Tried 
Nothing changed :(

**Comment by Stetocasa** [comment]
@bwp91 my impression is that the issue is related to adaptive lighting 
Any way to disable?

**Comment by bwp91** [comment]
what makes you think this?

**Comment by Stetocasa** [comment]
> what makes you think this?

When I long press the accessory to open the dimmer, is automatically selected into the first circle (adaptive lighting)
![image](https://user-images.githubusercontent.com/70729310/153769849-4d530cec-4386-49c5-9f32-cf6c249633f1.jpeg)

**Comment by bwp91** [comment]
I see. It’s possible that a scene or automation may be turning this back on. You can disable adaptive lighting by setting the “adaptive lighting shift” in the light settings to `-1`.

**Comment by Stetocasa** [comment]
Seems solved
