### ISSUE TITLE
"Please check that you properly call the callback!"

### ISSUE THREAD

**Issue by CadLiara** [bwp91/homebridge-govee#212]
### What issue do you have? Please be as thorough and explicit as possible.

At first I thought this was more of a global issue but have been able to narrow it down to govee only devices that are controlled via voice/Siri through HOOBS and this plugin. 
On a rather regular basis I can ask Siri to turn on/off or change the color/brightness, etc of a device and it will carry out the request successfully, but then report to me that either the device is taking too long and/or that it failed to respond. 
Rarely is it that it actually takes too long or doesn't carry out the request but it is quite annoying to have my homepod minis constantly telling me that something isn't working that is. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBS in a box

* Which version of Homebridge/HOOBS do you have?

4.1.22

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

HOOBS in a box 
NODE: 16.14.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

4.28 
(Just installed 4.28.1-beta 5 to see if that may help, but no)

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

It doesn't seem to matter as I have over a dozen different devices (models) and it seems to randomly effect almost all of them at different times/instances. Whether it is WiFi light strips, Neon, Glide, etc. 

### Please paste any relevant logs below.

```
2/13/2022, 8:35:37 PMGoveeERROR[Govee 08B7@Hue] The write handler for the characteristic 'Hue' on the accessory 'Office Closet' was slow to respond!
2/13/2022, 8:35:37 PMGoveeERROR[Govee 08B7@On] The write handler for the characteristic 'On' on the accessory 'Corner' was slow to respond!
2/13/2022, 8:35:37 PMGoveeERROR[Govee 08B7@On] The write handler for the characteristic 'On' on the accessory 'Desk Lights' was slow to respond!
2/13/2022, 8:35:37 PMGoveeERROR[Govee 08B7@Hue] The write handler for the characteristic 'Hue' on the accessory 'Bricks' was slow to respond!
2/13/2022, 8:35:37 PMGoveeERROR[Govee 08B7@Hue] The write handler for the characteristic 'Hue' on the accessory 'Upper' was slow to respond!
2/13/2022, 8:35:37 PMGoveeERROR[Govee 08B7@On] The write handler for the characteristic 'On' on the accessory 'Portal' was slow to respond!
2/13/2022, 8:35:37 PMGoveeERROR[Govee 08B7@Hue] The write handler for the characteristic 'Hue' on the accessory 'Glide' was slow to respond!
2/13/2022, 8:35:37 PMGoveeGoveeWARNING[Office Closet] device supports 'colorwc' command, let me know on Github with model number [H6144].
2/13/2022, 8:35:37 PMGoveeGovee[Office Closet] current colour [rgb 191 239 255].
2/13/2022, 8:35:37 PMGoveeGovee[Immersion] current colour [rgb 191 239 255].
2/13/2022, 8:35:38 PMGoveeGoveeWARNING[Lively] device supports 'colorwc' command, let me know on Github with model number [H610A].
2/13/2022, 8:35:38 PMGoveeGovee[Lively] current colour [rgb 191 239 255].
2/13/2022, 8:35:38 PMGoveeGoveeWARNING[Kitchen Neon] device supports 'colorwc' command, let me know on Github with model number [H61A0].
2/13/2022, 8:35:39 PMGoveeGovee[Kitchen Neon] current colour [rgb 191 239 255].
2/13/2022, 8:35:39 PMGoveeGovee[Bricks] current colour [rgb 191 239 255].
2/13/2022, 8:35:40 PMGoveeGovee[Upper] current colour [rgb 191 239 255].
2/13/2022, 8:35:40 PMGoveeGovee[Glide] current colour [rgb 191 239 255].
2/13/2022, 8:35:41 PMGoveeGoveeWARNING[Office Closet] device supports 'colorwc' command, let me know on Github with model number [H6144].
2/13/2022, 8:35:43 PMGoveeERROR[Govee 08B7@On] The write handler for the characteristic 'On' on the accessory 'Corner' didn't respond at all!. Please check that you properly call the callback!
2/13/2022, 8:35:43 PMGoveeERROR[Govee 08B7@On] The write handler for the characteristic 'On' on the accessory 'Desk Lights' didn't respond at all!. Please check that you properly call the callback!
2/13/2022, 8:35:43 PMGoveeERROR[Govee 08B7@On] The write handler for the characteristic 'On' on the accessory 'Portal' didn't respond at all!. Please check that you properly call the callback!
```

**Comment by bwp91** [comment]
Hi @CadLiara 

Do you have your govee username and password and API key in the plugin settings?

Also have you setup the plugin to control any devices via bluetooth?

Just trying to work out your setup so far!

**Comment by CadLiara** [comment]
Username/password  both in config of plug-in along with my API key.

And no, no other settings on any of the other devices are checked and/or utilized. 

Due to an unrelated issue (prior to which I had the same problem I am reporting here) I had to pull and reflash the HOOBS memory card and reinstall everything from scratch and still this issue came back along with it.

This didn’t used to be a problem in the past and cropped up in the last 2-3 months.

**Comment by bwp91** [comment]
Can you show me your plugin startup logs?

**Comment by CadLiara** [comment]
Sure thing.
(I enabled debug logging at 11:15 2-15-22 and proceeded to reboot the govee plugin if that helps to isolate in the logs)
[log.txt](https://github.com/bwp91/homebridge-govee/files/8074045/log.txt)

**Comment by CadLiara** [comment]
And as I think I may have mentioned, I recently reflashed the HOOBS memory card and re-installed all the plugins and generated a new API key for it from Govee. I used Bonjour before and Ciao after the re-install. The issue was present before and remains after. 
The reason for the reflash was due to HOOBS not allowing an update and being advised by the HOOBS folks that that would be my go to solution for that issue.
Not sure if any of this is helpful, but trying to think of any information that I may be able to provide that could help clue in what might be going on here.

**Comment by bwp91** [comment]
I am wondering if you need to request a new API key from Govee. Could you do this, update the config with the new API key you receive from govee and then restart the govee bridge?

**Comment by CadLiara** [comment]
Just got a new key, input it, restarted the bridge. The issue persists.

**Comment by theyluvloki** [comment]
I'm having the same issue. It hangs up homebridge so no other device can be used until it finishes going through all of the brightness steps. "The write handler for the characteristic 'Brightness' on the accessory 'XXX' was slow to respond!".

**Comment by bwp91** [comment]
Could either of you get me some logs with the plugin debug mode setting on?

@theyluvloki are you using hoobs or homebridge?

Sorry its taken me a while to respond to this!

**Comment by CadLiara** [comment]
The logs I posted were with debug mode on.

**Comment by CadLiara** [comment]
Ok I am not sure what you did with 4.29 and I am knocking on wood, but I just updated and not only  is Siri no longer reporting the delays / cannot communicate with issues but the devices are responding almost instantly. 

Praying this will last.

**Comment by CadLiara** [comment]
Never mind. The issue remains. :(

**Comment by bwp91** [comment]
> The logs I posted were with debug mode on.

I cannot see any plugin debug logging in the logs you posted. Make sure you turn on debug logging in the plugin settings, this is separate to the debug mode that HOOBS has.

<img width="272" alt="Screenshot 2022-03-06 at 14 57 29" src="https://user-images.githubusercontent.com/43026681/156928666-44e0eec5-03a9-4dfb-9b96-b35c209ec30d.png">

Hopefully with this mode on, you will be able to recreate some of the errors so I can see exactly what is going wrong from the logs

**Comment by CadLiara** [comment]
My third post in this thread included the downloaded logs with debug on. 
I just ran another log with debug on as well (attached.) The issue persists, is consistently replicated and command to response through Homekit voice takes anywhere from 20 seconds to a full minute with Siri either reporting a "your device is taking too long to respond" or "is not responding" error even though the device eventually does what was asked. 

This is ONLY with govee devices through Hoobs/plugin. My other plugins/devices and native homekit devices work fine. 

 
[Govee debug log 3-6-22.txt](https://github.com/bwp91/homebridge-govee/files/8193289/Govee.debug.log.3-6-22.txt)

**Comment by CadLiara** [comment]
I have a theory (and bear with me as I have zero programming/backend experience) but I am wondering if perhaps throughout the history of me setting up homekit / adding-deleting devices, etc there may somehow be a "phantom" version of the plugin and/or perhaps somehow data that is still lingering causing siri/homekit to call to an a different version of the devices and/or multiple iterations of devices duplicating the efforts.

Is this possible? 
I have checked and cleared the cache, deleted and repaired the bridge, you name it, I have probably tried it to try and troubleshoot this issue. 

Perhaps I am chasing ghosts (no pun intended) but everything I have tried so far hasn't worked.

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.

**Comment by tjb1013** [comment]
Sorry, this is a minor issue (as it is working) but I am seeing the same:

- Ask Siri to turn on or off the bedroom air purifier.
- The command is executed (it goes on or off, appropriately)
- Siri responds "The bedroom air purifier is not responding"

Only message (with debug on) seems to be:

[10/19/2022, 7:00:31 PM] [Govee] [Bedroom Air Purifier] could not be updated as Request failed with status code 400 at settle (file:///usr/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).

**Comment by bwp91** [comment]
@tjb1013 which model is your device and which version of the plugin do you have?

**Comment by tjb1013** [comment]
> @tjb1013 which model is your device and which version of the plugin do you have?

My bad … Govee H7122

homebridge-govee v6.0.4

OS	Raspbian GNU/Linux Buster (10)

Node.js Version	[v16.17.1]

**Comment by bwp91** [comment]
> > @tjb1013 which model is your device and which version of the plugin do you have?
> 
> My bad … Govee H7122
> 
> homebridge-govee v6.0.4
> 
> OS Raspbian GNU/Linux Buster (10)
> 
> Node.js Version [v16.17.1]

Thanks, you should find this is fixed in the beta version of the plugin

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

^ i’m assuming you have your govee email and password in the plugin config?

**Comment by tjb1013** [comment]
> Thanks, you should find this is fixed in the beta version of the plugin
> 

That fixed it, thanks.
