### ISSUE TITLE
Add Support for Gaming Kit H604A

### ISSUE THREAD

**Issue by LiamSx45** [bwp91/homebridge-govee#213]
* **Please explain your feature request in a one or two sentences.**

Add support for the new Govee gaming light kit for full control.

* **Is your feature request related to a problem? Please describe.**

No problem, just a new device.

* **Any particular Govee devices that this relates to?**

H604A

* **Anything else?**

From home bridge logs running beta:

> {"device":"B8:0D:D8:39:32:37:21:4E","deviceName":"Computer Monitor","model":"H604A","httpInfo":{"groupId":2484250,"device":"B8:0D:D8:39:32:37:21:4E","sku":"H604A","spec":"","versionHard":"3.02.01","versionSoft":"1.00.11","deviceName":"Computer Monitor","deviceExt":{"deviceSettings":"{\"wifiName\":\"Jaspernet\",\"address\":\"D8:39:32:37:21:4E\",\"bleName\":\"Govee_H604A_214E\",\"topic\":\"GD/604c990035374859bd77dd070eab74fc\",\"wifiMac\":\"D4:AD:FC:2C:AF:60\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.02\",\"wifiHardVersion\":\"1.03.20\",\"ic\":48,\"secretCode\":\"ud7YOTI3IU4=\",\"sku\":\"H604A\",\"device\":\"B8:0D:D8:39:32:37:21:4E\",\"deviceName\":\"Computer Monitor\",\"versionHard\":\"3.02.01\",\"versionSoft\":\"1.00.11\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/d890bd9794ef26c707ea75a03800ddde-add_list_type_device_604a%403x.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":48}"},"pactType":1,"pactCode":1,"goodsType":95},"isAPIDevice":false}

**Comment by bwp91** [comment]
Hi @LiamSx45 

Please update to the beta version of the plugin: https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

the device should show as working.

Since this device is bluetooth only, the setup may be a little bit more involved, any issues setting it up please let me know

**Comment by LiamSx45** [comment]
Hi, @bwp91 

Thank you, I have updated to the latest beta version but realized that my home bridge server is being ran from a different location so I won't be able to test the bluetooth on the H604A lights until I move my server to my current location.
