### ISSUE TITLE
ColorWC Support for H619C

### ISSUE THREAD

**Issue by AirBerlin7421** [bwp91/homebridge-govee#214]
* **Please explain your feature request in a one or two sentences.**
In the console logs of home bridge, it says H619C supports color WC and I should let you know. 

* **Is your feature request related to a problem? Please describe.**
No.

* **Any particular Govee devices that this relates to?**

H619C

* **Anything else?**

Nope, but great plugin!

**Comment by bwp91** [comment]
Hi @Alters7 

thanks for reporting this, please can you update to the newest version of the plugin and check that colour control is still working from homebridge?

thanks

**Comment by stephenmd** [comment]
i received this command for the H6076 as well
