### ISSUE TITLE
Expose Govee Lights as Switches?

### ISSUE THREAD

**Issue by jeanofthedead** [bwp91/homebridge-govee#215]
### What issue do you have? Please be as thorough and explicit as possible.

I was wondering if it was poossible to expose my Govee lights as switches/outlets in Homekit, rather than lights? I have them set to DIY scenes and would prefer they simply stay the way they are currently set, and be powered on/off from Homekit like a switch (rather than allowing Siri to change the color/brightness along with the other lights). Please advise.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge

* Which version of Homebridge/HOOBS do you have?
1.4.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
4.28.0

**Comment by alikhodrali** [comment]
I'm interested in this as well. I hate having to open the app to change it back to my favourite scene because HomeKit sets it to 100% with a specific colour. Really annoying

**Comment by jeanofthedead** [comment]
Is it not possible? Thanks.

**Comment by bwp91** [comment]
Yes this definitely is possible to expose as a switch.

But it may be that the Eve app already offers what you are looking for.

When you create a scene or an automation in the Home app, with a light that supports colour, you are forced to choose a state (on/off) and if the state is ON then you must choose a brightness and a colour. When the scene or automation is run, homekit will change these three states (ON, BRIGHTNESS, COLOUR).

However, the Eve HomeKit app lets you create scenes and automations with just the items that you need. So in the Eve app it is possible to create scenes and automations that just control the state without changing the brightness and colour. 

These Eve scenes and automations are still HomeKit scenes and automations so once made in the Eve app they will appear in the Home app and be controllable with Siri etc.

By making an Eve app scene/automation just controlling the state (ON/OFF) this will not change the brightness and the colour when the scene is called, so the device should stay in the same govee scene as it was before.

**Comment by jeanofthedead** [comment]
Hey bwp91,

I'm familiar with the Eve app and this is a fantastic solution for automations (wish the Home.app was this granular). However, what I'm trying to avoid is changing the color/brightness of Govee lights when speaking to Siri (i.e. "turn all lights red," or "dim the living room lights"), if that makes sense. So being able to expose a few strips as mere switches would be super helpful.

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
