### ISSUE TITLE
Homebridge Govee Plugin Feedback

### ISSUE THREAD

**Issue by kmechols60** [bwp91/homebridge-govee#217]
Feedback as requested:

[Govee] [Shop_01-Ceiling] device supports 'colorwc' command, let me know on Github with model number [H619E].

-Kevin

**Comment by bwp91** [comment]
Hi @kmechols60 

thanks for reporting this, please can you update to the newest version of the plugin and check that colour control is still working from homebridge?

thanks

**Comment by kmechols60** [comment]
Working great!
-Kevin
    On Sunday, February 27, 2022, 03:02:19 AM CST, Ben ***@***.***> wrote:  
 
 


Hi @kmechols60

thanks for reporting this, please can you update to the newest version of the plugin and check that colour control is still working from homebridge?

thanks

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
