### ISSUE TITLE
Is there a way to add color control for LED light?

### ISSUE THREAD

**Issue by jnpatrick99** [bwp91/homebridge-govee#22]
* **Please explain your feature request in a one or two sentences.**
There's a way to control brightness with long click on the widget, is there a way to add color control (Hue) the same way?

* **Is your feature request related to a problem? Please describe.**
No way to control the color of Govee lights through Homebridge web interface.

* **Any particular Govee devices that this relates to?**
H6159

* **Anything else?**
That's it!

**Comment by bwp91** [comment]
Hi @jnpatrick99 
This is a feature that would need to be added to the homebridge-config-ui-x plugin itself.
There's nothing I can do within my own plugin to enable this functionality.
Sorry!
