### ISSUE TITLE
Please give support to Govee H6101 over BLE!

### ISSUE THREAD

**Issue by tomhillmeyer** [bwp91/homebridge-govee#221]
Hello! I'm attempting to connect my Govee H6101 lights to Homebridge over BLE, and my error logs give the following and said to post it here! 

It looks like Homebridge was able to detect my lights over BLE, but they're not supported. If there's anyway they could be supported that would be awesome. Thank you!

```
[TV Lights] is not currently supported, do create a Github issue with the following info:
{"device":"44:C9:86:A3:81:DD:A1:0B","deviceName":"TV Lights","model":"H6101","httpInfo":{"groupId":0,"device":"44:C9:86:A3:81:DD:A1:0B","sku":"H6101","spec":"","versionHard":"1.00.00","versionSoft":"1.01.17","deviceName":"TV Lights","deviceExt":{"deviceSettings":"{\"bleName\":\"ihoment_H6101_88CC\",\"ic\":0,\"sku\":\"H6101\",\"device\":\"44c986a381dda10b\",\"deviceName\":\"TV Lights\",\"versionHard\":\"1.00.00\",\"versionSoft\":\"1.01.17\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}

```

**Comment by bwp91** [comment]
Hi @tomhillmeyer 

If you update to the beta version of the plugin, then this device should appear in homebridge.
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

You may or may not find that the bluetooth works right away, it can be hit and miss, you may need to install some extra packages on your system (also, unfortunately latest versions of macos are not supported with bluetooth).

**Comment by tomhillmeyer** [comment]
Thank you @bwp91! After the update it successfully added my device.

I presume this error I'm getting is related to what you're saying about needing extra packages. I'm a couple versions behind of macOS so hopefully that's not the issue. What sort of packages do you mean? Any specific ones?

`[TV Lights] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15)`
