### ISSUE TITLE
H5082 Smart Outlet Schedule not updating

### ISSUE THREAD

**Issue by rmaes4** [bwp91/homebridge-govee#226]
I have several of the Govee H5082 smart outlets. I have set them to turn on/off at different times through the Govee app. When this schedule turns the outlet on/off the state is not updated in HomeKit. When I manually turn the outlet on/off through the Govee app the state IS updated in HomeKit. How can I get the outlet's state to be accurately reflected?

**Comment by bwp91** [comment]
Hi @rmaes4 slowly working my way through these old issues.

Do you still own these H5082 devices?

**Comment by rmaes4** [comment]
@bwp91 

I do still own these devices and I use them daily.

**Comment by bwp91** [comment]
From the plugin settings screen -> my devices tab, can you select one of these devices and tell me whether it shows as AWS Supported?

i believe you already have your govee username and password in the config right?

**Comment by rmaes4** [comment]
@bwp91 I do have my govee username and password in the config.

From the my devices tab:


Govee Model | H5082
-- | --
API Supported | No
AWS Supported | Yes
AWS Enabled | Yes


<br class="Apple-interchange-newline">

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
