### ISSUE TITLE
[Smart LED Bulb] device supports 'colorwc' command, let me know on Github with model number [H6008]

### ISSUE THREAD

**Issue by PandaUnit-TWL** [bwp91/homebridge-govee#227]
[Smart LED Bulb] device supports 'colorwc' command, let me know on Github with model number [H6008]

**Comment by sudds65** [comment]
I also have this issue.

**Comment by bwp91** [comment]
Hi @PandaUnit-TWL 

Are you able to update to the latest version of the plugin and confirm that colour control is still working for this model?
