### ISSUE TITLE
[Light Bar] device supports 'colorwc' command, let me know on Github with model number [H6056]

### ISSUE THREAD

**Issue by ljford7** [bwp91/homebridge-govee#228]
[Light Bar] device supports 'colorwc' command, let me know on Github with model number [H6056]

**Comment by bwp91** [comment]
Hi @ljford7 

Are you able to update to the latest version of the plugin and confirm that colour control is still working for this model?

Thanks!

**Comment by ljford7** [comment]
Good Morning,

Just updated and can confirm it is working.

Thanks!

**Comment by bwp91** [comment]
Great, thanks for the reply!
