### ISSUE TITLE
Eve alternative

### ISSUE THREAD

**Issue by ctml91** [bwp91/homebridge-govee#229]
Hello!

Home assistant user here. The [Govee integration for Home Assistant](https://community.home-assistant.io/t/govee-integration/228516/764) is not quite as mature as this plugin, there is only support for basic on/off/brightness/colour but no effects/scenes of any kind. Although I don't use home kit, I thought it might be possible to take advantage of HomeBridge and this plugin as there is a [HomeKit Controller](https://www.home-assistant.io/integrations/homekit_controller/) integration to connect to HomeBridge to gain access to HomeKit devices/controls.

I successfully connected Home Assistant to Home Bridge where I have installed your plugin, it can see the Govee lightstrip and I am able to control it which is great. The scenes though come through separate controls which I understand are setup in the Eve app separately. I figured, or maybe hoped that if I could get those buttons/switches setup for the Scenes/Video/Segment/Music options that then Home Assistant may discover them if they are seen as actual switches in Home Kit/Home Bridge. I don't know if that is true or not, but I think it may be my only shot. I am stuck though because I don't have access to a device compatible with Eve, although I own a newer macbook (my only apple device, so I have no other option) the eve app crashes on startup. Is configuring the additional switches/accessories through Eve a requirement, or is there another app that can accomplish the same thing for Home Kit and would they be discoverable through Homebridge? 

Thanks!

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
