### ISSUE TITLE
H5101 support request 

### ISSUE THREAD

**Issue by arekpk** [bwp91/homebridge-govee#23]
* **Please explain your feature request in a one or two sentences.**
* Can you please support a Bluetooth device H5101? These are simple thermometers 

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Govee devices that this relates to?**
H5101

* **Anything else?**

**Comment by bwp91** [comment]
Hi @arekpk 
Unfortunately this model is not supported by the Govee API that this plugin uses. There is a fixed device list that the plugin is limited to.
It might be worth you asking Govee directly to support this model, and maybe in a future version of the API I would be able to support the device in this plugin.
Thanks!

**Comment by bwp91** [comment]
There is also this plugin (I have never used it)
https://github.com/asednev/homebridge-plugin-govee
and it states support for the H5075, but you might find it works with a different thermostat model?

**Comment by arekpk** [comment]
Thanks!
Unfortunately, I tried the other plugin but it didn’t work with my model.
Would you be able to tell me what the limitation is to support my model so I could explain to Govee my request?

Thanks!

**Comment by bwp91** [comment]
The Govee API is cloud-based so any device it supports will need to have wifi capabilities (not bluetooth). The other plugin doesn't use the API, it uses bluetooth to connect to the device it supports. You _may_ have more luck contacting the dev of the other plugin to see if the H5101 could be supported.

If you have received your Govee API key email then you will have the PDF document attached - in that file you can see the devices that the API supports. It is currently limited to LED strip devices, so I don't know if they plan to implement thermometer devices in the future.

You'd need to ask if Govee could support the H5101 via the API. But if the device doesn't have wifi then I don't think you'd have much luck.

**Comment by bwp91** [comment]
https://github.com/asednev/homebridge-plugin-govee/issues/4

Could be worth a try?

**Comment by arekpk** [comment]
Thanks - appreciate the reply. I thought along the same lines about the other plug-in, but I didn’t realize Govee didn’t support the H5101 with its API. Thanks!

**Comment by bwp91** [comment]
> [asednev/homebridge-plugin-govee#4](https://github.com/asednev/homebridge-plugin-govee/issues/4)
> 
> Could be worth a try?

I think your best bet would be to get in contact with the dev of this plugin, perhaps following the steps in the issue linked, to see if they can implement support for your device.

Hope this helps :)
