### ISSUE TITLE
2 new device supports 'colorwc' command

### ISSUE THREAD

**Issue by LiamSx45** [bwp91/homebridge-govee#232]
### What issue do you have? Please be as thorough and explicit as possible.

`device supports 'colorwc' command, let me know on Github with model number [H604A]`
`device supports 'colorwc' command, let me know on Github with model number [H6073]`

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

I use Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

1.4.0 Homebridge

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi, Node.js Version 16.14.0 and NPM version 8.5.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

The latest version, 4.30

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H604A and H6073

### Please paste any relevant logs below.

```
device supports 'colorwc' command, let me know on Github with model number [H604A]
device supports 'colorwc' command, let me know on Github with model number [H6073]
```

**Comment by bwp91** [comment]
Hi @LiamSx45 

Thanks for this, are you able to update to the latest version of the plugin and confirm that colour control still works for both of these models?

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
