### ISSUE TITLE
H6127 cannot change color

### ISSUE THREAD

**Issue by wja731** [bwp91/homebridge-govee#235]
I cannot change the color of the H6127 strip using HomeKit.

I use Homebridge v1.4.0 running homebridge-config-ui-x v4.42.0 on a Raspberry Pi 3B. I am using homebridge-govee v4.30.1. I just started using this plugin. My light strip is a Govee H6127, Firmware 1.05.01, Hardware 1.00.01.

I am able to control the on/off state as well as the brightness of the strip. However I cannot change the hue of the strip. Here are the logs when trying to change the hue:
[01/04/2022, 21:02:30] [Govee] [Cloud] could not be updated as Cannot read properties of undefined (reading 'includes') at GoveePlatform.sendDeviceUpdate (/usr/local/lib/node_modules/homebridge-govee/lib/index.js:1105:49).

**Comment by apfatzgo** [comment]
I have the same issue. I can turn on and off, change the brightness but i can't change the colour. (Model: H6126, running Homebridge on an older pc with a bluetooth stick)

**Comment by bwp91** [comment]
hey, been extremely busy the last few days, will have a look at this this weekend!

**Comment by apfatzgo** [comment]
Thank you!

**Comment by bwp91** [comment]
Can anyone update to the beta version of the plugin 4.30.3-beta.0 to see if this has been resolved?

**Comment by wja731** [comment]
Woohoo!! It's working perfectly now. I can change the hue of the light. Thank you for your help.

**Comment by mimosaduspectacle** [comment]
Hello ! I am in the same situation, I made the last update of the plugin and since then I no longer have access to the color of the H6159 LED strip. The plugin is in version v9.4.2 and it runs on a Mac with Homebridge up to date v4.50.6.
I didn't have this problem before.

Thank you so much !
