### ISSUE TITLE
Issue with changing colors

### ISSUE THREAD

**Issue by 89c4vette** [bwp91/homebridge-govee#238]
When I control the lights on the iPad I have as the hub, they go to dim white, then the color, then bright white. When I use my phone it goes to dim white then the color. I also have the API key I don't know if that makes a difference though. I am very new to all this and am not advanced in it. 

### Details of your setup.
Homebridge UI-X, set up on mid 2011 on my iMac. 

* Which version of Homebridge/HOOBS do you have?
Homebridge v4.43.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Platform- Mac, intel (I don't know if that matters)
Node.js- v16.13.2
NPM- v8.1.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v4.30.3
I don't think I remember having an issue from a previous version, I had stopped using it for a while, I also had an iPhone 8, and now have a 13, I don't know if they had an effect. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6195
H6159

### Please paste any relevant logs below.

Here is a video of what is happening on one set.
https://drive.google.com/file/d/10EHh2t4O7uUDDcyeCcgbduhVL9oPM0bA/view?usp=sharing
```

```

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
