### ISSUE TITLE
h6052 support?

### ISSUE THREAD

**Issue by maxtaunton** [bwp91/homebridge-govee#24]
* **Please explain your feature request in a one or two sentences.**

support for H6052.

* **Is your feature request related to a problem? Please describe.**

no

* **Any particular Govee devices that this relates to?**
yes model h6052

* **Anything else?**

Govee dose say that there is support for this device
![IMG_1010](https://user-images.githubusercontent.com/71793795/102698206-ff8c1f00-41f8-11eb-855c-ea2e16dd34ca.jpg)

**Comment by bwp91** [comment]
It seems they have updated the API with support for new models!
Watch this space 🙂

**Comment by bwp91** [comment]
Please update to v2.4.0

**Comment by maxtaunton** [comment]
I just checked with my server (hoobs) and it wasn't available is there a way to update it with the cmd line?

**Comment by bwp91** [comment]
Run these commands separately from the HOOBS terminal:
```
cd ~/.hoobs/
npm install homebridge-govee@latest
```

**Comment by maxtaunton** [comment]
<img width="1028" alt="Screen Shot 2020-12-19 at 2 51 18 PM" src="https://user-images.githubusercontent.com/71793795/102700326-a8427a80-4209-11eb-9e45-eacad973ae06.png">
I received a error in npm

**Comment by bwp91** [comment]
Ah. Please try stopping HOOBS first then running the commands.

**Comment by maxtaunton** [comment]
thx I just got it working
