### ISSUE TITLE
Model H6161 is not currently supported

### ISSUE THREAD

**Issue by lhend941** [bwp91/homebridge-govee#245]
### What issue do you have? Please be as thorough and explicit as possible.

[Headboard] is not currently supported, do create a Github issue with the following info:
{"device":"5E:DA:AC:65:2B:E5:20:60","deviceName":"Headboard","model":"H6161","httpInfo":{"groupId":1020695,"device":"5E:DA:AC:65:2B:E5:20:60","sku":"H6161","spec":"","versionHard":"1.00.01","versionSoft":"1.05.01","deviceName":"Headboard","deviceExt":{"deviceSettings":"{\"bleName\":\"ihoment_H6161_2470\",\"pactType\":1,\"pactCode\":1,\"ic\":30,\"sku\":\"H6161\",\"device\":\"5edaac652be52060\",\"deviceName\":\"Headboard\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.05.01\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png\",\"ext\":\"\",\"ic\":30}"},"pactType":1,"pactCode":1,"goodsType":0},"isAPIDevice":false}

[Work Desk] is not currently supported, do create a Github issue with the following info:
{"device":"E7:63:67:B0:67:18:4A:78","deviceName":"Work Desk","model":"H6161","httpInfo":{"groupId":0,"device":"E7:63:67:B0:67:18:4A:78","sku":"H6161","spec":"","versionHard":"1.00.01","versionSoft":"1.01.20","deviceName":"Work Desk","deviceExt":{"deviceSettings":"{\"bleName\":\"ihoment_H6161_EA1C\",\"ic\":30,\"sku\":\"H6161\",\"device\":\"e76367b067184a78\",\"deviceName\":\"Work Desk\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.01.20\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png\",\"ext\":\"\",\"ic\":30}"},"goodsType":0},"isAPIDevice":false}

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
   - Homebridge 

* Which version of Homebridge/HOOBS do you have?
Raspbian GNU/Linux Bullseye (11)
   - Homebridge v1.4.0 (HAP v0.10.0)

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
   - homebridge-govee v4.30.3
   - Node.js Version | v16.15.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
   - H6161

**Comment by bwp91** [comment]
Hi @lucashend 

If you update to the beta version of the plugin, this device should be supported :)

Thanks!
