### ISSUE TITLE
Govee Outlet Issue

### ISSUE THREAD

**Issue by IceCreamGuys** [bwp91/homebridge-govee#247]
### What issue do you have? Please be as thorough and explicit as possible.
My Govee outlets appear to work as normal in Homekit, but do not actually cycle on and off as they should. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

3 - Hoobs

* Which version of Homebridge/HOOBS do you have?
Hoobs 4.0.104
Homebridge 1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi - Node 16.15.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

4.30.3
Issue started with this version, but not instantly so I don’t think it is the version. Rolled back to 4.30.2 and the same issue exists. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H5080 outlets (3 total)

Also, I changed my password as suggested for common fixes for this error and it worked - for about an hour - and then the issue came back. Changed passwords again and had no change. 

### Please paste any relevant logs below.

```

5/6/2022, 5:39:49 PMGovee BridgeGoveeWARNINGDisabling API client as Request failed with status code 429 at createError (/var/lib/hoobs/goveebridge/node_modules/axios/lib/core/createError.js:16:15).
5/6/2022, 5:39:49 PMBroadlink Rm Pro BridgeBridge is running on port 51846.
5/6/2022, 5:39:49 PMOnkyo Latest BridgeOnkyoEvent - Input changed: strm-box
5/6/2022, 5:39:49 PMGovee BridgeGoveeWARNINGDisabling BLE client as no enabled devices configured.

```

**Comment by masonjmiller** [comment]
Having the same issue except with all of my accessories, exact same log message. No accessories are responding in both hoobs or home.

**Comment by bwp91** [comment]
hi, please can you update to the beta version of the plugin?
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by masonjmiller** [comment]
Just updated and restarted the bridge, this is the logs still:

```
5/10/2022, 8:15:08 PM Govee Bridge starting
5/10/2022, 8:15:11 PM Govee Bridge Loaded plugin 'homebridge-govee'
5/10/2022, 8:15:11 PM Govee Bridge Loading 1 platforms...
5/10/2022, 8:15:11 PM Govee Bridge Govee Initialising plugin v4.30.4-beta.11 | Node v16.15.0 | HB v1.4.1 | HAPNodeJS v0.10.2 | HOOBS v4...
5/10/2022, 8:15:11 PM Govee Bridge Govee Plugin initialised. Setting up accessories....
5/10/2022, 8:15:12 PM Govee Bridge Bridge is running on port 55826.
5/10/2022, 8:15:12 PM Govee Bridge Govee WARNING Disabling BLE client as ERR_DLOPEN_FAILED.
```
Then it continues on with normal initialization without bluetooth

Should I try restarting the whole device?

Also following a rabbit hole of other solutions online, I determined the following error when I run in the terminal `service bluetooth status` I get:
```
May 10 15:36:43 hoobs bluetoothd[543]: Failed to set privacy: Rejected (0x0b)
```

But still see the service running. I've tried tons of solutions and none of them work, so I'm thinking the issue could be between Hoobs and Raspberry Pi possibly. Not sure though.

**Comment by bwp91** [comment]
The outlets aren’t controlled by bluetooth so you can ignore the bluetooth warning in the logs.
They are controlled by wifi, have you tried restarting the plugin again recently?

**Comment by bwp91** [comment]
I would also suggest updating your hoobs version to 4.2.x the latest version,

**Comment by masonjmiller** [comment]
I'm currently on 4.2.5, and my devices in question aren't outlets they're RGBIC strips unlike the original posters outlets. I've updated to the beta14 but same issue. I'm thinking it's an issue with my raspberry pi setup maybe. I'm guessing the bluetooth just isn't working at all. I might have to put in a ticket with raspberry pi.

**Comment by bwp91** [comment]
Can you make sure the pi software is up to date with a `sudo apt update` and then `sudo apt full-upgrade` in the terminal?

**Comment by masonjmiller** [comment]
Yup fully updated and upgraded already.

**Comment by IceCreamGuys** [comment]
I tried it all - and just ended up removing the Govee outlets from my configuration and using native homekit outlets instead.

The Govee outlets worked rock solid for the better part of a year up until last week. My other Govee products (LED strips, String Lights, and Smart bulbs) are all still functioning correctly. It was just the outlets.

On May 11, 2022, at 12:50 PM, Ben ***@***.***> wrote:

﻿

I would also suggest updating your hoobs version to 4.2.x the latest version,

**Comment by bwp91** [comment]
@IceCreamGuys there were changes to the govee api request limits that started last week. the beta version of the plugin is where i am trying to tackle this.

I guess this issue is resolved if you’re no longer using the outlets. You could always try them again if you wanted to .

**Comment by bwp91** [comment]
@masonjmiller have sent you a message on discord
