### ISSUE TITLE
Thermometer Issue

### ISSUE THREAD

**Issue by tonylewis42** [bwp91/homebridge-govee#252]
Not exactly sure how to post here simply following directions from the log file in hoobs.

[Indoor Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"0B:B0:A4:C1:38:2C:73:44","deviceName":"Indoor Thermometer","model":"B5178","httpInfo":{"groupId":0,"device":"0B:B0:A4:C1:38:2C:73:44","sku":"B5178","spec":"","versionHard":"1.00.01","versionSoft":"1.00.08","deviceName":"Indoor Thermometer","deviceExt":{"lastDeviceData":"{\"tem\":2440,\"hum\":2800,\"lastTime\":1651300980000}","deviceSettings":"{\"ic\":0,\"ic_sub_1\":0,\"address\":\"A4:C1:38:2C:73:44\",\"temWarning\":false,\"wifiLevel\":0,\"humMax\":10000,\"groupOrder\":0,\"fahOpen\":false,\"gatewayId\":0,\"humMin\":0,\"pactCode\":0,\"netWarning\":false,\"groupRole\":1,\"battery\":86,\"temMax\":6000,\"humWarning\":false,\"temMin\":-2000,\"pactType\":0,\"temCali\":0,\"ic_sub_2\":0,\"bleName\":\"B51787344\",\"header\":0,\"humCali\":0,\"uploadRate\":0,\"deviceName\":\"Indoor Thermometer\"}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/img/4c860fe1586d072171b1f12a63059e1c-add_list_type_device_b5178_1.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":14},"isAPIDevice":false}
5/17/2022, 2:12:27 AMGovee BridgeGoveeWARNING[Indoor Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"0B:B0:A4:C1:38:2C:73:44","deviceName":"Indoor Thermometer","model":"B5178","httpInfo":{"groupId":0,"device":"0B:B0:A4:C1:38:2C:73:44","sku":"B5178","spec":"","versionHard":"1.00.01","versionSoft":"1.00.08","deviceName":"Indoor Thermometer","deviceExt":{"lastDeviceData":"{\"tem\":2440,\"hum\":2800,\"lastTime\":1651300980000}","deviceSettings":"{\"ic\":0,\"ic_sub_1\":0,\"address\":\"A4:C1:38:2C:73:44\",\"temWarning\":false,\"wifiLevel\":0,\"humMax\":10000,\"groupOrder\":0,\"fahOpen\":false,\"gatewayId\":0,\"humMin\":0,\"pactCode\":0,\"netWarning\":false,\"groupRole\":1,\"battery\":86,\"temMax\":6000,\"humWarning\":false,\"temMin\":-2000,\"pactType\":0,\"temCali\":0,\"ic_sub_2\":0,\"bleName\":\"B51787344\",\"header\":0,\"humCali\":0,\"uploadRate\":0,\"deviceName\":\"Indoor Thermometer\"}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/img/4c860fe1586d072171b1f12a63059e1c-add_list_type_device_b5178_1.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":14},"isAPIDevice":false}
5/17/2022, 2:12:27 AMGovee BridgeGoveeWARNING[Outdoor Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"0B:B0:A4:C1:38:2C:73:44_1","deviceName":"Outdoor Thermometer","model":"B5178","httpInfo":{"groupId":0,"device":"0B:B0:A4:C1:38:2C:73:44_1","sku":"B5178","spec":"","versionHard":"1.00.00","versionSoft":"1.00.00","deviceName":"Outdoor Thermometer","deviceExt":{"lastDeviceData":"{}","deviceSettings":"{\"ic\":0,\"device\":\"0B:B0:A4:C1:38:2C:73:44_1\",\"pDevice\":\"0B:B0:A4:C1:38:2C:73:44\",\"ic_sub_1\":0,\"address\":\"A4:C1:38:2C:73:44\",\"temWarning\":false,\"wifiLevel\":0,\"humMax\":10000,\"groupOrder\":1,\"fahOpen\":false,\"gatewayId\":0,\"humMin\":0,\"pactCode\":0,\"netWarning\":false,\"groupRole\":2,\"sku\":\"B5178\",\"battery\":100,\"temMax\":6000,\"humWarning\":false,\"temMin\":-2000,\"deviceName\":\"Outdoor Thermometer\",\"pactType\":0,\"temCali\":0,\"ic_sub_2\":0,\"bleName\":\"B51787344\",\"header\":0,\"humCali\":0,\"uploadRate\":0}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/img/e57571028831ecb45811f1ef23022d6b-add_list_type_device_b5178_2.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":14},"isAPIDevice":false}
5/17/2022, 2:12:27 AMGovee BridgeGoveeWARNING[Outdoor Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"0B:B0:A4:C1:38:2C:73:44_1","deviceName":"Outdoor Thermometer","model":"B5178","httpInfo":{"groupId":0,"device":"0B:B0:A4:C1:38:2C:73:44_1","sku":"B5178","spec":"","versionHard":"1.00.00","versionSoft":"1.00.00","deviceName":"Outdoor Thermometer","deviceExt":{"lastDeviceData":"{}","deviceSettings":"{\"ic\":0,\"device\":\"0B:B0:A4:C1:38:2C:73:44_1\",\"pDevice\":\"0B:B0:A4:C1:38:2C:73:44\",\"ic_sub_1\":0,\"address\":\"A4:C1:38:2C:73:44\",\"temWarning\":false,\"wifiLevel\":0,\"humMax\":10000,\"groupOrder\":1,\"fahOpen\":false,\"gatewayId\":0,\"humMin\":0,\"pactCode\":0,\"netWarning\":false,\"groupRole\":2,\"sku\":\"B5178\",\"battery\":100,\"temMax\":6000,\"humWarning\":false,\"temMin\":-2000,\"deviceName\":\"Outdoor Thermometer\",\"pactType\":0,\"temCali\":0,\"ic_sub_2\":0,\"bleName\":\"B51787344\",\"header\":0,\"humCali\":0,\"uploadRate\":0}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/img/e57571028831ecb45811f1ef23022d6b-add_list_type_device_b5178_2.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":14},"isAPIDevice":false}

**Comment by bwp91** [comment]
Hi @tonylewis42 

Are you able to update to the new beta 5.2.1-beta.3 of the plugin? This device should then show up in Homebridge.

Instructions for beta installation if needed:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Thanks!
