### ISSUE TITLE
BLE Client / Color Error

### ISSUE THREAD

**Issue by bonxz** [bwp91/homebridge-govee#254]
### What issue do you have? Please be as thorough and explicit as possible.
![image](https://user-images.githubusercontent.com/61289944/168909025-54f9ad15-d218-46f3-8ff7-2191cb4f3f5c.png)

### Details of your setup.
Homebridge Synology SPK ( https://github.com/oznu/homebridge-syno-spk )

* Which version of Homebridge/HOOBS do you have?
homebridge-config-ui-x v4.44.1 /  Homebridge v1.4.1 (HAP v0.10.2) (Homebridge 3F91)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Synology DS 220+
Node.js Version | v16.15.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v4.30.3

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
homebridge-govee v4.30.3

### Please paste any relevant logs below.

```
[5/17/2022, 10:55:10 PM] [Govee] Disabling BLE client as Cannot find module '/volume1/homebridge/node_modules/.pnpm/@abandonware+bluetooth-hci-socket@0.5.3-8/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
Require stack:
- /volume1/homebridge/node_modules/.pnpm/@abandonware+bluetooth-hci-socket@0.5.3-8/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js
- /volume1/homebridge/node_modules/.pnpm/@abandonware+bluetooth-hci-socket@0.5.3-8/node_modules/@abandonware/bluetooth-hci-socket/index.js
- /volume1/homebridge/node_modules/.pnpm/homebridge-govee@4.30.3/node_modules/homebridge-govee/lib/index.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/lib/plugin.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/lib/pluginManager.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/lib/server.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/lib/cli.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/bin/homebridgeRequire stack:.
[5/17/2022, 10:55:10 PM] [Govee] [Led] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H619A].
[5/17/2022, 10:55:10 PM] [Govee] [Led] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableAWS":"no","enableBT":"no","logging":"standard"}.
[5/17/2022, 10:55:10 PM] [Govee] [Led] initialised with id [31:18:7C:A6:B0:9D:25:68] [H619A].
```

**Comment by imatarasso** [comment]
I am seeing the exact same error message on Govee plugin with Homebridge Synology SPK and same versions across the board as **bonxz**

**Comment by bwp91** [comment]
Hi @bonxz and @imatarasso 

Are you able to follow the guide here? And let me know if this fixes things

https://github.com/oznu/homebridge-syno-spk/wiki/DSM-7:-Enable-Compiling-Of-Native-Modules

Thanks!

**Comment by imatarasso** [comment]
After following the instructions and proceeding to completion, I am still seeing the same error. I am curious if @bonxz is more successful...

**Comment by bwp91** [comment]
@imatarasso is it _exactly_ the same error? if not can you post logs?

**Comment by imatarasso** [comment]
Disabling BLE client as Cannot find module '/volume1/homebridge/node_modules/.pnpm/@abandonware+bluetooth-hci-socket@0.5.3-8/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
Require stack:
- /volume1/homebridge/node_modules/.pnpm/@abandonware+bluetooth-hci-socket@0.5.3-8/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js
- /volume1/homebridge/node_modules/.pnpm/@abandonware+bluetooth-hci-socket@0.5.3-8/node_modules/@abandonware/bluetooth-hci-socket/index.js
- /volume1/homebridge/node_modules/.pnpm/homebridge-govee@4.30.3/node_modules/homebridge-govee/lib/index.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/lib/plugin.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/lib/pluginManager.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/lib/server.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/lib/cli.js
- /volume1/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/bin/homebridgeRequire stack:.

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
