### ISSUE TITLE
Add support for new Pet Purifier H7123

### ISSUE THREAD

**Issue by LiamSx45** [bwp91/homebridge-govee#258]
* **Please explain your feature request in a one or two sentences.**

Add support for the new Pet Purifier, model: H7123

* **Is your feature request related to a problem? Please describe.**

error logs in homebridge

* **Any particular Govee devices that this relates to?**

H7123

* **Anything else?**

From the debug:
`{"device":"19:D3:D4:AD:FC:1A:41:16","deviceName":"Pet Air Purifier","model":"H7123","httpInfo":{"groupId":2484236,"device":"19:D3:D4:AD:FC:1A:41:16","sku":"H7123","spec":"","versionHard":"1.02.00","versionSoft":"1.00.08","deviceName":"Pet Air Purifier","deviceExt":{"deviceSettings":"{\"wifiName\":\"The Homies Rock\",\"address\":\"D4:AD:FC:1A:41:17\",\"bleName\":\"ihoment_H7123_4117\",\"topic\":\"GD/865eb247409675115841a848a01eda55\",\"wifiMac\":\"D4:AD:FC:1A:41:16\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.08\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"rIOPGwmCCX0=\",\"filterExpireOnOff\":1,\"mcuSoftVersion\":\"1.00.43\\u0000\",\"mcuHardVersion\":\"1.00.04\\u0000\",\"sku\":\"H7123\",\"device\":\"19:D3:D4:AD:FC:1A:41:16\",\"deviceName\":\"Pet Air Purifier\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.08\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":110},"isAPIDevice":false}`

**Comment by bwp91** [comment]
Hi @LiamSx45 

Can you update to the beta version - these devices (this and the humidifier) should appear in Homebridge.

The functionality may or may not work straight away, there could be some extra things I need to sort out.

Let me know!
