### ISSUE TITLE
Support for H7101 Fan - New Feature

### ISSUE THREAD

**Issue by fraserbrookhouse** [bwp91/homebridge-govee#260]
It would be great if you could support the H7101 wifi tower fan.

**Comment by fraserbrookhouse** [comment]
Sorry, I just found out it is not supported by the api. I have contacted the api team instead to find out when they plan to support it.

**Comment by bwp91** [comment]
i can support stuff outside the api. will have a look at this soon!

**Comment by bwp91** [comment]
I've just realised this device is supported already, have you tried it?
