### ISSUE TITLE
Support for H7170 Kettle

### ISSUE THREAD

**Issue by Orkyboy** [bwp91/homebridge-govee#266]
Govee recently introduced Kettle, not sure of their API is new for it or I can use heather one

**Comment by bwp91** [comment]
Hi @Orkyboy 

Is this a wifi device? Do you own it?

**Comment by a-b** [comment]
Hi @bwp91, yes it is WiFi and I do have access. More info on [Amazon page](https://www.amazon.com/dp/B09TSKDKCL)

**Comment by michaellatman** [comment]
+1 would love to use it with Home bridge

```
Govee] [Smart Kettle] is not currently supported, do create a Github issue with the following info:
{"device":"90:EC:D4:AD:FC:5A:37:94","deviceName":"Smart Kettle","model":"H7170","httpInfo":{"groupId":0,"device":"90:EC:D4:AD:FC:5A:37:94","sku":"H7170","spec":"","versionHard":"1.02.00","versionSoft":"1.00.13","deviceName":"Smart Kettle","deviceExt":{"deviceSettings":"{\"wifiName\":\"Latman\",\"address\":\"D4:AD:FC:5A:37:95\",\"bleName\":\"ihoment_H7170_3795\",\"topic\":\"GD/62434f0a3db13280478e55a485e90e13\",\"wifiMac\":\"D4:AD:FC:5A:37:94\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.13\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"ZzFueeSBYD8=\",\"boilWaterExceptionNotiOnOff\":1,\"mcuSoftVersion\":\"1.00.63\",\"mcuHardVersion\":\"1.00.01\",\"sku\":\"H7170\",\"device\":\"90:EC:D4:AD:FC:5A:37:94\",\"deviceName\":\"Smart Kettle\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.13\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":103},"isAPIDevice":false}
```

**Comment by bwp91** [comment]
@michaellatman @a-b @Orkyboy 

Can you update to the beta version of the plugin?

The device should then appear in the home app it will show as unsupported. For the moment I am interested in the scene codes that appear in the homebridge log.

When you use the Govee app to control the kettle with a certain function, a code will appear in the log. I need a list of functions and corresponding codes (like switch on, off, etc)

Also codes may not appear if connected by bluetooth, so disable bluetooth on your phones at the time to force wifi :)

**Comment by michaellatman** [comment]
updated to beta. No logs showed when I switched it on and off via wifi 

![4AD41867-D642-4365-8FAD-16367DCB58AF](https://user-images.githubusercontent.com/236019/177023324-00830e38-b2b4-41bd-99f9-5980d141729c.jpeg)

**Comment by bwp91** [comment]
Hi @michaellatman please try newest beta :)

**Comment by michaellatman** [comment]
To turn on:
[Smart Kettle New/Unknown scene code received: [MMAAAAAAAAAAAAAAAAAAAAAABA=1]

but no scene code is shown when “canceling” the turn on

**Comment by bwp91** [comment]
I assume via the govee app you are able to cancel a turn on?

**Comment by michaellatman** [comment]
Yes. It doesn’t have an “off” just a cancel of it being on and heating

- Michael Latman

**Comment by bwp91** [comment]
I don’t know how many times you have tried cancelling to see if a code appears, but maybe try a couple more times just to see if anything appears!

**Comment by bwp91** [comment]
Please try the new beta 5.2.1-beta.5

**Comment by michaellatman** [comment]
On
[03/07/2022, 17:17:51] [Govee] [Smart Kettle] New/Unknown scene code received: [MwEBBQAAAAAAAAAAAAAAAAAAADY=].

off 
[03/07/2022, 17:17:56] [Govee] [Smart Kettle] New/Unknown scene code received: [MwEAAAAAAAAAAAAAAAAAAAAAADI=].

**Comment by bwp91** [comment]
ok beta 5.2.1-beta.6 _should_ let you flick the accessory switch in the home app to turn the kettle on.
Turning off I will need to implement another time.
Currently, the switch in the home app will turn off after 3 seconds. This is mainly due to the fact the plugin does not know (1) whether/when the kettle finishes boiling and (2) whether it was cancelled through the govee app half way through boiling
Turning off the switch during these three seconds will have no effect.
I'm also not sure what happens if after these three seconds you try to turn it on again whilst the kettle is still in heat/boiling mode.

**Comment by michaellatman** [comment]
It works! Thanks so much.

- Michael Latman

**Comment by Chiefton** [comment]
Thanks for adding the Kettle to the beta, it is working.  It turns on the Kettle to the "Black Tea/Boil" preset.  Looking at the homebridge console, I don't see the scene codes when turning it on from the Govee App.  But when I turn on the multiple preset from the Alexa app, these are the scene codes I see after selecting each one.  Is there an easy way to include each option?  Or to have the "on" button through Homekit do the preset we want? I would love to have it default to "coffee."  :)

Black Tea / Boil - MwUABQAAAAAAAAAAAAAAAAAAADM=
Coffee - MwUABAAAAAAAAAAAAAAAAAAAADI=
Oolong Tea - MwUAAwAAAAAAAAAAAAAAAAAAADU=
Green Tea - MwUAAgAAAAAAAAAAAAAAAAAAADQ=

**Comment by bwp91** [comment]
@Chiefton 

much easier for me to leave it as one switch but i could make it configurable so for example in your case you could enter the code for “coffee”

at a later date i could potentially look into having options for each option

**Comment by Chiefton** [comment]
Thanks, that would be great.

**Comment by sdavisNL** [comment]
I’d also love to see support added for the other presets + the custom one (which you’d obviously still need to configure within the Govee app). 

Even if we could add them as five separate devices and group them. That would at least allow easy voice control. 

Thanks so much to those working on this plugin!!

**Comment by bwp91** [comment]
Can someone share a screenshot of how the kettle appears in the govee app?

What id ideally like to know is a list of preset modes and also can you add as many custom modes as you want?

**Comment by Chiefton** [comment]
Sure thing.


________________________________

**Comment by bwp91** [comment]
i dunno whether you plan to add a screenshot or maybe you attached one to your reply but it hasn’t appeared here?

**Comment by sdavisNL** [comment]
![image](https://user-images.githubusercontent.com/558613/204166207-eff479fa-2893-4a8a-b2c1-b015eebae91d.png)

Above shows the main UI. There five settings in total, this corresponds with the five indicator lights on the front of the kettle's base. You have four set temps and one DIY setting that lets you customize the temp. 

While you can save multiple custom temps (see below), only one can be selected at a time. 

![image](https://user-images.githubusercontent.com/558613/204165989-5088e68a-7db2-48f5-ad9d-d8ce356c512b.png)

And the following is the screen where you can save the different custom temps. 

![image](https://user-images.githubusercontent.com/558613/204166251-ec7c005f-1037-479d-b465-9e3e0c7d5f01.png)

**Comment by Chiefton** [comment]
> i dunno whether you plan to add a screenshot or maybe you attached one to your reply but it hasn’t appeared here?

Sorry, I attached them to the email reply, but they did not show up here.  But Joecan00 got them posted before I did.

**Comment by bwp91** [comment]
Am i correct in seeing that it also displays the current temperature of the water in the kettle?

**Comment by bwp91** [comment]
if there is someone who would be willing to let me have access to this device for a while this would be most helpful for me.
Would be happy to message on discord
https://discord.gg/cMGhNtZ3tW

**Comment by sdavisNL** [comment]
Yes, the app does display the temp as it rises within the app. There is no temp display on the kettle itself.

**Comment by PNWOregon** [comment]
Joining in to add that being able to control custom (DIY temperatures) would be amazing!! Let me know if there is any info I can help provide to help keep this moving forward.

**Comment by bwp91** [comment]
The current options for the kettle in the plugin settings are:

<img width="491" alt="Screenshot 2023-04-30 at 13 52 47" src="https://user-images.githubusercontent.com/43026681/235353961-4d6f8f3a-7bf4-41a1-a295-70a6ff80afd5.png">

The last two custom modes relate to the first two custom modes that you may have set up in the Govee app.

Hope this helps!

**Comment by rigwig** [comment]
Was there ever any luck in getting current temp readings? Happy to share my kettle if needed.
