### ISSUE TITLE
Bluetooth is disabled but is used anyway

### ISSUE THREAD

**Issue by solbadguy2010** [bwp91/homebridge-govee#268]
### What issue do you have? Please be as thorough and explicit as possible.
Bluetooth is Disabled for the only Govee Device i own but noble keeps scanning for the device and connecting to it. This is problematic because the devices are far away from each other in my setup and the connection is not stable. Why is this not using AWS only?

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
I use Setup 1. stock HB Image flashed to a Pi. 

* Which version of Homebridge/HOOBS do you have?
Current.

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Pi 3b

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
Current Version. Yes, this startet recently but i dont know with wich version. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6199

![35085C4B-8324-4C43-A6FB-B12E73F970FB](https://user-images.githubusercontent.com/30244171/174468056-0bf89328-7244-4faa-9357-5a9dce2083cd.png)
![008F653A-346E-4F7A-8CC1-2E5EEF250B02](https://user-images.githubusercontent.com/30244171/174468058-5bdb2127-6968-42b4-827b-380bbdbc13e6.jpeg)

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @solbadguy2010 

Please update to the new beta of the plugin.

You should find bluetooth is disabled again :)

**Comment by solbadguy2010** [comment]
Looks good :-)

**Comment by solbadguy2010** [comment]
Thank you!
