### ISSUE TITLE
Support for RGBIC

### ISSUE THREAD

**Issue by bernhardmostrey** [bwp91/homebridge-govee#27]
Wondering if there is support for RGBIC models to control each led individually. Is this even possible in the homekit app?

**Comment by bwp91** [comment]
Hi @bernhardmostrey 
Unfortunately the Govee API in its current state does not support this functionality.
Also, even if it were possible through the API, I wouldn't see a nice way of implementing via the homekit app. The home app only allows for one colour for a light at any time.

**Comment by bernhardmostrey** [comment]
Thanks for the reply! Would it be possible to set a preset in the app, and then just activate and deactivate via Homebridge?

**Comment by bwp91** [comment]
This unfortunately isn't an option either. The API only allows to change:
* the on/off
* the brightness
* the colour

of a govee device.

Perhaps one day if the API is updated then this could possibly be a feature.

Sorry I can't be of more help 😅
