### ISSUE TITLE
Triggered leak sensor shows no response from accessory in Home or Homebridge 

### ISSUE THREAD

**Issue by CappyD** [bwp91/homebridge-govee#270]
see next

**Comment by CappyD** [comment]
In the Accessories list in homebridge, I see that each leak sensor now has a battery level accessory and a leak sensor accessory. But when I trigger one of the sensors, I see no indication in the accessory icon in homebridge or the Home app or in the homebridge log that a leak was detected. But the Govee Home app shows a leak was detected and it sent email. In the Home app, I had an automation for a light to be turned on if the leak sensor triggered and it also did not run.

**Comment by CappyD** [comment]
@bwp91  ... Ben, can you offer any help on this? The config seems fine and the sensors show up in Homebridge and in the iOS Home app, but they never show leak detection when a sensor is triggered.

**Comment by kclimie** [comment]
I have the same issue. The H5054 sensor state updates in the Govee Home app when triggered, but not in the iOS Home app.

**Comment by bwp91** [comment]
will definitely look into this at some point soon!

**Comment by TristanBrotherton** [comment]
I have this same issue. The sensor is shown in homekit - Govee app reports the leak status, but the Homebridge receives no notification. I'd love to help resolve this.

**Comment by bwp91** [comment]
Hi all,

if there is someone who would be happy to give me access to a govee account with the water sensors added, and also have some time to spend splashing some water on it a couple of times, then I can definitely look into this. 

It’s on my long list of things!

Let me know and perhaps we could message on discord

thanks!
