### ISSUE TITLE
Beta: Can't add any fan or humidifier/purifier to Homebridge

### ISSUE THREAD

**Issue by LiamSx45** [bwp91/homebridge-govee#273]
### What issue do you have? Please be as thorough and explicit as possible.

Does not add any Fan, purifier or humidifier to Homebridge 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
I use Homebridge UI-x

* Which version of Homebridge/HOOBS do you have?
Version 1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Synology DS720+
Node version: v16.15.1
NPM version: 8.11.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

v5.2.1-beta.3

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

- H7111
- H7160
- H7123
- H7142
- H7121

### Please paste any relevant logs below.

```
[Humidifier] could not be initialised as Cannot read properties of undefined (reading 'includes') at default.initialiseDevice (file:///volume1/homebridge/node_modules/homebridge-govee/lib/platform.js:669:50).
[Air Purifier] could not be initialised as Cannot read properties of undefined (reading 'includes') at default.initialiseDevice (file:///volume1/homebridge/node_modules/homebridge-govee/lib/platform.js:669:50).
[Medium Humidifier] could not be initialised as Cannot read properties of undefined (reading 'includes') at default.initialiseDevice (file:///volume1/homebridge/node_modules/homebridge-govee/lib/platform.js:669:50).
[Pet Air Purifier] could not be initialised as Cannot read properties of undefined (reading 'includes') at default.initialiseDevice (file:///volume1/homebridge/node_modules/homebridge-govee/lib/platform.js:669:50).
[Fan] could not be initialised as Cannot read properties of undefined (reading 'includes') at default.initialiseDevice (file:///volume1/homebridge/node_modules/homebridge-govee/lib/platform.js:669:50).
```

**Comment by bwp91** [comment]
Hi @LiamSx45 please try newest beta!

**Comment by LiamSx45** [comment]
Hi @bwp91 it works great now, thank you for the quick fix

**Comment by bwp91** [comment]
Hi @LiamSx45 

I see you have the H7160, if you have some spare time could you look at this?

https://github.com/bwp91/homebridge-govee/issues/321

**Comment by bwp91** [comment]
and for H7123
