### ISSUE TITLE
Feature for Hygrometers H5100

### ISSUE THREAD

**Issue by LiamSx45** [bwp91/homebridge-govee#276]
The hygrometers appear great in HomeKit and send the climate information very nicely. However, they are "offline" in HomeKit per the option to make them that way for any 'off' device. I don't know if there is an option to make them have a status as on instead of offline? If not, I understand due to the HomeKit limitations!

Thank you!

**Comment by bwp91** [comment]
Hi @LiamSx45 

What do you mean by `they are "offline" in HomeKit`? The plugin does not have an option to show whether a sensor is online/offline in HomeKit.

So I'm scratching my head a little at what you mean!

Thanks!
