### ISSUE TITLE
Device request

### ISSUE THREAD

**Issue by bcnation** [bwp91/homebridge-govee#282]
* **Please explain your feature request in a one or two sentences.**
please add support for H5074 and H5174 humidity sensors

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

H5074 and H5174

* **Anything else?**

**Comment by bwp91** [comment]
These devices are already supported by this plugin if they are wifi 

are they wifi? or just bluetooth?
