### ISSUE TITLE
Air purifier H7122: no fan speed control

### ISSUE THREAD

**Issue by horsenoggingit** [bwp91/homebridge-govee#289]
### What issue do you have? Please be as thorough and explicit as possible.

Issue
When I change the fan speed slider in the Home App the air purifier selects “custom” fan speed for fan speeds <= 75% and auto mode for fan speeds greater than 75%

Expected 
Fan speeds 1, 2 and 3 are selected based on the appropriate fan speed slider position  in the Home App

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge running on macOS with config-ui

* Which version of Homebridge/HOOBS do you have?

1.5.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

5.2.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Air purifier h7122

**Comment by rmaes4** [comment]
I actually like this feature as it allows me to use automations to set a fixed, low speed while I sleep at night and set auto mode for during the day,

**Comment by bwp91** [comment]
Hi @horsenoggingit 

I implemented this device with the following homekit speed to govee mode map:

* 0% - off
* 25% - govee speed 1 [low]
* 50% - govee speed 2 [med]
* 75% - govee speed 3 [high]
* 100% - govee auto mode

This was intentional and simply for a way to be able to put the device into auto mode if you wanted, as I couldn't think of a better way.

If you have any ideas please do let me know

**Comment by horsenoggingit** [comment]
I think that’s a nice compromise. Cheers. -JamesOn Oct 9, 2022, at 3:20 AM, Ben ***@***.***> wrote:﻿
Hi @horsenoggingit
I implemented this device with the following homekit speed to govee mode map:

0% - off
25% - govee speed 1 [low]
50% - govee speed 2 [med]
75% - govee speed 3 [high]
100% - govee auto mode

This was intentional and simply for a way to be able to put the device into auto mode if you wanted, as I couldn't think of a better way.
If you have any ideas please do let me know

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
