### ISSUE TITLE
Adaptive Lighting

### ISSUE THREAD

**Issue by smcarlsonpdx** [bwp91/homebridge-govee#29]
* **Please explain your feature request in a one or two sentences.**

Is there a way through scripting to enable the Govee light strips to work light the new Adaptive Lighting features appearing in HomeKit and other vendor specific apps?  I'm new to this platform so I'm not sure if there's another space where this would have been addressed in the past.
Hue plugin has something started here: https://github.com/ebaauw/homebridge-hue/commit/c656bac23cdc92ab929fdda31063922abaec4a64 

* **Is your feature request related to a problem? Please describe.**

No problem, just an enhancement request.

* **Any particular Govee devices that this relates to?**

I'm not sure of specific model but I have the Alexa enabled 32 and 16 ft RGBIC wifi/Bluetooth strips.

* **Anything else?**

Any questions, please feel free ask.

**Comment by bwp91** [comment]
Hi @smcarlsonpdx adaptive lighting is a new feature of Homebridge 1.3 beta, so you need to have this beta version installed... 
https://github.com/homebridge/homebridge/issues/2765
If you use config-ui-x, you can easily update to the beta by clicking on the Homebridge version on the main page and choosing a different version to install.

**Comment by smcarlsonpdx** [comment]
I'm currently running a HOOBS setup on their Rasp Pi 3 as I'm somewhat new to this project.  Any suggestions of how to do this update without disrupting their nice HOOBS interface?

> Hi @smcarlsonpdx adaptive lighting is a new feature of Homebridge 1.3 beta, so you need to have this beta version installed... 
> 
> https://github.com/homebridge/homebridge/issues/2765
> 
> If you use config-ui-x, you can easily update to the beta by clicking on the Homebridge version on the main page and choosing a different version to install.

**Comment by bwp91** [comment]
Ah I didn't realise you use HOOBS. I don't think it's possible to change the version of Homebridge with HOOBS.

**Comment by smcarlsonpdx** [comment]
> Ah I didn't realise you use HOOBS. I don't think it's possible to change the version of Homebridge with HOOBS.

What are advantages of using the Homebridge over the HOOBS (which includes Homebridge) projects?  Should I just switch?

**Comment by bwp91** [comment]
Of course, it's completely up to you whether you use Homebridge or HOOBS. There are many posts on reddit comparing the 'differences'. Although if you're already set up with HOOBS, is it really worth it... switching... for adaptive lighting?

I assume that when Homebridge 1.3 is released, that HOOBS will update their system in turn.

**Comment by smcarlsonpdx** [comment]
OK, thank you for that response , it was very helpful.  I’ll hang tight for the HOOBS team to update to hb 1.3 within their distribution.  

Regards,
