### ISSUE TITLE
MaxListenersExceedWarning from EventEmitter

### ISSUE THREAD

**Issue by intrepidsilence** [bwp91/homebridge-govee#295]
### What issue do you have? Please be as thorough and explicit as possible.
It appears that there may be a code bug as I am seeing this error in the HB log:
```
(node:116745) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Ubuntu LXD container on x86_64 Ryzen

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
5.2.0, not sure, just noticed

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6073 lamp is the device that reported when the error popped up. The error was right after this in the HB log:
```
[8/25/2022, 10:12:27 AM] [Govee] [Lamp] [API] receiving update [{"source":"API","online":true,"powerState":"off","brightness":24,"colorTemInKelvin":2200,"colorTem":2200}].
```

### Please paste any relevant logs below.
already provided above

```

```

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
