### ISSUE TITLE
New Air Quality Monitor Device H5106

### ISSUE THREAD

**Issue by LiamSx45** [bwp91/homebridge-govee#297]
* **Please explain your feature request in a one or two sentences.**

Add support for the new Air Quality Monitor

* **Is your feature request related to a problem? Please describe.**

`{"device":"27:0E:D7:32:38:31:54:93","deviceName":"Air Quality Monitor","model":"H5106","httpInfo":{"groupId":0,"device":"27:0E:D7:32:38:31:54:93","sku":"H5106","spec":"","versionHard":"3.01.01","versionSoft":"1.00.07","deviceName":"Air Quality Monitor","deviceExt":{"lastDeviceData":"{}","deviceSettings":"{\"humMin\":0,\"humWarning\":true,\"airQualityOnOff\":1,\"pactCode\":1,\"temCali\":0,\"pm25Max\":1000,\"wifiMac\":\"D4:AD:FC:93:C5:B2\",\"humCali\":0,\"bleName\":\"GVH5106_5493\",\"pm25Warning\":true,\"humMax\":10000,\"secretCode\":\"k1QxODLXAAA=\",\"temWarning\":true,\"temMin\":-1000,\"pm25Min\":0,\"pactType\":1,\"address\":\"D7:32:38:31:54:93\",\"temMax\":5000,\"uploadRate\":10,\"deviceName\":\"Air Quality Monitor\",\"topic\":\"GD/bd45611fb2598db7a6b411ab70ba91d3\"}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":124},"isAPIDevice":false}`

* **Any particular Govee devices that this relates to?**

Air Quality Monitor: H5106

* **Anything else?**

**Comment by bwp91** [comment]
Hi @LiamSx45 

Does this device measure temperature, humidity and PM2.5?

It looks like it is bluetooth-only and for the moment this plugin does not support and bluetooth-only temperature sensors.

Neither does there seem to be any data in the `"lastDeviceData":"{}"` in your logs. 

Have you tried this plugin at all?
https://www.npmjs.com/package/homebridge-plugin-govee

**Comment by bwp91** [comment]
please try the new beta version of the plugin

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
