### ISSUE TITLE
H6148 Brightness Issue

### ISSUE THREAD

**Issue by koryhutchison** [bwp91/homebridge-govee#30]
### What issue do you have? Please be as thorough and explicit as possible.
I have the H6148 model of light strip and when it's at 100% in the Govee app, it shows up as 39% in the home app.

### Details of your setup.
* Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?
     * v1.1.7

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
    * macOS High Sierra, Node 14.15.4

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
    * v2.5.2
    * I literally set this up last night and it's been this way from the start.

I'm pretty sure this is a super easy fix. It appears that my model number isn't included in `modelsNoScaleBrightness`. So I believe if you add H6148 to it, everything should work great. Thanks for making this plugin!

**Comment by bwp91** [comment]
Hi, I've just released v2.5.4 with the brightness fix for this model :)

**Comment by koryhutchison** [comment]
Thanks for the quick response!
