### ISSUE TITLE
Is the updatePlatformAccessories call really correct?

### ISSUE THREAD

**Issue by Apollon77** [bwp91/homebridge-govee#303]
You have a updatePlatformAccessories call here https://github.com/bwp91/homebridge-govee/blob/5ba6337c05a39f5951b94dd4105b1a7a00da437d/lib/platform.js#L837 ... but the  current specs just support https://github.com/homebridge/homebridge/blob/master/src/api.ts#L343 ... there is a parameter mismatch or?!

**Comment by bwp91** [comment]
Hi @Apollon77 
This is something i have not looked into for a long time since no issues have ever been reported.
But looks like you are right with the parameters.
Looks like i have a lot of plugins to update!
Thanks for pointing this out, I will let you know when i have fixed 👍🏻

**Comment by Apollon77** [comment]
I just wondered why updates do not work for my homebridge plug-in wrapper and sunbird over that. I also checked other plugins and they do it the other way .. then have fun updating. At least for one my PR might help ;-))

**Comment by bwp91** [comment]
Can you try the beta 6.0.0-beta.1? I have updated the `updatePlatformAccessories` function to only one argument for homebridge-govee.

If it works for you then I will update the rest of my plugins :)

**Comment by Apollon77** [comment]
I did that locally on my system too before ... I will re-check with new version tomorrow

**Comment by Apollon77** [comment]
looks good to me from the one test account I could check

**Comment by bwp91** [comment]
Closing this as fixed in v6. thanks @Apollon77 for bringing this to my attention. is also fixed in all my other plugins too.
