### ISSUE TITLE
error : unable to reach

### ISSUE THREAD

**Issue by tarunprakashsingh** [bwp91/homebridge-govee#309]
### What issue do you have? Please be as thorough and explicit as possible.
unable to reach Govee plug in.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
hoobs

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

<br class="Apple-interchange-newline">

Version | 4.2.8 
-- | --
Node Version | 16.17.0
Homebridge Version | 1.5.0
CPU | 2%
Memory | 64.4 MB (19.5 MB)
Manufacturer | HOOBS.org
Model | HSLF-1
System Version | 11
SKU | 7-45114-12418-0
Hostname | hoobs

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H618E

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @tarunprakashsingh 

I think this may be your issue, please check this out with the solution:

https://support.hoobs.org/topics/connectivity/plugin-site-unavailable

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
