### ISSUE TITLE
latest update v2.6.0

### ISSUE THREAD

**Issue by skir0cket** [bwp91/homebridge-govee#31]
Hi I have just updated to the latest update and im on beta 1.30 42 on homebridge, im getting an error when trying to control the lights [Tv lights] could not be updated and its status will revert soon - Cannot read property 'hs2rgb' of undefined.

**Comment by bwp91** [comment]
Hi, my bad!
Please try v2.6.1

**Comment by skir0cket** [comment]
works great thanks!
