### ISSUE TITLE
Govee Immersion TV leds stopped working with homebridge

### ISSUE THREAD

**Issue by lucianomunoz** [bwp91/homebridge-govee#310]
### What issue do you have? Please be as thorough and explicit as possible.
Govee Immersion TV leds stopped working with homebridge

* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
I use home bridge

* Which version of Homebridge/HOOBS do you have?
1.5.0 (latest available)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
I run it on a raspberri pi, dont know how to find the node .js version

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
I dont know if it was after an update to the govee app or to homebridge, i believe it was on their side

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6199

the device is recognized by the plugin and the buttons appear, yet when i press it it doesnt work, wether through the homebridge ui or via the home app.

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.

**Comment by lucianomunoz** [comment]
I did update to the latest beta and still doesnt work.

**Comment by bwp91** [comment]
does anything work? like on/off or brightness or colour? 

H6199 is this a wifi or bluetooth device?

**Comment by lucianomunoz** [comment]
Nothing works for me through the plugin, 
it's both wifi and bluetooth.

It's the govee Immpersion t1 (lights that go behind the tv and that pickup colors through a camera)

**Comment by alcorta2022** [comment]
I am also having a similar issue. Homebridge via raspberry pi 1.5.1 node 16.18.0 govee 7.1.1 product H605D I can turn it off and on but unable to change the brightness and color. I've deleted the item from govee and re added and the issue continues. My other govee products work just fine it is just this one.

**Comment by bwp91** [comment]
sorry i have not replied to this yet. is this still an issue?

**Comment by alcorta2022** [comment]
Yes it is still an issue
