### ISSUE TITLE
Govee Grill Thermometer

### ISSUE THREAD

**Issue by jivy12** [bwp91/homebridge-govee#311]
### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? Hoobs

* Which version of Homebridge/HOOBS do you have? 1.5

* Which version of this plugin (homebridge-govee) do you have? 5.2 
* Has the issue started since upgrading from a previous version? No

* Which Govee devices do you have that are causing issues? Bluetooth Grill Thermometer H5055

### Please paste any relevant logs below.
<!-- ABOUT LOGS
9/24/2022, 9:01:37 AMGovee BridgeGoveeWARNING[Meat Thermo] is not currently supported, do create a Github issue with the following info:
{"device":"86:F8:A4:C1:38:A1:D0:4F","deviceName":"Meat Thermo","model":"H5055","httpInfo":{"groupId":0,"device":"86:F8:A4:C1:38:A1:D0:4F","sku":"H5055","spec":"","versionHard":"1.00.02","versionSoft":"1.00.05","deviceName":"Meat Thermo","deviceExt":{"deviceSettings":"{\"bleName\":\"ihoment_H5055_A1D04F\",\"ic\":0,\"sku\":\"H5055\",\"device\":\"86:F8:A4:C1:38:A1:D0:4F\",\"deviceName\":\"Meat Thermo\",\"versionHard\":\"1.00.02\",\"versionSoft\":\"1.00.05\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}

```

```

**Comment by bwp91** [comment]
Hi @jivy12 

Can you update to the beta version of the plugin? and see if this works?

**Comment by jivy12** [comment]
Where do I find that?

**Comment by bwp91** [comment]
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by jivy12** [comment]
That detected the device and brought the sensors into HomeKit but the
sensors aren’t syncing. It just shows 1 temp of 32 degrees constantly

**Comment by bwp91** [comment]
Can you post the homebridge logs from restarting homebridge - so I can see how the plugin initialises

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.

**Comment by jivy12** [comment]
It should detect up to 6 temperature probes, i only use 2 but the device
supports 6.  Here is the log - it just keeps repeating the last section
over and over

10/8/2022, 9:29:49 AMgoveebridge2 stopping10/8/2022, 9:29:53 AMGovee Bridge
2 starting10/8/2022, 9:30:06 AMGovee Bridge 2Loaded plugin
'homebridge-govee'10/8/2022, 9:30:06 AMGovee Bridge 2Loading 1
platforms...10/8/2022,
9:30:06 AMGovee Bridge 2GoveeInitialising plugin v6.0.5-beta.6 | System
linux | Node v16.17.0 | HB v1.5.0 | HAPNodeJS v0.10.2...10/8/2022, 9:30:06
AMGovee Bridge 2GoveePlugin initialised. Setting up accessories....10/8/2022,
9:30:06 AMGovee Bridge 2Bridge is running on port 51886.10/8/2022, 9:30:09
AMGovee Bridge 2GoveeLAN client enabled.10/8/2022, 9:30:10 AMGovee Bridge 2
GoveeHTTP/AWS clients enabled as Govee username and password
provided.10/8/2022,
9:30:10 AMGovee Bridge 2GoveeWARNINGDisabling API client as API key not
provided.10/8/2022, 9:30:10 AMGovee Bridge 2GoveeBLE client enabled as
packages successfully found.10/8/2022, 9:30:10 AMGovee Bridge 2Govee[Meat
Thermo] initialising with options
{"logging":"standard","lowBattThreshold":20}.10/8/2022, 9:30:10 AMGovee
Bridge 2Govee[Meat Thermo] initialised with id [86:F8:A4:C1:38:A1:D0:4F]
[H5055].10/8/2022, 9:30:12 AMGovee Bridge 2GoveeWARNING[Meat Thermo] has
been reported [offline].
10/8/2022, 9:30:12 AMGovee Bridge 2ERROR[Govee Bridge 2 ***@***.***
Thermo@@Battery
Level] characteristic value expected valid finite number and received "NaN"
(number)10/8/2022, 9:30:12 AMGovee Bridge 2ERROR[Govee Bridge 2 ***@***.***
Thermo@@Current Temperature] characteristic value expected valid finite
number and received "NaN" (number)10/8/2022, 9:30:12 AMGovee Bridge
2ERROR[Govee
Bridge 2 ***@***.*** Thermo@@Current Relative Humidity] characteristic value
expected valid finite number and received "NaN" (number)10/8/2022, 9:30:12
AMGovee Bridge 2Govee[Meat Thermo] current battery [NaN%].10/8/2022,
9:30:12 AMGovee Bridge 2Govee[Meat Thermo] current temperature
[NaN°C].10/8/2022,
9:30:12 AMGovee Bridge 2Govee[Meat Thermo] current humidity [NaN%].10/8/2022,
9:30:13 AMGovee Bridge 2Govee✓ Setup complete. Join the plugin's Discord
community! https://discord.gg/cMGhNtZ3tW10/8/2022, 9:30:26 AMGovee Bridge 2
ERROR[Govee Bridge 2 ***@***.*** Thermo@@Battery Level] characteristic value
expected valid finite number and received "NaN" (number)10/8/2022, 9:30:26
AMGovee Bridge 2ERROR[Govee Bridge 2 ***@***.*** Thermo@@Current Temperature]
characteristic value expected valid finite number and received "NaN"
(number)10/8/2022, 9:30:26 AMGovee Bridge 2ERROR[Govee Bridge 2 ***@***.***
Thermo@@Current Relative Humidity] characteristic value expected valid
finite number and received "NaN" (number)10/8/2022, 9:30:26 AMGovee Bridge 2
Govee[Meat Thermo] current battery [NaN%].10/8/2022, 9:30:26 AMGovee Bridge
2Govee[Meat Thermo] current temperature [NaN°C].10/8/2022, 9:30:26 AMGovee
Bridge 2Govee[Meat Thermo] current humidity [NaN%].10/8/2022, 9:30:41 AMGovee
Bridge 2ERROR[Govee Bridge 2 ***@***.*** Thermo@@Battery Level]
characteristic value expected valid finite number and received "NaN"
(number)10/8/2022, 9:30:41 AMGovee Bridge 2ERROR[Govee Bridge 2 ***@***.***
Thermo@@Current Temperature] characteristic value expected valid finite
number and received "NaN" (number)

**Comment by lucaspbastos** [comment]
Hate to revive a nearly 2 year issue but I'm not able to detect my H5055 thermometer either, is this unsupported? @bwp91
