### ISSUE TITLE
Govee LAN

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-govee#312]
It has nothing to do with this plugin and it does not affect the funcality. I am very happy with the LAN function, it is a huge step in the right direction. Thank you so much for that!
I have blocked my Govee devices so that they only have access locally and it annoys me tremendously that Govee tries to gain access every two minutes for that reason. I can see it in the UniFi GUI. Every two minutes they disconnect and then reconnect my WiFi. I hope I can get you guys to write to Govee so we can get them to change this :)

**Comment by bwp91** [comment]
out of interest (I don't have any LAN devices to test)...

do you find LAN mode much more reliable than the cloud modes? and faster?

**Comment by ghost** [comment]
> out of interest (I don't have any LAN devices to test)...
> 
> do you find LAN mode much more reliable than the cloud modes? and faster?

It cannot be compared at all. Lan mode is much faster and more stable than Cloud. There is a small delay compared to zigbee devices, but it is so small that it is hard to see. I'm really excited about it.
And I'm really happy that I can block my devices in my firewall.

So a huge thank you for the work with the plugin.

**Comment by ghost** [comment]
I wrote that there is a slight delay ... there is no delay, at all. It is the lamp that is a bit "slow", it takes less than a second to switch on/off
The same applies when I use the remote control

**Comment by bwp91** [comment]
This is good to know! Finally something reliable and fast! Hopefully over time it will expand to more models including some of the much older models too.

Are you able to try beta 9 just to make sure things are still working okay?

**Comment by ghost** [comment]
> Are you able to try beta 9 just to make sure things are still working okay?

No problems with beta9 👍🏻

**Comment by Write** [comment]
Holy hell, thanks you so much for this upgrade ! Trying it right now !
