### ISSUE TITLE
Beta 5 error

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-govee#313]
[XX:XX ...] could not be updated as Cannot read properties of undefined (reading 'useLANControl') at default.sendDeviceUpdate (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1458:25).

Homebridge >Govee beta 5

There were no problems with beta 4

Govee H6072

**Comment by bwp91** [comment]
Hi @JanLp 

Please try beta 6!

**Comment by ghost** [comment]
> Hi @JanLp
> 
> Please try beta 6!

Perfect...that solved the problem. Thank you!
