### ISSUE TITLE
No switch button in Home app

### ISSUE THREAD

**Issue by iceage2609** [bwp91/homebridge-govee#315]
Hi there, recently i bought Govee Wifi Thermo-Hygrometer H5179. 
My English are really bad, i am not a native speaker but i'll do my best . My setup is Homebridge on Synology NAS without Docker and the version i thing is 1.5.0 and Node.js Version v16.17.0 if that matters.

I installed the latest version of your plugin with success , i guess from your documentation the bluetooth error is a common alert, but although i can see  in my Home App as sensors Thermometer and Humidity,there are no switches (maybe that's normal) and  i can not trigger an automation . For example i have created one " when humidity is below 55%, open that homekit native smartplug " ...but when humidity is 54%... nothing.It doesn't work. Am i doing anything wrong? 
Here is a quick video from the installation log and how it looks like in my home app. I didin't record the automation.
Thanks in advance.

[https://www.dropbox.com/s/n6u6a8dk4wxjwro/Govee%20Movie.mp4?dl=0](url)

**Comment by bwp91** [comment]
Hi @iceage2609 

Did you create this automation in the Home app?

Also a home hub is required for homekit automations - something like an apple tv or homepod, do you have one of these setup?

**Comment by iceage2609** [comment]
Thanks for answering. Yes i created the automation in home app and i have a homepod mini as a hub. The smart plug i am trying to trigger supports homekit natively.
The steps i followed in the home app are —> create automation-A sensor detects something (menu)-choose wifi thermometer temperature-if temperature rises above 25 degrees—then click the smartplug and next—abd double click on smart plug and set it to Turn ON.

**Comment by bwp91** [comment]
if you turn this smartplug off, go back into the automation and click "test this automation" does the smartplug turn on?

Just to clarify on the title of this issue - No switch button in Home app - this plugin will simply expose a temperature and humidity sensor in the home app, it does not expose a switch.

And it does not matter the fact that the smartplug is homekit native - homekit does not make a distinction between native accessories and those from homebridge (at least when it comes to scenes and automations).

**Comment by iceage2609** [comment]
Oh i see, so there is no switch for this plugin as the one i saw in a youtube video for the Govee Lights. Thanks for making that clear.

Yes the smart plug turn on when i press test this automation. Another strange thing is that although the Govee app shows for example different temperatures , the home app always shows 24 celsius.
Anyway I don't want to bother you more with this specific problem, it's very difficult to make assumptions without having an error or an event log, thanks for your answer.

I assume that my issue has something to do with the wifi networks. The smartplug and the homepod mini are directly connected to my fritzbox router that has the 2.4Ghx and 5Ghz combined to one ssid name and therefore the Govee can not connect to that.

So i have a 2.4Ghz powerline adapter connected to my router and the govee device connect to the adapter.
So maybe there is a lack of communication there.

Thank you.

**Comment by iceage2609** [comment]
Hi there, problem solved !!
Today i check again the Govee app in case i didin't see a menu or a specific option . So i saw that data refresh frequency was 30 minutes... I switched to 10 minutes and the automation worked like a charm after 10 minutes ( i guess after the govee app refresh it's data ).The smartplug turned ON... 
Thanks again for your help and for your great plugin.

Cheers

**Comment by bwp91** [comment]
Which platform are you running Homebridge on?

**Comment by bwp91** [comment]
Ah i see you mentioned this in your first post. When you start the plugin, what does it mention about bluetooth in the homebridge logs? Does your synology nas have a bluetooth module?

**Comment by iceage2609** [comment]
> Ah i see you mentioned this in your first post. When you start the plugin, what does it mention about bluetooth in the homebridge logs? Does your synology nas have a bluetooth module?

i am using a Synogy DS118 so i don’t think that it has a Bluetooth module. I installed homebridge from this tutorial [Natively Homebridge on Synology](https://github.com/oznu/homebridge-syno-spk) 
When i start the plugin i am getting the photo message, i know its not very clear but you can check it out on my video link on the first post.
![1F13D0D0-8CA0-4F3C-BD42-6AEC0E8B8B66](https://user-images.githubusercontent.com/102951608/194715387-494d98e9-c64d-4359-aefb-16229d37e8c1.jpeg)

**Comment by bwp91** [comment]
That yellow message is fine it’s just stating that bluetooth can’t be found.

I only asked because today I have tried to implement bluetooth scanning for temperature sensors. I have a H5179 and it’s working well, getting updates every two minutes

But obvsiouly this would not work on your setup without bluetooth

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
