### ISSUE TITLE
H61A0 / Lan not supported (?)

### ISSUE THREAD

**Issue by Write** [bwp91/homebridge-govee#316]
Just upgraded to 6.0, and enabled LAN Control inside my Govee APP, but it seems i can't control it locally.

Console says

```
[Govee] [B6:BE:D4:AD:FC:1B:F6:90] is not currently supported, do create a Github issue with the following info:
{"device":"B6:BE:D4:AD:FC:1B:F6:90","deviceName":"B6:BE:D4:AD:FC:1B:F6:90","isLANDevice":true}
```

![Screenshot du 2022-10-06 à 01 05 20](https://user-images.githubusercontent.com/541722/194179646-5daf1238-2203-4bd4-8262-1503b2ea4441.png)

**Comment by ghost** [comment]
remove the ip address in your config and it works. I think there is a bug in version 6 that occurs if you add an IP address

**Comment by bwp91** [comment]
@JanLp do you get the same issue if you manually add an IP?

I assume neither of you are removing govee credentials from the config?

**Comment by ghost** [comment]
Yes I have ;) I am not aware in which beta the bug occurred. But it has worked as it should, without errors.

**Comment by ghost** [comment]
> I assume neither of you are removing govee credentials from the config?

Nope :)

**Comment by bwp91** [comment]
@JanLp can we message on discord?
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
can you both try the 6.0.1-beta version?

**Comment by ghost** [comment]
> @JanLp can we message on discord?
> https://discord.gg/cMGhNtZ3tW

I'm at work but have access via vpn and beta 1 fixed it 👍🏻

**Comment by Write** [comment]
Did upgraded to beta and local control works !
I removed cloud control credentials from config (just to be sure).

It's way faster and way better like that.

I just have a weird issue where light instantly goes to 0%/off in the Home app after setting any %, in real life it stays at the defined percentage though. Couldn't debug why. 
So for now I have to use Govee App to turn off the light.

**Comment by bwp91** [comment]
@Write does this happy ONLY when you have removed cloud credentials? what does it say in the plugin settings “my devices” tab for cloud status?

**Comment by Write** [comment]
![Screenshot du 2022-10-06 à 13 02 55](https://user-images.githubusercontent.com/541722/194297032-65d123b9-a032-4f8f-a0dc-663510dd54a2.png)


Hmm i'll have to re-add my credentials (anyway I don't think it'll be able to control it since my firewall block access to internet for my IoT devices)

**Comment by Write** [comment]
Adding credentials doesn't change a thing, it turn it off instantly. [[ but the light does stay on ! ]]

![Screenshot du 2022-10-06 à 13 04 52](https://user-images.githubusercontent.com/541722/194297417-b215e68f-17a6-4c67-8299-46cf28f97d45.png)

**Comment by ghost** [comment]
> > I assume neither of you are removing govee credentials from the config?
> 
> Nope :)

Sorry ... I misunderstood the question.
I have also removed the cloud control credentials from config

**Comment by ghost** [comment]
> Did upgraded to beta and local control works ! I removed cloud control credentials from config (just to be sure).
> 
> It's way faster and way better like that.
> 
> I just have a weird issue where light instantly goes to 0%/off in the Home app after setting any %, in real life it stays at the defined percentage though. Couldn't debug why. So for now I have to use Govee App to turn off the light.

<img width="717" alt="Skærmbillede 2022-10-06 kl  13 07 23" src="https://user-images.githubusercontent.com/55313117/194297875-9a9837b1-b380-4e26-bd63-e5f3d48f4a33.png">

Untick here and your problem will go away

**Comment by bwp91** [comment]
> Adding credentials doesn't change a thing, it turn it off instantly. [[ but the light does stay on ! ]]
> 
> ![Screenshot du 2022-10-06 à 13 04 52](https://user-images.githubusercontent.com/541722/194297417-b215e68f-17a6-4c67-8299-46cf28f97d45.png)

ooh I need to change this rating in the logs to 4.5 🙊

Can you use the plugin settings to turn on debug logging? restart, and try to control again? and show the logs here?

**Comment by bwp91** [comment]
This 'offline as off' option crossed my mind. I may need to change this logic for lan-only devices.

**Comment by ghost** [comment]
> This 'offline as off' option crossed my mind. I may need to change this logic for lan-only devices.

🙂👍🏻

**Comment by Write** [comment]
> > Did upgraded to beta and local control works ! I removed cloud control credentials from config (just to be sure).
> > It's way faster and way better like that.
> > I just have a weird issue where light instantly goes to 0%/off in the Home app after setting any %, in real life it stays at the defined percentage though. Couldn't debug why. So for now I have to use Govee App to turn off the light.
> 
> <img alt="Skærmbillede 2022-10-06 kl 13 07 23" width="717" src="https://user-images.githubusercontent.com/55313117/194297875-9a9837b1-b380-4e26-bd63-e5f3d48f4a33.png">
> 
> Untick here and your problem will go away

Ooooh thanks it fixed my issue !


> > Adding credentials doesn't change a thing, it turn it off instantly. [[ but the light does stay on ! ]]
> > ![Screenshot du 2022-10-06 à 13 04 52](https://user-images.githubusercontent.com/541722/194297417-b215e68f-17a6-4c67-8299-46cf28f97d45.png)
> 
> ooh I need to change this rating in the logs to 4.5 🙊
> 
> Can you use the plugin settings to turn on debug logging? restart, and try to control again? and show the logs here?

Well do I still need to do it ? It seems effectively affected by the offline as off option :) !

**Comment by bwp91** [comment]
> Well do I still need to do it ? It seems effectively affected by the offline as off option :) !

No don't worry. It's kinda certain it's this!

**Comment by bwp91** [comment]
v6.0.2 should now fix this issue even when this offlineAsOff is selected. 

This option will have no effect for LAN-only devices (ie credentials removed)

**Comment by ghost** [comment]
> v6.0.2 should now fix this issue even when this offlineAsOff is selected.
> 
> This option will have no effect for LAN-only devices (ie credentials removed)

Thanks :) Maybe you should update Readme... It's pretty awesome that you made LAN available and I'm pretty sure that news will attract more people.

**Comment by Write** [comment]
It’s almost perfect, there’s only a small delay where the light will put itself as « On » on the interface, right when turned off, but it update quickly, and shows up as turned off in a few seconds.

**Comment by ghost** [comment]
> It’s almost perfect, there’s only a small delay where the light will put itself as « On » on the interface, right when turned off, but it update quickly, and shows up as turned off in a few seconds.

I only experience that behavior once, and that's after restarting Homebridge/Homebridge Govee

Do you have homebridge govee in a child bridge? If not, try it.

**Comment by Write** [comment]
> > It’s almost perfect, there’s only a small delay where the light will put itself as « On » on the interface, right when turned off, but it update quickly, and shows up as turned off in a few seconds.
> 
> I only experience that behavior once, and that's after restarting Homebridge/Homebridge Govee
> 
> Do you have homebridge govee in a child bridge? If not, try it.

Just tried it the issue is the same unfortunately. The state take approx 5sec to shows its correct state when turned off.
For example: I turn off the light -> IRL The light indeed turn off instantly -> In HomeKit, and in Homebridge console it shows up instantly as "Turned on" -> Few seconds later it sync correctly with the real light state.

Example when I turn it off : 
[10/7/2022, 11:50:49 AM] [Govee] [Glide] current state [off].
[10/7/2022, 11:50:49 AM] [Govee] [Glide] current state [on].
[10/7/2022, 11:50:55 AM] [Govee] [Glide] current state [off].

**Comment by ghost** [comment]
Ah ... I understood that it was in the Home app that you had that experience.

From off to on to off:
```
[07/10/2022, 15:01:27] [Govee] [XX:XX...] current state [on].
[07/10/2022, 15:01:27] [Govee] [XX:XX...] current state [off].
```

**Comment by Write** [comment]
> Ah ... I understood that it was in the Home app that you had that experience.
> 
> From off to on to off:
> 
> ```
> [07/10/2022, 15:01:27] [Govee] [XX:XX...] current state [on].
> [07/10/2022, 15:01:27] [Govee] [XX:XX...] current state [off].
> ```

Well it reflect in the Home app too that's why I said that

**Comment by ghost** [comment]
It is strange. I do not experience this.


https://user-images.githubusercontent.com/55313117/194589735-0d5ad140-ada2-4f2f-932a-afc36b0e9277.mp4

**Comment by Write** [comment]
![Screenshot du 2022-10-07 à 17 36 14](https://user-images.githubusercontent.com/541722/194592975-adbdaa13-c923-44c4-b368-5cf087da0cb4.png)

Well I just removed the plugin & the config, just to be sure and it still does the exact same thing.
In "MY DEVICES" it appears in double though, that may be the issue (?). It seems to be the autodetected one + when I add the unique adress, but i'm forced to add the unique adress otherwise the light wont show in homekit.

**Comment by Write** [comment]
I just tried to remove UUID from cache, then fully removing plugin & config, + reinstalling without touching anything, letting the autodiscovery do it's thing.
It does indeed at it automatically to homekit (With it's Unique ID as Name), and now I correctly have only one device in "My devices", but still the exact same issue unfortunately

**Comment by ghost** [comment]
Hm ... I see you're on HOOBS, maybe that's the difference. I have several devices from Govee that support LAN and there are none that behave like this.

**Comment by Write** [comment]
I’m not on HOOBS ?

**Comment by ghost** [comment]
It looked like this on your screenshot. So I don't know why you are experiencing that delay :)

**Comment by ghost** [comment]
I don't know ... but maybe my setup is a little atypical. All my devices except my robot vacuum cleaner are LAN only. So I am not "online" with my Govee devices. Could it be a "conflict" between cloud api and lan api?

**Comment by Write** [comment]
It’s not online anymore as I removed the whole plugin and config, it’s now lan only

**Comment by ghost** [comment]
Please resend a new screenshot of your device


![](https://user-images.githubusercontent.com/541722/194179646-5daf1238-2203-4bd4-8262-1503b2ea4441.png)

**Comment by Write** [comment]
![Homebridge](https://user-images.githubusercontent.com/541722/194601637-28fda0e0-d0a3-4fb3-8449-2f9207d90a92.png)

**Comment by ghost** [comment]
Which HUBS do you have in your home? HomePod(mini), Apple TV?

**Comment by Write** [comment]
I dont think it matter honestly it’s clearly a bug with the plug-in. I have 6 HomePods mini and 1 ATV 4K

**Comment by bwp91** [comment]
Can you use the plugin settings to enable Debug Logging, and then perform the same actions to get the logs like above

```
Example when I turn it off :
[10/7/2022, 11:50:49 AM] [Govee] [Glide] current state [off].
[10/7/2022, 11:50:49 AM] [Govee] [Glide] current state [on].
[10/7/2022, 11:50:55 AM] [Govee] [Glide] current state [off].
```

But there will be more logging due to the debug settings.

Can you do this and post the logs here?

**Comment by ghost** [comment]
Maybe, maybe not... I don't have that device like you, so it's hard. But I find it hard to believe it is reserved for a single unit. As written, I have several units, +8 without problems like yours.
But if the developer wants a log, I'm happy to contribute :)

**Comment by Write** [comment]
When turning it off : 
(it does the same weird thing when turning it on btw) 
```
10/7/2022, 6:42:50 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] current state [on].
[10/7/2022, 6:42:54 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] has been reported [offline] via API, so update may or may not be successful.
[10/7/2022, 6:42:54 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] [LAN] starting update with params [{"msg":{"cmd":"turn","data":{"value":0}}}].
[10/7/2022, 6:42:54 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] [LAN] command sent to [B6:BE:D4:AD:FC:1B:F6:90] at [10.0.0.185].
[10/7/2022, 6:42:54 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] current state [off].
[10/7/2022, 6:42:54 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] [LAN] receiving update [{"onOff":1,"brightness":21,"color":{"r":66,"g":56,"b":255},"colorTemInKelvin":0,"source":"LAN"}].
[10/7/2022, 6:42:54 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] current state [on].
[10/7/2022, 6:42:55 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] [LAN] receiving update [{"onOff":0,"brightness":21,"color":{"r":66,"g":56,"b":255},"colorTemInKelvin":0,"source":"LAN"}].
[10/7/2022, 6:42:55 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] current state [off].
[10/7/2022, 6:43:00 PM] [Govee] [B6:BE:D4:AD:FC:1B:F6:90] [LAN] receiving update [{"onOff":0,"brightness":21,"color":{"r":66,"g":56,"b":255},"colorTemInKelvin":0,"source":"LAN"}].
```

**Comment by bwp91** [comment]
@Write can you try v6.0.4-beta.0 ?

**Comment by ghost** [comment]
wtf :) This version makes my devices turn on instantly...so no lag AT ALL 🙈

**Comment by ghost** [comment]
Ben > If you didn't live in a non-EU country, I would have sent you a lamp that supports LAN 🫣👍🏻

**Comment by JanLp** [comment]
You have received a modest $5 as a thank you ☺️

**Comment by ghost** [comment]
I can state that my H6072 reacts faster than a HUE unit over deconz 👍🏻

**Comment by Write** [comment]
That’s 100 % fixed !!!! Thanks

**Comment by bwp91** [comment]
Awesome, glad is working well now!

@JanLp thank you for the support :)

**Comment by ghost** [comment]
Ben > I'm a bit curious about the issue...? I didn't experience any noticeable lag, but still it got a lot better.

**Comment by Write** [comment]
> Ben > I'm a bit curious about the issue...? I didn't experience any noticeable lag, but still it got a lot better.

Certainly a delay that was added but not correctly set to be ignored when using LAN control instead of AWS/API

**Comment by ghost** [comment]
> Certainly a delay that was added but not correctly set to be ignored when using LAN control instead of AWS/API

It makes sense. I don't need to understand it, nor do I have the skills to understand it. It just surprises me now that we have the same settings.

It's kind of irrelevant, but it really annoys me that my devices are making close to 50,000 requests when they don't have internet access. I'm getting a little tired of them reconnecting every two minutes ... but that's probably just me :(

**Comment by bwp91** [comment]
The issue in this case was that when sending the on/off command, the device responded with the old info still. 

So actually the plugin was correctly working with the data it received, even though it was incorrect in reality.

I added a small interval of 5 seconds in which the plugin will ignore incoming data after sending a lan command.

So it’s not really a fix, it’s (yet another) workaround.

I didn’t do anything which would speed up commands, but bonus if it’s reacting faster. the reasoning - 🤷🏼‍♂️
