### ISSUE TITLE
H6117 Lan support

### ISSUE THREAD

**Issue by lcsjandrey** [bwp91/homebridge-govee#317]
### What issue do you have? Please be as thorough and explicit as possible.
H6117 document states LAN support although it only works with API

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge 1.50 UI-X

* Which version of Homebridge/HOOBS do you have?
1.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Proxmox homebridge lxi 

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Updated

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6117

### Please paste any relevant logs below.

```

```

**Comment by Write** [comment]
Did you try updating to latest beta of the plug-in ?

**Comment by lcsjandrey** [comment]
I think I am running the latest version. I did try the beta and same issue. 
![image](https://user-images.githubusercontent.com/65430786/194444731-b1e553d3-d0d5-4f66-8d4b-1b2efecfcd83.png)

**Comment by bwp91** [comment]
Hi @lcsjandrey 

Have you enabled LAN mode for this device in the govee app?

Is it on the same local network as your homebridge instance? or maybe on a separate vlan?

**Comment by bwp91** [comment]
> Did you try updating to latest beta of the plug-in ?

Also v6.0.3 is the latest version now newer than the beta 👍🏻

**Comment by ghost** [comment]
Check wifiVersionSoft on your strip ... Reset your strip and try to force an update. Turn it on, press pover while quickly pressing color four times.
The firmware version you can see in the app is NOT wifiVersionSoft

**Comment by bwp91** [comment]
is this still an issue with the latest version of the plugin?

**Comment by lcsjandrey** [comment]
Yes, unfortunately still not working but it's much better than before. 
I did factory reset the strip, tried reinstalling the plugin. 
Light strip is updated and connected to Wi-Fi. 
Plug-in doesn't detect any lan connection, just API.

**Comment by bwp91** [comment]
Have you enabled LAN mode for this device in the govee app?

Is it on the same local network as your homebridge instance? or maybe on a separate vlan?

**Comment by lcsjandrey** [comment]
How would you enable LAN mode on the Govee App? It is connected to the same
network as the homebridge. No Vlan

**Comment by bwp91** [comment]
See the first image here:
https://app-h5.govee.com/user-manual/wlan-guide

**Comment by lcsjandrey** [comment]
I don’t see that option on the app. 
![248CE48B-BE1B-4F8D-9E8C-3046001FA5A4](https://user-images.githubusercontent.com/65430786/194714970-bbe98113-9a7e-4a97-998c-e81fb8521d97.png)

**Comment by bwp91** [comment]
Hmm I would have thought there would be a firmware update then.

In this case I am not sure, I would try getting in contact with Govee.

**Comment by bwp91** [comment]
https://app-h5.govee.com/share/community?client=0&postId=105086&t=1665243074361

Looks like you aren’t the only one

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.

**Comment by ghost** [comment]
> Closing this as a bit overwhelmed with issues.
> Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
> Thanks and apologies if closing prematurely.

I'm pretty sure it has nothing to do with homebridge govee...the update procedure is pretty random and a bit messy. Some devices support LAN and others don't, even if they have the same model number.
My advice would be not to go too deep into devices that cannot be seen in homebridge govee

Excuse my English, it leaves quite a bit ;)

**Comment by bwp91** [comment]
> Excuse my English, it leaves quite a bit ;)

dicho como un español, tengo razón?

**Comment by ghost** [comment]
> > Excuse my English, it leaves quite a bit ;)
> 
> dicho como un español, tengo razón?

Skrevet af en dansker 😂

**Comment by bwp91** [comment]
Can have the plugin log in your own language if you wanna translate all this!
https://github.com/bwp91/homebridge-govee/blob/latest/lib/utils/lang-en.js

**Comment by ghost** [comment]
I don't think it's worth the trouble. Most people understand what is happening. But if I get time, I will gladly translate 👍🏻
