### ISSUE TITLE
H7130 feature request

### ISSUE THREAD

**Issue by dabreu70** [bwp91/homebridge-govee#319]
* **Please explain your feature request in a one or two sentences.**

Heater shows as fan with fan speed instead of heater with temp controls and oscillation on/off. Can you add this?  Thanks!

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

H7130

* **Anything else?**

H5103 isnt available. DO you have a timeline of when it will be?

**Comment by bwp91** [comment]
Hi @dabreu70 

Do you own the H5103?

**Comment by dabreu70** [comment]
Yes just got it the other day.

On Oct 8, 2022, at 2:58 AM, Ben ***@***.***> wrote:

﻿

Hi @dabreu70<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdabreu70&data=05%7C01%7C%7C3b421b7438124cb4615608daa8fa7496%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638008090897909587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5f0xWno1t82OBT47s9fCBZxtt45d6vLIRzmukAsdJEo%3D&reserved=0>

Do you own the H5103?

**Comment by bwp91** [comment]
is there a message in your homebridge log when the plugin starts about adding this device?

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.

**Comment by dabreu70** [comment]
It states the following - [Wifi Thermometer] is not currently supported, do create a Github issue with the following info: {"device":"4A:73:C1:32:37:36:7A:35","deviceName":"Wifi Thermometer","model":"H5103","httpInfo":{"groupId":0,"device":"4A:73:C1:32:37:36:7A:35","sku":"H5103","spec":"","versionHard":"3.02.02","versionSoft":"1.00.25","deviceName":"Wifi Thermometer","deviceExt":{"lastDeviceData":"{\"online\":false,\"tem\":2290,\"hum\":5300,\"lastTime\":1665175440000}","deviceSettings":"{\"pactType\":1,\"battery\":100,\"humMax\":10000,\"temCali\":0,\"humMin\":0,\"address\":\"C1:32:37:36:7A:35\",\"temMax\":6000,\"wifiMac\":\"D4:AD:FC:7E:4D:A6\",\"humCali\":0,\"bleName\":\"GVH5103_7A35\",\"pactCode\":1,\"temMin\":-2000,\"temWarning\":false,\"humWarning\":false,\"uploadRate\":10,\"deviceName\":\"Wifi Thermometer\"}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":106}}
________________________________

**Comment by bwp91** [comment]
Please can you update to the beta version of the plugin?

**Comment by dabreu70** [comment]
Hi Ben I updated top the beta a couple days ago and it picked up both the thermometer but the heater still shows as a fan. Is there a way to align the setting with what it can actually do? i.e. heat settings, oscillation, modes?

________________________________

**Comment by bwp91** [comment]
Closing, please see and reply in https://github.com/bwp91/homebridge-govee/issues/335
Thanks!
