### ISSUE TITLE
No longer able to control Air Purifier H7122

### ISSUE THREAD

**Issue by rmaes4** [bwp91/homebridge-govee#320]
### What issue do you have? Please be as thorough and explicit as possible.
I am no longer able to control the fan speed of my Govee Air Purifier (H7122). This was previously working but broke with an update. I am able to see the following message in the logs:
```
[08/10/2022, 00:54:34] [Govee] [Big Air Purifier] could not be updated as no connection method available at file:///usr/local/lib/node_modules/homebridge-govee/lib/platform.js:1569:13.
```

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1 Homebridge UI

* Which version of Homebridge/HOOBS do you have?
v1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v6.0.4. Issue seems to be caused by upgrading.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H7122

### Please paste any relevant logs below.

```
[08/10/2022, 00:54:34] [Govee] [Big Air Purifier] could not be updated as no connection method available at file:///usr/local/lib/node_modules/homebridge-govee/lib/platform.js:1569:13.
```

**Comment by bwp91** [comment]
Hi @rmaes4 

Do you find that the purifier does in fact change to the correct speed even though you receive this message in the logs? (and i assume a no response message in the home app)

**Comment by bwp91** [comment]
Can you try the new beta version of the plugin?

**Comment by rmaes4** [comment]
Hi @bwp91 

I just updated to the beta. When changing the fan speed for the air purifier, I no longer see an error message. The fan speed of the purifier does not change at all though. I see the following message in the logs when changing the air purifier fan speed:

```
[08/10/2022, 23:58:13] [Govee] [Big Air Purifier] [AWS] receiving update [{"cmd":"ptReal","cmdVersion":0,"data":{"command":["MwUCAAAAAAAAAAAAAAAAAAAAADQ="]},"transaction":"v_1665291493532000","type":1,"source":"AWS"}].
```

**Comment by bwp91** [comment]
happy to message directly on discord about this and the smart outlet if easier for you.

**Comment by rmaes4** [comment]
@bwp91 sure, that works for me

**Comment by rmaes4** [comment]
Closing this issue as it is now resolved

**Comment by Mr-Tech-13** [comment]
> Closing this issue as it is now resolved

@rmaes4 Thank you for telling us how to fix the issue. So considerate

**Comment by rmaes4** [comment]
> > Closing this issue as it is now resolved
> 
> @rmaes4 Thank you for telling us how to fix the issue. So considerate

@Mr-Tech-13 I did not tell you how to fix the issue because I did not do anything to fix it. This required a plugin update that was implemented by @bwp91 If you simply update to the latest version of the plugin your issue should be resolved.

**Comment by Mr-Tech-13** [comment]
Thank you for the help. Although a plugin update is considered doing something to fix it

**Comment by bwp91** [comment]
keeping this plugin updated is definitely considered a best practice as I release fairly frequently.

I also maintain a readme with changes.

Thanks to @rmaes4 for all the work you put into helping me to implement this device since I don't own it myself.

I don't think the _sarcastic_ `So considerate` is fair to @rmaes4 considering the work he put in to help me with this.

If you have any further issues @Mr-Tech-13 please feel free to open a new ticket!

Thanks
