### ISSUE TITLE
H7131 Space Heater not correctly controlled from Home app

### ISSUE THREAD

**Issue by nevetssf** [bwp91/homebridge-govee#322]
I'm running  Govee Bridge 6.0.5 beta 13 non Hoobs 

* **Please explain your feature request in a one or two sentences.**
the H7131 space heater appears in the Home app, but isn't controlled correctly. It has a fan slider and oscillation direction, but they also don't work correctly.

Is there any way to set the mode and target temperature (in auto mode) from Homekit? I have it paired with 5074 hygrometer. 

* **Is your feature request related to a problem? Please describe.**
Sort of - the control in the Home app currently looks like a fan control, any way it can be tailored to space heater control with set temp?

* **Any particular Govee devices that this relates to?**
H7131 space heater.

* **Anything else?**
Thanks!

**Comment by WhatTheKJ** [comment]
Im having a similar problem. I can see my H7131 in the Home app but it just says no response. It’s connected using my credentials and API key. I also have it set up on Wifi working completely fine with the Govee app.

**Comment by bwp91** [comment]
> Im having a similar problem. I can see my H7131 in the Home app but it just says no response. It’s connected using my credentials and API key. I also have it set up on Wifi working completely fine with the Govee app.

have you linked the heater (in the govee app) to a temperature sensor?

**Comment by DebasishBahinipati** [comment]
I am having a similar problem. I can see my H7131 in the Home app but it just says no response. It’s connected using an API key. I have it set up on Wifi working completely fine with the Govee app. HomeBridge logs says state on and off when I try to on or off from homebridge or homekit but nothing happening to the actual device. No temperature sensor connected to the heater.

**Comment by WhatTheKJ** [comment]
> > Im having a similar problem. I can see my H7131 in the Home app but it just says no response. It’s connected using my credentials and API key. I also have it set up on Wifi working completely fine with the Govee app.
> 
> have you linked the heater (in the govee app) to a temperature sensor?

I haven’t. It’s just the stand alone heater. The beta allowed me to control the heater somewhat. I can turn it off and on but it’s always on Auto. If I turn on the heater from the Govee app then Home doesn’t see that its turned on.

**Comment by bwp91** [comment]
Closing, please see and reply in https://github.com/bwp91/homebridge-govee/issues/335
Thanks!
