### ISSUE TITLE
color temperature

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-govee#323]
Beta 13 and other version (Homebridge) Govee H6072

Lan only (maybe)? There is something completely wrong with color temperature, saturation, and hue in homekit
![IMG_0648 – mellem](https://user-images.githubusercontent.com/55313117/194909977-92bb4dd9-a823-40c8-8f20-f7a34be6cbe4.jpeg)
![IMG_0647](https://user-images.githubusercontent.com/55313117/194909983-1b3cdc87-f054-436c-85e6-d3f7694a9939.PNG)

**Comment by ghost** [comment]
With Adaptive Lightning 

![IMG_0650 – mellem](https://user-images.githubusercontent.com/55313117/194911204-83338dcd-40aa-4373-96de-92fe9f1a13be.jpeg)
![IMG_0649](https://user-images.githubusercontent.com/55313117/194911206-5b75aa51-5f7f-4356-9910-da89db05e5f3.PNG)

**Comment by ghost** [comment]
Log:

```
[10/10/2022, 18:23:34] [Govee] [Gulvlampe] current colour [2800K / 357M] via adaptive lighting.
[10/10/2022, 18:23:38] [Govee] [Gulvlampe] [LAN] receiving update [{"onOff":1,"brightness":30,"color":{"r":255,"g":173,"b":94},"colorTemInKelvin":0,"source":"LAN"}].
[10/10/2022, 18:23:38] [Govee] [Gulvlampe] current colour [rgb 255 173 94].
```

**Comment by ghost** [comment]
Warm on H6072 remote:

Log:
`[10/10/2022, 18:32:28] [Govee] [Gulvlampe] [LAN] receiving update [{"onOff":1,"brightness":30,"color":{"r":255,"g":255,"b":255},"colorTemInKelvin":2000,"source":"LAN"}].`

![IMG_0654 – mellem](https://user-images.githubusercontent.com/55313117/194913745-05d3382b-b546-4d5f-b22c-a9f33b4cb6b1.jpeg)
![IMG_0651](https://user-images.githubusercontent.com/55313117/194913750-9d0cb3c8-92c1-43bf-b548-b1d8d106bc2f.PNG)

**Comment by bwp91** [comment]
are you able to try the new beta?

**Comment by ghost** [comment]
> are you able to try the new beta?

Perfect 👍🏻It's amazing to report an error, and less than an hour later, it's solved. Thanks!

**Comment by bwp91** [comment]
you are lucky that my 'guess' fixes are working 😉

**Comment by ghost** [comment]
I've been lucky every time, it can't be by chance ;)
