### ISSUE TITLE
Govee Outdoor Plug Support

### ISSUE THREAD

**Issue by MaddisonM79** [bwp91/homebridge-govee#325]
From Homebridge logs: 
{"device":"ED:C2:D4:AD:FC:47:A4:AE","deviceName":"Outside Plug","model":"H5160","httpInfo":{"groupId":0,"device":"ED:C2:D4:AD:FC:47:A4:AE","sku":"H5160","spec":"0","versionHard":"1.02.00","versionSoft":"1.00.06","deviceName":"Outdoor Plug","deviceExt":{"deviceSettings":"{\"wifiName\":\"XXXXXX\",\"address\":\"D4:AD:FC:47:A4:AF\",\"bleName\":\"ihoment_H5160_A4AF\",\"topic\":\"GD/b847b0140c23c40f77f973cd5a2f151d\",\"wifiMac\":\"D4:AD:FC:47:A4:AE\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"\",\"wifiHardVersion\":\"\",\"ic\":0,\"secretCode\":\"XXXXXXXXX=\",\"boilWaterCompletedNotiOnOff\":1,\"subDevices\":{\"sub_0\":{\"name\":\"Plug 1\"},\"sub_1\":{\"name\":\"Plug 2\"},\"sub_2\":{\"name\":\"Plug 3\"}},\"sku\":\"H5160\",\"device\":\"ED:C2:D4:AD:FC:47:A4:AE\",\"deviceName\":\"Outdoor Plug\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.06\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":90}}

* **Please explain your feature request in a one or two sentences.**
Setup a new Govee plug and the logs from Homebridge said to submit a new issue.

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Govee devices that this relates to?**
https://www.amazon.com/Govee-Weatherproof-Countdown-Compatible-Assistant/dp/B09TZP2B2D/

* **Anything else?**
Contact me if you need a ything else or someone to test.

Have a wonderful day!

**Comment by bwp91** [comment]
Hi @LMarkham 

Since this is brand new device type (with three outlets) please could we message on discord so I can get some extra information about how this device works?

https://discord.gg/cMGhNtZ3tW

thanks!
