### ISSUE TITLE
H7130 Temp display stuck at 32 degrees on Beta

### ISSUE THREAD

**Issue by MikeyLew32** [bwp91/homebridge-govee#326]
### What issue do you have? Please be as thorough and explicit as possible.

H7130 Space Heater on latest beta. Used the same device ID for the heater and temp sensor ID. Temp is stuck on 32 degrees, Govee app shows 75 degrees.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

v1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Pi 4, NodeJS v16.18.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

v6.0.5-beta.15

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H7130

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @MikeyLew32 

Regarding the H7130 do you know if this model has an in-built temperature sensor?

**Comment by MikeyLew32** [comment]
@bwp91 Hi Ben, 

Yes it does. In the Govee app, I can see the current and setpoint temperature. But I can only find one device ID, and using that ID in the plugin is locking the displayed temp at 32 degrees.

**Comment by bwp91** [comment]
Closing, please see and reply in https://github.com/bwp91/homebridge-govee/issues/335
Thanks!
