### ISSUE TITLE
govee credentials > LAN only

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-govee#329]
Homebridge > latest > Govee beta 15

When you add govee credentials, devices other than those associated with the account are not added. LAN only devices that are not associated with the account are omitted.

Eg, two H5075 are connected to my Govee account, one H6075 is LAN only and not connected to my account, it is online on my vlan, but is omitted from Homebridge Govee

{
    "name": "Govee",
    "username": "xx@xx.com",
    "password": "xx+xx",
    "debug": false,
    "httpRefreshTime": 180,
    "bleRefreshTime": 120,
    "apiBleControlInterval": 5,
    "disableDeviceLogging": true,
    "lightDevices": [
        {
            "label": "Gulvlampe",
            "deviceId": "xx:xx:..",
            "enableBT": false,
            "customIPAddress": "192.168.30.40"
        }
    ],
    "_bridge": {
        "name": "Govee Bridge",
        "username": "xx:xx:...",
        "port": 51827
    },
    "platform": "Govee"
}

**Comment by bwp91** [comment]
please check beta 16

**Comment by ghost** [comment]
My Govee login has been disabled due to too many logins. But beta .17 works. Thanks again :)

**Comment by bwp91** [comment]
oops! i think it lasts only 24 hours but maybe you can contact them to enable again earlier

**Comment by ghost** [comment]
It was yesterday, hence my long response time :) I don't understand it though. I didn't think I had restarted homebridge-govee that many times :)
