### ISSUE TITLE
How do I disable Adaptive Lighting on my Immersion TV accessory?

### ISSUE THREAD

**Issue by TrackieDax** [bwp91/homebridge-govee#333]
Can someone point me to where the config file for my Immersion TV accessory might be?
I'm trying to set the AdaptiveLighting property to false but I can't find the right config file.
Model is H6199, running on MacOS 12.6

**Comment by bwp91** [comment]
Hi @TrackieDax 

Are you using homebridge UI?

**Comment by TrackieDax** [comment]
Hi BenYep. And I can see the command in the logs for the light temp to be adjusted every half hour or so and it throws the light out of Movie mode,  but I can’t for the life of me find where I can set the light to ignore Adaptive mode. Thanks for the reply I really appreciate it. R. Sent from my iPhoneOn 21 Oct 2022, at 8:04 am, Ben ***@***.***> wrote:﻿
Hi @TrackieDax
Are you using homebridge UI?

**Comment by bwp91** [comment]
The adaptive lighting shift option set to `-1` 🙂

**Comment by bwp91** [comment]
this will remove the feature altogether

**Comment by TrackieDax** [comment]
Do you know where I can find that option in Homebridge UI? Or a config file? I can't see it.

**Comment by bwp91** [comment]
at the bottom. you need to type in a device label and device id for the options to show

<img width="383" alt="Screenshot 2022-10-20 at 23 58 05" src="https://user-images.githubusercontent.com/43026681/197074743-c0e91794-13dd-4fee-9065-72636237fa83.png">

**Comment by TrackieDax** [comment]
Thank you so much mate. This worked (sorry I took so long to get back to you).
You're a life saver.
