### ISSUE TITLE
H7131 Additional Settings

### ISSUE THREAD

**Issue by brylee123** [bwp91/homebridge-govee#334]
* **Please explain your feature request in one or two sentences.**
There are additional settings not available in the integration right now. Some additional features available in the Govee app for this device are:

1. Full RGB Night Light (color and brightness slider)
2. Display (Indicator LEDs Always ON/OFF)
3. Oscillate (ON/OFF) 
4. Tip-Over Sensor
5. Temperature Calibration Offset (I am guessing you would try to get this value to match up with your room thermometer)
6. Lock (Heater will not respond to any button touch), can be unlocked by physically long pressing Timer and Mode button or toggling this setting.

* **Is your feature request related to a problem? Please describe.**
I believe there is a separate issue regarding the 5 modes not working: (Low, Med, High, Fan, Auto)
Oscillation control is also not working.
https://github.com/bwp91/homebridge-govee/issues/322

* **Any particular Govee devices that this relates to?**
H7131

* **Anything else?**
I will be more than happy to supply logs and do testing.

**Comment by bwp91** [comment]
Closing, please see and reply in https://github.com/bwp91/homebridge-govee/issues/335
Thanks!
