### ISSUE TITLE
🔥  Govee Heaters H7130/H7131/H7132

### ISSUE THREAD

**Issue by bwp91** [bwp91/homebridge-govee#335]
Many tickets recently regarding the heaters and it's easier for me to have all in one place.

Discussions are:
* commands no longer working from the home app, but still working from the Govee app
* requests for additional functionality (like lock, light, modes, etc(
* showing as a heater accessory, either:
  * using the in-built device temperature sensor
  * using a separate sensor

Tickets:
* https://github.com/bwp91/homebridge-govee/issues/334
* https://github.com/bwp91/homebridge-govee/issues/326
* https://github.com/bwp91/homebridge-govee/issues/322
* https://github.com/bwp91/homebridge-govee/issues/319

I will post updates here as progress is made 👍 

---

Beta should support:

* show accessory as heater instead of fan
* sync the current temperature and target temperature every few minutes
* control from home app:
  * on/off
  * target temperature
  * oscillation
  * lock
* sync when controlled from govee app:
  * on/off
  * target temperature
  * oscillation
  * lock

there’s obviously still a lot to do and i will post new betas over time!

TODO:

* implement modes (AWS & API)
* device light
* clean up logging (and unused codes, there are a lot!)

**Comment by bwp91** [comment]
@nevetssf @WhatTheKJ 

please try the latest beta to see if on and off are working from the home app (nothing else will probably work)

---

@DebasishBahinipati please try the above, updating to the beta. since you are using an API key rather than govee username and password your case is slightly different and may or not work compared with the above users, I'm hoping on and off works for you still now

**Comment by MikeyLew32** [comment]
Looking forward to see progress towards this fix. Everything works perfectly (device shows up as a heater, i can toggle oscillation on and off) but the internal thermostat is not reporting the correct temp to homekit.

**Comment by DebasishBahinipati** [comment]
On/Off is working now with an API key. No Other controls. Also Device On/Off status is not getting changed in HomeKit if Device is getting turned on/off manually or from Govee App.

**Comment by WhatTheKJ** [comment]
> @nevetssf @WhatTheKJ
> 
> please try the latest beta to see if on and off are working from the home app (nothing else will probably work)
> 
> @DebasishBahinipati please try the above, updating to the beta. since you are using an API key rather than govee username and password your case is slightly different and may or not work compared with the above users, I'm hoping on and off works for you still now

Updated to latest beta. Same problem unfortunately. When turning on the heater from the Govee app, Home app doesn’t notice it’s turned on but if you adjust the slider in Home you can still control it. Not an issue really just something I noticed. Not sure if there is anything you can do but it seems like more of an issue with Govee not telling homebridge thus not updating the Home app.

**Comment by bwp91** [comment]
> On/Off is working now with an API key. No Other controls. Also Device On/Off status is not getting changed in HomeKit if Device is getting turned on/off manually or from Govee App.

I would recommend you enter your username and password into the config. The API key method is very limited, can only change on/off and the mode, it cannot request status or control the target temperature.

**Comment by bwp91** [comment]
comment moved to initial post

**Comment by MikeyLew32** [comment]
Lastest beta still showing 32 degrees in Homekit while the Govee app is showing 72 degrees. 

I have both username/password access and API code in the plugin config.

**Comment by DebasishBahinipati** [comment]
> > On/Off is working now with an API key. No Other controls. Also Device On/Off status is not getting changed in HomeKit if Device is getting turned on/off manually or from Govee App.
> 
> I would recommend you enter your username and password into the config. The API key method is very limited, can only change on/off and the mode, it cannot request status or control the target temperature.

Any way I can show only specific devices? I have lot of temperature sensors and I dont want all of those to be shown. That's why I was using only API key. now with the Username and Password Heater is working with state changes, but those sensors are showing. Please let me know if there is a way to show only heater devices or specific devices. Thank you.

**Comment by DebasishBahinipati** [comment]
These are the Error Logs I see in the Logs as well.

[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qhIAAAAAAAAAAAAAAAAAAAAAALg=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qhEAAAAAAAAAAAAAAAAAAAAAALs=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qgUBAwAAAAAAAAAAAAAAAAAAAK0=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qhYB/////wAAAAAAAAAAAAAAAL0=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qggAAAAAAAAAAAAAAAAAAAAAAKI=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qhkFoAAAAAAAAAAAAAAAAAAAABY=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qhoAAZ7cgQr8gAABAAAAAAAAAAU=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qhsBAGQAAAAAAAAAAAAAAAAAANQ=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qhsFDf+rBQAAAAAAAAAAAAAAAOg=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qh4BAgAAAAAAAAAAAAAAAAAAALc=].
[20/10/2022, 08:58:03] [Govee] [Smart Space Heater] new/unknown scene code received: [qhcAAAAAAAAAAAAAAAAAAAAAAL0=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qhIAAAAAAAAAAAAAAAAAAAAAALg=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qhEAAAAAAAAAAAAAAAAAAAAAALs=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qgUBAwAAAAAAAAAAAAAAAAAAAK0=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qhYB/////wAAAAAAAAAAAAAAAL0=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qggAAAAAAAAAAAAAAAAAAAAAAKI=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qhkFoAAAAAAAAAAAAAAAAAAAABY=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qhoAAZ7cgQr8gAABAAAAAAAAAAU=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qhsBAGQAAAAAAAAAAAAAAAAAANQ=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qhsFDf+rBQAAAAAAAAAAAAAAAOg=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qh4BAgAAAAAAAAAAAAAAAAAAALc=].
[20/10/2022, 08:58:33] [Govee] [Smart Space Heater] new/unknown scene code received: [qhcAAAAAAAAAAAAAAAAAAAAAAL0=].

**Comment by bwp91** [comment]
@DebasishBahinipati these yellow entries in the log referring to codes are not errors. i post them in yellow to get users attention. 

And yes it is possible to hide devices. Use the device ids that are listed when the plugin starts, and use the homebridge ui plugin settings screen to enter the device ids and click the hide/ignore from homekit box.

it may be a bit tedious doing all your devices you want to hide but you only need to do it once :)

**Comment by DebasishBahinipati** [comment]
> @DebasishBahinipati these yellow entries in the log referring to codes are not errors. i post them in yellow to get users attention.
> 
> And yes it is possible to hide devices. Use the device ids that are listed when the plugin starts, and use the homebridge ui plugin settings screen to enter the device ids and click the hide/ignore from homekit box.
> 
> it may be a bit tedious doing all your devices you want to hide but you only need to do it once :)

Thank you. I got it now.

**Comment by wills721** [comment]
Chiming in......I get tons and tons of these now after upgrading to the new plug-in.  I mean,  warnings or not it will fill the logs
[qhcAAAAAAAAAAAAAAAAAAAAAAL0=] [aa170000000000000000000000000000000000bd].
1:26:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhkFoAAAAAAAAAAAAAAAAAAAABY=] [aa1905a000000000000000000000000000000016].
1:26:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qghs5HKBjOMAAAAAAAAAAAAAALY=] [aa086ce472818ce30000000000000000000000b6].
1:26:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhoBAQh6AQOy4gAAAAAAAAAAAJA=] [aa1a0101087a0103b2e200000000000000000090].
1:26:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qh4AAAAAAAAAAAAAAAAAAAAAALQ=] [aa1e0000000000000000000000000000000000b4].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhIBAAAAAAAAAAAAAAAAAAAAALk=] [aa120100000000000000000000000000000000b9].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhMAAQMAAAEAAAAAAAAAAAAAALo=] [aa130001030000010000000000000000000000ba].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qgUBAAAAAAAAAAAAAAAAAAAAAK4=] [aa050100000000000000000000000000000000ae].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhAAAAAAAAAAAAAAAAAAAAAAALo=] [aa100000000000000000000000000000000000ba].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhgBAAAAAAAAAAAAAAAAAAAAALM=] [aa180100000000000000000000000000000000b3].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhcAAAAAAAAAAAAAAAAAAAAAAL0=] [aa170000000000000000000000000000000000bd].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhkFoAAAAAAAAAAAAAAAAAAAABY=] [aa1905a000000000000000000000000000000016].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qghs5HKBjOMAAAAAAAAAAAAAALY=] [aa086ce472818ce30000000000000000000000b6].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhoBAQh6AQO2ygAAAAAAAAAAALw=] [aa1a0101087a0103b6ca000000000000000000bc].
1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qh4AAAAAAAAAAAAAAAAAAAAAALQ=] [aa1e0000000000000000000000000000000000b4].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhIBAAAAAAAAAAAAAAAAAAAAALk=] [aa120100000000000000000000000000000000b9].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhMAAQMAAAEAAAAAAAAAAAAAALo=] [aa130001030000010000000000000000000000ba].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qgUBAAAAAAAAAAAAAAAAAAAAAK4=] [aa050100000000000000000000000000000000ae].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhAAAAAAAAAAAAAAAAAAAAAAALo=] [aa100000000000000000000000000000000000ba].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhgBAAAAAAAAAAAAAAAAAAAAALM=] [aa180100000000000000000000000000000000b3].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhcAAAAAAAAAAAAAAAAAAAAAAL0=] [aa170000000000000000000000000000000000bd].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhkFoAAAAAAAAAAAAAAAAAAAABY=] [aa1905a000000000000000000000000000000016].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qghs5HKBjOMAAAAAAAAAAAAAALY=] [aa086ce472818ce30000000000000000000000b6].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhoBAQh6AQOy4gAAAAAAAAAAAJA=] [aa1a0101087a0103b2e200000000000000000090].
1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene cod

**Comment by bwp91** [comment]
> Chiming in......I get tons and tons of these now after upgrading to the new plug-in. I mean, warnings or not it will fill the logs
> [qhcAAAAAAAAAAAAAAAAAAAAAAL0=] [aa170000000000000000000000000000000000bd].
> 1:26:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhkFoAAAAAAAAAAAAAAAAAAAABY=] [aa1905a000000000000000000000000000000016].
> 1:26:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qghs5HKBjOMAAAAAAAAAAAAAALY=] [aa086ce472818ce30000000000000000000000b6].
> 1:26:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhoBAQh6AQOy4gAAAAAAAAAAAJA=] [aa1a0101087a0103b2e200000000000000000090].
> 1:26:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qh4AAAAAAAAAAAAAAAAAAAAAALQ=] [aa1e0000000000000000000000000000000000b4].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhIBAAAAAAAAAAAAAAAAAAAAALk=] [aa120100000000000000000000000000000000b9].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhMAAQMAAAEAAAAAAAAAAAAAALo=] [aa130001030000010000000000000000000000ba].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qgUBAAAAAAAAAAAAAAAAAAAAAK4=] [aa050100000000000000000000000000000000ae].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhAAAAAAAAAAAAAAAAAAAAAAALo=] [aa100000000000000000000000000000000000ba].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhgBAAAAAAAAAAAAAAAAAAAAALM=] [aa180100000000000000000000000000000000b3].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhcAAAAAAAAAAAAAAAAAAAAAAL0=] [aa170000000000000000000000000000000000bd].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhkFoAAAAAAAAAAAAAAAAAAAABY=] [aa1905a000000000000000000000000000000016].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qghs5HKBjOMAAAAAAAAAAAAAALY=] [aa086ce472818ce30000000000000000000000b6].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhoBAQh6AQO2ygAAAAAAAAAAALw=] [aa1a0101087a0103b6ca000000000000000000bc].
> 1:27:25 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qh4AAAAAAAAAAAAAAAAAAAAAALQ=] [aa1e0000000000000000000000000000000000b4].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhIBAAAAAAAAAAAAAAAAAAAAALk=] [aa120100000000000000000000000000000000b9].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhMAAQMAAAEAAAAAAAAAAAAAALo=] [aa130001030000010000000000000000000000ba].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qgUBAAAAAAAAAAAAAAAAAAAAAK4=] [aa050100000000000000000000000000000000ae].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhAAAAAAAAAAAAAAAAAAAAAAALo=] [aa100000000000000000000000000000000000ba].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhgBAAAAAAAAAAAAAAAAAAAAALM=] [aa180100000000000000000000000000000000b3].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhcAAAAAAAAAAAAAAAAAAAAAAL0=] [aa170000000000000000000000000000000000bd].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhkFoAAAAAAAAAAAAAAAAAAAABY=] [aa1905a000000000000000000000000000000016].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qghs5HKBjOMAAAAAAAAAAAAAALY=] [aa086ce472818ce30000000000000000000000b6].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene code: [qhoBAQh6AQOy4gAAAAAAAAAAAJA=] [aa1a0101087a0103b2e200000000000000000090].
> 1:27:55 PMAllDevicesGoveeWARNING[EnsleyRoom Heater] new scene cod

hi @wills721 
these are currently there whilst i am trying to implement devices properly like the heater. eg as a heater homekit device rather than a fan.
they shouldn’t appear if you don’t have debug logging on. 
it is something i eventually plan to reduce 👍🏻

**Comment by wills721** [comment]
I do not have debug logging on -- never did.

**Comment by bwp91** [comment]
> I do not have debug logging on -- never did.

ok will check this!

**Comment by MikeyLew32** [comment]
Any updates on fixing the internal temp sensor in H7130?

**Comment by stwrz** [comment]
My heater (H7130) went from presenting in Home as a fan (simple ON/OFF) to now displaying as three devices: thermometer, fan, and light. None of the controls seem to have any bearing on the heater. Upgraded to the latest beta to no avail. In the settings, I've entered my username, password, and API. Kind of a bummer, as none of my automatons works as a result of this.

**Comment by bwp91** [comment]
> My heater (H7130) went from presenting in Home as a fan (simple ON/OFF) to now displaying as three devices: thermometer, fan, and light. None of the controls seem to have any bearing on the heater. Upgraded to the latest beta to no avail. In the settings, I've entered my username, password, and API. Kind of a bummer, as none of my automatons works as a result of this.

Can you show me a screenshot of how the H7130 appears in the govee app? Does it show the current (ambient) temperature? 
Also does this model have a light?

**Comment by nowornever211** [comment]
I am having same issue. The control in home app has no effect on the heater. It seems the `on` command was send by the aws client but then it just went straight back to `off`. Seeing some logs like below

```
[11/8/2022, 3:32:53 PM] [Govee] [Smart Heater] current state [on].
[11/8/2022, 3:32:53 PM] [Govee] [AWS] message event [{"proType":2,"sku":"H7130","device":"","softVersion":"1.00.27","wifiSoftVersion":"1.00.27","cmd":"multiSync","type":2,"transaction":"v_1667950373359000","pactType":1,"pactCode":1,"state":{"result":0}}].
[11/8/2022, 3:32:53 PM] [Govee] [Smart Heater] [AWS] receiving update {"source":"AWS","result":0}.
[11/8/2022, 3:33:03 PM] [Govee] [Smart Heater] [AWS] sending update {"msg":{"cmd":"status","cmdVersion":2,"transaction":"v_1667950383163000","type":0}}.
[11/8/2022, 3:33:03 PM] [Govee] [AWS] message event [{"proType":2,"sku":"H7130","device":"","softVersion":"1.00.27","wifiSoftVersion":"1.00.27","cmd":"status","type":0,"transaction":"v_1667950383163000","pactType":1,"pactCode":1,"state":{"onOff":0,"sta":{"setTem":7300,"curTem":6800,"stc":"0040000003"},"result":1},"op":{"command":["qhIAAAAAAAAAAAAAAAAAAAAAALg=","qhEAAAAAAAAAAAAAAAAAAAAAALs=","qgUBAAAAAAAAAAAAAAAAAAAAAK4=","qhYB/////wAAAAAAAAAAAAAAAL0=","qhABAAAAAAAAAAAAAAAAAAAAALs=","qhgAAAAAAAAAAAAAAAAAAAAAALI=","qhcAAAAAAAAAAAAAAAAAAAAAAL0=","qhkFoAAAAAAAAAAAAAAAAAAAABY=","qggAAAAAAAAAAAAAAAAAAAAAAKI=","qhoBAJyEgQEakAAAAAAAAAAAAKM=","qh4CAAAAAAAAAAAAAAAAAAAAALY="]}}].
[11/8/2022, 3:33:03 PM] [Govee] [Smart Heater] [AWS] receiving update {"source":"AWS","onOff":0,"sta":{"setTem":7300,"curTem":6800,"stc":"0040000003"},"result":1,"commands":["qhIAAAAAAAAAAAAAAAAAAAAAALg=","qhEAAAAAAAAAAAAAAAAAAAAAALs=","qgUBAAAAAAAAAAAAAAAAAAAAAK4=","qhYB/////wAAAAAAAAAAAAAAAL0=","qhABAAAAAAAAAAAAAAAAAAAAALs=","qhgAAAAAAAAAAAAAAAAAAAAAALI=","qhcAAAAAAAAAAAAAAAAAAAAAAL0=","qhkFoAAAAAAAAAAAAAAAAAAAABY=","qggAAAAAAAAAAAAAAAAAAAAAAKI=","qhoBAJyEgQEakAAAAAAAAAAAAKM=","qh4CAAAAAAAAAAAAAAAAAAAAALY="]}.
[11/8/2022, 3:33:03 PM] [Govee] [Smart Heater] current state [off].
```

**Comment by bwp91** [comment]
If someone has a H7130 that they could allow me to access via a govee account, i can try to sort this out.
Could be that this model (separately from the 7131 and 7132) uses different commands to control

**Comment by stwrz** [comment]
> If someone has a H7130 that they could allow me to access via a govee account, i can try to sort this out.
> Could be that this model (separately from the 7131 and 7132) uses different commands to control

I'm willing to do that. Thanks for taking a closer look at this. How do we go about that?

**Comment by bwp91** [comment]
> > If someone has a H7130 that they could allow me to access via a govee account, i can try to sort this out.
> > Could be that this model (separately from the 7131 and 7132) uses different commands to control
> 
> I'm willing to do that. Thanks for taking a closer look at this. How do we go about that?

Happy to message on discord!
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
I have made a lot of progress with the H7130 in the new beta version of the plugin

**Comment by mperone** [comment]
It seems like the integration for these heaters may have stopped working overnight. At least my H7132 no longer responds to commands from Homebridge or reports updates to Homebridge. The device works fine from the Govee app.

**Comment by WhatTheKJ** [comment]
> It seems like the integration for these heaters may have stopped working overnight. At least my H7132 no longer responds to commands from Homebridge or reports updates to Homebridge. The device works fine from the Govee app.

Came here to say this. My H7131 have stopped responding. Running v7.1.5

**Comment by stwrz** [comment]
> > It seems like the integration for these heaters may have stopped working overnight. At least my H7132 no longer responds to commands from Homebridge or reports updates to Homebridge. The device works fine from the Govee app.
> 
> Came here to say this. My H7131 have stopped responding. Running v7.1.5

Hate being the bearer of bad news, but same for my H7130.

**Comment by DebasishBahinipati** [comment]
> > > It seems like the integration for these heaters may have stopped working overnight. At least my H7132 no longer responds to commands from Homebridge or reports updates to Homebridge. The device works fine from the Govee app.
> > 
> > 
> > Came here to say this. My H7131 have stopped responding. Running v7.1.5
> 
> Hate being the bearer of bad news, but same for my H7130.

Looks like Heaters and Temprature Sensors are not connected to Wifi, they are all BLE. Please check in Govee App to see if it shows both Wi-fi and BLE or just BLE. For me only waterleak sensors are connecting to Wi-fi, nothing else.

**Comment by WhatTheKJ** [comment]
Looks like this is an issue on the  Govee side. https://twitter.com/goveeofficial/status/1593262431978987521?s=46&t=d9TcS80nVcSEgNzst4rvQg

**Comment by DebasishBahinipati** [comment]
With the latest version turning on heater with heater mode (heat mode in homekit) turns on fan only.
[11/23/2022, 3:08:46 PM] [Govee] [Smart Space Heater] current mode [fan-only].

It was working before as expected, Could you please Check on that.

**Comment by bwp91** [comment]
> With the latest version turning on heater with heater mode (heat mode in homekit) turns on fan only. [11/23/2022, 3:08:46 PM] [Govee] [Smart Space Heater] current mode [fan-only].
> 
> It was working before as expected, Could you please Check on that.

This is expected now. Access the govee “auto” mode using the “auto” homekit mode.
The homekit “heat” mode should be used with the home app fan slider which now controls the different speeds:
25% - fan only govee mode
50% - low govee mode
75% - medium govee mode
100% - high govee mode

**Comment by mattperone** [comment]
The H7132 heater is no longer showing target temperature after a recent update, only the HVAC modes.

I'd also note for anyone having issues that it seems important to use the user/pass setup rather than the API setup for this device. The above comment about auto <-> auto and heat + fan slider <-> fan/low/medium/high looks like it only works when you set up with a username and password. If you set up with the API I think you can only get the heater into Auto mode no matter what the settings.

Thanks as always for all the bug hunting you're doing on this plugin!

**Comment by bwp91** [comment]
@oakstreetrec is not showing target temperature even with your govee username and password?

Yes for these appliances, govee user and pass are recommended. The API offers barely any functionality. I am thinking about removing these appliances from homebridge if the user does not have the user and pass in the config.

**Comment by mattperone** [comment]
Correct - just the different modes:

![image](https://user-images.githubusercontent.com/52012475/205350183-b2852e8b-a35b-487c-98c3-b575d02d461c.png)

**Comment by bwp91** [comment]
You should have target temperature control within the home app

**Comment by mattperone** [comment]
Ahh, I actually have it connected to home assistant. The integration there used to be able to to set the temperature but now it can't. I went into the homebridge ui to see if I noticed anything and saw that the Govee shows the above while my nest thermostat (which can adjust temp from home assistant) shows the below... so I thought I had found the culprit. I guess not!

![image](https://user-images.githubusercontent.com/52012475/205355001-01434aaa-713a-4894-a75f-a924f368f591.png)

**Comment by bwp91** [comment]
This is most likely because your nest thermostat has been exposed to Homebridge as a `Thermostat` service type which has a `TargetTemperature` characteristic.

This plugin exposes these devices as a `HeaterCooler` service type which has a `HeatingThresholdTemperature` characteristic (instead of target temperature). Most likely this characteristic is not supported in the Homebridge UI. 

I wonder if there is a way to expose this to home assistant - how to you use this plugin with home assistant?

**Comment by mattperone** [comment]
I use the Homekit Controller integration: https://www.home-assistant.io/integrations/homekit_controller

**Comment by bwp91** [comment]
Hmm I had a quick look at the code for this integration and it seems like it should support the HeaterCooler HeatingThresholdTemperature function :/

**Comment by mattperone** [comment]
Thanks so much for taking a look. I'll do some more digging - maybe I can find some home assistant logs that can point me in the right direction.

**Comment by bwp91** [comment]
I saw this here

https://github.com/home-assistant/core/blob/d3b35ca2a78e3abfecc2c506004e092a6158da46/homeassistant/components/homekit_controller/climate.py#L171

Though I know next to nothing about Home Assistant and how it works.

**Comment by mattperone** [comment]
Well... I figured out a way to make it work.

There was a message in the Home Assistant (HA) logs that setting temperature in "heat_cool" mode is not supported yet. I had previously found that setting "heat_cool" mode in HA was the only way to get Homebridge into Auto rather than Fan. BUT, given that piece of information I tried to have HA set "heat" mode (which would usually put it into Fan) and the target temperature at the same time in the same command... and lo and behold that worked!

**Comment by notm1ke** [comment]
Just a heads up to anyone also having this issue - I have an H7130 and controls weren't working (it showed up in the Home app, but toggling modes and all of that updated in Homebridge but didn't actually do anything on the device.) 

I managed to fix it by supplying my email/password instead of an API key, or a combination of both credentials and an API key. After a restart everything started working as expected, so if anyone else is having this issue and has looked through all of GitHub issues here and couldn't find a solution, I hope this helped!
