### ISSUE TITLE
H5198 Multi Probe thermometer

### ISSUE THREAD

**Issue by SD-TADAMS** [bwp91/homebridge-govee#338]
Hi it looks like the API supports the device below. This is a 'Thermometer' used for grilling and I can see it in the API, looking via postman. Would be really cool if you could add this device in to your support. I have included the debug snippet from my home bridge. Thanks for your work !!

[Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"BB:ED:D8:39:32:37:21:88","deviceName":"Thermometer","model":"H5198","httpInfo":{"groupId":0,"device":"BB:ED:D8:39:32:37:21:88","sku":"H5198","spec":"","versionHard":"3.02.02","versionSoft":"1.00.11","deviceName":"Thermometer","deviceExt":{"deviceSettings":"{\"wifiName\":\"REMOVED\",\"address\":\"REMOVED\",\"bleName\":\"GVH5198_372188\",\"topic\":\"GD/658a1edb31cb36c20a72e3b6183eeda4\",\"wifiMac\":\"D4:AD:FC:4A:38:5C\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"\",\"wifiHardVersion\":\"\",\"ic\":0,\"secretCode\":\"BoghNzI52AA=\",\"boilWaterCompletedNotiOnOff\":1,\"sku\":\"H5198\",\"device\":\"BB:ED:D8:39:32:37:21:88\",\"deviceName\":\"Thermometer\",\"versionHard\":\"3.02.02\",\"versionSoft\":\"1.00.11\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/86609e7abca785e37937f654675b881a-add_list_type_device_5198.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":85}}

**Comment by bwp91** [comment]
Hi @SD-TADAMS please install the beta version of the plugin i have added this as a supported device.

**Comment by sabertoothstu** [comment]
Hi @bwp91 , I just got this same device today, and tried to install the Beta version, but it looks like its an outdated plugin? Is the latest Beta with support for this v7.0.2 beta 9? If there is a later version, i'm not seeing it in HomeBridge UI. Any help would be appreciated! Thanks for this!

**Comment by bwp91** [comment]
At the time of writing it was a beta but now the latest version is 7.1.0!

**Comment by sabertoothstu** [comment]
Hi @bwp91 thanks for the response! Do I need to perform additional setup? I am running in to another issue that was reported separately where the thermometer only reports one of the four temp sensors and is stuck at default. I set it to ignore when turned off but it is a wifi thermometer so not sure if the BLE settings need to be utilized. Any help would be appreciated!

**Comment by brylee123** [comment]
@bwp91 I just want to bump this. It does not seem like this is working. There is supposed to be 4 thermometer sensors as opposed to (2 thermometer + 1 hygrometer). These values also do not change.

![image](https://github.com/bwp91/homebridge-govee/assets/22011502/73b57b6c-f72d-4367-8abe-8ea90bc6ccbc)
