### ISSUE TITLE
(H61A0) 🔥 Firewalling my Govee Light Strip 💡 Makes it reconnect itself to Wi-Fi Every 5 Minutes

### ISSUE THREAD

**Issue by Write** [bwp91/homebridge-govee#339]
Hi everyone,

This "Issue" has nothing to do with this plugin, but I really wouldn't know where to put this request, since it's the only plugin that support LAN / Local control (Even HA plugin doesn't support it yet IIRC).

As soon as I'm blocking internet access for my govee light strip (H61A0) it keep reconnecting to my wi-fi network every 5 minutes, I'm guessing it needs to be able to connect to a remote server, and if it can't, it reconnect to the wi-fi.

Does anyone have the same issue and / or a workaround ?

Thanks a lot.

**Comment by ghost** [comment]
https://github.com/bwp91/homebridge-govee/issues/312#issue-1391032596

**Comment by Write** [comment]
Well yes, I even answered to that thread, but it seems there's no workaround ^^?

**Comment by ghost** [comment]
No, it's Govee support you have to contact and hope they change the behavior, which is pretty bad behavior.

**Comment by Write** [comment]
Well, doesn't seems to be like LIFX unfortunately, it really does try to connect to a remote server, not just trying a DNS request :(

**Comment by ghost** [comment]
Yes unfortunately. I have chosen to ignore it. But that's bad behavior. I use pihole and I don't like what I see!

**Comment by Write** [comment]
I just contacted Govee support by mail, will post here if they follow up.
I'd encourage all of you to do the same, in the hope they stop the device from reconnecting to the Wi-Fi network if it can't connect to AWS MQTT Broker on port 8883.

In the meantime, If someone wants it to NOT disconnect from Wi-Fi Network, I encourage you to allow ONLY outgoing connection from Govee's device to remote port 8883, because it has tendencies to be chatty to some IP over unsecured port 80, (maybe it's encrypted, but still). I was too lazy to capture those packets, as allowing the device to connect only to remote IP on port 8883 (MQTT Broker) work just fine. 

----

> To: support@govee.com
> Subject: LAN Control : MQTT not reachable, the device keep disconnecting from Wi-Fi Network
>
> Hello,
> I reach to you today, hoping you could forward this mail to the tech department.
> Following the recent update allowing devices control over LAN, I tried to firewall my H61A0 (Govee Light Strip) to prevent it from leaking data over the internet. 
>
> Unfortunately, it seems that if the device can’t connect to the remote AWS MQTT Broker, on port 8883, the Govee Device disconnect itself after 5 minutes and few seconds. 
>
> Other than that, it’s fully usable and work very great, thanks a bunch for adding LAN control which work perfectly.
> Related Github Thread : https://github.com/bwp91/homebridge-govee/issues/339
>
> Kind regards,
>
> [redacted]

**Comment by ghost** [comment]
> I just contacted Govee support by mail, will post here if they follow up. I'd encourage all of you to do the same, in the hope they stop the device from reconnecting to the Wi-Fi network if it can't connect to AWS MQTT Broker on port 8883.
> 
> In the meantime, If someone wants it to NOT disconnect from Wi-Fi Network, I encourage you to allow ONLY outgoing connection from Govee's device to remote port 8883, because it has tendencies to be chatty to some IP over unsecured port 80, (maybe it's encrypted, but still). I was too lazy to capture those packets, as allowing the device to connect only to remote IP on port 8883 (MQTT Broker) work just fine.
> 
> > To: [support@govee.com](mailto:support@govee.com)
> > Subject: LAN Control : MQTT not reachable, the device keep disconnecting from Wi-Fi Network
> > Hello,
> > I reach to you today, hoping you could forward this mail to the tech department.
> > Following the recent update allowing devices control over LAN, I tried to firewall my H61A0 (Govee Light Strip) to prevent it from leaking data over the internet.
> > Unfortunately, it seems that if the device can’t connect to the remote AWS MQTT Broker, on port 8883, the Govee Device disconnect itself after 5 minutes and few seconds.
> > Other than that, it’s fully usable and work very great, thanks a bunch for adding LAN control which work perfectly.
> > Related Github Thread : #339
> > Kind regards,
> > [redacted]

Have you received a response from Govee?

**Comment by Write** [comment]
> Have you received a response from Govee?

Indeed, but not really confirming if something will be done though.

![Screenshot du 2022-11-25 à 15 26 08](https://user-images.githubusercontent.com/541722/204005266-3592711b-dc7a-473a-b7b0-2e4564ce7ac5.png)
