### ISSUE TITLE
Govee 6148

### ISSUE THREAD

**Issue by justinkerns1** [bwp91/homebridge-govee#34]
I thought the Govee 6148 supported adaptive lighting potentially but not 100% sure. Is this a possibility? 

Also,my 6148 seems to not respond to HomeKit automation. I had this set to turn off at a certain time and it didn't. It also appears to start flashing different colors randomly and I go into the Govee app to find it somehow was switched to "Scene" mode. Any thoughts on this? 

Thanks for all your work on this plugin!! I appreciate it!

**Comment by bwp91** [comment]
Hi @justinkerns1 

> I thought the Govee 6148 supported adaptive lighting potentially but not 100% sure. Is this a possibility?

The option for adaptive lighting should appear for all the models. Are you using the Homebridge beta? Make sure it's updated to the latest (beta) version.

> Also,my 6148 seems to not respond to HomeKit automation. I had this set to turn off at a certain time and it didn't. 

Please try this again. Are there any logs at the time the automation was meant to run? Please turn on debug logging too.

> It also appears to start flashing different colors randomly and I go into the Govee app to find it somehow was switched to "Scene" mode. Any thoughts on this?

This is very strange as the [Govee API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf) doesn't support switching to scenes. Could there be another automation running somewhere to turn this on? Like via the Govee app (if this is possible?) or through Google Home/Alexa?

> Thanks for all your work on this plugin!! I appreciate it!

😃

**Comment by justinkerns1** [comment]
Thanks for the quick reply. 

So I'm using HOOBS version 3.3.2 so maybe that's why adaptive lighting won't work? Is it supported in Homebridge only? 

Also, here is what I could find when it last started flashing random colors and brightnesses. I'm not sure exactly when it did it but I think it was around this time. Some of these is probably me trying to get it to stop. I also just turned on the Debug Log. 
1/12/2021, 8:57:18 PM [Govee] [H6148_EA6B] current colour [rgb 120 121 135].
1/12/2021, 8:57:48 PM [Govee] [H6148_EA6B] current colour [rgb 0 0 0].
1/12/2021, 8:58:23 PM [Govee] [H6148_EA6B] current brightness [1%].
1/12/2021, 8:58:48 PM [Govee] [H6148_EA6B] current colour [rgb 255 255 255].
1/12/2021, 8:59:12 PM [Govee] [H6148_EA6B] current brightness [100%].
1/12/2021, 8:59:20 PM [Govee] [H6148_EA6B] current brightness [1%].
1/12/2021, 9:00:11 PM [Govee] [H6148_EA6B] current colour [rgb 128 128 128].
1/12/2021, 9:00:12 PM [Govee] [H6148_EA6B] current colour [rgb 120 120 135].
1/12/2021, 9:00:18 PM [Govee] [H6148_EA6B] current brightness [4%].
1/12/2021, 9:01:09 PM [Govee] [H6148_EA6B] current brightness [50%].
1/12/2021, 9:03:18 PM [Govee] [H6148_EA6B] current brightness [4%].

As far as the automation I think what happened was I didn't have it clicked to turn off so at 11:30pm when the automation was to run nothing happened (It was set to be 4% which from what I can tell from the log it was already at 4%). Sorry to waste your time on that one I dug into it and it was for sure my fault.

**Comment by bwp91** [comment]
Ahh if you're using HOOBS their 'included' Homebridge version is v1.1.7. There is no way to change this. Adaptive lighting for your Govee model will be available when Homebridge 1.3 is released and HOOBS update their system to include Homebridge 1.3.

From your logs it looks like you were having a little disco 😛 

If you have any further issues with the plugin please do get in touch!
