### ISSUE TITLE
V7.1.0 adds meat thermometer

### ISSUE THREAD

**Issue by PNWOregon** [bwp91/homebridge-govee#340]
The newest update adds my Meat Thermometer to HomeKit. The meat thermometer is a Bluetooth device, and is not regularly on/connected.  which adds the value of 32° to my home by default. I would like the option to remove the single device if possible.

Thanks for all the hard work and overall great plug in!

**Comment by bwp91** [comment]
Hi @PNWOregon 

There is already the option of hiding devices using the config.

Using the device id that is shown when the plugin starts, you can create an entry for your device in the config using this device id and enable the “hide from homekit” option

**Comment by PNWOregon** [comment]
This worked, thanks! It added automatically so it never occurred to me to manually add it then hide it. 

Thanks again!
