### ISSUE TITLE
[BLE] disabling client as ERR_DLOPEN_FAILED.

### ISSUE THREAD

**Issue by tjridge** [bwp91/homebridge-govee#342]
### What issue do you have? Please be as thorough and explicit as possible.
[BLE] disabling client as ERR_DLOPEN_FAILED.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge CLI

* Which version of Homebridge/HOOBS do you have?
1.5.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 3 B+

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
7.1.1

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @tjridge please join the discord channel the link is on the open a new issue page. 
i can guide you though how much to fix this irritating error

**Comment by bwp91** [comment]
https://discord.gg/cMGhNtZ3tW

there we go ^

**Comment by bwp91** [comment]
Closing as fixed. Anybody in the future please create a new issue or message directly on discord 🙂
