### ISSUE TITLE
Unable to configure Custom Scenes Modes in UI

### ISSUE THREAD

**Issue by dgrodrigues** [bwp91/homebridge-govee#348]
Im trying to configure the H6199 led strip. I've got the AWS codes for when i click the video mode. 
I try to go to the plugin's Custom/Scenes Modes, but i click the arrow and nothing appears. BLT is enabled and also AWS. 

<img width="748" alt="Captura de ecrã 2022-10-31, às 20 04 35" src="https://user-images.githubusercontent.com/19906028/199100693-a952f4e3-60e5-42d3-b628-20c0f55bdaac.png">

Any snippet on how to configure scenes by adding the code in the homebridge config json?

Thanks

**Comment by bwp91** [comment]
Hi @dgrodrigues 

You need to enter the 23 digit govee device id (as per your screenshot I can see the warning message) for these options to appear.

The UI is designed to show required options before other options appear to avoid any confusion.

I hope it makes sense that any codes that you enter need to be mapped to a specific device.

**Comment by dgrodrigues** [comment]
@bwp91 That was it. I was missing one number. Thanks 👍
