### ISSUE TITLE
Looking to see if this is still an integration that can not be done on Mac? 

### ISSUE THREAD

**Issue by col4bin** [bwp91/homebridge-govee#349]
Recently acquired a HOOBS device and have been having blast syncing things to the home kit. 

I do not have any technical accolades, so I have been trying to pick up the best I can when it comes to the "coding moments" :)

I am seeing that there can be some problems syncing the lights depended on what type they are, and the functionality of your device (I am on the pre-built/purchased HOOBS). 

I was able to grab the API key from Govee, and I have been able to get the lights to show up in my dashboard, but none of it is functional (lights won't change colors/ turn on or off when pressed). I wanted to reach out here cause it seems that a majority of people can get it to work and love it; so would be grateful if anyone can help me get this one rolling! 

For details on my environment, I am on a new Mac Book (M1), and I am using version 4.2.8 of HOOBS (pre built/purchased from HOOBS). I am not terribly sure about the "Node.js"... Ill just add where I stand, I thought I had read the "node" won't work on Mac.. Def out of my wheelhouse! 

Based off other videos I saw, I tried older releases as well as the most current. Did not get any different functionality that I could notice. 

The lights we are attempting to connect to are, " H6125" Hardware Version 1.00.06. 

I did take a swing at the code to be able to "connect" to each different light, and it seemed to work haha, but nothing responds sadly. 

Thank you for any help or experience you might be able to give! Hope everyone is having a great weekend! 

{
    "name": "Govee",
    "username": "utler@gmail.com",
    "password": "password",
    "apiKey": "REMOVED",
    "platform": "Govee"
    "lightDevices": [
        {
           "label": "?? Kitchen ??",
           "deviceId": "E2:08:9C:04:A0:0B:B8:DB",
           "ignoreDevice": false,
           "enableBT": true,
           "brightnessStep": 10,
           "adaptiveLightingShift": 0,
           "overrideLogging": "default"
        }
     ]
    "lightDevices": [
        {
           "label": "T.V. Console",
           "deviceId": "E9:9D:A:C1:38:87:6B:CF",
           "ignoreDevice": false,
           "enableBT": true,
           "brightnessStep": 10,
           "adaptiveLightingShift": 0,
           "overrideLogging": "default"
        }
     ]
    "lightDevices": [
        {
           "label": "Dining Room Left",
           "deviceId": "11:27:D4:AD:FC:1B:29:27",
           "ignoreDevice": false,
           "enableBT": true,
           "brightnessStep": 10,
           "adaptiveLightingShift": 0,
           "overrideLogging": "default"
        }
     ] 
    "lightDevices": [
        {
           "label": "Dining Room Window",
           "deviceId": "CE:78:D4:AD:FC:1C:1E:B2",
           "ignoreDevice": false,
           "enableBT": true,
           "brightnessStep": 10,
           "adaptiveLightingShift": 0,
           "overrideLogging": "default"
        }
     ]
    "lightDevices": [
        {
           "label": "Dining Room Right",
           "deviceId": "51:B6:D4:AD:FC:1B:A4:85",
           "ignoreDevice": false,
           "enableBT": true,
           "brightnessStep": 10,
           "adaptiveLightingShift": 0,
           "overrideLogging": "default"
        }
     ]
    "lightDevices": [
        {
           "label": "Bedroom Mirror",
           "deviceId": "7C:63:A4:C1:38:4C:AD:6F",
           "ignoreDevice": false,
           "enableBT": true,
           "brightnessStep": 10,
           "adaptiveLightingShift": 0,
           "overrideLogging": "default"
        }
     ]
}

**Comment by bwp91** [comment]
Hi @col4bin 

Thanks for your detailed issue and sorry it's taken a while to reply.

Have you had any success with this in the meantime?

**Comment by bwp91** [comment]
Here is your config as it should be, remember to replace your username and password. Since your devices are bluetooth only, the API key has no effect and does not need to be in the config

```json
{
   "name": "Govee",
   "username": "utler@gmail.com",
   "password": "password",
   "platform": "Govee",
   "lightDevices": [
      {
         "label": "?? Kitchen ??",
         "deviceId": "E2:08:9C:04:A0:0B:B8:DB",
         "enableBT": true,
         "brightnessStep": 10
      },
      {
         "label": "T.V. Console",
         "deviceId": "E9:9D:A:C1:38:87:6B:CF",
         "enableBT": true,
         "brightnessStep": 10
      },
      {
         "label": "Dining Room Left",
         "deviceId": "11:27:D4:AD:FC:1B:29:27",
         "ignoreDevice": false,
         "enableBT": true,
         "brightnessStep": 10
      },
      {
         "label": "Dining Room Window",
         "deviceId": "CE:78:D4:AD:FC:1C:1E:B2",
         "enableBT": true,
         "brightnessStep": 10
      },
      {
         "label": "Dining Room Right",
         "deviceId": "51:B6:D4:AD:FC:1B:A4:85",
         "enableBT": true,
         "brightnessStep": 10
      },
      {
         "label": "Bedroom Mirror",
         "deviceId": "7C:63:A4:C1:38:4C:AD:6F",
         "enableBT": true,
         "brightnessStep": 10
      }
   ]
}
```

**Comment by col4bin** [comment]
Hey Ben!

Wow thank you for the reply here that is very kind of you man!

I will give this a whirl and see what I can get! Ill follow up for
conversations sake and if I had a question I would love to run it by you!

Thank you again; hope you had a good holiday last week.

Kind regards,
C
