### ISSUE TITLE
duplication

### ISSUE THREAD

**Issue by andrewsixten** [bwp91/homebridge-govee#350]
my devices are duplicating 

using homebridge 1.5.1

on raspberry pi 4

homebridge-govee v7.1.2

led light strips 
![2022-11-08_21-28-37](https://user-images.githubusercontent.com/89404855/200680059-6633e1db-d695-460d-a22e-f23d68fecb0c.jpg)

### Please paste any relevant logs below.

```

```
![2022-11-08_21-28-37](https://user-images.githubusercontent.com/89404855/200680119-8f634012-9b14-44bd-87d4-334d51546e55.jpg)

**Comment by ghost** [comment]
Remove them under "Homebridge Settings/Manage Cached Accessories"

**Comment by andrewsixten** [comment]
very kind. Thank you for replying!

**Comment by bwp91** [comment]
I would also check your homebridge config json to make sure you don’t (by mistake) have the plugin configured three times.

**Comment by andrewsixten** [comment]
Hi. 

My govee x7 light strips have now gone missing form HK  x3 in last 2 months.

Im having to reinstall the bridge
Is it do with updates?
They reappear when I connect a new bridge but I’m losing all my aotomation 

All my other 87 HK devices and 9 bridges are ok

Can you advise? 

Many thanks
