### ISSUE TITLE
39% on LED rope backlight 

### ISSUE THREAD

**Issue by StuartKicks** [bwp91/homebridge-govee#351]
### What issue do you have? Please be as thorough and explicit as possible.

Getting the 39% light bug when displaying in Home app, the model number is H61B2

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

 1.5.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

MACOS only installed today so latest Node I think

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

7.1.2 this is the only version I have ever installed 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H61B2

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @StuartKicks 

Please can you update to the beta version of the plugin to see if this is resolved?

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Thanks!

**Comment by StuartKicks** [comment]
Hi Ben

Fixed with Beta, thank you so much. Could I buy you a coffee for your hard work?

**Comment by bwp91** [comment]
Hi Stuart, glad all is fixed 👍🏻
And thank you for your support!
