### ISSUE TITLE
Unable to control H7130

### ISSUE THREAD

**Issue by qx1996** [bwp91/homebridge-govee#353]
### What issue do you have? Please be as thorough and explicit as possible.

When I try to control it on my iPhone Home app, it can not be turned on. On the log file, it says it was turned on, and after few seconds it turned off.
[11/10/2022, 6:18:26 AM] [Govee] [Smart Heater] current state [on].
[11/10/2022, 6:18:33 AM] [Govee] [Smart Heater] current state [off].

But actually, it never turns on.

I have correctly put Govee credentials and API key

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

Homebridge [v1.5.1]

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

BeagleBone/Green running Debian. Node.js 18.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-config-ui-x v4.50.1. This is the first version I used

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H7130

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @qx1996 

H7130 heater is a known issue, please see

https://github.com/bwp91/homebridge-govee/issues/335

still a work in progress!

at the time i assumed all the heater devices worked the same but seems the H7130 is different.

**Comment by qx1996** [comment]
Thanks for the quick reply. I have messaged you on discord.
