### ISSUE TITLE
Temp reporting for Heater?

### ISSUE THREAD

**Issue by wills721** [bwp91/homebridge-govee#354]
### What issue do you have? Please be as thorough and explicit as possible.
Hoobs

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

3

* Which version of Homebridge/HOOBS do you have?

4.2.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

16.8.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

7.1.3

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Heater

### Please paste any relevant logs below

WARNING[EnsleyRoom Heater] you should enable `tempReporting` in the config for this device.

Looking at Config docs I don't see this setting?

```

```

**Comment by bwp91** [comment]
Hi @wills721 

I don't know why this option is not appearing in the Hoobs UI config page.

If you are comfortable editing the config json directly, please use the following format:

```json
"heaterDevices": [
  {
    "label": "My Heater",
    "deviceId": "11:22:33:44:55:66:77:88",
    "tempReporting": true
   }
],
```

I will get in contact with HOOBS to see why this isn't appearing on the graphical config screen!

**Comment by bwp91** [comment]
if you clear the cache of your hoobs instance then the config item should appear in the ui now

**Comment by wills721** [comment]
Thanks.  That did it (but I don't know what tempReporting is :) )

**Comment by wills721** [comment]
If I clear the entire cache I have to re-setup Home all over again -- not your issue.  I normally just clear ind devices.

**Comment by bwp91** [comment]
Ah not i’m not talking about the accessory cache, i mean the hoobs ui cache, i think the option is in “hub settings”… it won’t affect your accessories
