### ISSUE TITLE
Cloud device is offline, unable to control via Home app 

### ISSUE THREAD

**Issue by FranciRoosters** [bwp91/homebridge-govee#357]
### What issue do you have? Please be as thorough and explicit as possible.

All of a sudden, I can't control the Govee DreamView through the Home app. No log errors, but the plugin settings show that the cloud of my DreamView devices is offline. Control through Govee app works fine, can't do anything through Home app. Everything worked fine until yesterday.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Config-Ui

* Which version of Homebridge/HOOBS do you have?

1.5.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

7.1.5

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Govee Dreamview.

**Comment by rmaes4** [comment]
Having similar issues with my H6008 and H5082. Started last night. No changes made on my end.

**Comment by oakstreetrec** [comment]
Same with H7132

**Comment by mperone** [comment]
Same with H7132

**Comment by CadLiara** [comment]
Same here. About 30 govee devices ranging from lights, to fans, etc. one by one starting yesterday night, they ceased to respond to voice commands or commands through the home app. They also show as "wifi off" in the govee app. (Bluetooth still works)

I noticed this in the logs:

11/17/2022, 7:21:13 AMGVEEGoveeWARNING[HTTP] could not use existing access token as getaddrinfo EAI_AGAIN app2.govee.com at Function.AxiosError.from (file:///var/lib/hoobs/gvee/node_modules/axios/lib/core/AxiosError.js:89:14).
11/17/2022, 7:21:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:21:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:22:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:22:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:23:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:23:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:24:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:24:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:25:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:25:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:26:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:26:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:27:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:27:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:28:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:28:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:29:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:29:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:30:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:30:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:31:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:31:43 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:32:13 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].
11/17/2022, 7:32:44 AMGVEEGoveeWARNING[HTTP] Unable to reach Govee, retrying in 30 seconds [login() - EAI_AGAIN].


From what I am seeing this is an issue on Govee's end (that they are aware of and working on) and not an issue with Hoobs/Homebridge nor the plugin. 

Check out this post from Govee for more info. 

https://www.govee.com/posts/115482

**Comment by rmaes4** [comment]
Just wanted to confirm that this did appear to be Govee's issue and it is now resolved for me.

**Comment by CadLiara** [comment]
After Govee's announcement that things were back up I was still encountering the "plugin site not responding" nonsense,  but a quick jaunt to the terminal and it is fixed. All good now. (crosses fingers and hopes Govee speeds up full LAN control)
