### ISSUE TITLE
H5080 Plugs Not Responding

### ISSUE THREAD

**Issue by tjridge** [bwp91/homebridge-govee#358]
### What issue do you have? Please be as thorough and explicit as possible.
Just the H5080 plugs are not responding to commands. It shows correctly on the Hombridge Logs, and control works through other apps. 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge

* Which version of Homebridge/HOOBS do you have?

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

7.1.5

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H5080

### Please paste any relevant logs below.

```

```

**Comment by jserinoc** [comment]
I have the same issue. All working except the plugs (H5080) as described by tjridge. 
Using Homebridge (with UI) - version 1.5
Plugin version homebridge-govee v7.1.5

**Comment by bwp91** [comment]
Can you unplug and plug back in to get them to connect to wifi again?
There were Govee issues yesterday and I don’t know whether this could have something to do with it.

Otherwise, can you turn on debug logging, use the govee app to turn on and off (disable bluetooth on your phone if the devices supports it) and show the logs that appear in homebridge?

**Comment by jserinoc** [comment]
I have plugged and unplugged them several times. 
Turned on debugging and followed your steps turning on and off with the Govee app...the log looks the same as if it was in regular non-debugging mode:

[11/18/2022, 9:08:30 AM] [Govee] [Christmas Tree] current state [on].
[11/18/2022, 9:08:31 AM] [Govee] [Christmas Tree] current state [off].

**Comment by tjridge** [comment]
Tried unplugging still have the same issue. Below are the error logs:

[18/11/2022, 21:26:03] [Govee] [Witch] cur
rent state [on].
[18/11/2022, 21:26:03] [Govee] [AWS] messa
ge event [{"proType" : 2, "sku" : "H5080"
"devi
ce":"35:28:7C:A6:B0:3F: 28:C4", "softversion
": "1.00.21"
"wifisoftversion":"1.00.21", "c
md": "status'
"type": 0, "transaction" : "v_166
[8824763642000](tel:8824763642000)", "pactrype" :1, "pactCode" :1, " state":{"onoff":0, "result": 1}, "op": { " comma
nd": [ "ghIABAAAAAAAAAAAAAAAAAAAALw=
"ghMAA
AAAgAAAAIAAAACAAAAAgIk=", "grQAAAAAgAAAAIAA
AACAAAAAgB4="
." grAAAQAAAAAAAAAAAAAAAAAAABS
="
"grAAAAAAAAAAAAAAAAAAAAAAABO="17}1.
[18/11/2022,
21:26:03] [Govee] [Witch] [AW
SI receiving update {"source": "AWS", "onoff
":o, "result" :1,
"commands": [ "ghIABAAAAAAAAA
AAAAAAAAAAALw=","ghMAAAAAgAAAAIAAAACAAAAAg
("GrAAA
Lk=", "grQAAAAAgAAAAIAAAACAAAAAgB4=", "GrAAA
QAAAAAAAAAAAAAAAAAAABs="
, "GrAAAAAAAAAAAAAA

**Comment by bwp91** [comment]
@tjridge could we message on discord?

**Comment by tjridge** [comment]
For sure. Let me know when. Sent from my iPhoneOn Nov 19, 2022, at 12:39 PM, Ben ***@***.***> wrote:﻿
@tjridge could we message on discord?

**Comment by bwp91** [comment]
Here’s a link
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
Fixed in beta version :)
