### ISSUE TITLE
39% Issue with H7022

### ISSUE THREAD

**Issue by jpiestrak** [bwp91/homebridge-govee#36]
### What issue do you have? Please be as thorough and explicit as possible.
Can't change brightness values to above 39%. When set to 100% in Govee app, logs show 39%

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
1

* Which version of Homebridge/HOOBS do you have?

* 1.0.17

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
* Raspberry Pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
2.7.3

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
* H7022

### Please paste any relevant logs below.

```
[17/01/2021, 23:21:04] [Govee] [Deck lights ] current brightness [39%].```
Note that they are actually at 100%

**Comment by bwp91** [comment]
Hi @jpiestrak 
I've just released v2.8.0 which should fix the brightness for your device.
Thanks for reporting this!
Ben
