### ISSUE TITLE
H6159_30D0 could not be updated as Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by houmark** [bwp91/homebridge-govee#360]
First thank you for your work on this. Really appreciate it!

### What issue do you have? Please be as thorough and explicit as possible.

My logs are flooding (about once a minute) with:

[11/18/2022, 4:01:51 PM] [Govee] [H6159_30D0] could not be updated as Cannot read properties of undefined (reading 'includes') at default.sendDeviceUpdate (file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1648:50).

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X.

* Which version of Homebridge/HOOBS do you have?

Latest

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Latest homebridge-govee v7.1.6.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6159_30D0 which is the only Govee device I have on the network.

Not sure what more I can provide to help, but here's a screenshot with the device config:

![CleanShot 2022-11-18 at 16 05 16@2x](https://user-images.githubusercontent.com/467330/202802403-4edbe1d4-3a1d-40e6-bbaa-7670aa399622.png)

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @houmark 

Since this is flooding the logs i figure you may have adaptive lighting turned on.

I need to make a fix for certain models including yours when choosing a colour temperature.

Will sort this out when I get home, but is an easy fix 👍🏻

Will let you know when an update is ready!

Thanks for alerting me to this

**Comment by houmark** [comment]
You are absolutely right. I can disable that for now and I'm happy to test a new version once you have it ready. No hurry, I can live without adaptive lightning :)

**Comment by bwp91** [comment]
> I can live without adaptive lightning

oh this is a relief to hear 😝🤣

**Comment by houmark** [comment]
Meanwhile just confirming errors went away when I disabled adaptive lightning for this light strip.

**Comment by bwp91** [comment]
For the moment you could rollback to v7.1.3 this should work. though i’ll fix within the next few hours 👍🏻

**Comment by bwp91** [comment]
Please check v7.1.7 :)

**Comment by houmark** [comment]
Smooth, no more errors with adaptive lighting :) Super fast. Thanks again! Have a nice weekend!
