### ISSUE TITLE
Fan Tile Does Nothing

### ISSUE THREAD

**Issue by gedeyenite** [bwp91/homebridge-govee#361]
Good Day.

Thank you SO MUCH for making this plugin. The Bridge seems to be working in HomeKit through HOOBS. I have each space heater split into tiles which show temp, fan, and light.  The fan tile doesn't do anything. Is there (a) to make it work or (b) to make it not show up? It will just confuse my spouse if it doesn't do anything.

**Comment by bwp91** [comment]
Hi @gedeyenite 

Please tell your spouse that the fan accessory as part of the heater does not do anything at the moment!

The heater accessory is still a bit under construction, I plan to use this fan to enable switching between the low medium and high modes in the govee app 👍🏻

**Comment by gedeyenite** [comment]
Thank you for the quick response.
Thanks for the update. Having a heater controlled by HK is awesome.
Do you have a way I can throw you some money?

**Comment by gedeyenite** [comment]
NVM! I see it below.

**Comment by bwp91** [comment]
Would be cool to message on discord if you are on there?
https://discord.gg/cMGhNtZ3tW
