### ISSUE TITLE
Govee API quota limits reached

### ISSUE THREAD

**Issue by justin-bond** [bwp91/homebridge-govee#363]
### What issue do you have? Please be as thorough and explicit as possible.
Been getting the error `Govee API quota limits reached` for over a week even though I only have 2 devices and default settings. Not sure how my quota is being reached. Also tested the GET devices API call in Postman and shows that I have over 9000 daily calls left and I am able to see the devices in the return payload.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge UI-X v4.50.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi, Node v18.12.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v7.1.9, no it was happening before the upgrade

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
I only have 2 devices that were showing up before, but since this error they are no longer showing
`H6198` and `H6199`

### Please paste any relevant logs below.

```
[11/24/2022, 6:03:04 PM] [Govee] Initializing Govee platform...
[11/24/2022, 6:03:04 PM] [Govee] Initialising plugin v7.1.9 | System linux | Node v18.12.1 | HB v1.5.1 | HAPNodeJS v0.10.4...
[11/24/2022, 6:03:04 PM] [Govee] Plugin initialised. Setting up accessories....
[11/24/2022, 6:03:04 PM] Homebridge v1.5.1 (HAP v0.10.4) (Homebridge 4124) is running on port 51907.
[11/24/2022, 6:03:06 PM] [Govee] [LAN] client enabled and found 0 device(s).
[11/24/2022, 6:03:07 PM] [Govee] [HTTP] client enabled and found 2 device(s).
[11/24/2022, 6:03:07 PM] [Govee] [AWS] client enabled.
[11/24/2022, 6:03:07 PM] [Govee] Govee API quota limits reached, will try again in 10 minutes...
[11/24/2022, 6:03:07 PM] [Govee] Unfortunately the plugin will not work until fully initialised.
```

**Comment by DorChris** [comment]
same issues...

logs:
```
[27.11.2022, 08:24:23] [Govee] Govee API quota limits reached, will try again in 10 minutes...
[27.11.2022, 08:24:23] [Govee] Unfortunately the plugin will not work until fully initialised.
[27.11.2022, 08:34:24] [Govee] Still receiving 429 [rate limit exceeded], trying again in 10 minutes...
[27.11.2022, 08:44:25] [Govee] Still receiving 429 [rate limit exceeded], trying again in 10 minutes... 
```

config file:
```
        {
            "name": "Govee",
            "username": "#####",
            "password": "#####",
            "apiKey": "71ba721d-####-####-####-############",
            "debug": false,
            "apiRefreshTime": 300,
            "bleDisable": true,
            "offlineAsOff": true,
            "lightDevices": [
                {
                    "label": "Schrankwand Oben",
                    "deviceId": "",
                    "customIPAddress": "10.20.0.1"
                },
                {
                    "label": "Sofabeleuchtung",
                    "deviceId": "",
                    "customIPAddress": "10.20.0.2"
                },
                {
                    "label": "Kleiderschrank Hinten",
                    "deviceId": "",
                    "customIPAddress": "10.20.0.50"
                },
                {
                    "label": "Bett",
                    "deviceId": "",
                    "customIPAddress": "10.20.0.51"
                }
            ],
            "platform": "Govee"
        }
```

**Comment by bwp91** [comment]
Hey guys.

I know this isn’t really solving the issue here. But the plugin is in a state now where if you have your govee credentials in the config, you don’t actually need your API key.

The API doesn’t offer anything more than the functionality you can get from having the credentials there instead.

**Comment by justin-bond** [comment]
@bwp91 Didn't change anything in my configs and yesterday the error is no longer showing and my devices are now working appropriately. Not sure what changed, but everything is working now.

**Comment by DorChris** [comment]
Hey guys,
I have also not made any settings...
however, the plugin does not always seem to be able to address the API.
I was able to control the devices around 5 pm without any problems. When I just came home, it throws me again errors in the log.
`[29.11.2022, 22:44:32] [Govee] Govee API quota limits reached, will try again in 10 minutes...
[29.11.2022, 22:44:32] [Govee] Unfortunately the plugin will not work until fully initialised.`

**Comment by DorChris** [comment]
> I know this isn’t really solving the issue here. But the plugin is in a state now where if you have your govee credentials in the config, you don’t actually need your API key.
> 
> The API doesn’t offer anything more than the functionality you can get from having the credentials there instead.

Then I will now disable the API and only try via the credentials.

I have given my H619A a fixed IP address from my DHCP server and configured the LAN control. Have now not yet found out if the product is supported, but I have prepared it for now.
