### ISSUE TITLE
BLE connection slow due to connect/disconnect - use "HTTP:?

### ISSUE THREAD

**Issue by polycat33** [bwp91/homebridge-govee#366]
As stated in the support pages, only a small number of BLE connections are available so the plugin connects via BLE when it needs to, and disconnects when it's done. This makes changes requested in the Home app very slow. 

Logs indicated the HTTP client found a device, can I use that instead? How do I set it up? 

[26/11/2022, 21:12:52] [Govee] [HTTP] retrieved access token from cache.
[26/11/2022, 21:12:53] [Govee] [HTTP] client enabled and found 1 device(s).
[26/11/2022, 21:12:53] [Govee] [AWS] client enabled.
[26/11/2022, 21:12:53] [Govee] [AWS] connect event.
[26/11/2022, 21:12:53] [Govee] [API] client enabled and found 0 device(s).

**Comment by bwp91** [comment]
Hi @polycat33 

which device model is this?

**Comment by polycat33** [comment]
This is a light strip (H017A?). I'm running Homebridge on a Raspberry Pi, newest version of Homebridge and plugin.

**Comment by bwp91** [comment]
Knowing the H number would be helpful to answer properly

**Comment by polycat33** [comment]
H617A1D1

**Comment by bwp91** [comment]
I see, this model is bluetooth only.

The HTTP client is used to login and obtain a device list, for your model it is used to pull some basic details about the device. It cannot be used to control the device.

Your model can only be controlled by bluetooth from the plugin. However you said

> This makes changes requested in the Home app very slow.

From user feedback in the past, the bluetooth control is normally pretty responsive? Are you finding it slow?

**Comment by polycat33** [comment]
Yes, quite slow, and also unreliable... seems half the time I try to turn it off it can't be found. Attached a lot of fresh reboot plus power-on request, power-off request [failed], power off request [suceeded].
[homebridge.log-4.txt](https://github.com/bwp91/homebridge-govee/files/10099453/homebridge.log-4.txt)

**Comment by bwp91** [comment]
do you have any other homebridge plugin which utilises bluetooth?

**Comment by polycat33** [comment]
I don't think so, but attached a screen shot just in case I'm wrong. 
<img width="1666" alt="Screen Shot 2022-11-27 at 3 37 22 PM" src="https://user-images.githubusercontent.com/67032491/204165818-9158c5ff-7a5c-4284-9700-904a7c045db8.png">

**Comment by bwp91** [comment]
switchbot uses bluetooth.

i have never been able to confirm this, but i have a feeling that other plugins that use bluetooth can interfere with the bluetooth connection of a plugin.

do you have many switchbot devices - would it be feasible for you to disable that plugin (which would mean these devices would be removed from homekit) and then seeing if this improves things for govee?

I don't mean this as a permanent solution - just out of interest.

**Comment by polycat33** [comment]
I disabled and restarted, tried on/off a bunch, no issue, then tried dimming a couple times and got same error. 
[homebridge.log-6.txt](https://github.com/bwp91/homebridge-govee/files/10099475/homebridge.log-6.txt)

Attached a log, it's way at the bottom, need to trash it and start over. :P

**Comment by polycat33** [comment]
What item features are needed to utilize the other connection type(s)? It seems the only other option for light strips is IR. 

EDIT: I found one with WiFi, is that how to use the other connection type(s)?

**Comment by bwp91** [comment]
I have made a pretty robust table here of which models support which connection types

https://github.com/bwp91/homebridge-govee/wiki/Supported-Devices

In your case your model is H617A1D1, so simply just look at the first 5 characters, ie, yours is the H617A.

_If_ you are looking at getting a new model, would definitely recommend the LAN supported models. And it's cyber monday tomorrow so you may get a good deal somewhere!

The bluetooth connection for some reason works very well for some users but not very well for other users.

Just another suggestion, is your raspberry pi firmware/software up to date? You can run these commands to update

```
sudo apt update
sudo apt full-upgrade
```
