### ISSUE TITLE
H5083 not responding

### ISSUE THREAD

**Issue by WhatTheKJ** [bwp91/homebridge-govee#371]
The smart outlet H5083 doesn’t seem to be responding. My heaters are responding just fine from Homebridge and Home but the outlets only seem to work from the Govee app. Looks like node.js needs to be updated but this instance of Homebridge is on a raspberry pi so I don’t believe I can update that right? Also Homebridge is running the latest version.
![BF85DA35-C9E8-43C1-9996-C75392334E6D](https://user-images.githubusercontent.com/28029584/204926861-651698ce-b566-45c5-964a-1976d70041fc.jpeg)

**Comment by lakeshow20** [comment]
I am having the same issue. This is related to the AWS connection issue mentioned prior. H5083 is only able to connect via AWS via the support doc. You will probably see AWS close event  | AWS reconnect event throughout the logs.

**Comment by bwp91** [comment]
Closing, please see https://github.com/bwp91/homebridge-govee/issues/367
