### ISSUE TITLE
Oscillation button missing for grouped Heater accessories 

### ISSUE THREAD

**Issue by addisonjames** [bwp91/homebridge-govee#374]
### What issue do you have? Please be as thorough and explicit as possible.
Missing Oscillation button when accessories are grouped. 
Using Smart Heater H7130. The plugin creates 2 accessories, and groups them by default. When they are grouped, there is no way to control Oscillation. 
If I ungroup them, the "fan" device gains an oscillation toggle. 
But when grouped, there is no option, even when you browse to the separate fan accessory.
(There is an Oscillation control when creating an automation, even if accessories are grouped.)

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge

* Which version of Homebridge/HOOBS do you have?
1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi
Node.js v16.16.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
7.3.0. This is my first time using the plugin so not sure if the issue existed before. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Govee Smart Heater H7130

Thank you!

**Comment by topshelf510** [comment]
Same experience. You can toggle the Oscillation and Child Lock by click into the grouped accessories and then selecting the thermostat and then scroll down. A bit much to get to but I'm sure they'll eventually make it easier :smile:
