### ISSUE TITLE
Govee H5075 show as 0% humidity 32 degree only. deleted plug in, still there.

### ISSUE THREAD

**Issue by todesto** [bwp91/homebridge-govee#38]
### What issue do you have? Please be as thorough and explicit as possible.

I installed plug in for govee H5075 and it shows as 0% humidity and 32 degree and it doesn't change. So I uninstalled plug in, but it still shows up in homekit.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Hoobs

* Which version of Homebridge/HOOBS do you have?

3.2.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Plug in govee
I didn't upgrade. it was working fine, then I had to reboot Hoobs, then this.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H5075

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @todesto 

Accessories are sometimes not removed when uninstalling their associated plugins. Please try searching 'how to remove an accessory from the HOOBS cache'  as other users may have found ways to do this for example google, reddit, hoobs forums. A HOOBS reset is most likely needed to remove unwanted accessories.

Unfortunately this is something my plugin cannot help with.

Thanks
