### ISSUE TITLE
Change Homekit device Type

### ISSUE THREAD

**Issue by solbadguy2010** [bwp91/homebridge-govee#383]
* **Please explain your feature request in a one or two sentences.**
I use the plugin only to switch my Ambilight on or off with the TV. Since the device appear as a light in homekit it reacts to „hey siri, switch on the light in the living room“. Would love to change the type to „switch“.

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Govee devices that this relates to?**
H6199 and other ambilights

* **Anything else?**

**Comment by bwp91** [comment]
I am sure this is something I can do. Will get back to you :)

**Comment by bwp91** [comment]
Please install the beta of the plugin. And then use the configuration to change the "Show As" type of your lights to a switch.

**Comment by solbadguy2010** [comment]
Tested. Works perfectly as i imagined it :-)
Great job! Thank you!

**Comment by solbadguy2010** [comment]
Hi, is the heavy logging in the Homebrige Log part of the beta? Can i disable it?

**Comment by farkis644** [comment]
I have no idea if I have the beta or not. Sent from my iPhoneOn Dec 16, 2022, at 3:06 AM, solbadguy2010 ***@***.***> wrote:﻿
Hi, is the heavy logging in the Homebrige Log part of the beta? Can i disable it?

**Comment by solbadguy2010** [comment]
@farkis644 Bro, really? :-D

**Comment by solbadguy2010** [comment]
@bwp91 Can you help me?

**Comment by farkis644** [comment]
> @farkis644 Bro, really? :-D

Ha. My bad. Responsed via email by mistake. Thought I was replying to the support request I opened. : )

**Comment by solbadguy2010** [comment]
@farkis644 Happens :-D
Was a little bit wondering about the answer :-)

**Comment by bwp91** [comment]
Beta versions force enable debug logging.
makes it a lot easier for me when debugging with users.
just released a new version which you should be able to update to :)

**Comment by solbadguy2010** [comment]
Understand. Thanks again for the great support
