### ISSUE TITLE
H6054 Brightness issue

### ISSUE THREAD

**Issue by gradyg21** [bwp91/homebridge-govee#385]
### What issue do you have? Please be as thorough and explicit as possible.

H6054 Brightness issue -- HomeKit 100% brightness is Govee (actual) 35% brightness, HomeKit 50% is Govee (Actual) 13%, etc.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI

* Which version of Homebridge/HOOBS do you have?

v.1.6.0, same bug on older versions

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

macOS Monterey, node.js version v.16.16.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Not sure if caused by an update, but the bug has remained over a few updates (and a full reinstall of homebridge)

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6054 only

### Please paste any relevant logs below.

```
[12/11/2022, 11:57:39 AM] [Govee] [Grady Light Bars] current brightness [100%].
[12/11/2022, 11:57:40 AM] [Govee] [Grady Light Bars] current brightness [100%].

This is Homebridge reporting 100% brightness. Govee App shows 35% at this moment, and can be turned onto 100%
```

**Comment by bwp91** [comment]
Hi @gradyg21 

Can you use the plugin settings to enable debug logging and get me the the logs that appear when using the govee app to turn the brightness to around 20%?

**Comment by gradyg21** [comment]
[12/11/2022, 1:05:46 PM] [Govee] [Grady Light Bars] current brightness [68%]
That's with Debug Logging on, setting brightness  in the Govee app to 22%

iOS home app also shows 68%.

**Comment by gradyg21** [comment]
Also, thanks for your quick response!

**Comment by bwp91** [comment]
There should be much more logging that appears with debug logging on.
Please use the plugins settings to enable this, not the global homebridge debug mode.

There should be logging like in this post:
https://github.com/bwp91/homebridge-govee/issues/356

**Comment by gradyg21** [comment]
Whoops, turned on the toggle but didn't see the save button. Sorry about that, dumb mistake. 

Here's what happens when I set the lights up to 100% and then down to 18% in the Govee app.

**Comment by gradyg21** [comment]
```
[AWS] message event [{"proType":2,"pactType":1,"pactCode":1,"sku":"H6054","device":"23:8A:A4:C1:38:63:5A:11","softVersion":"1.09.01","hardVersion":"1.00.00","cmd":"status","type":0,"transaction":"1234567890","cmdVersion":0,"state":{"connected":"true","subOnOff":[1,1],"onOff":1,"wifiSoftVersion":"1.01.29","wifiHardVersion":"1.00.01","brightness":254,"colorTemInKelvin":0,"color":{"r":245,"g":242,"b":255},"mode":4},"op":{"opcode":"all","modeValue":["qgUEFgAAAAAAAAAAAAAAAAAAAL0="],"sleepValue":["qhEAHg8PAAAAAAAAAAAAAAAAAKU="],"wakeupValue":["qhL/ZAAAgAoAAAAAAAAAAAAAAKk="],"timerValue":["qgr/AAAAgAAAAIAAAACAAAAAgF8="]}}].
[12/12/2022, 9:14:00 AM] [Govee] [Grady Light Bars] [AWS] receiving update {"source":"AWS","connected":"true","subOnOff":[1,1],"onOff":1,"wifiSoftVersion":"1.01.29","wifiHardVersion":"1.00.01","brightness":254,"colorTemInKelvin":0,"color":{"r":245,"g":242,"b":255},"mode":4}.
[12/12/2022, 9:14:00 AM] [Govee] [Grady Light Bars] current brightness [100%].
[12/12/2022, 9:14:02 AM] [Govee] [AWS] message event [{"proType":2,"pactType":1,"pactCode":1,"sku":"H6054","device":"23:8A:A4:C1:38:63:5A:11","softVersion":"1.09.01","hardVersion":"1.00.00","cmd":"status","type":0,"transaction":"1234567890","cmdVersion":0,"state":{"connected":"true","subOnOff":[1,1],"onOff":1,"wifiSoftVersion":"1.01.29","wifiHardVersion":"1.00.01","brightness":58,"colorTemInKelvin":0,"color":{"r":245,"g":242,"b":255},"mode":4},"op":{"opcode":"all","modeValue":["qgUEFgAAAAAAAAAAAAAAAAAAAL0="],"sleepValue":["qhEAHg8PAAAAAAAAAAAAAAAAAKU="],"wakeupValue":["qhL/ZAAAgAoAAAAAAAAAAAAAAKk="],"timerValue":["qgr/AAAAgAAAAIAAAACAAAAAgF8="]}}].
[12/12/2022, 9:14:02 AM] [Govee] [Grady Light Bars] [AWS] receiving update {"source":"AWS","connected":"true","subOnOff":[1,1],"onOff":1,"wifiSoftVersion":"1.01.29","wifiHardVersion":"1.00.01","brightness":58,"colorTemInKelvin":0,"color":{"r":245,"g":242,"b":255},"mode":4}.
[12/12/2022, 9:14:02 AM] [Govee] [Grady Light Bars] current brightness [58%].
```

**Comment by bwp91** [comment]
I have never seen this property before in a notification `"subOnOff":[1,1]`

Do you have these lights in some special mode or maybe linked with another light or _anything_ slightly out of the ordinary?

**Comment by gradyg21** [comment]
No, nothing that comes to mind. They are not linked to anything else in HomeKit or the Govee app. I'm racking my brain, but I can't see any factor out of an ordinary setup with this plugin.

**Comment by bwp91** [comment]
Can you show me a screenshot of the current state of this device in the govee app?

**Comment by gradyg21** [comment]
![IMG_2075](https://user-images.githubusercontent.com/26560257/207115910-5cec0300-6bce-4337-a04d-775b0ca35c79.PNG)
![IMG_2076](https://user-images.githubusercontent.com/26560257/207115918-210822c4-f615-4359-a928-f25ef25e3b35.PNG)
![IMG_2074](https://user-images.githubusercontent.com/26560257/207115922-727fb18f-10b4-4c23-a05e-5abff6d9afc9.PNG)
![IMG_2077](https://user-images.githubusercontent.com/26560257/207115928-ef7ee2b4-a599-4a11-9730-5ba60b533cd9.PNG)

**Comment by bwp91** [comment]
If you switch to the “color” tab in the govee app, and choose a colour there, does the brightness appear correctly in the home app?

**Comment by gradyg21** [comment]
It does not, unfortunately. Same 100->35% behaviour.

**Comment by bwp91** [comment]
does choosing a colour from the home app change to the colour correctly on the device?

**Comment by gradyg21** [comment]
Oh interesting, no it doesn’t. The color stays as whatever it was last set as in the Govee app. I don’t get any error or ‘no response’ from the home app.

**Comment by bwp91** [comment]
Can you update to the beta version of the plugin to see if this fixes things?

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by gradyg21** [comment]
Updating to the beta at this moment, will update once it's done!

**Comment by gradyg21** [comment]
Good news! Everything is working! Both colour change and brightness go through correctly! Thanks my friend. Two questions: first, I noticed you wrote colour instead of color. Any chance you're a fellow canadian? Second, what is the best way to donate a few dollars as thanks?

**Comment by gradyg21** [comment]
I know you have several spots (patreon, PayPal) but I ask so I can choose whatever is most convenient/lowest fee for you

**Comment by bwp91** [comment]
> first, I noticed you wrote colour instead of color

I simply wrote color as it were in your screenshot. Trust me it was hard since I am from the UK and (sure you know) here it is spelt **correctly** as colour!

> Second, what is the best way to donate a few dollars

Kofi is a nice one. Obviously, anything is greatly appreciated although I never expect anything in return for immediate help.

Just glad this is working well for you now!

**Comment by gradyg21** [comment]
I sent through GitHub, I don't have a PayPal so seemed like the best option. PayPal aside, Kofi does seem like a nice platform, good to know for future. Thanks again!

**Comment by bwp91** [comment]
Pleasure! And thank you!

**Comment by gradyg21** [comment]
No worries man :) I'll close the issue now.
