### ISSUE TITLE
Govee Plugin

### ISSUE THREAD

**Issue by chuckktn** [bwp91/homebridge-govee#391]
I am trying to figure out how to set the mode on the Govee plugin.  When I click on custom scane/mode it doesn't give me fields to put in the mode codes I have.  I made sure the AWS and BLE boxes were not checked.

Any suggestions?  You can see on screenshot that it just says read more... 

<img width="769" alt="Screenshot 2022-12-17 at 8 30 41 PM" src="https://user-images.githubusercontent.com/76010509/208278555-763b43cf-833c-4736-aec3-767d8cbe39f8.png">

**Comment by bwp91** [comment]
This does not look long enough for a device id, please get it from the “my devices” tab of the config screen

**Comment by bwp91** [comment]
out of interest, where did you get what you have currently from?
