### ISSUE TITLE
H61E1 - Can't change color/brightness

### ISSUE THREAD

**Issue by HeyWatchOutDude** [bwp91/homebridge-govee#392]
Hi,

I can't change the color/brightness of my Govee M1 LED strip (H61E1).

So I only can turn on/off the LED strip.

Homebridge is up-to-date.
Plugin is up-to-date.
Govee Firmware is up-to-date.

Any idea what is causing that kind of issue?

Note: In the logs I can clearly see that the color adjustment where done - no error.

**Comment by bwp91** [comment]
Hi @HeyWatchOutDude 

This may seem a strange request but can you use the home app to try and change the brightness between 0 and 25% and see if this kinda scales to the device brightness of 0 to 100% and does this work?

**Comment by HeyWatchOutDude** [comment]
I found out that the "brightness control" kinda works ... when I set it to "30%" in the "Apple Home App" it jumps up to 39% ?? Kinda weird. 

Furthermore I have set the brightness to 100% in the "Govee App", to get the full "brightness control" in "Apple Home".

Colour adjustment still doesn't work.

**Comment by bwp91** [comment]
Yes but what I asked, does this work?

**Comment by bwp91** [comment]
Can you update to beta version of the plugin and check if now working?

**Comment by HeyWatchOutDude** [comment]
I can confirm that

**Comment by HeyWatchOutDude** [comment]
Looking good, I'm also able to change the colour through "Apple Home" app :) 

What was the issue?

I noticed that the adjustments are kinda laggy, check the video out. (Look at the numbers (%) they are constantly changing without an input)

https://imgur.com/a/f86M490

**Comment by HeyWatchOutDude** [comment]
H61A2 - Same issue can't change color and brightness via Apple Home App. (Plugin Version 7.7.0)


H61E1 - Is still working.

**Comment by Damiexxi** [comment]
I'm having a similar issue with H615C...when I try to change to colors it doesn't change and goes to a orange color though matter what I choose and the brightness shows 39% all the time. I have other light strip and they work fine H6159 & H6141...tried the Beta and no luck

**Comment by bwp91** [comment]
@HeyWatchOutDude @Damiexxi 

Please try the newest beta

**Comment by Damiexxi** [comment]
> @HeyWatchOutDude @Damiexxi
> 
> Please try the newest beta

YESSSSS....it's working 
you are awesome bro thanks

**Comment by HeyWatchOutDude** [comment]
> @HeyWatchOutDude @Damiexxi 
> 
> 
> 
> Please try the newest beta 

Is working, thanks!

**Comment by RobertN82** [comment]
I'm having the same issue with the H601A.
Brightness goes to 39% max and cannot change colors.
Running homebridge-govee v7.9.1, HomeBrige up to date, Govee up to date.
