### ISSUE TITLE
yet another BLE problem

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-govee#393]
Homebridge updated 
Govee version v7.6.1-beta.0 **and** v7.6.0

```
[19/12/2022, 14:27:57] [Govee LAN] [BLE] disabling client as btClient.on is not a function at new default (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/ble.js:18:14).
>>
>>
>>
[19/12/2022, 14:27:57] [Govee LAN] [BLE] sync for thermo-hygrometer sensors disabled as required hardware/packages not available.
```

**Comment by gnthr** [comment]
Here the same.
Homebridge v1.6.0
Govee v6.7.0

**Comment by bwp91** [comment]
@JanLp @gnthr 
please can you confirm your versions of node?

**Comment by gnthr** [comment]
> 

Node v18.12.1

**Comment by bandundu** [comment]
Hi I am getting the same error.

System:
Raspberry Pi 4 Model B Rev 1.4

OS:
Raspbian GNU/Linux 10 (buster)


```
[20/12/2022, 09:51:00] [Govee] [BLE] disabling client as btClient.on is not a function at new default (file:///usr/lib/node_modules/homebridge-govee/lib/connection/ble.js:18:14).
[20/12/2022, 09:51:00] [Govee] [H6181_48BF] will be visible but uncontrollable as BLE not available.
[20/12/2022, 09:51:00] [Govee] [H6181_48BF] [0x04,0x09] is not a valid code - please update with a new code from the log that starts with 33.
[20/12/2022, 09:51:00] [Govee] [H6181_48BF] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[20/12/2022, 09:51:00] [Govee] [H6181_48BF] initialised with id [55:B9:A4:C1:38:AB:48:BF] [H6181].
[20/12/2022, 09:51:02] [Govee] ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW
[20/12/2022, 09:51:15] [Govee] [H6181_48BF] could not be updated as no connection method available at file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1855:13.
[20/12/2022, 09:51:20] [Govee] [H6181_48BF] could not be updated as no connection method available at file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1855:13.
```

with Node v. 18.12.1

During installation i get the same error as state in the other open issue:: https://github.com/bwp91/homebridge-govee/issues/394

**Comment by bwp91** [comment]
Please follow here:
https://github.com/abandonware/noble/issues/282#issuecomment-1359000503

This is an issue that has cropped up with a new version of the bluetooth package the plugin uses.
As soon as an update to this is available, i will make a new release of the plugin 🙂

**Comment by FlorinFrance** [comment]
24/12/2022 14:37:06HOOBSGoveeWARNING[Outdoor Strip Lights] could not be updated as no connection method available at file:///var/lib/hoobs/hoobs/node_modules/homebridge-govee/lib/platform.js:1855:13.
24/12/2022 14:37:11HOOBSGoveeWARNING[Outdoor Strip Lights] could not be updated as no connection method available at file:///var/lib/hoobs/hoobs/node_modules/homebridge-govee/lib/platform.js:1855:13.



hello, same error.
thx for your effort !

**Comment by bandundu** [comment]
> Hi I am getting the same error.
> 
> System: Raspberry Pi 4 Model B Rev 1.4
> 
> OS: Raspbian GNU/Linux 10 (buster)
> 
> ```
> [20/12/2022, 09:51:00] [Govee] [BLE] disabling client as btClient.on is not a function at new default (file:///usr/lib/node_modules/homebridge-govee/lib/connection/ble.js:18:14).
> [20/12/2022, 09:51:00] [Govee] [H6181_48BF] will be visible but uncontrollable as BLE not available.
> [20/12/2022, 09:51:00] [Govee] [H6181_48BF] [0x04,0x09] is not a valid code - please update with a new code from the log that starts with 33.
> [20/12/2022, 09:51:00] [Govee] [H6181_48BF] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
> [20/12/2022, 09:51:00] [Govee] [H6181_48BF] initialised with id [55:B9:A4:C1:38:AB:48:BF] [H6181].
> [20/12/2022, 09:51:02] [Govee] ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW
> [20/12/2022, 09:51:15] [Govee] [H6181_48BF] could not be updated as no connection method available at file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1855:13.
> [20/12/2022, 09:51:20] [Govee] [H6181_48BF] could not be updated as no connection method available at file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1855:13.
> ```
> 
> with Node v. 18.12.1
> 
> During installation i get the same error as state in the other open issue:: #394

With the new update v7.7.0 everything is working fine again! Thanks for the quick action and merry christmas to you all.

**Comment by bwp91** [comment]
> > Hi I am getting the same error.
> > System: Raspberry Pi 4 Model B Rev 1.4
> > OS: Raspbian GNU/Linux 10 (buster)
> > ```
> > [20/12/2022, 09:51:00] [Govee] [BLE] disabling client as btClient.on is not a function at new default (file:///usr/lib/node_modules/homebridge-govee/lib/connection/ble.js:18:14).
> > [20/12/2022, 09:51:00] [Govee] [H6181_48BF] will be visible but uncontrollable as BLE not available.
> > [20/12/2022, 09:51:00] [Govee] [H6181_48BF] [0x04,0x09] is not a valid code - please update with a new code from the log that starts with 33.
> > [20/12/2022, 09:51:00] [Govee] [H6181_48BF] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
> > [20/12/2022, 09:51:00] [Govee] [H6181_48BF] initialised with id [55:B9:A4:C1:38:AB:48:BF] [H6181].
> > [20/12/2022, 09:51:02] [Govee] ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW
> > [20/12/2022, 09:51:15] [Govee] [H6181_48BF] could not be updated as no connection method available at file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1855:13.
> > [20/12/2022, 09:51:20] [Govee] [H6181_48BF] could not be updated as no connection method available at file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1855:13.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with Node v. 18.12.1
> > During installation i get the same error as state in the other open issue:: #394
> 
> With the new update v7.7.0 everything is working fine again! Thanks for the quick action and merry christmas to you all.

Great! merry christmas

**Comment by ghost** [comment]
> @JanLp @gnthr
> please can you confirm your versions of node?

Thanks for the update...and Merry Christmas to you

**Comment by bwp91** [comment]
is working now?

**Comment by ghost** [comment]
> is working now?

I find it a bit difficult to contribute with troubleshooting as I have no other bluetooth devices than the H5075.
But I haven't experienced any problems and they update humidity and temperature correctly in HomeKit

**Comment by bwp91** [comment]
> > is working now?
> 
> I find it a bit difficult to contribute with troubleshooting as I have no other bluetooth devices than the H5075. But I haven't experienced any problems and they update humidity and temperature correctly in HomeKit

Excellent. To be honest i don’t have many devices either - just the H5075 and a light device. All comes down to a collective effort with different users 🙂

**Comment by ghost** [comment]
homebridge-govee v7.9.3 > the same goes for the latest beta
Node.js Version v18.14.2

```
[26/02/2023, 23:29:02] [Govee] [BLE] disabling client as required hardware/packages not available.
... 
[26/02/2023, 23:29:02] [Govee] [BLE] sync for thermo-hygrometer sensors disabled as required hardware/packages not available.
```

**Comment by krozgrov** [comment]
Same issue as @JanLp.

**Comment by bwp91** [comment]
hey all please try reinstalling

**Comment by ghost** [comment]
> hey all please try reinstalling

Solves the problem 🙂
