### ISSUE TITLE
H6182 39% and colour changing issue

### ISSUE THREAD

**Issue by ashleymoat** [bwp91/homebridge-govee#4]
**What issue do you have? Please be as thorough and explicit as possible.**
[Device Name] could not be updated and its status will be reverted soon. Error: Request failed with status code 400.
I am getting this error on Govee H6182. Also doesn't change colour every time correctly. Sticks on 39% alot of time too
...

**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge

...

Which version of Homebridge/HOOBS do you have?
1.1.6
...

Which version of this plugin (homebridge-govee) do you have?
2.0.0
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.
[10/17/2020, 4:48:15 PM] [Govee] [Lounge TV] updating hue to [306°] and sat to [0%].
[10/17/2020, 4:48:33 PM] [Govee] [Lounge TV] updating hue to [358°] and sat to [0%].
[10/17/2020, 4:48:36 PM] [Govee] [Lounge TV] could not be updated and its status will be reverted soon. Error: Request failed with status code 400.
[10/17/2020, 4:48:36 PM] [Govee] [Lounge TV] could not be updated and its status will be reverted soon. Error: Request failed with status code 400.
...

**Comment by bwp91** [comment]
Hi, this should now be fixed in v2.0.1.
Thanks for bringing this to my attention.

**Comment by ashleymoat** [comment]
Thats quick. Thank you. That looks to have worked.

Sometimes the 6 colour options in homekit dont show the correct colour, but minor issue as majority of time I have as white anyway.

**Comment by bwp91** [comment]
Unfortunately there is always the potential for a mismatch in colour between the (device/govee app) and Home app.
These two use two different colour systems, so there is a lot of conversion that happens in the plugin.
In fact there is a normally less of mismatch when the colours chosen are more to the *outside* of the colour wheel.
But I'm glad you're no longer receiving the error 400 with the brightness and for this reason I am going to go ahead and close this issue.
Thanks again
