### ISSUE TITLE
Govee lightstrip H6199 not responding in Homekit

### ISSUE THREAD

**Issue by RELAXUJ** [bwp91/homebridge-govee#400]
Hi, 

I updated the Govee plugin to v7.7.0 and my lightstrip is showing as not reposning in the homekit app, while being online in both Govee and Hombridge UI.

I run freshly installed Homebridge BC8F on Raspbian GNU/Linux Bullseye (11) with Node.js  v18.12.1

My device details: 
Govee lightstrip, model H6199

any troubleshooting ideas out there? 
thanks

**Comment by bwp91** [comment]
Can you show logs from the plugin initialising? Basically from “restarting” to the “plugin setup complete” line

**Comment by RELAXUJ** [comment]
Hello there, 
let me know if you were able to find it. 
[770.txt](https://github.com/bwp91/homebridge-govee/files/10300074/770.txt)

**Comment by bwp91** [comment]
Okay this looks okay.

Next can you show logs that appear when trying to control the device from the home app?

**Comment by RELAXUJ** [comment]
I do see status change in the terminal of homebridge when i cotnroll the light strip with Govee app. 

But theres no action I can do with Home app, although it is visible in the home app it is not responding.

**Comment by bwp91** [comment]
yes but when you control from the home app, logs will appear in the homebridge log detailing why it failed, this is what i am hoping to see

**Comment by RELAXUJ** [comment]
when i installed the previous version of the govee plugin yesterday, it changed my mode to color in Govee native app. I noticed the Colours do not sync with the video, so I changed the mode to Video In Govee app. It might be that the problem started there and not with the update of the plug in. Not sure.

**Comment by RELAXUJ** [comment]
> yes but when you control from the home app, logs will appear in the homebridge log detailing why it failed, this is what i am hoping to see

I literally cannot control it in the home app at all and that is the problem . Since it is not responding I dont see anything in the homebridge when I click the icon in homeapp.
