### ISSUE TITLE
Govee light strip H619A can no longer be switched off

### ISSUE THREAD

**Issue by DorChris** [bwp91/homebridge-govee#402]
### What issue do you have? Please be as thorough and explicit as possible.
_I currently have a problem with the Govee H619A with hardware revision 2.01.02. Using Homebridge / the Home app and Siri, the devices can be turned on and colors can be changed, but I can no longer turn them off. The devices are also displayed as "off" in the Homebridge._
`[27.12.2022, 10:55:34] [Govee] [Schrankwand oben] current colour [rgb 255 204 204].
[27.12.2022, 10:55:34] [Govee] [Schrankwand oben] current state [on].
[27.12.2022, 10:55:35] [Govee] [Schrankwand oben] current state [off].`

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
_homebridge-config-ui-x v4.50.2_ 

* Which version of Homebridge/HOOBS do you have?
_Version 1.6.0_

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
_Raspberry Pi 4
Node.js Version 18.12.1_

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
_homebridge-govee v7.7.0
I have had this problem for a few versions now. Unfortunately, I can not say exactly since which one._

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
_H619A_

### Please paste any relevant logs below.
```
[27.12.2022, 11:02:52] [Govee] [Schrankwand oben] current state [on].
[27.12.2022, 11:02:53] [Govee] [Schrankwand oben] current state [off].
[27.12.2022, 11:03:02] [Govee] [Schrankwand oben] current colour [rgb 0 255 0].
[27.12.2022, 11:03:02] [Govee] [Schrankwand oben] current state [on].
[27.12.2022, 11:03:02] [Govee] [Schrankwand oben] current state [off].
```

**Comment by bwp91** [comment]
Hi @DorChris 

which credentials do you have in the plugin config? and also, do you have the “offline as off” setting enabled?

**Comment by DorChris** [comment]
Thanks for the help, it was due to the "offline as off" configuration.
