### ISSUE TITLE
Add option for offset of hygrometers 

### ISSUE THREAD

**Issue by anthonyb82** [bwp91/homebridge-govee#407]
* **Please explain your feature request in a one or two sentences.**
Requesting an option to add an offset to the humidity readings of a hygrometer for calibration.

**Comment by bwp91** [comment]
Hi @anthonyb82 

I normally add this option in my plugins, but for Govee I have not since this functionality exists within the Govee app, and the plugin should take this offset into account already.

**Comment by anthonyb82** [comment]
@bwp91 Thank you! I apologize, I was using another Govee plugin for my hygrometer that needed an offset. I loaded this one up for lights I wanted to add and saw it duplicated my hygrometer, so just assumed an option for an offset would be needed here. Nope, make it in the app and good to go! Thanks for the one stop shop now for my Govee plug-ins! Just saw you also own the Wemo plug-in- that one has been awesome for me as well, thank you! Happy New Year!
