### ISSUE TITLE
Leak Sensor Errors

### ISSUE THREAD

**Issue by schwaggy** [bwp91/homebridge-govee#408]
### What issue do you have? Please be as thorough and explicit as possible.
Ever since a leak was detected and cleared in the Govee app, the plug-in still throws 2 different errors throughout the day. When I attempt to clear the leak information in the Govee app, typically I’ve had to Delete Data. The “Got It” always says “Success” but doesn’t clear the leak alert info. Delete Data does clear the leak info.
However when I click Delete Data now I get an error, literally “Device is not be empty” and the leak information is still shown. Home app is ok, no alerts or leak info, the sensor displays no leak detected in Home.

I’ve removed and re-added the sensor to the Govee app. I’ve removed the sensor from Home and from the Homebridge cache. I’ve removed the sensor and the battery and added it back an hour later but it still causes these errors

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?
* HB UI-X 4.50.2

* Which version of Homebridge/HOOBS do you have?
* 1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
* macOS 12.6.2 Node.js 18.12.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
* 7.7.1 (issue started under 7.7.0)

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
* Leak detectors H5054

### Please paste any relevant logs below.

```
[Govee] [Laundry Room] could not be refreshed as timeout of 10000ms exceeded at RedirectableRequest.handleRequestTimeout (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/adapters/http.js:563:16).

[Govee] [Laundry Room] could not be refreshed as Request failed with status code 502 at settle (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).
```

**Comment by schwaggy** [comment]
This appears to have been caused by the Govee app not able to fully clear the leak alert. An update of the app allowed the leak info to be deleted and the errors in HB have stopped.

**Comment by recoi1er** [comment]
> This appears to have been caused by the Govee app not able to fully clear the leak alert. An update of the app allowed the leak info to be deleted and the errors in HB have stopped.

how did you clear the leak alert? I have this exact same issue and in the app I see alerts from awhile back but when I tap Got It on the page with the alerts nothing happens? Up to date app

**Comment by schwaggy** [comment]
> how did you clear the leak alert? I have this exact same issue and in the app I see alerts from awhile back but when I tap Got It on the page with the alerts nothing happens? Up to date app

You have to go one step further in the app and _delete data_ for that particular sensor.

**Comment by recoi1er** [comment]
> > how did you clear the leak alert? I have this exact same issue and in the app I see alerts from awhile back but when I tap Got It on the page with the alerts nothing happens? Up to date app
> 
> You have to go one step further in the app and _delete data_ for that particular sensor.

Ah ok, that's not super clear on their end but thanks for the info, issue now resolved for me! Maybe @bwp91  can update plugin to ignore old alerts!
