### ISSUE TITLE
Adaptive lighting not working with neon lights

### ISSUE THREAD

**Issue by samwhu30** [bwp91/homebridge-govee#413]
### What issue do you have? Please be as thorough and explicit as possible.
I purchased the Neon lights (H61A0) and I have them set for adaptive lighting but I haven't seen any change in the light colour, it is still at a really bright white light.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge with config UI

* Which version of Homebridge/HOOBS do you have?
v1.6.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

V7.7.1 (new device so not sure if it was happening before)

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Neon lights (H61A0)

### Please paste any relevant logs below.

`[05/01/2023, 17:43:49] [Govee] [Sofa lights] [AWS] receiving update {"source":"AWS","onOff":1,"brightness":100,"color":{"r":0,"g":0,"b":0},"colorTemInKelvin":4000,"mode":21,"result":1,"op":{"command":["qgUVAQAAAAAAAAAAAAAAAAAAALs=","qqUBZP/VoWT/1aFk/9WhAAAAAOE=","qqUCZP/VoWT/1aFk/9WhAAAAAOI=","qqUDZP/VoWT/1aFk/9WhAAAAAOM=","qqUEZP/VoWT/1aFk/9WhAAAAAOQ=","qqUFZP/VoWT/1aFk/9WhAAAAAOU=","qhEAHg8PAAAAAAAAAAAAAAAAAKU=","qhL/ZAAAgAoAAAAAAAAAAAAAAKk=","qiP/AAAAgAAAAIAAAACAAAAAgHY="]}}.

[05/01/2023, 17:43:40] [Govee] [Sofa lights] skipping adaptive lighting update as device is off or kelvin is same as before [4000K /250M].`

(Will update this ticket with more logs throughout the night.)

Thanks!
```

```

**Comment by samwhu30** [comment]
[homebridge.log-2.txt](https://github.com/bwp91/homebridge-govee/files/10355932/homebridge.log-2.txt)
I have attached the log.

It's the 'Sofa lights' that aren't working with the adaptive lighting.

Sorry for all the other rubbish in the logs, I did turn of the logs for my other govee devices but that didn't seem to take them out.

**Comment by GMarty93** [comment]
I’m having the same issue with the neon led rope light H61A0. 

I have adaptive lighting turned in for it but it’s just a cool white it doesn’t change throughout the day correctly as it should.
