### ISSUE TITLE
Kettle Issues - Shows Off when On, Temperature always 32 degrees

### ISSUE THREAD

**Issue by macguyincali** [bwp91/homebridge-govee#415]
### What issue do you have? Please be as thorough and explicit as possible.

Thanks for your work on this great plug in. The Kettle appears in Homekit and it is a combined device (a switch and a sensor). When I activate the device through Homekit, it initiates the boiling cycle, though in Homekit the switch immediately turns off (the kettle is still heating though). Also, it seems to always default to Black Tea / Boil setting which is not the temperature I would like to use. I use the Green Tea or Custom settings. Would be great if we could specify which setting to use.  In addition, the temperature always shows 32 degrees which is not correct. Is there something I am doing wrong?

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

v1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

MacOS Ventura 13.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee v7.7.1

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Smart Kettle

### Please paste any relevant logs below.

```

```

**Comment by alexanderspetrov** [comment]
I am also encountering this! (Homebridge UI-X on RPi) It's worth noting that the messages in the log appear to correctly report the current temperature, so this seems to be an issue of the data not getting to the right place (vs. not being available)  
```
[08/01/2023, 21:23:46] [Govee] [Govee Smart Kettle] current target [100°C].
[08/01/2023, 21:23:46] [Govee] [Govee Smart Kettle] current on base [yes].
[08/01/2023, 21:23:46] [Govee] [Govee Smart Kettle] current temperature [86°C].
```

**Comment by bwp91** [comment]
@macguyincali @alexanderspetrov 
I am aware of these issues - the kettle is still a work in progress although I hope to have some better news soon.
However you will find the latest version of the plugin most likely makes the kettle stop working altogether - plan to get this fixed as soon as possible (eta days not weeks)

**Comment by bwp91** [comment]
Just released a new beta enabling support for the kettle again (hopefully!)

**Comment by macguyincali** [comment]
excellent. Will take a look. Thanks!

**Comment by bwp91** [comment]
let me know how it goes.
i also added config options to allow for the first two custom modes that you may have in the govee app

**Comment by macguyincali** [comment]
Hey there. Looks like the kettle functionality is back.  For some reason, on MacOS, it won't respond, but on iOS the switches do appear to work for the various Settings (green, oolong, coffee, blk/boil).  I'd like to try to set up the custom mode, but not quite sure how to do this.

**Comment by macguyincali** [comment]
Also, I should note that there is still a kettle related accessory in Homekit that still shows 32˚

**Comment by CadLiara** [comment]
Well done Ben!

I was hoping that at some point the individual settings might be addressable via homekit directly but I didn't think you would have this one out and done so quick. (Little did I know this kettle would fast become one my home's most used smart accessories.)

Thank you :)

**Comment by macguyincali** [comment]
Hey Ben!  Thanks for updating the plugin. I'm still confused about how to add the custom setting. Right now I have the built-in presets.  Also, I'm getting 32˚ as a temperature reading on the kettle.  Any thoughts would be appreciated!

**Comment by macguyincali** [comment]
OK. I've figured out how to add Custom mode; works like a charm.  Now, I'm still troubleshooting the temperature reading 32˚. It appears that in the log, the temperature reading is correct and updated regularly. However, when I go to the accessories page in Homebridge, it reads 32.  And it reads 32 in Homekit app as well. Happy to provide more input if that helps.  Thanks!

**Comment by macguyincali** [comment]
Any way to correct the temperature readings on the kettle?  (I now have 2). In the logs, they show up as having the correct temperature, but the accessory shows 32˚ and in HomeKit it shows 32˚ as well.
