### ISSUE TITLE
Govee T2 Backlight H605C Auto changing to Color every few minutes

### ISSUE THREAD

**Issue by ivmarsic** [bwp91/homebridge-govee#418]
i am running Homebridge on Raspberry pi 4 and am running into an issue with the new T2 Backlight auto changing to the color setting versus the “video” which makes it a solid color versus syncing to the content of the TV.

am i missing a setting or is this a known bug?

i just installed the plugin as well as a fresh home bridge flash so everything should be  fully updated.

**Comment by rafinesse** [comment]
advanced settings - color safe mode

**Comment by ivmarsic** [comment]
> advanced settings - color safe mode

Wow, thank you so much. I looked through the advanced settings but the descriptions confused me.

**Comment by bwp91** [comment]
Maybe you (unknowingly) had adaptive lighting switched on? This would indeed explain the behaviour of it changing to colour mode every few minutes.

Well yes, the colour safe mode inadvertently removes the adaptive lighting feature so glad this has solved your issue!
