### ISSUE TITLE
Support for Govee Music Sync Box (H1162011)

### ISSUE THREAD

**Issue by xhi-nico** [bwp91/homebridge-govee#422]
I'm not sure if Govee's Music Sync Box (H1162011) is supported by the API. If it is, it would be great to have it available as a switch (ON/OFF)  in HomeKit.

If it's not, understood and this can be closed.

**Comment by bwp91** [comment]
hi @GeorgeeNico do you own this model already?

**Comment by xhi-nico** [comment]
I do.

**Comment by bwp91** [comment]
do you have the plugin running? please enter your username and password in the config, you should see a message in the log about this device not being supported, would be useful to have this log message.

**Comment by xhi-nico** [comment]
Yup, here you go:

`[21/01/2023, 14:42:22] [Govee] [Govee Music Sync Box] is not currently supported, do create a Github issue with the following info:
{"device":"9B:66:D0:32:38:30:2F:6A","deviceName":"Govee Music Sync Box","model":"H1162","httpInfo":{"groupId":0,"device":"9B:66:D0:32:38:30:2F:6A","sku":"H1162","spec":"","versionHard":"3.01.00","versionSoft":"1.01.03","deviceName":"Govee Music Sync Box","deviceExt":{"deviceSettings":"{\"address\":\"D0:32:38:30:2F:6A\",\"bleName\":\"GVH11622F6A\",\"topic\":\"GD/27beebf4e2b1a4f26511c0071435d23b\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"\",\"wifiHardVersion\":\"\",\"ic\":0,\"secretCode\":\"NzVjNDFkMTE=\",\"boilWaterCompletedNotiOnOff\":1,\"sku\":\"H1162\",\"device\":\"9B:66:D0:32:38:30:2F:6A\",\"deviceName\":\"Govee Music Sync Box\",\"versionHard\":\"3.01.00\",\"versionSoft\":\"1.01.03\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5f8b337fec9c0c7b321e13699a0d57f8-add_list_type_device_1162.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/eaa00e28db07555a4b95a4913c54dcce-new_switch_pics_h1162_on%403x.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/e3411556ccf090b87205de604b1b2dd7-new_switch_pics_h1162_off%403x.png\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":87}}`

**Comment by bwp91** [comment]
please update to the beta version of the plugin. this will be added to the home app as an "unsupported accessory".

However you should see logging appear in the homebridge log when you use the govee app to switch this device on and off (please disable bluetooth on your phone to force the device to connect via wifi).

If you should show me the logs for switching the device ON and OFF I should be able to implement this.

**Comment by xhi-nico** [comment]
Done, though I'm starting to realize this product likely does not have wifi... It may work only through bluetooth...

```
[22/01/2023, 18:28:42] [Govee] [Govee Music Sync Box] initialising with options {}.
[22/01/2023, 18:28:42] [Govee] [Govee Music Sync Box] initialised with id [9B:66:D0:32:38:30:2F:6A] [H1162].
```

Nothing in the log comes up related to the device, may not be possible to build into the plugin.

**Comment by bwp91** [comment]
which platform are you running homebridge on?

(if a raspberry pi) how close is this device physically? and would you consider yourself pretty technical? i know the last question is quite relative 😁

**Comment by xhi-nico** [comment]
Running on a raspberry pi 4 and it's close enough to reach the device.

Problem is that I've been having trouble with plugins being able to access to the BLE connection, I gave up on this a while ago and never bothered to fix it (I have the same problem with the SwitchBot plugin):
`[23/01/2023, 13:24:43] [Govee] [BLE] disabling client as ERR_DLOPEN_FAILED.`

I'm technical enough and am willing to try and figure this out with you, though it may be slow to get there (especially with the BLE issue I've been facing).
