### ISSUE TITLE
Installation 404 Not found

### ISSUE THREAD

**Issue by Jericho3698** [bwp91/homebridge-govee#429]
While installing the plugin I got the error „install response status 404 Not found ..“ (see attached picture) 
This was the only problem while installing the plugin.
![757AC378-3D44-4E2F-96A6-84470F8AD78A](https://user-images.githubusercontent.com/123262444/213879805-005575ea-1634-44cb-a84e-1772435cc3fd.jpeg)

I use the Homebridge UI. 
Version 4.50.2 is installed.

It is installed on Raspberry Pi.

Govee version 7.9.0 is installed.

Node version 18.13.0
Npm version 9.3.1

**Comment by bwp91** [comment]
please use the homebridge terminal to run these commands:

```
cd /usr/local/lib/node_modules/homebridge-govee
```

```
sudo npm install @abandonware/bluetooth-hci-socket
```

```bash
sudo npm install @abandonware/noble
```

restart homebridge and see if this has worked 🤔

**Comment by Jericho3698** [comment]
This worked for me. But after making an update to the plugin I recieved the same error. Do you think this will cause any problems? 
I also struggle to connect the hygrometer H 5075 to my homebridge. 
thanks for help in advance

**Comment by Jericho3698** [comment]
I used sudo hcitool inq and sudo hcitool scan but without any result. Thats why I can‘t pair the hygrometer with the homebridge. 
With command hcitool dev I see hci0 I guess this is the bluetooth MAC from the raspberry
