### ISSUE TITLE
Please Convert the AWS Code

### ISSUE THREAD

**Issue by Stonie70** [bwp91/homebridge-govee#430]
Hy,
please can you convert the AWS Code: qgUKAQAAAAAAAAAAAAAAAAAAAKQ=\\\ 
for the last Plugin, to use the DYI Scene ?

Thank you in Advance.
Roman

**Comment by bwp91** [comment]
Hi, please try this!

```
33050a010000000000000000000000000000003d
```

**Comment by Stonie70** [comment]
Hi, thak you but I get this notice in the log:
![image](https://user-images.githubusercontent.com/90376181/213912229-1b54b27c-cfb9-40a6-9709-da5a789391a0.png)
and it doesn`t work.

**Comment by bwp91** [comment]
can you paste here your govee config section of the homebridge config file?
Remove username/password/api keys etc.

**Comment by Stonie70** [comment]
Sure:

{
    "name": "Govee",
    "username": "xxxxx.xxxxx@xxxxx.xx",
    "password": "xxxxxxxxxxxx",
    "apiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "debug": false,
    "offlineAsOff": false,
    "lightDevices": [
        {
            "label": "LED Wohnzimmer",
            "deviceId": "0E:73:A4:C1:38:4E:64:41",
            "scene": "DYI",
            "diyMode": "33050a010000000000000000000000000000003d",
            "overrideLogging": "default"
        }
    ],
    "platform": "Govee"
}

**Comment by bwp91** [comment]
The log is complaining because you have a scene  code set as `DYI` which is obviously not valid

**Comment by bwp91** [comment]
you should remove this line from the config, and use the “DIY Mode” scene that appears in the Eve app

**Comment by Stonie70** [comment]
Thank you. 

Now I get no error entry log, but the light don`t switch to the DYI Mode when I switch it in the EVE App.

**Comment by Stonie70** [comment]
This is the full line when I switch in debug mode with the govee app to DYI:

[AWS] message event [{"proType":0,"msg":"{\"transaction\":\"1234567890\",\"sku\":\"H6159\",\"device\":\"0E:73:A4:C1:38:4E:64:41\",\"cmdVersion\":0,\"type\":0,\"cmd\":\"status\",\"data\":\"{\\\"softversion\\\":\\\"1.07.02\\\",\\\"wifiSoftVersion\\\":\\\"1.03.05\\\",\\\"turn\\\":1,\\\"brightness\\\":254,\\\"modeValue\\\":[\\\"qgUKAQAAAAAAAAAAAAAAAAAAAKQ=\\\"],\\\"mode\\\":10,\\\"timer\\\":{\\\"enable\\\":0,\\\"time\\\":[{\\\"openHour\\\":0,\\\"openMin\\\":0,\\\"closeHour\\\":23,\\\"closeMin\\\":59}]},\\\"color\\\":{\\\"red\\\":0,\\\"green\\\":0,\\\"blue\\\":0},\\\"colorTemInKelvin\\\":0}\"}","state":{"onOff":1,"brightness":254,"connected":"true","sku":"H6159","device":"0E:73:A4:C1:38:4E:64:41"}}].

Maybe you see more for the convertet Code from your plugin ?
Thank you

**Comment by bwp91** [comment]
Can you show what appears in the log if you use the govee app to turn to this mode/scene?

**Comment by bwp91** [comment]
disable bluetooth on your phone if the model supports bluetooth

**Comment by Stonie70** [comment]
This is what the log shoes (without bluetooth):

[1/22/2023, 3:09:08 PM] [Govee] [AWS] message event [{"proType":0,"msg":"{\"transaction\":\"v_1674396547390151\",\"sku\":\"H6159\",\"device\":\"0E:73:A4:C1:38:4E:64:41\",\"cmdVersion\":0,\"type\":0,\"cmd\":\"pt\",\"data\":\"{\\\"op\\\":\\\"mode\\\",\\\"value\\\":[\\\"oQIAAgAAAAAAAAAAAAAAAAAAAKE=\\\",\\\"oQIBAQAAMBj/AAD/fwD//wAA/ws=\\\",\\\"oQICAAD////P8f/Og////wAAAC0=\\\",\\\"oQL/AAAAAAAAAAAAAAAAAAAAAFw=\\\",\\\"MwUKAQAAAAAAAAAAAAAAAAAAAD0=\\\"]}\"}"}].

[1/22/2023, 3:09:33 PM] [Govee] [TV_Wohnzimmer] [API] receiving update {"online":true,"powerState":"on","brightness":100,"color":{"r":240,"b":255,"g":240},"source":"API"}.

**Comment by bwp91** [comment]
Ah I see.

There are older models that use a different kind of command structure that the plugin did support before, but due to changes that govee made, i have only managed to implement these scene codes for newer models.

So there’s nothing you can do to get this to work at the moment.

I know there are a number of users waiting for an update which I need to implement. Will try to work on this today 👍🏻

**Comment by Stonie70** [comment]
Thank you bwp91,
I believed was get stupid, because this has worked before.
Do you know a model which you can recommend, and where you plugin works with the DYI Scene ?
Otherwise, I`m waiting till you have implemented this change:

CU

**Comment by bwp91** [comment]
Any chance we could message on discord?
https://discord.gg/cMGhNtZ3tW
