### ISSUE TITLE
Govee API quota limits reached will not work until fully initialized

### ISSUE THREAD

**Issue by alcorta2022** [bwp91/homebridge-govee#435]
### What issue do you have? Please be as thorough and explicit as possible.

Initially, I was having the issue where my light strip (H605B) was not changing color or brightness however, my other Govee products were working just fine. Now none of the Govee products are working at all. They are showing in HomeKit as if they are, but none are actually turning on or off as it shows in HomeKit. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge 

* Which version of Homebridge/HOOBS do you have?

V1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry pi 
V18.13.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

V7.9.0 and no

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H605B, H6054, H6008, H610A, H7170

### Please paste any relevant logs below.

```
![image](https://user-images.githubusercontent.com/108943782/214760972-0237fc4c-ac7a-43f6-bf57-605c9638225b.jpeg)

![image](https://user-images.githubusercontent.com/108943782/214760999-684ac654-b316-482b-8cee-8fb335da88b8.jpeg)
```

**Comment by bwp91** [comment]
Hi 

please consider using your govee username and password (if you haven’t already got them there) 
and removing the api key from the config

there will be no loss of functionality!

**Comment by alcorta2022** [comment]
Okay so now everything but H6054 and H605D is working. They will turn on and off but I'm unable to change the color.

**Comment by bwp91** [comment]
for both of these models, if you use the govee app to turn the brightness to 100%, what brightness % does it then show in the home app?

**Comment by alcorta2022** [comment]
Okay so now none of my govee accessories are working with HomeKit via homebridge.  They show in HomeKit but turning off and on and changing color does not work
