### ISSUE TITLE
H6009 Bulb dimming percentage not working properly

### ISSUE THREAD

**Issue by markspidle** [bwp91/homebridge-govee#437]
### What issue do you have? Please be as thorough and explicit as possible.
When I use the Apple Home app to put the bulb at 100% it actually goes dimmer.  I don't really see any change in the brightness of the bulb from 0-80% or so then above that it gets dimmer.  I thought this was similar to issue #431 but it looks like you resolved that issue.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Hoobs

* Which version of Homebridge/HOOBS do you have?
4.2.8

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
7.9.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6009 WiFi Bulb

### Please paste any relevant logs below.

```
1/27/2023, 1:43:20 PMGovee BridgeGovee[Right Lamp] skipping adaptive lighting update as device is off or kelvin is same as before [3900K /258M].
1/27/2023, 1:43:38 PMGovee BridgeGovee[Left Lamp] [AWS] sending update {"msg":{"cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1674848618944000","type":1}}.
1/27/2023, 1:43:38 PMGovee BridgeGovee[Left Lamp] current state [on].
1/27/2023, 1:43:39 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"status","type":0,"transaction":"v_1674848618944000","pactType":1,"pactCode":1,"state":{"onOff":1,"brightness":127,"color":{"r":255,"g":221,"b":190},"colorTemInKelvin":4600,"mode":13,"result":1},"op":{"command":["qgUN/92+EfgAAAAAAAAAAAAAANc=","qhEAHg8AAAAAAAAAAAAAAAAAAKo=","qhL/ZAAAgA8AAAAAAAAAAAAAAKw=","qiP/AAAAgAAAAIAAAACAAAAAgHY="]}}].
1/27/2023, 1:43:39 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","onOff":1,"brightness":127,"color":{"r":255,"g":221,"b":190},"colorTemInKelvin":4600,"mode":13,"result":1,"op":{"command":["qgUN/92+EfgAAAAAAAAAAAAAANc=","qhEAHg8AAAAAAAAAAAAAAAAAAKo=","qhL/ZAAAgA8AAAAAAAAAAAAAAKw=","qiP/AAAAgAAAAIAAAACAAAAAgHY="]}}.
1/27/2023, 1:43:39 PMGovee BridgeGoveeWARNING[Left Lamp] new scene code: [qgUN/92+EfgAAAAAAAAAAAAAANc=] [aa050dffddbe11f80000000000000000000000d7] [op:aa].
1/27/2023, 1:43:44 PMGovee BridgeGovee[Left Lamp] [AWS] sending update {"msg":{"cmd":"brightness","cmdVersion":0,"data":{"val":211},"transaction":"v_1674848624123000","type":1}}.
1/27/2023, 1:43:44 PMGovee BridgeGovee[Left Lamp] current brightness [83%].
1/27/2023, 1:43:44 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"brightness","type":0,"transaction":"v_1674848624123000","pactType":1,"pactCode":1,"state":{"brightness":211,"result":1}}].
1/27/2023, 1:43:44 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":211,"result":1}.
1/27/2023, 1:43:44 PMGovee BridgeGovee[Left Lamp] current brightness [83%].
1/27/2023, 1:43:44 PMGovee BridgeGovee[Left Lamp] [AWS] sending update {"msg":{"cmd":"brightness","cmdVersion":0,"data":{"val":254},"transaction":"v_1674848624492000","type":1}}.
1/27/2023, 1:43:44 PMGovee BridgeGovee[Left Lamp] current brightness [100%].
1/27/2023, 1:43:45 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"brightness","type":0,"transaction":"v_1674848624492000","pactType":1,"pactCode":1,"state":{"brightness":254,"result":1}}].
1/27/2023, 1:43:45 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":254,"result":1}.
1/27/2023, 1:43:45 PMGovee BridgeGovee[Left Lamp] current brightness [100%].
1/27/2023, 1:43:47 PMGovee BridgeGovee[Downstairs Thermomete] [HTTP] receiving update {"source":"HTTP","battery":100,"temperature":2200,"humidity":3030,"online":false}.
1/27/2023, 1:43:47 PMGovee BridgeGovee[Upstairs Thermometer] [HTTP] receiving update {"source":"HTTP","battery":100,"temperature":2240,"humidity":2660,"online":false}.
1/27/2023, 1:43:48 PMGovee BridgeGovee[Left Lamp] [AWS] sending update {"msg":{"cmd":"brightness","cmdVersion":0,"data":{"val":218},"transaction":"v_1674848628445000","type":1}}.
1/27/2023, 1:43:48 PMGovee BridgeGovee[Left Lamp] current brightness [86%].
1/27/2023, 1:43:48 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"brightness","type":0,"transaction":"v_1674848628445000","pactType":1,"pactCode":1,"state":{"brightness":218,"result":1}}].
1/27/2023, 1:43:48 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":218,"result":1}.
1/27/2023, 1:43:48 PMGovee BridgeGovee[Left Lamp] current brightness [86%].
1/27/2023, 1:43:48 PMGovee BridgeGovee[Left Lamp] [AWS] sending update {"msg":{"cmd":"brightness","cmdVersion":0,"data":{"val":193},"transaction":"v_1674848628811000","type":1}}.
1/27/2023, 1:43:48 PMGovee BridgeGovee[Left Lamp] current brightness [76%].
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] [AWS] sending update {"msg":{"cmd":"brightness","cmdVersion":0,"data":{"val":185},"transaction":"v_1674848629179000","type":1}}.
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] current brightness [73%].
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] [AWS] sending update {"msg":{"cmd":"brightness","cmdVersion":0,"data":{"val":168},"transaction":"v_1674848629546000","type":1}}.
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] current brightness [66%].
1/27/2023, 1:43:49 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"brightness","type":0,"transaction":"v_1674848629179000","pactType":1,"pactCode":1,"state":{"brightness":193,"result":1}}].
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":193,"result":1}.
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] current brightness [76%].
1/27/2023, 1:43:49 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"brightness","type":0,"transaction":"v_1674848629179000","pactType":1,"pactCode":1,"state":{"brightness":185,"result":1}}].
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":185,"result":1}.
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] current brightness [73%].
1/27/2023, 1:43:49 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"brightness","type":0,"transaction":"v_1674848629546000","pactType":1,"pactCode":1,"state":{"brightness":168,"result":1}}].
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":168,"result":1}.
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] current brightness [66%].
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] [AWS] sending update {"msg":{"cmd":"brightness","cmdVersion":0,"data":{"val":152},"transaction":"v_1674848629919000","type":1}}.
1/27/2023, 1:43:49 PMGovee BridgeGovee[Left Lamp] current brightness [60%].
1/27/2023, 1:43:50 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"brightness","type":0,"transaction":"v_1674848629919000","pactType":1,"pactCode":1,"state":{"brightness":152,"result":1}}].
1/27/2023, 1:43:50 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":152,"result":1}.
1/27/2023, 1:43:50 PMGovee BridgeGovee[Left Lamp] current brightness [60%].
1/27/2023, 1:43:53 PMGovee BridgeGovee[Left Lamp] [AWS] sending update {"msg":{"cmd":"turn","cmdVersion":0,"data":{"val":0},"transaction":"v_1674848633678000","type":1}}.
1/27/2023, 1:43:53 PMGovee BridgeGovee[Left Lamp] current state [off].
1/27/2023, 1:43:53 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"status","type":0,"transaction":"v_1674848633678000","pactType":1,"pactCode":1,"state":{"onOff":0,"brightness":152,"color":{"r":255,"g":221,"b":190},"colorTemInKelvin":4600,"mode":13,"result":1},"op":{"command":["qgUN/92+EfgAAAAAAAAAAAAAANc=","qhEAHg8AAAAAAAAAAAAAAAAAAKo=","qhL/ZAAAgA8AAAAAAAAAAAAAAKw=","qiP/AAAAgAAAAIAAAACAAAAAgHY="]}}].
1/27/2023, 1:43:53 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","onOff":0,"brightness":152,"color":{"r":255,"g":221,"b":190},"colorTemInKelvin":4600,"mode":13,"result":1,"op":{"command":["qgUN/92+EfgAAAAAAAAAAAAAANc=","qhEAHg8AAAAAAAAAAAAAAAAAAKo=","qhL/ZAAAgA8AAAAAAAAAAAAAAKw=","qiP/AAAAgAAAAIAAAACAAAAAgHY="]}}.
1/27/2023, 1:43:53 PMGovee BridgeGoveeWARNING[Left Lamp] new scene code: [qgUN/92+EfgAAAAAAAAAAAAAANc=] [aa050dffddbe11f80000000000000000000000d7] [op:aa].

```

**Comment by markspidle** [comment]
Ok just saw issue #233 and this is the same problem I believe, since this is the same bulb H6008/6009 I notice when I use the Govee app to set the brightness to 41% the Govee Plugin sees it as 16% so there is something off here.

1/27/2023, 2:02:12 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":29,"result":1}.
1/27/2023, 2:02:12 PMGovee BridgeGovee[Left Lamp] current brightness [11%].
1/27/2023, 2:02:17 PMGovee BridgeGovee[Downstairs Thermomete] [HTTP] receiving update {"source":"HTTP","battery":100,"temperature":2200,"humidity":3030,"online":false}.
1/27/2023, 2:02:17 PMGovee BridgeGovee[Upstairs Thermometer] [HTTP] receiving update {"source":"HTTP","battery":100,"temperature":2240,"humidity":2660,"online":false}.
1/27/2023, 2:02:18 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"brightness","type":0,"transaction":"v_1674849738218061","pactType":1,"pactCode":1,"state":{"brightness":100,"result":1}}].
1/27/2023, 2:02:18 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":100,"result":1}.
1/27/2023, 2:02:18 PMGovee BridgeGovee[Left Lamp] current brightness [39%].
1/27/2023, 2:02:20 PMGovee BridgeGovee[Right Lamp] skipping adaptive lighting update as device is off or kelvin is same as before [3900K /258M].
1/27/2023, 2:02:28 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"colorwc","type":0,"transaction":"v_1674849747865517","pactType":1,"pactCode":1,"state":{"color":{"r":255,"g":221,"b":190},"colorTemInKelvin":3300,"result":1}}].
1/27/2023, 2:02:28 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","color":{"r":255,"g":221,"b":190},"colorTemInKelvin":3300,"result":1}.
1/27/2023, 2:02:28 PMGovee BridgeGovee[Left Lamp] current colour [3300K / 303M].
1/27/2023, 2:02:31 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"colorwc","type":0,"transaction":"v_1674849750793633","pactType":1,"pactCode":1,"state":{"color":{"r":255,"g":221,"b":190},"colorTemInKelvin":5900,"result":1}}].
1/27/2023, 2:02:31 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","color":{"r":255,"g":221,"b":190},"colorTemInKelvin":5900,"result":1}.
1/27/2023, 2:02:31 PMGovee BridgeGovee[Left Lamp] current colour [5900K / 169M].
1/27/2023, 2:02:32 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"colorwc","type":0,"transaction":"v_1674849751939137","pactType":1,"pactCode":1,"state":{"color":{"r":255,"g":221,"b":190},"colorTemInKelvin":4200,"result":1}}].
1/27/2023, 2:02:32 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","color":{"r":255,"g":221,"b":190},"colorTemInKelvin":4200,"result":1}.
1/27/2023, 2:02:32 PMGovee BridgeGovee[Left Lamp] current colour [4200K / 238M].
1/27/2023, 2:02:33 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"colorwc","type":0,"transaction":"v_1674849752785049","pactType":1,"pactCode":1,"state":{"color":{"r":255,"g":221,"b":190},"colorTemInKelvin":4800,"result":1}}].
1/27/2023, 2:02:33 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","color":{"r":255,"g":221,"b":190},"colorTemInKelvin":4800,"result":1}.
1/27/2023, 2:02:33 PMGovee BridgeGovee[Left Lamp] current colour [4800K / 208M].
1/27/2023, 2:02:40 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"4E:D9:D4:AD:FC:97:0F:D6","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"brightness","type":0,"transaction":"v_1674849760207641","pactType":1,"pactCode":1,"state":{"brightness":41,"result":1}}].
1/27/2023, 2:02:40 PMGovee BridgeGovee[Left Lamp] [AWS] receiving update {"source":"AWS","brightness":41,"result":1}.
1/27/2023, 2:02:40 PMGovee BridgeGovee[Left Lamp] current brightness [16%].
1/27/2023, 2:02:45 PMGovee BridgeGovee[Upstairs Thermometer] [BLE] receiving update {"temperature":1823.5600000000002,"temperatureF":6482.408000000001,"humidity":3560,"battery":100,"source":"BLE"}.
1/27/2023, 2:02:45 PMGovee BridgeGovee[Upstairs Thermometer] FGT addData() [{ temp: 18.23, time: 1674849766 }] immediate [false].
1/27/2023, 2:02:45 PMGovee BridgeGovee[Upstairs Thermometer] current temperature [18.23°C / 6482.408000000001°F].
1/27/2023, 2:02:45 PMGovee BridgeGovee[Upstairs Thermometer] FGT addData() [{ humidity: 35.6, time: 1674849766 }] immediate [false].
1/27/2023, 2:02:45 PMGovee BridgeGovee[Upstairs Thermometer] current humidity [35.6%].
1/27/2023, 2:02:47 PMGovee BridgeGovee[Downstairs Thermomete] [HTTP] receiving update {"source":"HTTP","battery":100,"temperature":2200,"humidity":3030,"online":false}.
1/27/2023, 2:02:47 PMGovee BridgeGovee[Upstairs Thermometer] [HTTP] receiving update {"source":"HTTP","battery":100,"temperature":2240,"humidity":2660,"online":false}.
1/27/2023, 2:02:50 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H6009","device":"D1:FE:D4:AD:FC:97:AA:44","softVersion":"1.00.14","wifiSoftVersion":"1.00.14","cmd":"status","type":0,"transaction":"y_1674849770050964","pactType":1,"pactCode":1,"state":{"onOff":0,"brightness":140,"color":{"r":255,"g":225,"b":198},"colorTemInKelvin":4800,"mode":13,"result":1},"op":{"command":["qgUN/+HGEsAAAAAAAAAAAAAAAKg=","qhEAHg8AAAAAAAAAAAAAAAAAAKo=","qhL/ZAAAgA8AAAAAAAAAAAAAAKw=","qiP/AAAAgAAAAIAAAACAAAAAgHY="]}}].
1/27/2023, 2:02:50 PMGovee BridgeGovee[Right Lamp] [AWS] receiving update {"source":"AWS","onOff":0,"brightness":140,"color":{"r":255,"g":225,"b":198},"colorTemInKelvin":4800,"mode":13,"result":1,"op":{"command":["qgUN/+HGEsAAAAAAAAAAAAAAAKg=","qhEAHg8AAAAAAAAAAAAAAAAAAKo=","qhL/ZAAAgA8AAAAAAAAAAAAAAKw=","qiP/AAAAgAAAAIAAAACAAAAAgHY="]}}.
1/27/2023, 2:02:50 PMGovee BridgeGoveeWARNING[Right Lamp] new scene code: [qgUN/+HGEsAAAAAAAAAAAAAAAKg=] [aa050dffe1c612c00000000000000000000000a8] [op:aa].
1/27/2023, 2:02:50 PMGovee BridgeGovee[AWS] message event [{"proType":2,"sku":"H7141","device":"2D:BD:D4:AD:FC:79:8A:82","softVersion":"1.00.28","wifiSoftVersion":"1.00.28","cmd":"status","type":0,"transaction":"y_1674849770051870","pactType":1,"pactCode":1,"state":{"onOff":0,"result":1},"op":{"command":["qhIAAAAAAAAAAAAAAAAAAAAAALg=","qhEAAAAAAAAAAAAAAAAAAAAAALs=","qgUABAEAAAAAAAAAAAAAAAAAAKo=","qgUBBQAAAAAAAAAAAAAAAAAAAKs=","qgUCAAgAPAA8BQA8ADwB/////6E=","qgUDqAAAAAAAAAAAAAAAAAAAAAQ=","qhYA/////wAAAAAAAAAAAAAAALw=","qghk8404waQAAAAAAAAAAAAAAOU=","qhABAshUAAAAAAAAAAAAAAAAACU=","qhgA/////wAAAAAAAAAAAAAAALI=","qgEAAQLIVAABAAAAAAAAAAAAADU="]}}].
1/27/2023, 2:02:50 PMGovee BridgeGovee[Smart H

**Comment by bwp91** [comment]
Hi, if you set the brightness in the govee app to 100%, what % does is show as in the home app?

Also are you able to change colour via the home app?

**Comment by markspidle** [comment]
Home app says 39%No I can’t change color from the home appOn Jan 28, 2023, at 4:40 PM, Ben ***@***.***> wrote:﻿
Hi, if you set the brightness in the govee app to 100%, what % does is show as in the home app?
Also are you able to change colour via the home app?

**Comment by bwp91** [comment]
@markspidle please try the beta version of the plugin to see if this improves anything.
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by markspidle** [comment]
Yes, those changes seems to have done the trick.

Thanks

**Comment by dfritter4** [comment]
I’m experiencing this exact same brightness issue with H6008 bulbs. 100% in the Govee app shows up as 39% in HomeKit. I’m on the latest version of Homebridge (1.6.1) and this plugin (9.0.0). Colors in the Home app seem to work fine.

**Comment by bwp91** [comment]
@dfritter4 please check wiki article:
https://github.com/bwp91/homebridge-govee/wiki/Common-Errors

**Comment by davidwfritz** [comment]
That worked for me, thank you @bwp91
