### ISSUE TITLE
I can no longer switch the Lightstripe via Homebridge on and off

### ISSUE THREAD

**Issue by Bastie82** [bwp91/homebridge-govee#44]
### What issue do you have? Please be as thorough and explicit as possible.

I can no longer switch the Lightstripe via Homebridge. Switching on and off is no longer possible, although the device is displayed.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

Homebridge Version 1.2.5, homebridge-config-ui-x v4.38.0 

* Which version of Homebridge/HOOBS do you have?

Homebridge Version 1.2.5, homebridge-config-ui-x v4.38.0 

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 4 4GB,  Node.js Version | v14.15.4 Npm Version V6.14.10

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee v2.9.0 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6159

### Please paste any relevant logs below.

```[07/02/2021, 03:10:43] [Govee] [Lightstripe Govee] received update [{"online":"false","powerState":"off","brightness":51,"color":{"r":189,"b":66,"g":128}}].
[07/02/2021, 03:10:47] [Govee] [Lightstripe Govee] sending update {"name":"turn","value":"on"}.
[07/02/2021, 03:10:48] [Govee] [Lightstripe Govee] current state [on].
[07/02/2021, 03:10:55] [Govee] [Lightstripe Govee] sending update {"name":"turn","value":"off"}.
[07/02/2021, 03:10:55] [Govee] [Lightstripe Govee] current state [off].
[07/02/2021, 03:10:58] [Govee] [Lightstripe Govee] ignoring update [{"online":"false","powerState":"off","brightness":51,"color":{"r":189,"b":66,"g":128}}].
[07/02/2021, 03:11:28] [Govee] [Lightstripe Govee] ignoring update [{"online":"false","powerState":"off","brightness":51,"color":{"r":189,"b":66,"g":128}}].
[07/02/2021, 03:11:44] [Govee] [Lightstripe Govee] ignoring update [{"online":"false","powerState":"off","brightness":51,"color":{"r":189,"b":66,"g":128}}].
```

**Comment by bwp91** [comment]
Hi @Bastie82 
Whilst your LED strip is reported as `online: false` there is a chance that controlling it through the plugin won’t work.
This state is reported to the plugin by Govee and is something out of my control

**Comment by Bastie82** [comment]
I was able to solve the problem. Unfortunately I still have a problem with the color rendering. Unfortunately, red is not shown as red, but rather as orange. Do you have another tip for me? Unfortunately, today's update has not brought any improvement.

Thank you for your help.

**Comment by bwp91** [comment]
HomeKit uses a different colour system to Govee devices (and the Govee app) so this need to convert colours can result in colour differences. This is always going to be a frustration and not much I can do about.

HomeKit uses hue and saturation whereas Govee devices use RGB.

I am using a conversion function that many other Homebridge plugins use, who share the same issue with RGB devices.

**Comment by Bastie82** [comment]
all right, thank you for the answer and all your work. I wish you a nice evening.

this thread can be closed.

**Comment by bwp91** [comment]
Thank you. Any other questions you have in the future please do ask!
