### ISSUE TITLE
Govee post to github notification

### ISSUE THREAD

**Issue by deokwons9004dev** [bwp91/homebridge-govee#455]
* **Please explain your feature request in a one or two sentences.**

I got this log output:
[2/17/2023, 1:05:48 PM] [Govee] [Bathroom Dehumidifer] Please post the following on GitHub:
H7150
{
  "mode": {
    "options": [
      {
        "name": "Low",
        "value": "1"
      },
      {
        "name": "High",
        "value": "2"
      },
      {
        "name": "Auto",
        "value": "3"
      },
      {
        "name": "Dryer",
        "value": "8"
      }
    ]
  }
}

and this:
[2/17/2023, 1:05:48 PM] [Govee] [Kitchen Purifier] Please post the following on GitHub:
H7123
{
  "mode": {
    "options": [
      {
        "name": "Low",
        "value": 1
      },
      {
        "name": "Medium",
        "value": 2
      },
      {
        "name": "High",
        "value": 3
      },
      {
        "name": "Auto mode",
        "value": 4
      },
      {
        "name": "Sleep mode",
        "value": 5
      }
    ]
  }
}

..and this:
[2/17/2023, 1:05:48 PM] [Govee] [Bathroom Purifier] Please post the following on GitHub:
H7120
{
  "mode": {
    "options": [
      {
        "name": "Low",
        "value": 1
      },
      {
        "name": "Medium",
        "value": 2
      },
      {
        "name": "High",
        "value": 3
      },
      {
        "name": "Sleep mode",
        "value": 5
      }
    ]
  }
}

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

* **Anything else?**

**Comment by bwp91** [comment]
Thanks for this 👍
