### ISSUE TITLE
New Govee Kettle (released 3 days ago--need support)

### ISSUE THREAD

**Issue by josephdc18** [bwp91/homebridge-govee#461]
### What issue do you have? Please be as thorough and explicit as possible.
Unsupported Smart Kettle that was released 3 days ago

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge

* Which version of Homebridge/HOOBS do you have?
Homebridge HyperV

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Windows 10 Pro

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
7.9.3

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Smart Kettle H7171

### Please paste any relevant logs below.
{"device":"2C:42:D4:AD:FC:BA:4A:70","deviceName":"Smart Kettle","model":"H7171","httpInfo":{"groupId":0,"device":"2C:42:D4:AD:FC:BA:4A:70","sku":"H7171","spec":"","versionHard":"1.02.00","versionSoft":"1.00.07","deviceName":"Smart Kettle","deviceExt":{"deviceSettings":"{\"address\":\"D4:AD:FC:BA:4A:71\",\"bleName\":\"ihoment_H7171_4A71\",\"topic\":\"GD/b55e58142f979dc3d98897778bc1e3bd\",\"wifiMac\":\"D4:AD:FC:BA:4A:70\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.07\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"C/RcIj9xV3o=\",\"boilWaterExceptionNotiOnOff\":1,\"mcuSoftVersion\":\"1.00.40\",\"mcuHardVersion\":\"1.00.05\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"sku\":\"H7171\",\"device\":\"2C:42:D4:AD:FC:BA:4A:70\",\"deviceName\":\"Smart Kettle\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.07\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5a06b85a05ee571c128a884447ac8e86-add_list_type_device_7171.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":135}}

**Comment by bwp91** [comment]
Hi @josephdc18 please try the beta version of the plugin.

Could you show a screenshot of how this kettle appears in the govee app?

I have based the current functions and code on the previous model of the kettle so not sure if it will work first time or not!

Thanks

**Comment by josephdc18** [comment]
Sure Ben! I don’t see the beta version of this plugin. The latest I see is 7.9.3 but please let me know where to find it.Attached are the photos of this kettle in-app. -JosephOn Mar 5, 2023, at 12:35, Ben ***@***.***> wrote:﻿
Hi @josephdc18 please try the beta version of the plugin.
Could you show a screenshot of how this kettle appears in the govee app?
I have based the current functions and code on the previous model of the kettle so not sure if it will work first time or not!
Thanks

**Comment by josephdc18** [comment]
Sure Ben! I don’t see the beta version of this plugin. The latest I see is 7.9.3 but please let me know where to find it.


![Govee Kettle 2](https://user-images.githubusercontent.com/126998075/223016897-77a975b7-8430-4590-84b1-40008d1ca13c.png)
![Govee Kettle](https://user-images.githubusercontent.com/126998075/223016901-88b1e97b-1cb2-41f3-b46e-91f5529a3dcf.png)
![Govee Kettle 3](https://user-images.githubusercontent.com/126998075/223016903-24650d93-17d4-4136-92e2-5213a774aad4.png)

**Comment by josephdc18** [comment]
Was able to install the beta version just now. Unfortunately my Kettle does not show up in Homekit. Let me know if I can be of any further help. Thanks again

**Comment by bwp91** [comment]
Thanks for the screenshots!

Assuming you are on the beta (could be worth updating again to latest beta), can you post here the start up logs for the plugin? feel free to remove any device ids etc

**Comment by toadboi98** [comment]
@bwp91 I noticed in the Changelog under 8.0.0 (2023-03-21) it states support has been added for this device but under Supported Devices, it is not listed. Do you know the current status?

**Comment by bwp91** [comment]
> @bwp91 I noticed in the Changelog under 8.0.0 (2023-03-21) it states support has been added for this device but under Supported Devices, it is not listed. Do you know the current status?

It _should_ work, it will definitely appear in homebridge as an accessory, but it hasn’t been confirmed if the commands the plugin sends are properly working.

If they aren’t working, it’s no issue to get them working, i just need someone with the device to help!
