### ISSUE TITLE
Scenes do not switch on Govee Neon LED Strip 3m H61A0

### ISSUE THREAD

**Issue by MrData2000** [bwp91/homebridge-govee#465]
### What issue do you have? Please be as thorough and explicit as possible.
The scenes are not switched on the Govee Neon LED Strip 3m H61A0. If you change the scene in the Govee app, the Homebridge log always shows the same scene codes.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
(1)

* Which version of Homebridge/HOOBS do you have?
1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Docker Container with oznu/homebridge:ubuntu Image (20.04.4 LTS)
Node.js v16.17.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v7.9.3

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H61A0

### Please paste any relevant logs below.
#first Scene Switch with Govee-App (built-in Scene, not DIY))
[3/10/2023, 8:44:52 PM] [Govee] [Neon eins] current scene [3302000000000000000000000000000000000031] [op:a3].
[3/10/2023, 8:44:52 PM] [Govee] [Neon eins] current scene [3305000000000000000000000000000000000036] [op:33].
#second Scene Switch to different Scene with Govee-App  (built-in Scene, not DIY)
[3/10/2023, 8:45:05 PM] [Govee] [Neon eins] current scene [3302000000000000000000000000000000000031] [op:a3].
[3/10/2023, 8:45:05 PM] [Govee] [Neon eins] current scene [3305000000000000000000000000000000000036] [op:33].
#third Scene Switch to different Scene with Govee-App (built-in Scene, not DIY)
[3/10/2023, 8:45:12 PM] [Govee] [Neon eins] current scene [3302000000000000000000000000000000000031] [op:a3].
[3/10/2023, 8:45:12 PM] [Govee] [Neon eins] current scene [3305000000000000000000000000000000000036] [op:33].

**Comment by jaidon** [comment]
Been having the same issue with device specs like yours, and same with the logs. Any update?

**Comment by MrData2000** [comment]
I'm now on Homebridge v1.6.0, Node.js v18.16.0, homebridge-govee v8.1.2.
unfortunately same behaviour.
Should i edit the first post and update the versions?

**Comment by bwp91** [comment]
Hi @MrData2000 and @jaidon 

I was hoping you would be able to test a new method for obtaining scene codes I have implemented in the beta version of the plugin. It requires a bit more involvement but hopefully will result in it working properly.

- First please update to the beta version of the plugin (9.0.0-beta.0)
  - https://github.com/bwp91/homebridge-govee/wiki/Beta-Version
- Then follow the first section of this *updated* wiki page to setup and grab the proper codes
  - https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

**Comment by jaidon** [comment]
Works great now! Thank you!

**Comment by bwp91** [comment]
@jaidon do you know if your device commands are going via LAN control?

**Comment by jaidon** [comment]
Yea working great on LAN now also, using H61B2 with LAN control on

**Comment by bwp91** [comment]
What i was hoping to check (since i don’t have a device which supports lan) is that the scene commands are being sent via lan too? is it possible to decipher from the logging?

**Comment by jaidon** [comment]
https://pastebin.com/Y9giiY3z It seems to be sent over LAN instead of AWS

**Comment by bwp91** [comment]
Oh this is amazing news! thanks for that!

**Comment by MrData2000** [comment]
I can confirm that it now works with plugin v9.0.0. I use the "Philips Hue Dimmable Light Switch" and with it I can now switch all 4 Govee H61A0 Light Strips at once via WIFI. The new method for determining the scene codes is challenging, but the main thing is that it works now. Thank you very much for your effort and support!
