### ISSUE TITLE
Changing colour at my H6154 it automatically changes back to 49,49,49 after changing

### ISSUE THREAD

**Issue by NicNic200** [bwp91/homebridge-govee#468]
* **Please explain your feature request in a one or two sentences.**

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

* **Anything else?**

**Comment by NicNic200** [comment]
I have tried all thing from https://github.com/bwp91/homebridge-govee/wiki/Common-Errors  but it still hasnd worked and the Brightness is also not working right

**Comment by bwp91** [comment]
@NicNic200 please update to the new version 9.0.2 and then try the steps again on that wiki page
