### ISSUE TITLE
Add Support for Smart Tower Fan model H7100

### ISSUE THREAD

**Issue by DebasishBahinipati** [bwp91/homebridge-govee#473]
Please Add support for Govee Tower Fan Pro Model H7100.

**Comment by bwp91** [comment]
Hi, please try the new beta version of the plugin
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by DebasishBahinipati** [comment]
yup, the basic functionality works now in the beta version

**Comment by bwp91** [comment]
great
