### ISSUE TITLE
New 42" Fan (Govee Life Smart Tower Fan Pro H7100)

### ISSUE THREAD

**Issue by OttoVonSkidmark** [bwp91/homebridge-govee#474]
* **Please explain your feature request in a one or two sentences.**

I recently received a new model of Govee Smart fan (H7100) and it does not show up through the plugin.  I was wondering if this fan (and its built-in thermometer/hygrometer ) may have a different integration.  I know you won't support new models unless the API changes - but I was curious if this model resulted in a change to the API.

Thanks for an awesome plugin!

* **Is your feature request related to a problem? Please describe.**

No

* **Any particular Govee devices that this relates to?**

H7100 (New fan model)

* **Anything else?**

**Comment by doctarrwho** [comment]
+1 and also adding the log entry about the fan. Duplicate issue #473.

[3/23/2023, 5:24:42 PM] [Govee] [Office Fan] is not currently supported, do create a Github issue with the following info:

{"device":"`<deviceID>`","deviceName":"Office Fan","model":"H7100","httpInfo":{"groupId":0,"device":"`<deviceID>`","sku":"H7100","spec":"","versionHard":"1.02.00","versionSoft":"1.00.13","deviceName":"Office Fan","deviceExt":{"deviceSettings":"{\"wifiName\":\"`<WiFi>`\",\"address\":\"`<Address>`\",\"bleName\":\"ihoment_H7100_5711\",\"topic\":\"GD/d359630d33fde00c5454205e7acae1f6\",\"wifiMac\":\"`<MAC>`\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.13\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"`<SecretCode>`",\"mcuSoftVersion\":\"1.00.03\\u0000\",\"mcuHardVersion\":\"1.00.01\\u0000\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"sku\":\"H7100\",\"device\":\"`<deviceID>`\",\"deviceName\":\"Office Fan\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.13\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/c42ecc5cbfe7123d97bbb0cff74e8c01-add_list_type_device_7100.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":129}}

**Comment by bwp91** [comment]
Hi, please try the new beta version of the plugin
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by OttoVonSkidmark** [comment]
Installed the beta and it works like a charm!  Nice job!
