### ISSUE TITLE
Error on Seemingly Proper Scene Code & Inability to Correct in the Config Editor

### ISSUE THREAD

**Issue by iSteve-O** [bwp91/homebridge-govee#477]
### What issue do you have? Please be as thorough and explicit as possible.
When I installed the latest version it said my scene codes were not configured properly and that I should reconfigure in the UI, however there are no spaces for scene codes in the config UI

### Details of your setup.
I use Homebridge UI-X 

* Which version of Homebridge/HOOBS do you have?
v1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi w/ Node.js v18.15.0 / npm v9.6.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v8.0.1

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6199 & H605B

### Please paste any relevant logs below.

```
[20/03/2023, 23:58:52] [Govee] lightDevices.E6:86:CC:31:30:30:38:2D.videoMode incorrectly configured - please use the config screen to reconfigure this item:
[20/03/2023, 23:58:52] [Govee] lightDevices.E6:86:CC:31:30:30:38:2D.videoMode: 3305000001030032000000000000000000000006
[20/03/2023, 23:58:52] [Govee] Config entry [lightDevices.E6:86:CC:31:30:30:38:2D.videoMode] is not configured correctly so ignoring.
```

Here is my config portion with the scene code:
```
"label": "LG Backlight",
"deviceId": "E6:86:CC:31:30:30:38:2D",
"brightnessStep": 5,
"adaptiveLightingShift": -1,
"videoMode": "3305000001030032000000000000000000000006"
```

See this screenshot where there is nowhere to configure scenes:
![Screen Shot 2023-03-21 at 12 06 25 AM](https://user-images.githubusercontent.com/10133108/226515390-41394cdd-d8ec-4861-bf8a-f5061f5e6581.png)

**Comment by insimbi-stuart** [comment]
I also have this issue, there doesn't seem to be any documentation on what the new scene configuration JSON should look like, and the config interface in UI-X is broken.

**Comment by iSteve-O** [comment]
Version 8.0.2 seems to address this issue. 

New config for scene codes:

```
"label": "LG Backlight",
"deviceId": "E6:86:CC:31:30:30:38:2D",
"brightnessStep": 5,
"adaptiveLightingShift": -1,
"videoMode": {
    "sceneCode": "3305000001030032000000000000000000000006"
    }
```

I appreciate your work on this!

**Comment by bwp91** [comment]
Hi all,
yep 6.0.2 should fix the scene codes in the config screen. 
wanted to make this change to be able to add more options to a particular scene code in the future - for example to expose as a switch instead of an Eve-only button. there’s a lot of home assistant users who have been requesting to expose as a switch instead!
