### ISSUE TITLE
Scenes setup error post 8.02 update

### ISSUE THREAD

**Issue by CadLiara** [bwp91/homebridge-govee#479]
### What issue do you have? Please be as thorough and explicit as possible.

I just updated to version 8.02 and the two video mode scenes I had set up and that were working before ceased to work. I went through the guide here, the instructions in the changelog and erased/redid the process as described but keep getting the same error in the logs. What am I missing?
The two effected devices: 
G1-Pro
Dreamview T1

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Hoobs

* Which version of Homebridge/HOOBS do you have?

Hoobs 4.3 / Homebridge 1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Hoobs Box

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

8.02

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6199 Dreamview T1
H604A G1 Pro

### Please paste any relevant logs below.

```3/22/2023, 7:48:49 PMGVEEGoveeWARNINGlightDevices.DE:BF:C3:33:36:32:39:11.scene incorrectly configured - please use the config screen to reconfigure this item:
3/22/2023, 7:48:49 PMGVEEGoveeWARNINGlightDevices.DE:BF:C3:33:36:32:39:11.scene: 3305000000320032000000000000000000000036
3/22/2023, 7:48:49 PMGVEEGoveeWARNINGConfig entry [lightDevices.DE:BF:C3:33:36:32:39:11.scene] is not configured correctly so ignoring.```
```

```

**Comment by iSteve-O** [comment]
You should either use the configUI to add the scenes or use the new config format as follows (example configure for "video mode" scene):

```
"videoMode": {
    "sceneCode": "3305000000320032000000000000000000000036"
    }
```

**Comment by CadLiara** [comment]
Hey iSteve-O

Thanks for the reply. 
I deleted the code from the UI (under video mode) and added the code you posted in the advanced section. Right now it looks like this:

```"lightDevices": [
        {
            "label": "G1-Pro",
            "deviceId": "DE:BF:C3:33:36:32:39:11",
            "videoMode": {
                "sceneCode": "3305000000320032000000000000000000000036"
            } 
```
            
I looked and the line  - [object Object] - has appeared under video mode in the UI. Other than "label" and "device ID" I don't have any other field filled. 

So now the "error" is gone in the log, but I don't see the scene in the Eve app to then create it for Homekit. What am I missing?

**Comment by iSteve-O** [comment]
> Hey iSteve-O
> 
> Thanks for the reply. I deleted the code from the UI (under video mode) and added the code you posted in the advanced section. Right now it looks like this:
> 
> ```
>         {
>             "label": "G1-Pro",
>             "deviceId": "DE:BF:C3:33:36:32:39:11",
>             "videoMode": {
>                 "sceneCode": "3305000000320032000000000000000000000036"
>             } 
> ```
> 
> I looked and the line - [object Object] - has appeared under video mode in the UI. Other than "label" and "device ID" I don't have any other field filled.
> 
> So now the "error" is gone in the log, but I don't see the scene in the Eve app to then create it for Homekit. What am I missing?

I copied that code from your log & gave it back to you just as an example. The directions for finding the codes & creating scenes in the eve app are still valid. That config looks proper, so now just go to the eve app and make a scene using the G1-Pro device. When making the scene you'll see a switch for "video mode" you'll want to turn on and then turn the on switch on (scenes have 2 on switches, one to include in the scene and one to actually set the scene on or off) and save the scene. 

you'll find the instructions for that on the scene page here -> https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

Good luck!

**Comment by CadLiara** [comment]
Thanks. It took a little tinkering but I was able to get it to work. Couldn't in visual, only advanced by manually inputting lines of code for both devices. 

Appreciate the help ;)

**Comment by bwp91** [comment]
@CadLiara 
if you look in the plugin settings screen now, (on latest version of plugin) can you now visually see what you inputted manually before?
