### ISSUE TITLE
Govee settings in configui not allowing to change to a different device

### ISSUE THREAD

**Issue by kelmers** [bwp91/homebridge-govee#48]
Settings , under my devices, if you try to switch to a second light, the gear just spins. Have seen this since late 1.x version of this plugin (when I started using this). 

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
* 1

* Which version of Homebridge/HOOBS do you have?
1.30 beta53

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
MacOS

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
2.10.2-3

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
All except whichever is the first device shown. Issue only seen when trying to switch to new device in settings webUI.
![spinning settings](https://user-images.githubusercontent.com/35855420/107396958-db93de00-6ac3-11eb-84cb-991d2f5f25a2.PNG)

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @kelmers 

That’s for bringing this to my attention. Never noticed this as I only have one govee device!

Should be fixed in the latest beta.
