### ISSUE TITLE
8.02 being disabled by Hoobs

### ISSUE THREAD

**Issue by wilky761** [bwp91/homebridge-govee#480]
### What issue do you have? Please be as thorough and explicit as possible.
THE GOVEE PLUGIN ISN'T WORKING ANYMORE. SEE LOG. I didn't make any changes to my configuration, and the API key is not included

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
V4.3.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
HOOBS BOX

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
8.0.2

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
ALL OF THEM. NONE OF MY GOVEE DEVICES ARE BEING CONTROLLED.
<img width="1202" alt="Screenshot 2023-03-23 at 08 22 03" src="https://user-images.githubusercontent.com/74021414/227450644-9f7e739a-0ba3-4b1f-908e-6344e3e294b0.png">

**Comment by bwp91** [comment]
Hi, looks like your govee username and password in the plugin config is incorrect? as the logs state it is failing to login

**Comment by wilky761** [comment]
Thanks Ben, not sure how that's happened as I never changed my password, but yes, you're correct. Thanks
