### ISSUE TITLE
Homebridge and HomeKit light brightness are not showing the same, erratic behavior.    When HomeKit is set to 100%, the lights doesn't respond and will come on and off once I bring the brightness down to 0

### ISSUE THREAD

**Issue by pgogins1** [bwp91/homebridge-govee#485]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by andrzejom** [comment]
Hey, I have a similar issue. It is not exactly the same but very similar. I have described that in more detail in the issue under Homebridge repo so I will just post the link not to double the same text on two different sites.

https://github.com/homebridge/homebridge/issues/3344#issue-1646467939
