### ISSUE TITLE
Support for Movie watching DreamView scenes

### ISSUE THREAD

**Issue by NamelessPharaoh** [bwp91/homebridge-govee#486]
In the Govee App with some devices like T2 light strips and Light bar you can sync devices and get what they call Movie watching DreamView
this uses a Sync center and a controlled device, so basically both devices will be on the same scene. 
I cannot manage to uncover the scene to use for this mode. 
Thanks

**Comment by NamelessPharaoh** [comment]
For anyone out there wanting to do the same and sync multiple lights together, and it works when you launch the main from the home app, for the moment you can do it via the Govee automation. 
set it so when the main light is on the scene is on as well. 
the issue is that you can only use your lights in that mode…

**Comment by Sovenger** [comment]
I'm trying to figure out the bluetooth command for the Movie watching dream view on a T1 at the moment. This is proving difficult because the bluetooth-hci-socket node package has errors on installing.

**Comment by bwp91** [comment]
what can i do to try and help?

**Comment by Newgit2025** [comment]
Hello, i'm having a similar problem:
i see correctly the goove strip led in homekit.
here there is the problem: is use the strip led in dreamview (it change based on the image displayed in the tv) if I say to siri to turn it on/off it works and it is always in dreamview mode but if I include the strip led in a Homekit automation it turns on in a normal color status (red). Why is that? please help me. I'm not an expert of coding.
