### ISSUE TITLE
H6199 doesn’t retain last settings when turned on

### ISSUE THREAD

**Issue by FranciRoosters** [bwp91/homebridge-govee#487]
### What issue do you have? Please be as thorough and explicit as possible.

Every time I turn on my H6199, the light strip reverts back to Color instead of retaining Videos, the last setting before turning off. 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge with config-ui

* Which version of Homebridge/HOOBS do you have?

1.6.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

8.1.1. No, it was there before, just happened less often.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6199

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi, will look into this but just wanted to rule out one thing:

if you have adaptive lighting turned on in the home app then sometimes the plugin will continue this routing when you turn a light back on.

Are you able to confirm that your issue still happens even when you definitely don’t have adaptive lighting turned on in the home app?

**Comment by FranciRoosters** [comment]
Knock on wood, but the lightstrip hasn’t reverted to the Color setting in the last 48 hours. Maybe having deleted and recreated the automation that would turn on the lightstrip when my TV would turn on has fixed it. 🤷‍♂️
