### ISSUE TITLE
Auto stop button for H7130 heater

### ISSUE THREAD

**Issue by daigoi** [bwp91/homebridge-govee#488]
* **Please explain your feature request in a one or two sentences.**
 
It would be great if you can add a switch for the auto stop function in the thermostat mode. The auto mode in HomeKit now enables the thermostat mode in Govee (thank you!) but it does not turn on auto stop mode. These are photos of HomeKit and Govee app when I set the heater to the auto mode just in case. 

![IMG_2188](https://user-images.githubusercontent.com/65671473/230820471-4e24ccae-beba-4bbc-8553-bba09ff655e7.png)
![IMG_2189](https://user-images.githubusercontent.com/65671473/230820475-81194d3e-5856-4f2c-ad40-eb1c26eae80f.png)

* **Is your feature request related to a problem? Please describe.**

No, but it would be a great improvement. 

* **Any particular Govee devices that this relates to?**

Smart heater H7130

* **Anything else?**

**Comment by willykev** [comment]
Same request. I rely on this feature so much that I can't use this plugin without it. Will just have to revert back to the govee app.
