### ISSUE TITLE
'externalUpdate' and 'eveService' error logs with v2.11.0 upgrade

### ISSUE THREAD

**Issue by pranitl** [bwp91/homebridge-govee#49]
### What issue do you have? Please be as thorough and explicit as possible.

On my central Homebridge log status dashboard, I am seeing a flood of the log entries below for the 4 switches I have from Govee ever 10-15 seconds. After trying to trace down which specific version this issue it started from by reinstalling previous versions, this only came up on v2.11.0. I had to downgrade to avoid the Homebridge log cluttering up.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

(1) Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?

v1.2.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

v2.11.0. Yes it has started only since this upgrade from v2.10.1

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H5081 Switches

### Please paste any relevant logs below.

```
[2/9/2021, 8:06:36 PM] [Govee] [Router] could not be refreshed as Cannot read property 'externalUpdate' of undefined at /homebridge/node_modules/homebridge-govee/lib/index.js:335:29.
[2/9/2021, 8:06:51 PM] [Govee] [Router] could not be initialised as Cannot read property 'eveService' of undefined at new deviceSwitch (/homebridge/node_modules/homebridge-govee/lib/device/switch.js:36:51).
```

**Comment by bwp91** [comment]
Hi @rasterize-art 

Thanks for alerting me to this.

I have fixed this issue in v2.11.1 so it's safe to update!
