### ISSUE TITLE
Support for H61C3 Neon Rope Lights

### ISSUE THREAD

**Issue by LoresLabyrinth** [bwp91/homebridge-govee#491]
* **Please explain your feature request in a one or two sentences.**

Add support for H61C3

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

* **Anything else?**

{"device":"20:C6:38:32:31:74:6C:FF","deviceName":"RGBIC Neon Rope Lights","model":"H61C3","httpInfo":{"groupId":0,"device":"20:C6:38:32:31:74:6C:FF","sku":"H61C3","spec":"","versionHard":"3.01.10","versionSoft":"3.03.23","deviceName":"RGBIC Neon Rope Lights","deviceExt":{"deviceSettings":"{\"wifiName\":\"Helluva Router\",\"address\":\"C6:38:32:31:74:6C\",\"bleName\":\"Govee_H61C3_746C\",\"topic\":\"GD/88684961fc7165d339e21cc9e8ac38b4\",\"wifiMac\":\"D4:AD:FC:E7:23:6C\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"\",\"wifiHardVersion\":\"\",\"ic\":34,\"secretCode\":\"stzGODIxdGw=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"sku\":\"H61C3\",\"device\":\"20:C6:38:32:31:74:6C:FF\",\"deviceName\":\"RGBIC Neon Rope Lights\",\"versionHard\":\"3.01.10\",\"versionSoft\":\"3.03.23\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/f5ec32d31356ace478047a328fc1d2eb-add_list_type_device_61c3.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/4addaa687b6920b78bce6dfb5ee6c1d7-new_switch_pics_h61c3_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/c6c97026272130282beb41c00e35b204-new_switch_pics_h61c3_off.png\",\"ext\":\"\",\"ic\":42}"},"pactType":1,"pactCode":1,"goodsType":141}}

**Comment by LoresLabyrinth** [comment]
Sorry in advance if I'm not doing this right, it's my first time on GitHub.

**Comment by bwp91** [comment]
All good 👍🏻 let me see what i can do

**Comment by bwp91** [comment]
Can you follow the instructions here to update to the beta version of the plugin, and hopefully this device should be working?
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Let me know how you get on!

**Comment by LoresLabyrinth** [comment]
Wow that was fast!!! It works like a charm, thank you so much!

**Comment by bwp91** [comment]
Nice 👍🏻 enjoy! will close this now
