### ISSUE TITLE
Requesting support for new Govee RGBIC Gaming Lights

### ISSUE THREAD

**Issue by Abhi-devrepo** [bwp91/homebridge-govee#496]
* **Please explain your feature request in a one or two sentences.**
Requesting support for new Govee RGBIC Gaming Lights
I was prompted to create a issue by the Homebridge plugin

[Govee] [Desk light] is not currently supported, do create a Github issue with the following info:

`{"device":"C7:D8:38:32:31:0C:3F:FF","deviceName":"Desk light","model":"H61C3","httpInfo":{"groupId":0,"device":"C7:D8:38:32:31:0C:3F:FF","sku":"H61C3","spec":"","versionHard":"3.01.10","versionSoft":"3.03.23","deviceName":"Desk light","deviceExt":{"deviceSettings":"{\"wifiName\":\"REDACTED\",\"address\":\"D8:38:32:31:0C:3F\",\"bleName\":\"Govee_H61C3_0C3F\",\"topic\":\"GD/dd439febb47a3ee47adc72bcfc4f8275\",\"wifiMac\":\"D4:AD:FC:C8:C3:58\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"\",\"wifiHardVersion\":\"\",\"ic\":42,\"secretCode\":\"fZ3YODIxDD8=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"sku\":\"H61C3\",\"device\":\"C7:D8:38:32:31:0C:3F:FF\",\"deviceName\":\"Desk light\",\"versionHard\":\"3.01.10\",\"versionSoft\":\"3.03.23\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/f5ec32d31356ace478047a328fc1d2eb-add_list_type_device_61c3.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/4addaa687b6920b78bce6dfb5ee6c1d7-new_switch_pics_h61c3_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/c6c97026272130282beb41c00e35b204-new_switch_pics_h61c3_off.png\",\"ext\":\"\",\"ic\":42}"},"pactType":1,"pactCode":1,"goodsType":141}}`

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Govee devices that this relates to?**
https://www.amazon.com/gp/product/B0BXNCRPS1/

* **Anything else?**
Thanks a lot for all the work you do for the community

**Comment by bwp91** [comment]
please install the beta version of the plugin, this device should show :)

**Comment by Abhi-devrepo** [comment]
Thanks a lot, yes it works on 8.1.3-beta.1
