### ISSUE TITLE
H6089 needs to be added to no scale brightness

### ISSUE THREAD

**Issue by J-Hoffman** [bwp91/homebridge-govee#5]
**What issue do you have? Please be as thorough and explicit as possible.**
The brightness gets set to 39% in HomeKit because it is being divided by 2.54. 
...

**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge
...

Which version of Homebridge/HOOBS do you have?
1.1.6
...

Which version of this plugin (homebridge-govee) do you have?
2.0.1
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.
[Main Light] could not be updated and its status will be reverted so on. Error: Request failed with status code 400.
...

**Comment by bwp91** [comment]
All done. Please update to v2.0.2 and this should be fixed.
Thanks for alerting me of this!
