### ISSUE TITLE
Request to add support for getting thermo-hygrometer readings from H7101 smart tower fan when a thermo-hygrometer is bound to it

### ISSUE THREAD

**Issue by emassey0135** [bwp91/homebridge-govee#501]
* **Please explain your feature request in a one or two sentences.**

The Govee H7101 tower fan allows you to connect a thermo-hygrometer directly to it, and if its readings are available in the API under the fan instead of under the thermo-hygrometer, it would be useful to add support for obtaining temperature and humidity readings from the fan to allow some thermo-hygrometer models that do not make new data available without opening the app to automatically send temperature and humidity readings to HomeKit.

* **Is your feature request related to a problem? Please describe.**

My H7101 tower fan came with an H5177 thermo-hygrometer, which is one of the models that does not support connecting to WiFi. I have both devices added in the Govee app, and when I enabled this plugin both devices appeared in HomeKit. However, the temperature and humidity readings do not automatically update. At first, HomeKit showed temperature and humidity readings from around 6 months ago, since that was the last time I opened the thermo-hygrometer in the Govee app. When I opened it in the app, it displayed this old data for like 15 seconds until it finished refreshing, and then the updated readings also appeared in HomeKit. When I closed the app and waited, the temperature and humidity readings stopped updating again, and in the Eve app, the history view for the device only shows readings for the times the thermo-hygrometer was refreshed in the Govee app. However, since I have bound my thermo-hygrometer with the tower fan, the page for the tower fan in the Govee app displays current temperature and humidity readings from the thermo-hygrometer instantly without the 15 second refresh time.

* **Any particular Govee devices that this relates to?**

The H7101 tower fan and H5177 thermo-hygrometer

* **Anything else?**

Since the H5177 only supports Bluetooth and not WiFi, I would guess that when I open the device in the Govee app, the app is connecting to the thermo-hygrometer over Bluetooth and uploading the readings to the Govee cloud where this plugin retrieves it, but the device cannot upload its readings to the cloud by itself. However, since the fan is connected to WiFi and can be controlled through the cloud without the app open, and the app displays the readings from a thermo-hygrometer connected to it very quickly, the fan seems to be periodically uploading these readings to Govee. Also, the H5177 is not listed as supported by this plugin at all, so I have not tried BLE mode.

**Comment by bwp91** [comment]
Hi @emassey0135 are you running homebridge on a platform that supports bluetooth? I think the first think to potentially sort out is the plugin working with the H5177 over BLE

> Also, the H5177 is not listed as supported by this plugin at all, so I have not tried BLE mode.

This is only because support has never been confirmed

**Comment by emassey0135** [comment]
Yes, I am running Homebridge on a Raspberry Pi 400 running Arch Linux ARM. How should I enable BLE for the H5177? Under "Thermo devices", I tried to add the device ID of my thermometer, but in the settings list that appears there is no option for enabling BLE for the device.

**Comment by bwp91** [comment]
you shouldn't _need_ to enable the ble support for this device, so long as ble is compatible on your homebridge then it should be scanning.

^ having said this it is never been confirmed for the H5177 but interested in the result

can you restart the plugin and post your initial plugin logs? of course remove any device ids etc as necessary

**Comment by emassey0135** [comment]
The log said that BLE was disabled, and it turns out that I didn't have Bluez installed and I also needed to enable a parameter in config.txt to make the kernel recognize the Bluetooth controller, but after I fixed that, the plugin says BLE is enabled in the logs. New values are printed now for the thermometer for temperature and humidity in the log beyond the initial sync, so it seems that BLE is working with the H5177! This fixes my problem, thank you.

**Comment by bwp91** [comment]
nice! does this device report temperature and humidity? do the values seem to report okay in the homebridge log and homebridge itself? if so i can add this device to the supported list 👍🏻

**Comment by bwp91** [comment]
also for the purposes of documentation, 

could you elaborate on this?

 I also needed to enable a parameter in config.txt to make the kernel recognize the Bluetooth controller

**Comment by emassey0135** [comment]
Yes, in the Homebridge UI, it shows both temperature and humidity readings from the H5177 that are up to date. In the Home app's climate page, it shows temperature and humidity readings from this thermometer along with readings from my HomePod Mini, and when I ask the HomePod for the temperature and humidity in the room, it either just says the temperature or humidity if both devices report the same value, or says something like "The humidity is low in the bedroom, at about 26 to 32%" when the devices' readings are different. Also, the Eve app now shows the temperature and humidity values from the H5177 changing a little over time instead of always being the exact same value. The temperature from the H5177 now matches the temperature from the HomePod Mini, which makes me confident that the readings are correct, although the humidity is different between the two by 6%, but that probably has to do with the thermometer itself or possibly where it is placed.

On Raspberry Pis, config.txt is used to configure the Raspberry Pi bootloader, including passing device tree parameters to the kernel. The bluetooth controller seems to be disabled by default, at least on Arch Linux ARM with the 64-bit Raspberry Pi kernel (not U-boot), and to enable it you must add the option "dtparam=krnbt=on" to config.txt. There does not seem to be any official documentation of this parameter, but there is a discussion of it [here](https://forums.raspberrypi.com/viewtopic.php?t=322229). This might only be necessary for Arch Linux ARM 64-bit using the non-U-boot Raspberry Pi kernel, but I am not sure since I have not used other distributions or kernels on a Raspberry Pi 4 in a few years.

**Comment by emassey0135** [comment]
As of today, new readings from the thermometer are still being frequently updated in HomeKit! Also, for documentation or advertisement purposes, as of now HomeKit with Homebridge might be the only smart home system to support the H5177, since it does not show up at all in Alexa or Google Home with the official integrations.

**Comment by bwp91** [comment]
Great news!
And thanks for the lengthy explanation by the way. Might put a link to this in a wiki somewhere!
So i guess i’d like to confirm one more thing:
- in cases like this where you can pair a BLE-only thermo-sensor device like the H5177 - to the H7101 fan in this case - I assume the H7101 has a bluetooth module which can read from the sensor and update the values to the cloud, even when the sensor itself cannot update to the cloud until the govee app is opened (and data is synced) ? (since obviously the H7101 has a wifi module too)

**Comment by emassey0135** [comment]
Yes, this seems to be the case. The purpose of this pairing feature is to allow the fan to automatically turn on and off or change speed based on changes in temperature, but after pairing the Govee app shows updated temperature readings from the H5177 very quickly after opening the page for the H7101, far quicker than opening the page for the H5177 and waiting for readings to refresh. However, this behavior in the app is pretty much the only evidence I have for this because Govee has not added support for sending these readings to Alexa or Google Home.

**Comment by emassey0135** [comment]
I at least know for certain that the fan acquires readings from the H5177 over BLE since the fan can change its settings based on temperature after it is paired with it without the app being open, and BLE seems like the only way to obtain live readings from the H5177. The fan uploading this data to the cloud over WiFi is a bit less certain but seems very probable.
