### ISSUE TITLE
OpenSSL installation 

### ISSUE THREAD

**Issue by DanMarkwood** [bwp91/homebridge-govee#503]
When I click on the link for these instructions, the page is blank. Can you point me to the instructions?

**Comment by DanMarkwood** [comment]
I give up!

**Comment by bwp91** [comment]
why giving up?

**Comment by DanMarkwood** [comment]
I run Homebridge on a Windows 10 laptop and spent three days reading through your issues to try to get OpenSSL working. I installed OpenSSL per the instructions I found but nothing has worked.

**Comment by bwp91** [comment]
Did you stumble across this comment at all?
https://github.com/bwp91/homebridge-govee/issues/405#issuecomment-1513506027

**Comment by DanMarkwood** [comment]
Yes, I did all of those suggestions but it still didn’t work for me.
