### ISSUE TITLE
Scene, Music, DIY Modes - Without Eve App or HomeKit Scenes

### ISSUE THREAD

**Issue by BeardedWonderDev** [bwp91/homebridge-govee#507]
First a huge thank you for the amazing work on the plugin!! 

This plugin is actually the only reason I still utilize Homebridge as I have migrated everything else to Home Assistant. Unfortunately Govee support within Home Assistant is not nearly is well supported as what you have done with this plugin which leads me to my request.

Is there any way to have the scene, music, and diy modes created as accessories within Homebridge instead of just utilizing Eve scenes?

The problem I am having is that Home Assistant does not support HomeKit Scenes making the current setup unusable for scenes.

Thanks for all your hard work!

**Comment by bwp91** [comment]
Hi @BoiseITGuru yes please see this thread:

https://github.com/bwp91/homebridge-govee/issues/462

**Comment by bwp91** [comment]
don’t forget to show off my plugin to all home assistant users 😉
