### ISSUE TITLE
No color changing on h6141

### ISSUE THREAD

**Issue by Gotcha182** [bwp91/homebridge-govee#508]
### Details of your setup.
Homebridge with ui 

* Which version of Homebridge/HOOBS do you have?
1.6.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

9.0.0 but has been an issue for the past few releases

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
 H6141 light strip

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @Gotcha182 please check this wiki article for colours not working:
https://github.com/bwp91/homebridge-govee/wiki/Common-Errors

**Comment by anshumanbhatia** [comment]
Have the same issue, these previously used to work just fine. Nothing changed in my setup and I don't have color control.

**Comment by bwp91** [comment]
Hi @anshumanbhatia did you check the other comments on here? Please see:

https://github.com/bwp91/homebridge-govee/wiki/Common-Errors#colour-issues

**Comment by anshumanbhatia** [comment]
Thanks! Appears solved for me, surprised I had to change something after a few years of solid use but no bother, thanks for the awesome plug in!

**Comment by bwp91** [comment]
> Thanks! Appears solved for me, surprised I had to change something after a few years of solid use but no bother, thanks for the awesome plug in!

Normally i’ve been able to detect different device parameters per model, and included this into the plugin, but recently it seems that there are differences even between the same models, so i
possible for me to detect, so it’s easier to add the “differences” into the plugin config, which means in some cases it would affect existing users 😬

**Comment by bwp91** [comment]
gonna close this, please reopen if any issues still persist
