### ISSUE TITLE
1 of 2 strips (same model) not work in HomeKit

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-govee#51]
Hi, after last update 1 of 2 strips are not working. In HomeKit the icon switch on and off correctly but this not really switch the strip.
Ok Govee app normally works fine.
Pasted the log (check "Ingresso")

5/2/2021, 13:46:07 [Govee] [Ingresso] ignoring update [{"online":"false","powerState":"off","brightness":101,"colorTemInKelvin":9000}].
15/2/2021, 13:46:08 [Govee] [Ingresso] sending update {"name":"turn","value":"on"}.
15/2/2021, 13:46:08 [Govee] [Ingresso] current state [on].
15/2/2021, 13:46:11 [Govee] [Ingresso] sending update {"name":"turn","value":"off"}.
15/2/2021, 13:46:11 [Govee] [Ingresso] current state [off].
15/2/2021, 13:46:16 [Govee] [Ingresso] sending update {"name":"turn","value":"on"}.
15/2/2021, 13:46:16 [Govee] [Ingresso] current state [on].
15/2/2021, 13:46:22 [Govee] [Ingresso] ignoring update [{"online":"false","powerState":"off","brightness":101,"colorTemInKelvin":9000}].
15/2/2021, 13:46:22 [Govee] [Letto] received update [{"online":true,"powerState":"off","brightness":5,"color":{"r":78,"b":214,"g":41}}].
15/2/2021, 13:46:37 [Govee] [Letto] received update [{"online":true,"powerState":"off","brightness":5,"color":{"r":78,"b":214,"g":41}}].
15/2/2021, 13:46:37 [Govee] [Ingresso] ignoring update [{"online":"false","powerState":"off","brightness":101,"colorTemInKelvin":9000}].
15/2/2021, 13:46:41 [Govee] [Ingresso] sending update {"name":"turn","value":"off"}.
15/2/2021, 13:46:41 [Govee] [Ingresso] current state [off].
15/2/2021, 13:46:52 [Govee] [Letto] received update [{"online":true,"powerState":"off","brightness":5,"color":{"r":78,"b":214,"g":41}}].
15/2/2021, 13:46:52 [Govee] [Ingresso] ignoring update [{"online":"false","powerState":"off","brightness":101,"colorTemInKelvin":9000}].

**Comment by Stetocasa** [comment]
![image](https://user-images.githubusercontent.com/70729310/107948865-b526e480-6f94-11eb-81fb-e5e1ee69b486.png)

**Comment by bwp91** [comment]
Please check your logs:

```
5/2/2021, 13:46:07 [Govee] [Ingresso] ignoring update [{"online":"false","powerState":"off","brightness":101,"colorTemInKelvin":9000}].
15/2/2021, 13:46:22 [Govee] [Ingresso] ignoring update [{"online":"false","powerState":"off","brightness":101,"colorTemInKelvin":9000}].
15/2/2021, 13:46:22 [Govee] [Letto] received update [{"online":true,"powerState":"off","brightness":5,"color":{"r":78,"b":214,"g":41}}].
15/2/2021, 13:46:37 [Govee] [Letto] received update [{"online":true,"powerState":"off","brightness":5,"color":{"r":78,"b":214,"g":41}}].
15/2/2021, 13:46:37 [Govee] [Ingresso] ignoring update [{"online":"false","powerState":"off","brightness":101,"colorTemInKelvin":9000}].
15/2/2021, 13:46:52 [Govee] [Letto] received update [{"online":true,"powerState":"off","brightness":5,"color":{"r":78,"b":214,"g":41}}].
15/2/2021, 13:46:52 [Govee] [Ingresso] ignoring update [{"online":"false","powerState":"off","brightness":101,"colorTemInKelvin":9000}].
```

You can see that Govee is reporting the 'Letto' as online but 'Ingresso' as offline.

This is why the device isn't being updated - for some reason Govee is reporting the device as offline.

The Govee app is possibly using bluetooth to control the device which is why this is working. Try disabling bluetooth on your phone and controlling 'Ingresso' (which will force it to use Wifi)

Check the wifi connection of the 'Ingresso' device and also using Home app to control the device again once the log line 

```
[Govee] [Ingresso] ignoring update [{"online":"false", ...
```

changes to:

```
[Govee] [Ingresso] receiving/ignoring update [{"online":"true", ...
```

**Comment by bwp91** [comment]
In your screenshot you can see one of the devices is not connected to wifi by the red icon
