### ISSUE TITLE
Video / Movie mode in version 9.x 

### ISSUE THREAD

**Issue by CadLiara** [bwp91/homebridge-govee#511]
### What issue do you have? Please be as thorough and explicit as possible.

Before upgrading to version 9.x I read the changelog and followed the instructions on the wiki to familiarize myself with the process prior to the update. I saw how the process to find/enable scenes now happens through the Govee app, but when I tried it out in the Govee app, I didn't find movie/video or game modes available through that process for devices that have them and which are functioning fine already such as my T1 Dreamview TV lighting or my G1 Pro computer lights. I can see how one would use this method to set up any other scene, but am hesitant to update and potentially lose these modes as they are working now. What am I missing?

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

4.3

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

HOOBS Box

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

1.6 / No/NA

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

G1 Pro H604A
Dreamview T1 H6199

### Please paste any relevant logs below.

```

```

**Comment by CadLiara** [comment]
If anyone who is running 9.x and using any of the T1, T2, G1 or other video/movie mode enabled devices, can you chime in whether you are seeing any issues post update, and what was your process for getting these modes into homekit? Thanks

**Comment by CadLiara** [comment]
Can confirm. The update broke the ability to create a video mode scene.  @bwp91 any ideas or updates on this?

**Comment by bwp91** [comment]
Don’t suppose you still have the old code you used @CadLiara ?
Also could be useful to chat on discord if you are on there?

**Comment by CadLiara** [comment]
Old code? If you mean the “33xyz….” Indeed I do. I saved it prior to the update just in case.Not on discord but I guess I can sign up.On May 22, 2023, at 11:16 AM, Ben ***@***.***> wrote:﻿
Don’t suppose you still have the old code you used @CadLiara ?
Also could be useful to chat on discord if you are on there?

**Comment by bwp91** [comment]
can you send me the whole code?

**Comment by CadLiara** [comment]
> can you send me the whole code?

You got it:

For G1 Pro (H604A): 330500004703002e00000000000000000000005c
For T1 (H6199):  3305000000320032000000000000000000000036

**Comment by bwp91** [comment]
- for 1, please try this code `MwUAAEcDAC4AAAAAAAAAAAAAAFw=`
- for 2, please try this code `MwUAAAAyADIAAAAAAAAAAAAAADY=`

So just to confirm, these modes dont appear when following the wiki instructions?

**Comment by CadLiara** [comment]
Correct.I have them set up in configuration using the codes I provided and nada in Eve or otherwise.I’ll try the codes you provided and report back.On May 25, 2023, at 11:42 AM, Ben ***@***.***> wrote:﻿

for 1, please try this code MwUAAEcDAC4AAAAAAAAAAAAAAFw=
for 2, please try this code MwUAAAAyADIAAAAAAAAAAAAAADY=

So just to confirm, these modes dont appear when following the wiki instructions?

**Comment by CadLiara** [comment]
Just tried em (replacing the old 33 codes with the ones you provided) under the video mode in configuration, and voila, back to working fine. 
How can I reproduce getting such codes that aren't provided for (per the instructions in the wiki) in the Govee app in the future? I don't want to bug you for it.

**Comment by bwp91** [comment]
In this case since you already had the codes from before, all that is necessary is to convert them from hex to base64:
- https://base64.guru/converter/encode/hex

The reason I mentioned discord before was to message you in a bit more depth about looking to see if there was a way to obtain these codes, without having to know them in the first place (like in this case!)

**Comment by CadLiara** [comment]
Got it. Gonna sign up to be ready for the next time (just in case.)On May 25, 2023, at 2:18 PM, Ben ***@***.***> wrote:﻿
In this case since you already had the codes from before, all that is necessary is to convert them from hex to base64:

https://base64.guru/converter/encode/hex

The reason I mentioned discord before was to message you in a bit more depth about looking to see if there was a way to obtain these codes, without having to know them in the first place (like in this case!)

**Comment by CadLiara** [comment]
Rude me.Forgot to say; THANK YOU!On May 25, 2023, at 2:18 PM, Ben ***@***.***> wrote:﻿
In this case since you already had the codes from before, all that is necessary is to convert them from hex to base64:

https://base64.guru/converter/encode/hex

The reason I mentioned discord before was to message you in a bit more depth about looking to see if there was a way to obtain these codes, without having to know them in the first place (like in this case!)
