### ISSUE TITLE
Requesting addition of Humidifier H7143

### ISSUE THREAD

**Issue by CharlieLovesMe** [bwp91/homebridge-govee#515]
### What issue do you have? Please be as thorough and explicit as possible.

{"device":"2D:00:D4:AD:FC:50:F6:74","deviceName":"Warm/Cool Humidifier","model":"H7143","httpInfo":{"groupId":4671427,"device":"2D:00:D4:AD:FC:50:F6:74","sku":"H7143","spec":"","versionHard":"1.02.00","versionSoft":"1.00.14","deviceName":"Warm/Cool Humidifier","deviceExt":{"deviceSettings":"{\"wifiName\":\"EvilDead\",\"address\":\"D4:AD:FC:50:F6:75\",\"bleName\":\"ihoment_H7143_F675\",\"topic\":\"GD/65885048e9aaa11d194288f4a7ed06fb\",\"wifiMac\":\"D4:AD:FC:50:F6:74\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.14\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"bRgaCA1wEQM=\",\"waterShortageOnOff\":1,\"mcuSoftVersion\":\"1.00.08\",\"mcuHardVersion\":\"1.00.01\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"sku\":\"H7143\",\"device\":\"2D:00:D4:AD:FC:50:F6:74\",\"deviceName\":\"Warm/Cool Humidifier\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.14\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/0d4086f8bc400798679b4b9fb8d3d21f-add_list_type_device_7143.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":126}}

**Comment by bwp91** [comment]
Hi @CharlieLovesMe 

Please can you update to the beta version of the plugin? Guide here:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

let me know if this device seems to work with the plugin!

thanks

**Comment by CharlieLovesMe** [comment]
This worked, thank you!
