### ISSUE TITLE
H6006 Support

### ISSUE THREAD

**Issue by anthonymkz** [bwp91/homebridge-govee#516]
* **Please explain your feature request in a one or two sentences.**
Support for H6006 WiFi/BLE bulbs

* **Is your feature request related to a problem? Please describe.**
I bought these by accident thinking they were the same as my H6009 bulbs and was surprised to see they're not supported by the plugin. I'm not sure why since they are also WIFI and Bluetooth

* **Any particular Govee devices that this relates to?**
H6006

**Comment by bwp91** [comment]
Hi @anthonymkz 

Please install the beta version of the plugin, docs at
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

This should get this model working

**Comment by anthonymkz** [comment]
This worked like a charm. Thank you so much and thanks for all your hard work!
