### ISSUE TITLE
H61E0 Support

### ISSUE THREAD

**Issue by schmidt787** [bwp91/homebridge-govee#517]
* **Please explain your feature request in a one or two sentences.**
The new H61E0 Device (M1 Lightstrip with new Matter Controller) is not supported yet. Would you support it, even it has Matter Support?

* **Is your feature request related to a problem? Please describe.**
The log says that the H61E0 is not supportet and I should make a ticket here.

* **Any particular Govee devices that this relates to?**
H61E0 Lightstrip

**Comment by bwp91** [comment]
Hi @schmidt787 

Please install the beta version of the plugin, docs:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Note that this will still use the cloud to control the device rather than matter

**Comment by schmidt787** [comment]
Thank you for the fast response. I've tried to install the beta. But there was a problem with the installation. I'll test again today's evening and post more from the problem.

**Comment by schmidt787** [comment]
So now I try to fix the problem and I got the 2 H61E0 to work. The number of percent is different at first and need some time to get to the right number. But other functions are working. So thank you form making your software ready for the H61E0!

**Comment by bwp91** [comment]
Hi @schmidt787 

I don't understand this:

> The number of percent is different at first and need some time to get to the right number.

Do you mean brightness?
