### ISSUE TITLE
Please enable support for the Govee H6006 LED bulb

### ISSUE THREAD

**Issue by ykoval34** [bwp91/homebridge-govee#522]
Hi,
Thank you so much for the support and product that you’ve created. I was hoping to request support for the Govee H6006 LED bulb which isn’t included in the supported list. 
Thanks again!

**Comment by bwp91** [comment]
Hi @ykoval34 
Please see https://github.com/bwp91/homebridge-govee/issues/516 with instructions to update to the beta version of the plugin

**Comment by bwp91** [comment]
Having said that, please update to the latest version of the plugin instead

**Comment by ykoval34** [comment]
Wow, that was fast! Thank you so much! It works flawlessly. 
:)
