### ISSUE TITLE
H7130 Heater Support for advanced feature like temperature setting

### ISSUE THREAD

**Issue by DBahinipati** [bwp91/homebridge-govee#525]
Currently Heater Model H7130 supports only turn on or off as a fan but no option to read tempratures and set tempratures like other heater. Below is the log as well from Home bridge. Currently for this model it shows as a fan and only control the speed, turn on/off is possible

[Govee] [Smart Heater 4] you should enable `tempReporting` in the config for this device.

**Comment by bwp91** [comment]
Have you done what the log says?

**Comment by DBahinipati** [comment]
yup, that gives the temperature on the homekit icon but still no option to set a temperature for a heater. Still shows as a fan with temperature reading.

**Comment by bwp91** [comment]
How does the accessory appear in the homebridge ui? as a fan? or a heater?

**Comment by DBahinipati** [comment]
![image](https://github.com/bwp91/homebridge-govee/assets/15758000/360cea00-856a-4a17-81a1-a43d6addf04e)
![image](https://github.com/bwp91/homebridge-govee/assets/15758000/18e65615-e57b-446c-b557-a04c3fec7824)

**Comment by DBahinipati** [comment]
After adding the config to show temperature, the main icon changed but after clicking on it, still shows the fan.

**Comment by DBahinipati** [comment]
No Sure why it took time in homekit, but now it is showing me option as a heater to set temperature. Thank you for your time.
