### ISSUE TITLE
Trying to integrate scene into homebridge's plugin, BLE undefined

### ISSUE THREAD

**Issue by kamalmplus** [bwp91/homebridge-govee#528]
### What issue do you have? Please be as thorough and explicit as possible.
Trying to integrate the scenes into homebridge, following the instructions to fine the code after configuring 'Tap to Run'
the logs show now AWS command, only BLE followed by 'undefined'

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

HB on raspberry Pi, node -v = [v18.16.0]

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v9.1.0, first try, cannot say it started from upgrading.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6182

### Please paste any relevant logs below.

``` 
[20/06/2023, 22:57:57] [Govee] [H6182_F18E] [Music] [BLE] undefined
[20/06/2023, 22:57:57] [Govee] [H6182_F18E] [Glow] [BLE] undefined
```

```

**Comment by bwp91** [comment]
Hi @kamalmplus sorry taken a while to get back to you, is this still something you are looking to do?

**Comment by kamalmplus** [comment]
Yes, that is correct

**Comment by bwp91** [comment]
Can you update to beta version 9.2.1-beta.X?

and then show the output of just before you see these messages in the log?

```
[20/06/2023, 22:57:57] [Govee] [H6182_F18E] [Music] [BLE] undefined
[20/06/2023, 22:57:57] [Govee] [H6182_F18E] [Glow] [BLE] undefined
```
