### ISSUE TITLE
sync process failed 

### ISSUE THREAD

**Issue by skir0cket** [bwp91/homebridge-govee#53]
hi I seem to be getting the errors listed below, im currently on homebridge v1.3.1  and v2.12.2 of the govee plugin 

Sync process failed as timeout of 10000ms exceeded at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15)

[Tv lights] could not be refreshed as timeout of 10000ms exceeded at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15)

**Comment by bwp91** [comment]
Hi @skir0cket 
This is a message that shows if the plugin is having trouble contacting the Govee servers during the background sync.
If you see this message now and again there is nothing to worry about as the plugin will try again on the next background sync run.
In the next version of the plugin I will change the message to explain better that the plugin will try again.
Are you getting the error a lot?

**Comment by skir0cket** [comment]
Hi thanks for the info! its been ok today but yesterday I noticed its more often.

**Comment by bwp91** [comment]
I think it’s sometimes a small issue with the Govee servers as a lot of people including myself on occasions seem to get this message.
Just need to reword the log message so it makes it more obvious it’s not a real problem and the plugin will continue to do its syncing!

**Comment by skir0cket** [comment]
ok cool, I seem to be having a problem with the plugin disabling itself now though. 

[Govee] ***** Disabling plugin [v2.12.2]. *****

**Comment by bwp91** [comment]
There must be more logs before and after?

**Comment by skir0cket** [comment]
all I have is ***** timeout of 10000ms exceeded at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15). ***** after it comes up its disabling plugin its started happening after updating NPM to v7.6.0 if that makes any difference 

Edit 
restarted homebridge and its loaded the plugin. seems to be working at the minute.

**Comment by bwp91** [comment]
I was going to suggest restarting Homebridge as this is the only way of rectifying this at the moment.
I’ll look into a way of automatically trying the connection again to govee on the plugin startup rather than disabling in the event of error!

**Comment by bwp91** [comment]
The next version of the plugin will:

* Retry requests (in certain cases like you encountered) to Govee on plugin startup rather than disabling the plugin
* Make the log messages clearer that the plugin will retry (ie it's no real bother and the plugin will continue to function)

Unfortunately there is nothing I can do about the intermittent Govee server issues except work-arounds like the points above.

Thanks!
