### ISSUE TITLE
Govee lighting not working in Homebridge and Homekit

### ISSUE THREAD

**Issue by STENEB** [bwp91/homebridge-govee#530]
### What issue do you have? Please be as thorough and explicit as possible.

ive set up the govee plugin as normal and everything has showed up and connected but i cant control the lights within homebridge or homekit. it does not say "not responding" i can interact with it in homekit and homebridge but the lights do nothing. ive tried restarting and reinstalling but that has done nothing. when installing an error came up but i do not know what it means i tried looking it up but ive found nothing on it 

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth_hci_socket-0.5.3-8-node-v108-linux-arm.tar.gz 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

im not sure where to see this 

* Which version of Homebridge/HOOBS do you have?

homebridge v1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 
Node.js v18.16.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee v9.1.0
just installed 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Tv LED back ligths 
Model H6199

### Please paste any relevant logs below.
 node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth_hci_socket-0.5.3-8-node-v108-linux-arm.tar.gz 

``` 

```

**Comment by Scope666** [comment]
All of my Govee devices have stopped working as well, perhaps the API is acting up.

`[6/28/2023, 2:01:12 PM] [Govee] [HTTP] could not use existing access token as no data received from Govee server whilst obtaining devices at default.getDevices (file:///homebridge/node_modules/homebridge-govee/lib/connection/http.js:162:15).
[6/28/2023, 2:01:12 PM] [Govee] [HTTP] disabling client as The number of consecutive failed logins for this account has reached the maximum. Please try again in 5 minutes. at default.login (file:///homebridge/node_modules/homebridge-govee/lib/connection/http.js:58:15).
[6/28/2023, 2:01:12 PM] [Govee] [AWS] disabling client as requires HTTP client.
[6/28/2023, 2:01:12 PM] [Govee] [BLE] client enabled.
[6/28/2023, 2:01:12 PM] [Govee] ***** Disabling plugin [v9.1.0]. *****
[6/28/2023, 2:01:12 PM] [Govee] ***** No devices found to initialise. *****`
