### ISSUE TITLE
Govee Lyra Floor Lamp suddenly stopped working via Homebridge

### ISSUE THREAD

**Issue by gethubbahub** [bwp91/homebridge-govee#532]
### What issue do you have? Please be as thorough and explicit as possible.

I have been using Homebridge to control my Lyra floor lamp via the Home app - it's been working for months with no issues and suddenly it stopped working. I've tried reinstalling the plug and config with no luck. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1.)

* Which version of Homebridge/HOOBS do you have?

1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
9.1.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Lyra Floor Lamp

**Comment by bwp91** [comment]
Hiya need to know more specific details like is on/off working? brightness? colour?

**Comment by gethubbahub** [comment]
Unfortunately nothing is, working including on/off! Worked great for months until recently when it just seemed to stop.

**Comment by MSL-DA** [comment]
Try unplugging the power for more than 10 minutes
I have the same lamp and have no problems

**Comment by gethubbahub** [comment]
Unfortunately unplugging for a few hours and plugging it back in still didn't fix it. Open to trying anything else you recommend!

**Comment by MSL-DA** [comment]
I have no other solutions. I don't know your network, but maybe something is blocking it. I myself am on a complex network, but as I wrote, I have no problems. Maybe you can try resetting your lamp. I can't remember the procedure, it's kind of stupid, but Govee support is pretty good at helping

**Comment by bwp91** [comment]
Can you show two things from the homebridge log,
1. logs from the plugin initialising after a restart and 
2. logs from trying to control the device from the home app? a simple on/off will do
