### ISSUE TITLE
Node MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by mrlightison** [bwp91/homebridge-govee#533]
### What issue do you have? Please be as thorough and explicit as possible.

Upon initializing the plugin, I get this error. Everything works as it should; however, I'm obviously concerned about the possible memory leak.

`(node:2024) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 devices loaded listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2024) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit`

### Details of your setup.
Homebridge–UIX

* Which version of Homebridge/HOOBS do you have?

HomeBridge 1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

macOSX | Node.js [v18.16.1]

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

HomeBridge-govee 9.1.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

All devices work as they should. This error displays upon the plugin's startup.

### Please paste any relevant logs below.

`(node:2024) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 devices loaded listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2024) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit`

**Comment by bwp91** [comment]
hi @mrlightison 

thanks for this, although i believe this is simply due to the amount of govee devices you have -

out of interest how many do you have?
