### ISSUE TITLE
H7033 support

### ISSUE THREAD

**Issue by afazzi** [bwp91/homebridge-govee#537]
* **Please explain your feature request in a one or two sentences.**
Supporting string lights H7033 

* **Is your feature request related to a problem? Please describe.**
recieved [LED Bulb String Lights] is not currently supported, do create a Github issue ....

* **Any particular Govee devices that this relates to?**
H7033 string lights seen here https://us.govee.com/products/govee-outdoor-string-lights-h1

* **Anything else?**
I see some personal information in the homebridge readout, but I can provide if needed. Thanks so much for the help, great work and much appreciated.

**Comment by bwp91** [comment]
Hi @afazzi 

This model should be working in the new beta version of the plugin:

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Thanks!
