### ISSUE TITLE
Humidifier H7140 support

### ISSUE THREAD

**Issue by prajeeshkrish** [bwp91/homebridge-govee#539]
Govee released anew humidifier H7140. https://www.amazon.com/dp/B0BT93MJ4G
 
Log from HomeBridge
{"device":"28:2A:D4:AD:FC:81:83:C1","deviceName":"Humidifier","model":"H7140","httpInfo":{"groupId":0,"device":"28:2A:D4:AD:FC:81:83:C1","sku":"H7140","spec":"","versionHard":"1.02.00","versionSoft":"1.00.11","deviceName":"Humidifier","deviceExt":{"deviceSettings":"{\"wifiName\":\"\",\"address\":\"\",\"bleName\":\"ihoment_H7140_83C2\",\"topic\":\"GD/da5fc6234f637b4a47918a478e27d685\",\"wifiMac\":\"",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.11\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"KndQKmztJz4=\",\"waterShortageOnOff\":1,\"mcuSoftVersion\":\"1.00.10\",\"mcuHardVersion\":\"1.00.01\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H7140\",\"device\":\"",\"deviceName\":\"Humidifier\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.11\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":151}}

**Comment by bwp91** [comment]
Hi @prajeeshkrish 

This model should be working in the new beta version of the plugin:

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Thanks!
