### ISSUE TITLE
Control by BT

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-govee#54]
Ben, Govee led strip has a lot of wifi issue. Any possibility to control the strips by BT and not by wifi trough api?

**Comment by bwp91** [comment]
Hi @Stetocasa 
Bluetooth functionality is not something that I plan to add to the plugin.
You could try resetting the govee strip and reestablishing the wifi connection, I know some users have had success doing this.

**Comment by Stetocasa** [comment]
I did several times but if the strip lose the connection cannot re connect again and just reset will permit work again

**Comment by bwp91** [comment]
Hi @Stetocasa 

Initial bluetooth support has been added in the latest version of the plugin, it’s still experimental, but wondered if you’d want to test with your models.

**Comment by Stetocasa** [comment]
Good news! Govee wifi something broke, the BT could definitely solve and let a better stability.
How can I test it?

**Comment by bwp91** [comment]
Could you remind me which govee models you have?

Also, which system do you run hoobs on, do you have the hoobs box?

**Comment by Stetocasa** [comment]
H6159 with hoobs

**Comment by bwp91** [comment]
You should be able to update to v3.4.0 of the plugin. Then you can

1. add your govee username and password to the configuration
2. add/edit the entry for your device in the 'Light Devices' section of the configuration, checking the "Enable Bluetooth Control"
3. Restart the plugin and check for any errors in the logs

**Comment by Stetocasa** [comment]
All done but seems not work, this is the log

12/7/2021, 16:33:12Govee BridgeGovee[Letto] current state [on].
12/7/2021, 16:33:20Govee BridgeGovee[Letto] reverting to cloud update as no bluetooth connection at GoveePlatform.sendDeviceUpdate (/var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/index.js:610:17).
12/7/2021, 16:33:20Govee BridgeGovee[Letto] sending update [cloud] {"name":"turn","value":"off"}.
12/7/2021, 16:33:21Govee BridgeGovee[Letto] current state [off].
