### ISSUE TITLE
Unable to Use Device Model H7135 with Plugin, gives attached error. 

### ISSUE THREAD

**Issue by michael-mcnulty117** [bwp91/homebridge-govee#540]
### What issue do you have? Please be as thorough and explicit as possible.
I'm trying to setup a Govee Space Heater (model: H7135) using this plugin for HomeBridge, but I'm getting an error in the logs (shown below) saying the device isn't supported. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
I'm using Homebridge v1.6.1, I'm not sure how to tell if it's UI-X or CLI, it's just a HomeBridge config I flashed onto my Raspberry Pi.

* Which version of Homebridge/HOOBS do you have?
v1.6.1, the current version. 

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi, and the version of Node.js is v18.16.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v9.1.0, and no, this was the current version that came when I installed it earlier today. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Just one govee space heater, model: H7135

### Please paste any relevant logs below.

```
[10/07/2023, 15:00:03] [Govee] [Smart Space Heater] is not currently supported, do create a Github issue with the following info:
{"device":"1F:7E:D4:AD:FC:81:87:46","deviceName":"Smart Space Heater","model":"H7135","httpInfo":{"groupId":0,"device":"1F:7E:D4:AD:FC:81:87:46","sku":"H7135","spec":"","versionHard":"1.02.00","versionSoft":"1.00.09","deviceName":"Smart Space Heater","deviceExt":{"deviceSettings":"{\"wifiName\":\"The Tower 2.0\",\"address\":\"D4:AD:FC:81:87:47\",\"bleName\":\"ihoment_H7135_8747\",\"topic\":\"GD/a4b47d21228b6cc69c5f2e2eb51f753b\",\"wifiMac\":\"D4:AD:FC:81:87:46\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.09\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"J/JiKWVr4R8=\",\"dumpOnOff\":1,\"mcuSoftVersion\":\"1.00.06\\u0000\",\"mcuHardVersion\":\"1.00.01\\u0000\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H7135\",\"device\":\"1F:7E:D4:AD:FC:81:87:46\",\"deviceName\":\"Smart Space Heater\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.09\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/209c5fb948cc42c6572b494c96310901-add_list_type_device_7135.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":153}}
```

**Comment by bwp91** [comment]
Hi @michael-mcnulty117 

Please try new beta version of plugin:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Some of the functions may or may not work, i'm basing the commands that it uses on similar models.

Let me know how it goes!
