### ISSUE TITLE
TempReporting a) not working and b) false error in log

### ISSUE THREAD

**Issue by kylemcdaniel1010** [bwp91/homebridge-govee#541]
### What issue do you have? Please be as thorough and explicit as possible.
Configuration on Space Heater has Temp Reporting box checked/marked `true` but does not work/generates error in log
- I have the checkbox for Temp Reporting checked in configuration (and double checked the advanced view as well, and shows as marked `true` - please see both attached screen shots)
- However, I'm not actually getting any temp reporting
- Beyond that, every minute my logs print out the suggestion that I "should enable TempReporting in the configuration for this device" despite it being set to true (see logs)
- You can also see in the logs that when initializing it's stating {"tempReporting":false}

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Hoobs

* Which version of Homebridge/HOOBS do you have?
Hoobs v3.4.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
running on a Hoobs box
Node version 16.20.1
Homebridge version 1.6.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
Using version 9.1.0 of the homebridge-govee plugin
this issue has been present since I installed the plugin 6+ months ago

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Govee Smart Space Heater (model number H7130)

### Please paste any relevant logs below.

```
7/14/2023, 2:41:00 PMGovee BridgeLoaded plugin 'homebridge-govee'
7/14/2023, 2:41:00 PMGovee BridgeLoading 1 platforms...
7/14/2023, 2:41:00 PMGovee BridgeGoveeInitialising plugin v9.1.0 | System linux | Node v16.20.1 | HB v1.6.0 | HAPNodeJS v0.11.0...
7/14/2023, 2:41:00 PMGovee BridgeGoveeWARNINGConfig entry [apiKey] is unused and can be removed.
7/14/2023, 2:41:00 PMGovee BridgeGoveeWARNINGConfig entry [heaterDevices.D4:AD:FC:B9:88:94.overrideLogging] is unused and can be removed.
7/14/2023, 2:41:00 PMGovee BridgeGoveePlugin initialised. Setting up accessories....
7/14/2023, 2:41:00 PMGovee BridgeBridge is running on port 51846.
7/14/2023, 2:41:02 PMGovee BridgeGovee[LAN] client enabled and found 0 device(s).
7/14/2023, 2:41:03 PMGovee BridgeGovee[HTTP] client enabled and found 1 device(s).
7/14/2023, 2:41:04 PMGovee BridgeGovee[AWS] client enabled.
7/14/2023, 2:41:04 PMGovee BridgeGovee[BLE] client enabled.
7/14/2023, 2:41:04 PMGovee BridgeGovee[Space Heater] initialising with options {"tempReporting":false}.
7/14/2023, 2:41:04 PMGovee BridgeGovee[Space Heater] initialised with id [16:A1:D4:AD:FC:B9:88:94] [H7130].
7/14/2023, 2:41:05 PMGovee BridgeGovee✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
7/14/2023, 2:41:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:42:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:43:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:44:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:45:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:46:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:47:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:48:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:49:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:50:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:51:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
7/14/2023, 2:52:05 PMGovee BridgeGoveeWARNING[Space Heater] you should enable `tempReporting` in the config for this device.
```
<img width="840" alt="Screenshot 2023-07-14 at 3 03 34 PM" src="https://github.com/bwp91/homebridge-govee/assets/139590476/2e0b2b26-10ee-4eb7-8692-886e62e8fb04">

<img width="369" alt="Screenshot 2023-07-14 at 3 03 46 PM" src="https://github.com/bwp91/homebridge-govee/assets/139590476/41ca13aa-5a8a-4ff5-b9b1-4d539861e073">

**Comment by bwp91** [comment]
deviceid you have in the config does not look long enough for a normal device id, please make sure you are using correct device id, they are all shown in the homebridge log when the plugin starts

**Comment by bwp91** [comment]
In fact i can tell you the device id from your helpful logging: `16:A1:D4:AD:FC:B9:88:94`

**Comment by kylemcdaniel1010** [comment]
Thank you for your response, Ben! That did the trick - must have miscopied
during initial setup and just didn't notice.

Thanks,
Kyle

**Comment by bwp91** [comment]
I hope that in the new version of hoobs it will mimic the same as the homebridge ui right now in the fact that any options per device will not show until a device id with the proper length is entered!
Glad all is working for you, will close this now
