### ISSUE TITLE
leak sensor http requests

### ISSUE THREAD

**Issue by bwp91** [bwp91/homebridge-govee#543]
Original post: https://www.reddit.com/r/homebridge/comments/150ei7h/homebridgegovee_exceeding_allowed_http_requests/

---

I'm using the homebridge-govee plugin with my Govee leak sensors. I have (2) H5040 hubs and (17) total H5054 leak sensors. I just installed a new smart valve actuator and setup its automation triggers to close the valve when a leak sensor detects a leak. Yesterday I noticed in testing that I was no longer getting leak sensor notifications from the Govee app, and within the app when try to look at sensor data I get "Too many requests. Try again later". The homebridge log doesn't show any errors, but even if a leak is detected the leak state does not change in the homebridge logs (still shows "leakdetected":false). Note that if I change the batteries in a sensor, the govee-homebridge logs do show the updated battery level, but the leakdetected state never updates.

So I disabled the homebridge-govee plugin and waited a day. Now the app works as usual (no longer reporting "Too amy requests"), and the govee-homebridge logs now do report the correct leakdetected state, Homekit sends the leak notification and all is working well for now.

Is there a known limit on HTTP requests? From what I read, there is a 10k daily limit on Govee's API requests but I can't seem to find anything regarding HTTP request limits so that I can calculate what I should set the HTTP request interval to (I currently have it set at 30 seconds which is apparently too frequent). Perhaps **I** can shed some light on this? I am not using any other Govee products other than these leak sensors. If HTTP requests are also limited to 10k requests per day, I believe with 17 sensors I'd need to set the refresh interval to 150 seconds (or split the sensors between two different accounts to get this refresh interval down a bit). Any input would be appreciated!

**Comment by brettcp** [comment]
Thank you, looking forward to your feedback on this!

**Comment by bwp91** [comment]
to be honest when implementing the leak devices (which are problematic in the first place) I guess I was never expecting a user to have 17 of them 😅

**Comment by rAf19** [comment]
Same here.  I only have 3 water leak sensors and upon checking the Govee app, I received the "Too many requests, please try again" message.  I set the "HTTP Refresh Interval" to 150 yesterday but this morning I saw the same error.  I did see this message below in Homebridge and apparently the limit may be 30000ms:

_[Govee] [HTTP] sync failed as timeout of 30000ms exceeded at RedirectableRequest.handleRequestTimeout (file:///homebridge/node_modules/homebridge-govee/node_modules/axios/lib/adapters/http.js:628:16)._

**Comment by brettcp** [comment]
Mine has been running without any reported errors for a few days now at a 150 second refresh interval, I have 2x hubs and 17x leak sensors total.  No errors in the homebridge log, just the status updates from each sensor reported by the Govee plugin every 2.5 minutes as expected.

I did disable the plugin entirely for a day before turning it back on, just to be sure any request limits were reset on Govee's side.

**Comment by bwp91** [comment]
I don’t suppose anyone knows what the threshold is for http calls to govee? this isn’t related to the api threshold

**Comment by rAf19** [comment]
@brettcp I did disable it for a day but I will try to do it a bit longer and try again.

**Comment by bwp91** [comment]
Out of every govee model, the leak sensors have been most complicated to implement. It could be that i need to increase the http polling rate by a scale of how many leaks sensors a user has. I know the rate is already configurable but I'm thinking a default increase is needed that will override any configured rate.

**Comment by bwp91** [comment]
I hope it is understandable that I cannot do anything about Govee's limits 😀

**Comment by rAf19** [comment]
Thx @bwp91 for chimin in!

**Comment by brettcp** [comment]
Govee released a new version of their leak sensors a few weeks ago.. they now have native IFTTT, Alexa, and Google Assistant support.. I would think this would allow the leak trigger notifications to be pushed, versus having to poll it repeatedly where we're running into their 10k/day query limit.  I ordered one to test.

https://www.amazon.com/gp/product/B0C3BB2X9J

**Comment by rAf19** [comment]
Thanks for letting me know!  Still having issues so I ordered the three pack of the new version and will be returning the old ones.

https://a.co/d/8hb6iSF

**Comment by brettcp** [comment]
> Thanks for letting me know!  Still having issues so I ordered the three pack of the new version and will be returning the old ones. https://a.co/d/8hb6iSF

That link you posted for the 3 pack doesn't appear to include the hub.. I believe the new version of the sensors need the newer version of the hub as well.  Just FYI.

Also - they're not natively Homekit compatible, but I'm hoping with their new Google Assistant integration I can tie them into my home automation system (I use Homeseer/homebridge with a handful of google nest minis).

**Comment by rAf19** [comment]
Installed the new version but bummer... the new water sensor (Gateway and sensors) are not supported yet.  Below is an export of the logs in HomeBridge:

[Kitchen Water Sensor] is not currently supported, do create a Github issue with the following info:
{"device":"01:32:7A:C4:06:03:8E:3E","deviceName":"Kitchen Water Sensor","model":"H5058","httpInfo":{"groupId":0,"device":"01:32:7A:C4:06:03:8E:3E","sku":"H5058","spec":"","versionHard":"4.1","versionSoft":"1.11","deviceName":"Kitchen Water Sensor","deviceExt":{"deviceSettings":"{\"battery\":100,\"openPush\":true,\"sno\":2,\"deviceType\":12,\"muteLevel\":3,\"gatewayVersionHard\":\"1.04.01\",\"gatewayVersionSoft\":\"1.00.18\",\"gatewayId\":315419,\"gatewayInfo\":{\"device\":\"30:2A:60:74:F4:2C:36:AC\",\"sku\":\"H5043\",\"topic\":\"GD/c8a9eb7a2da0c8d91898ba0169aa72ef\",\"bleName\":\"ihoment_H5043_36AD\",\"address\":\"60:74:F4:2C:36:AD\",\"secretCode\":\"GSGOJvpf924=\"},\"sku\":\"H5058\",\"device\":\"01:32:7A:C4:06:03:8E:3E\",\"deviceName\":\"Kitchen Water Sensor\",\"versionHard\":\"4.1\",\"versionSoft\":\"1.11\"}","lastDeviceData":"{\"online\":true,\"gwonline\":true,\"lastTime\":0,\"read\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"share":0,"goodsType":159}}

**Comment by ex3ndr** [comment]
I also have a problem, i have been using them as leak sensor and when i got an actual leak (thanks it was my fault in front of my eyes) i got no notifications anywhere. Govee App in my home network throws error now and i can't reset the "leaking" state. Homekit state didn't updated at all after a 24+ hours. I suppose every request to cloud is timeouted.

**Comment by ironjaw72** [comment]
I have 21 leak detectors and 2 gateways. When trying to open devices in the app, I receive an error of "Too many requests. Try again later". I changed the frequency of the homebridge-govee polling to 150 seconds, then 180 seconds. It didn't stop the errors in the app, even giving 24 hours to clear up. I finally disabled homebridge-govee and now the app is working correctly. 

While in this weird state, I did have a sensor trigger. The Govee app itself did not give me a notification or send me an email as it normally does. However, my Alexa did get a notification and alert me.

I will try a higher number than 180 seconds, but wanted to get this posted first.

(210 didn't work)

**Comment by ex3ndr** [comment]
I am pretty sure that notification to alexa is sent separately to amazon servers directly, that's why it worked.

**Comment by ironjaw72** [comment]
I've tried all the way to 300s and it still fails. The math says this should be way within limits of 10K per day. Hmm

**Comment by bwp91** [comment]
where has this 10k a day limit idea come from?

**Comment by ironjaw72** [comment]
It is mentioned on other Govee threads (not necessarily for water detectors)

**Comment by bwp91** [comment]
yes but are people maybe confusing the Govee API limit for any govee http request limit?

**Comment by ironjaw72** [comment]
Seems like it would be pretty straightforward to test the limit. Just do http requests for 1 device until you hit a limit, let's call that the 1 hour limit. Then do a different test keeping under the 1 hour limit per hour until you hit another limit which would presumably be the daily limit. Then we would know for sure

**Comment by ironjaw72** [comment]
600s worked (300 didn't) for my 21 devices with 2 gateways. I'll try reducing down to see when it breaks again

**Comment by brettcp** [comment]
> where has this 10k a day limit idea come from?

I called Govee and they claim the HTTP request limit is the same as the API request limit at 10k per day, however I don't think the tech I spoke with was very confident when answering this question.

I have 17 sensors (2 gateways) and have my timing set to 150s and don't seem to have any issues.

**Comment by ironjaw72** [comment]
I am running a test right now to see how many Homebridge HTTPs I can do in 1 hr before I start getting errors in the app. Note that no errors are shown within Homebridge, it's only when you go into the app.

Well, I didn't try the app until my HTTP count was at about 650 total (hit that in 15 minutes via 20s intervals)  and it was already getting errors. That was about 30 total refreshes for my system (21 device).

I'll try again.

**Comment by ironjaw72** [comment]
Between 250 and 275 HTTPs (1 minute intervals, 21 devices) on my test within Homebridge, my Govee app started getting the errors. After every 21 HTTPs through 250, I checked the app each time and didn't have an issue. But I was also running up HTTPs in the app, so let's call it 300 until things broke (in < 15 minutes). Last time it took 2 hours for the errors to clear after stopping Homebridge. It did seem a bit like one of the gateways' devices triggered before the other. I have 9 on one and 12 on the other. 

Not sure what to do here except put the time back to 10 min intervals, but that can't be relied on to quickly catch a water leak

**Comment by ironjaw72** [comment]
Could Apple Homekit be causing additional HTTPs for the water detectors? All I have going are Homebridge, Homekit, and my Android app

**Comment by ironjaw72** [comment]
I ran overnight (2600 HTTPs) with 450s interval without issue. Restarted with 375s and when I checked after 650 HTTPs the app had started producing errors. This 7.5 minute refresh (to support 21 devices, 2 gateways) isn't the best.

**Comment by vabello** [comment]
I just experienced the same problem. I have three of the sensors. I heard one going off in my basement but didn't get any alerts either via the Govee app or HomeKit. I was luckily in the house at the time and heard it. When I go into the Govee app and open the sensor, it says too many requests. I'm probably just going to disable this plugin as I'd rather be notified than have HomeKit integration.

**Comment by rAf19** [comment]
Works for me in the app after reaching out to govee support team at support@govee.com
They ask me to make sure my email address is in the app for email notifications (which it was).  But deleting the app, waiting for a couple of  days and testing it again worked for me.
I’m still hoping for dev updates so it works with these sensors in HomeKit.

**Comment by brettcp** [comment]
> I just experienced the same problem. I have three of the sensors. I heard one going off in my basement but didn't get any alerts either via the Govee app or HomeKit. I was luckily in the house at the time and heard it. When I go into the Govee app and open the sensor, it says too many requests. I'm probably just going to disable this plugin as I'd rather be notified than have HomeKit integration.

I haven't had any issues since throttling back the HTTP refresh interval to 150 seconds (this is with 17 sensors and 2 gateways).  I made this change nearly 3 months ago and all has been well.  You can figure out the math to determine what you refresh interval can be based on the number of sensors and Govee's limit of 10k requests per day.  I get the alerts via the Govee app and the "critical" leak alerts via the Homekit app (and have an automation to shut off the main water valve when these alerts are triggered).

**Comment by ironjaw72** [comment]
My real world experiments above showed I need a much slower reading of APIs (450s) than the math indicates (181s). I could not reproduce what @brettcp is experiencing.

I finally turned If off in Homekit and am just using Home Assistant without issue (it uses a different scheme via mqtt instead of API calls). The response time to a leak is instant.

**Comment by sdaltons1** [comment]
> My real world experiments above showed I need a much slower reading of APIs (450s) than the math indicates (181s). I could not reproduce what @brettcp is experiencing.
> 
> I finally turned If off in Homekit and am just using Home Assistant without issue (it uses a different scheme via mqtt instead of API calls). The response time to a leak is instant.

You have the water leak sensors reporting in MQTT? Which addon?

**Comment by brettcp** [comment]
> > My real world experiments above showed I need a much slower reading of APIs (450s) than the math indicates (181s). I could not reproduce what @brettcp is experiencing.
> > I finally turned If off in Homekit and am just using Home Assistant without issue (it uses a different scheme via mqtt instead of API calls). The response time to a leak is instant.
> 
> You have the water leak sensors reporting in MQTT? Which addon?

There is a way to use the Govee leak sensors with a USB RTL-SDR/RTL-433 device and MQTT.  This eliminates the need for the Govee gateway.  I haven't done this myself but I know somebody who has and it works well.  There's info about it if you search around, but here's one thread:  [https://community.home-assistant.io/t/govee-wifi-water-sensor/213277/77](url)

**Comment by ironjaw72** [comment]
> > > My real world experiments above showed I need a much slower reading of APIs (450s) than the math indicates (181s). I could not reproduce what @brettcp is experiencing.
> > > I finally turned If off in Homekit and am just using Home Assistant without issue (it uses a different scheme via mqtt instead of API calls). The response time to a leak is instant.
> > 
> > 
> > You have the water leak sensors reporting in MQTT? Which addon?
> 
> There is a way to use the Govee leak sensors with a USB RTL-SDR/RTL-433 device and MQTT. This eliminates the need for the Govee gateway. I haven't done this myself but I know somebody who has and it works well. There's info about it if you search around, but here's one thread: [https://community.home-assistant.io/t/govee-wifi-water-sensor/213277/77](url)

Yes, this is how I did it. I use RTL-433 to receive the water alerts, button presses, and battery updates from my 20+ sensors. That information is all published into MQTT.

Here are some other useful links:
https://www.kyleniewiada.org/blog/2021/10/affordable-water-leak-and-temp-monitoring/
https://www.reddit.com/r/homeassistant/comments/11yq4kg/govee_water_leak_detector/
https://www.reddit.com/r/homeassistant/comments/r2u639/govee_leak_detectors_and_rtl_433/

**Comment by mynameisbobwehadababyitsaboy** [comment]
Seems like this issue is still alive.

I've got 11 sensors, one of them went off today... Neither Govee OR Homebridge notified me. When looking at the Govee app it says "Too many requests. Try again later" -- so Homebridge is sending so many API requests that my app isn't functioning properly either.

Unfortunately that's a big enough issue that I'm gonna have to uninstall this plugin for the time being. Given that this issue is over a year old, I may have to try another solution, such as the RTL-433 idea that was mentioned.

**Comment by brettcp** [comment]
> Seems like this issue is still alive.
> 
> I've got 11 sensors, one of them went off today... Neither Govee OR Homebridge notified me. When looking at the Govee app it says "Too many requests. Try again later" -- so Homebridge is sending so many API requests that my app isn't functioning properly either.
> 
> Unfortunately that's a big enough issue that I'm gonna have to uninstall this plugin for the time being. Given that this issue is over a year old, I may have to try another solution, such as the RTL-433 idea that was mentioned.

Consider checking out YoLink sensors.  I ditched the Govee sensors about 4 months ago and switched to YoLink, they work very well and have a Home Assistant integration that works as expected.  I'm using 17 sensors and haven't had any issues so far.
