### ISSUE TITLE
Support for AI Syncbox

### ISSUE THREAD

**Issue by anthonymkz** [bwp91/homebridge-govee#545]
* **Please explain your feature request in a one or two sentences.**
Support for new Govee AI Syncbox 

* **Is your feature request related to a problem? Please describe.**
[AI Gaming Sync Box] is not currently supported, do create a Github issue with the following info:
{"device":"15:B6:D9:89:47:54:65:E0","deviceName":"AI Gaming Sync Box","model":"H6602","httpInfo":{"groupId":0,"device":"15:B6:D9:89:47:54:65:E0","sku":"H6602","spec":"","versionHard":"3.04.13","versionSoft":"1.00.26","deviceName":"AI Gaming Sync Box","deviceExt":{"deviceSettings":"{\"wifiName\":\"MKZNetwork\",\"address\":\"D9:89:47:54:65:E0\",\"bleName\":\"Govee_H6602_65E0\",\"topic\":\"GD/f396374ca652ca40d3e1d79f1bd748b1\",\"wifiMac\":\"2C:05:47:ED:CC:18\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.29\",\"wifiHardVersion\":\"2.01.01\",\"ic\":72,\"secretCode\":\"nNbZiUdUZeA=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6602\",\"device\":\"15:B6:D9:89:47:54:65:E0\",\"deviceName\":\"AI Gaming Sync Box\",\"versionHard\":\"3.04.13\",\"versionSoft\":\"1.00.26\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/2b113db7511f0ccce00a26c6a22a338a-add_list_type_device_6602.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/81c2b941168afdd4d9fbc8557b22916c-new_light_title_6602_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/88511aa03e5f779981cdee3b2b6b00d3-new_light_title_6602_off.png\",\"ext\":\"\",\"ic\":72}"},"pactType":1,"pactCode":1,"share":0,"goodsType":142}}

* **Any particular Govee devices that this relates to?**
AI Syncbox H6602

* **Anything else?**
Love my new syncbox. Please add support if possible!

**Comment by bwp91** [comment]
Hi @anthonymkz what does this device actually do?
Which homekit accessory type would best 'represent' what this does?

**Comment by anthonymkz** [comment]
Hi. This is a control box for TV bias lighting. It is similar to the T1 and T2 Dreamview units but it works through HDMI input and not a camera. I'm not familiar with the list of accessory types but whichever is used for the T1 and T2 models (H6199 and H605C) I think would work.

**Comment by bwp91** [comment]
Can you show a screenshow of how this device looks in the govee app? the control page?

**Comment by anthonymkz** [comment]
![IMG_0475](https://github.com/bwp91/homebridge-govee/assets/122386592/b0a93e6b-0196-4e81-a5e0-75e39a6ef8b8)
![IMG_0476](https://github.com/bwp91/homebridge-govee/assets/122386592/4a38301d-c93c-429d-a9ab-777c19ed07ea)
![IMG_0473](https://github.com/bwp91/homebridge-govee/assets/122386592/5fdc5f11-984b-4de1-8950-db504e642b68)
![IMG_0474](https://github.com/bwp91/homebridge-govee/assets/122386592/5890e2dd-91dd-4a51-8fee-f3f98a5a02cd)

**Comment by bwp91** [comment]
Can you update to the latest version of the plugin, and see if you have any 'yellow' logging in the homebridge log about this device? and anything that appears if you for example change the colour of the lights?

**Comment by anthonymkz** [comment]
I'm getting the below, but it isn't actually showing as a device in my accessories

On startup:
[29/07/2023, 13:23:26] [Govee] [AI Gaming Sync Box] {"state":"on","brightness":39,"rgb":{"r":0,"g":0,"b":255},"commands":["qgUAAAgyAAIyAAAAAAAAAAAAAKU=","qhEAHg8PAAAAAAAAAAAAAAAAAKU=","qhL/ZAAAgAoAAAAAAAAAAAAAAKk=","qiP/AAAAgAAAAIAAAACAAAAAgHY=","qgcHDAAAAAAAAAAAAAAAAAAAAKY=","qgcIZA8BZAABAGT///8AAAAAADE=","qrcAAAAAAAAAAAAAAAAAAAAAAB0=","qq4BBEtLS0sAAAAAAAAAAAAAAAE=","qqkBAQEAAAAAAAAAAAAAAAAAAAI=","qqkDAgJAAAAAAAAAAAAAAAAAAEA=","qqkEBwACAAEABAAAAAAAAAAAAAc=","qqkFAzIyMgAAAAAAAAAAAAAAADc=","qqkJAQAAAAAAAAAAAAAAAAAAAAs=","7jAIAgAAAAAAAAAAAAAAAAAAANQ="],"baseCmd":"op","source":"AWS"}.

Color Change
[29/07/2023, 13:23:26] [Govee] [AI Gaming Sync Box] {"state":"on","brightness":39,"rgb":{"r":0,"g":0,"b":255},"commands":["qgUAAAgyAAIyAAAAAAAAAAAAAKU=","qhEAHg8PAAAAAAAAAAAAAAAAAKU=","qhL/ZAAAgAoAAAAAAAAAAAAAAKk=","qiP/AAAAgAAAAIAAAACAAAAAgHY=","qgcHDAAAAAAAAAAAAAAAAAAAAKY=","qgcIZA8BZAABAGT///8AAAAAADE=","qrcAAAAAAAAAAAAAAAAAAAAAAB0=","qq4BBEtLS0sAAAAAAAAAAAAAAAE=","qqkBAQEAAAAAAAAAAAAAAAAAAAI=","qqkDAgJAAAAAAAAAAAAAAAAAAEA=","qqkEBwACAAEABAAAAAAAAAAAAAc=","qqkFAzIyMgAAAAAAAAAAAAAAADc=","qqkJAQAAAAAAAAAAAAAAAAAAAAs=","7jAIAgAAAAAAAAAAAAAAAAAAANQ="],"baseCmd":"op","source":"AWS"}.

**Comment by bwp91** [comment]
Thanks - could be this is supported as simply a light strip.

Can you try the beta version I have just published?  9.3.1-beta.0

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by anthonymkz** [comment]
I just updated and seems to be working. Thank you!!! I don't see why it couldn't be controlled as just a strip? Is that how the T1 and T2 dreamview products are supported?

**Comment by bwp91** [comment]
All i’m aware of is the Hxxxx numbers for models, i don’t know which devices i support by the govee names!

I think i got hesitant because this seems like a “box” rather than a light strip? maybe i just got confused!
