### ISSUE TITLE
H7019 Support

### ISSUE THREAD

**Issue by jman1118** [bwp91/homebridge-govee#546]
* **Please explain your feature request in a one or two sentences.**
Please add support for H7019 string lights

* **Is your feature request related to a problem? Please describe.**
[LED Bulb String Lights] is not currently supported, do create a Github issue with the following info:
{"device":"39:18:CF:33:33:36:3F:0D","deviceName":"LED Bulb String Lights","model":"H7019","httpInfo":{"groupId":0,"device":"39:18:CF:33:33:36:3F:0D","sku":"H7019","spec":"","versionHard":"3.01.01","versionSoft":"1.00.25","deviceName":"LED Bulb String Lights","deviceExt":{"deviceSettings":"{\"bleName\":\"Govee_H7019_3F0D\",\"pactType\":1,\"pactCode\":1,\"ic\":8,\"sku\":\"H7019\",\"device\":\"39:18:CF:33:33:36:3F:0D\",\"deviceName\":\"LED Bulb String Lights\",\"versionHard\":\"3.01.01\",\"versionSoft\":\"1.00.25\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/6004e4f2fdb37401887ff62e3bb95d6f-add_list_type_device_7019_01.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/a6e9bc3caaf3096d9ec02cfce2d7bd08-new_light_title_7019_alexa_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5db871d069884a2a188961cce3720dd6-new_light_title_7019_alexa_off.png\",\"ext\":\"\",\"ic\":8}"},"pactType":1,"pactCode":1,"share":0,"goodsType":148}}

* **Any particular Govee devices that this relates to?**
Govee Warm White S14 Bulb String Lights 24feet

* **Anything else?**

**Comment by bwp91** [comment]
Hi @jman1118 

Thanks for this. Have added this as a supported model in the beta version of the plugin.
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Note that since this device is bluetooth control only, you will need to make sure that your homebridge instance has 'access' to a bluetooth module, more info here:
https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control
