### ISSUE TITLE
[Schlafzimmer led] is not currently supported, do create a Github issue with the following info:

### ISSUE THREAD

**Issue by DevelgameDE** [bwp91/homebridge-govee#548]
[Schlafzimmer led] is not currently supported, do create a Github issue with the following info:
{"ip":"192.168.178.36","device":"38:4C:C6:38:32:34:1E:35","sku":"H61BE","bleVersionHard":"3.05.00","bleVersionSoft":"3.00.05","wifiVersionHard":"1.02.00","wifiVersionSoft":"2.05.08","httpInfo":{"groupId":0,"device":"38:4C:C6:38:32:34:1E:35","sku":"H61BE","spec":"","versionHard":"3.05.00","versionSoft":"3.00.05","deviceName":"Schlafzimmer led","deviceExt":{"deviceSettings":"{\"wifiName\":\"FRITZ!Box 6690 MP\",\"address\":\"C6:38:32:34:1E:35\",\"bleName\":\"Govee_H61BE_1E35\",\"topic\":\"GD/0304ea5a1fc6c38df54e192f31fd9bcc\",\"wifiMac\":\"60:74:F4:28:6D:9E\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"2.05.08\",\"wifiHardVersion\":\"1.02.00\",\"ic\":40,\"secretCode\":\"K2PGODI0HjU=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H61BE\",\"device\":\"38:4C:C6:38:32:34:1E:35\",\"deviceName\":\"Schlafzimmer led\",\"versionHard\":\"3.05.00\",\"versionSoft\":\"3.00.05\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/d94209fe664656f55e99b8a6f9ac40b8-add_list_type_device_61be.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/07c10ede03d01d3b8dca963414a16d64-h61be_light_title_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/bba0c5d45c2f1c73dfbc2929d2bc5bb3-h61be_light_title_off.png\",\"ext\":\"\",\"ic\":40}"},"pactType":1,"pactCode":1,"share":0,"goodsType":175},"model":"H61BE","deviceName":"Schlafzimmer led","isLANDevice":true}

**Comment by bwp91** [comment]
Hi @DevelgameDE 

if you update to the beta version of the plugin:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

you should find this device starts working

**Comment by DevelgameDE** [comment]
im on: homebridge-govee v9.2.1-beta.3


and its still not working

**Comment by DevelgameDE** [comment]
omg it work now, I update one more

**Comment by bwp91** [comment]
Yes i enabled this model in beta 4
good to hear it’s working 😁

**Comment by bwp91** [comment]
out of interest does this device offer the lan mode functionality in the govee app?

**Comment by DevelgameDE** [comment]
I think so, I can turn LAN on in the settings from the device

**Comment by bwp91** [comment]
Please update to the newer beta,  9.2.1-beta.5, you should find the plugin controls your device via LAN (if you have this option enabled in the govee app)

Thanks!
