### ISSUE TITLE
Light Strip: Ability to switch between music sync and normal scenes

### ISSUE THREAD

**Issue by geozakk** [bwp91/homebridge-govee#55]
* **Currently it’s only possible to turn on/off music sync feature via the remote attached to the light strip. A button to control this from home bridge would be a nice addition.**

* **Relates to Govee light strips with music sync feature**

Thanks!

**Comment by bwp91** [comment]
Hi @geozakk 
Unfortunately the Govee API doesn't currently support changing scenes including music mode, so for now this is impossible.
Rest assured, if and when the Govee API does enable this functionality, I will add it to the plugin as soon as I can.
Thanks
