### ISSUE TITLE
Please add support for H5104 Thermometer/Hydrogmeter

### ISSUE THREAD

**Issue by davidjbullock** [bwp91/homebridge-govee#553]
{"device":"CE:1E:D9:38:31:39:27:7B","deviceName":"Basement Thermometer","model":"H5104","httpInfo":{"groupId":12795807,"device":"CE:1E:D9:38:31:39:27:7B","sku":"H5104","spec":"","versionHard":"3.01.01","versionSoft":"1.00.05","deviceName":"Basement Thermometer","deviceExt":{"lastDeviceData":"{}","deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":true,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":6500,\"humWarning\":true,\"humCali\":0,\"netWaring\":true,\"battery\":87,\"wifiLevel\":0,\"bleName\":\"GVH5104_277B\",\"address\":\"D9:38:31:39:27:7B\",\"secretCode\":\"eyc5MTjZAAA=\",\"bdType\":1,\"deviceName\":\"Basement Thermometer\"}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"share":0,"goodsType":154}}

Thermometer/Hydrogmeter

**Comment by bwp91** [comment]
Hi @davidjbullock 

Please install and try the beta version of the plugin:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Thanks!

**Comment by davidjbullock** [comment]
That seems to do the trick!  The device now shows up.
