### ISSUE TITLE
Home app accessory not responding 

### ISSUE THREAD

**Issue by Adnaan77** [bwp91/homebridge-govee#554]
### What issue do you have? Please be as thorough and explicit as possible.

the accessory in home app is not responding 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1. homebridge 

* Which version of Homebridge/HOOBS do you have?

v1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

macOS 

node version: [v18.17.0](https://homebridge.io/w/JTKEF)

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Homebridge Govee
homebridge-govee v9.3.1-beta.2

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Govee T2 envisual 
model: H605C

```

```

**Comment by Ademord** [comment]
Hello, I am having the same problem, i set up the scenes in the Eve app and they work with the H6062 (Govee Glides) but the H605C (TV Backlight) doesnt work. Can someone help me, or how did you fix it @Adnaan77 ?
