### ISSUE TITLE
H7029 not supported

### ISSUE THREAD

**Issue by wja731** [bwp91/homebridge-govee#555]
[Back Porch Lights] is not currently supported, do create a Github issue with the following info:
{"device":"B2:CD:C2:33:33:36:2F:57","deviceName":"Back Porch Lights","model":"H7029","httpInfo":{"groupId":12895121,"device":"B2:CD:C2:33:33:36:2F:57","sku":"H7029","spec":"","versionHard":"3.01.01","versionSoft":"1.00.17","deviceName":"Back Porch Lights","deviceExt":{"deviceSettings":"{\"address\":\"C2:33:33:36:2F:57\",\"bleName\":\"Govee_H7029_2F57\",\"pactType\":1,\"pactCode\":1,\"ic\":8,\"sku\":\"H7029\",\"device\":\"B2:CD:C2:33:33:36:2F:57\",\"deviceName\":\"Back Porch Lights\",\"versionHard\":\"3.01.01\",\"versionSoft\":\"1.00.17\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/121d9db7733df8b28af1d0302f3ab5ae-add_list_type_device_7029_01.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5174b78cb3eeda0456fce0a5e1d1e3b5-new_light_title_7029_alexa_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5db871d069884a2a188961cce3720dd6-new_light_title_7029_alexa_off.png\",\"ext\":\"\",\"ic\":8}"},"pactType":1,"pactCode":1,"share":0,"goodsType":149}}

**Comment by bwp91** [comment]
Hi @wja731 

Please install and try the beta version of the plugin:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Thanks!
