### ISSUE TITLE
Govee Dehumidifier does not work. 

### ISSUE THREAD

**Issue by gav70** [bwp91/homebridge-govee#556]
### What issue do you have? Please be as thorough and explicit as possible.
Installed the Homebridge Govee plugin to connect my new Govee basement dehumidifier. Once the plugin is setup and i restart homebridge, i get the below message in my startup logs:

[03/08/2023, 16:31:28] [Govee] [Smart Dehumidifier Max] is not currently supported, do create a Github issue with the following info:
{"device":"16:9B:D4:AD:FC:EC:12:1C","deviceName":"Smart Dehumidifier Max","model":"H7151","httpInfo":{"groupId":0,"device":"16:9B:D4:AD:FC:EC:12:1C","sku":"H7151","spec":"","versionHard":"1.02.00","versionSoft":"1.00.11","deviceName":"Smart Dehumidifier Max","deviceExt":{"deviceSettings":"{\"wifiName\":\"GHOME\",\"address\":\"D4:AD:FC:EC:12:1D\",\"bleName\":\"ihoment_H7151_121D\",\"topic\":\"GD/374fd03b48f3f93481cbcceba1a838f1\",\"wifiMac\":\"D4:AD:FC:EC:12:1C\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.11\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"NwFqLfDqaG8=\",\"waterFull\":1,\"thermometerUnit\":1,\"mcuSoftVersion\":\"1.00.08\\u0000\",\"mcuHardVersion\":\"1.00.01\\u0000\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H7151\",\"device\":\"16:9B:D4:AD:FC:EC:12:1C\",\"deviceName\":\"Smart Dehumidifier Max\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.11\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/e56fed8032f2a7c161baad696732350e-add_list_type_device_7151.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":147}}
[03/08/2023, 16:31:29] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Timezone: GMT-0400
OS: Raspbian GNU/Linux Buster (10)
Hostname: homebridge
Node.js Version: v18.17.0
Storage Path: /var/lib/homebridge
Config Path: /var/lib/homebridge/config.json
Service Mode: Yes

* Which version of Homebridge/HOOBS do you have?
v1.6.1
All plugins up to date

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
OS: Raspbian GNU/Linux Buster (10)
Raspberry pi 3
Node.js Version: v18.17.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v9.3.0

Just downloaded and installed the plugin for the first time and setup with my account. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Smart Dehumidifier 
Model name: H7151
https://www.amazon.com/dp/B0BR7RHQB9?ref_=cm_sw_r_apin_dp_MTH3C9D7F7RWG2YJXFDZ_1

### Please paste any relevant logs below.

[03/08/2023, 16:31:28] [Govee] [HTTP] client enabled and found 1 device(s).
[03/08/2023, 16:31:28] [Govee] [AWS] client enabled.
[03/08/2023, 16:31:28] [Govee] [BLE] client enabled.
[03/08/2023, 16:31:28] [Govee] [Smart Dehumidifier Max] is not currently supported, do create a Github issue with the following info:
{"device":"16:9B:D4:AD:FC:EC:12:1C","deviceName":"Smart Dehumidifier Max","model":"H7151","httpInfo":{"groupId":0,"device":"16:9B:D4:AD:FC:EC:12:1C","sku":"H7151","spec":"","versionHard":"1.02.00","versionSoft":"1.00.11","deviceName":"Smart Dehumidifier Max","deviceExt":{"deviceSettings":"{\"wifiName\":\"GHOME\",\"address\":\"D4:AD:FC:EC:12:1D\",\"bleName\":\"ihoment_H7151_121D\",\"topic\":\"GD/374fd03b48f3f93481cbcceba1a838f1\",\"wifiMac\":\"D4:AD:FC:EC:12:1C\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.11\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"NwFqLfDqaG8=\",\"waterFull\":1,\"thermometerUnit\":1,\"mcuSoftVersion\":\"1.00.08\\u0000\",\"mcuHardVersion\":\"1.00.01\\u0000\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H7151\",\"device\":\"16:9B:D4:AD:FC:EC:12:1C\",\"deviceName\":\"Smart Dehumidifier Max\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.11\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/e56fed8032f2a7c161baad696732350e-add_list_type_device_7151.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":147}}
[03/08/2023, 16:31:29] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!

```

```

**Comment by bwp91** [comment]
Hi @gav70 

Please install and try the beta version of the plugin:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Thanks!

**Comment by gav70** [comment]
Thanks Ben for the quick response. I updated to the beta and no longer receive the error. I see the device but can only see if is running. Fan control does not seem to do anything but will look forward to some added functionality in the future.

Thanks
![IMG_0074](https://github.com/bwp91/homebridge-govee/assets/34777396/6830f699-a5d2-4732-aa71-e4d4e8f06359)
![IMG_0075](https://github.com/bwp91/homebridge-govee/assets/34777396/648568a2-7a3f-468f-a25f-ab717e989c29)

**Comment by bwp91** [comment]
It may use a different command for speed compared to other similar models.

What are the available fan speeds for this model in the govee app?

**Comment by gav70** [comment]
Govee app shows Low, medium and high for fan speeds. 

Below are all the settings on the Govee app to view and control
View: 
- Current Temperature and Humidity
- Historical data for the last week (Temp and Humidity)

Control:
- Fan: Low, Med, High, Auto
- Set Humidity: Comfort (Auto), Manual, Range

Alert:
- Full bucket

Hope this helps.

Thanks
Gaurav


![IMG_0617](https://github.com/bwp91/homebridge-govee/assets/34777396/7a86252b-14c9-4c85-9edd-a1a78f329c82)
