### ISSUE TITLE
H713A not supported

### ISSUE THREAD

**Issue by oscar-pitts** [bwp91/homebridge-govee#557]
[Smart Heater] is not currently supported, do create a Github issue with the following info:
{"device":"2F:28:60:74:F4:0C:E8:F8","deviceName":"Smart Heater","model":"H713A","httpInfo":{"groupId":0,"device":"2F:28:60:74:F4:0C:E8:F8","sku":"H713A","spec":"","versionHard":"1.02.01","versionSoft":"1.00.07","deviceName":"Smart Heater","deviceExt":{"deviceSettings":"{\"wifiName\":\"BTHub5-RNZ9\",\"address\":\"60:74:F4:0C:E8:F9\",\"bleName\":\"ihoment_H713A_E8F9\",\"topic\":\"GD/8a76e89aa38be22e7bd4e7893628e157\",\"wifiMac\":\"60:74:F4:0C:E8:F8\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.07\",\"wifiHardVersion\":\"1.02.01\",\"ic\":0,\"secretCode\":\"Zg1wAwAkWSA=\",\"dumpOnOff\":1,\"mcuSoftVersion\":\"23.02.02\",\"mcuHardVersion\":\"23.02.03\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H713A\",\"device\":\"2F:28:60:74:F4:0C:E8:F8\",\"deviceName\":\"Smart Heater\",\"versionHard\":\"1.02.01\",\"versionSoft\":\"1.00.07\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":164}}

**Comment by bwp91** [comment]
Hi @oscar-pitts 

Please install the beta of the plugin using the guide here:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

You should find this light starts working!
Ta

**Comment by TobyM23** [comment]
Hi, this has connected the heater to homekit but it is now showing as a light. Is there a simple fix for this? Thank you.
