### ISSUE TITLE
All govee devices no longer responding

### ISSUE THREAD

**Issue by minecraftuser1243** [bwp91/homebridge-govee#559]
### What issue do you have? Please be as thorough and explicit as possible.
All of my devices are no longer working in HomeKit. They work in the govee app and through homebridge. It is saying there isn't an aws connection. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Latest version 1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Mac OS 
node.js version 18.7.1
npm version 9.6.7

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
* 9.3.0
* yes the issue started once I updated. I have tried reverting back but that hasn't fixed it. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6008
H619A
H604A
H619E
H6087
H6052
H6072
H6056
H605B

### Please paste any relevant logs below.

```
[8/11/2023, 9:01:07 PM] [Govee] [Tv lights] could not be updated as no connection method available, see https://shorturl.at/eCN04 for more info at file:///usr/local/lib/node_modules/homebridge-govee/lib/platform.js:1749:13.
```

**Comment by samwhu30** [comment]
I also have this issue

**Comment by bwp91** [comment]
Hi @minecraftuser1243 and @samwhu30 

Please check this wiki entry: https://github.com/bwp91/homebridge-govee/wiki/Common-Errors#no-connection-method
