### ISSUE TITLE
Govee Light Strip turns on then changes brightness

### ISSUE THREAD

**Issue by MattB1981** [bwp91/homebridge-govee#56]
### What issue do you have? Please be as thorough and explicit as possible.
When an automation turns on my Govee light strip, it turns on first and then changes settings second, so if it's at night it might be very bright white at first before switching to it's dim red settings.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?
1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
os x 10.15 iMac
Node.js Version  v14.16.0
NPM Version v6.14.11

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v2.13.2

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
LED Light strip  - H6117-F867
Firmware 1.04.06

### Please paste any relevant logs below.

```
 [37m[3/17/2021, 10:24:06 AM] [39m[36m[Govee][39m [v2.13.2] initialised. Syncing with Govee.
[37m[3/17/2021, 10:24:06 AM] [39m[36m[eWeLink][39m [v5.5.0] initialised. Syncing with eWeLink.
[37m[3/17/2021, 10:24:06 AM] [39m[36m[Govee][39m [H6117_F867] initialised with id 69:B3:A4:C1:38:8F:F8:67.
[37m[3/17/2021, 10:24:06 AM] [39m[36m[Govee][39m ✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91
...
 [37m[3/16/2021, 11:43:16 PM] [39m[36m[Bed Light Timer][39m Setting switch to true
[37m[3/16/2021, 11:43:16 PM] [39m[36m[Govee][39m [H6117_F867] current state [on].
[37m[3/16/2021, 11:43:17 PM] [39m[36m[Govee][39m [H6117_F867] current brightness [2%].
```

**Comment by bwp91** [comment]
This behaviour will be 'fixed' in the next release of the plugin 👍
