### ISSUE TITLE
Please add support for H5121 motion sensor.

### ISSUE THREAD

**Issue by i-93** [bwp91/homebridge-govee#560]

**Comment by bwp91** [comment]
Please provide more info

**Comment by i-93** [comment]
The homebridge-govee integration doesn't see H5121 motion sensor and doesn't create device/entity for it as it does for other devices.

**Comment by inventor7777** [comment]
Same here, it shows up in the logs as an unrecognized device for me.

**Comment by bwp91** [comment]
Hi @i-93 and @inventor7777  yes but I need some logs from the homebridge log to know where to start

**Comment by bwp91** [comment]
im sure the homebridge log asks to post this info in a github issue

**Comment by inventor7777** [comment]
Here's my log:
@bwp91 @i-93 
[8/30/2023, 11:43:28 AM] [Govee] [Motion Sensor] is not currently supported, do create a Github issue with the following info:
{"device":"58:F7:CF:32:39:37:60:85","deviceName":"Motion Sensor","model":"H5121","httpInfo":{"groupId":9663127,"device":"58:F7:CF:32:39:37:60:85","sku":"H5121","spec":"","versionHard":"1","versionSoft":"4","deviceName":"Motion Sensor","deviceExt":{"deviceSettings":"{\"address\":\"CF:32:39:37:60:85\",\"bleName\":\"GV51216085\",\"ic\":0,\"sku\":\"H5121\",\"device\":\"58:F7:CF:32:39:37:60:85\",\"deviceName\":\"Motion Sensor\",\"versionHard\":\"1\",\"versionSoft\":\"4\",\"battery\":100,\"time\":1693412750708}","lastDeviceData":"{\"online\":true,\"bind\":true}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"share":0,"goodsType":130}}

**Comment by livefeed** [comment]
Any luck with adding the H5121?

**Comment by bwp91** [comment]
this device is bluetooth only right?

**Comment by livefeed** [comment]
I believe so [](url)

**Comment by inventor7777** [comment]
Yes, BT only. It normally uses distributed gateway in the Govee app.

**Comment by bwp91** [comment]
The plugin in its current form should be able to (although it doesn’t) scan find these devices via bluetooth. The issue is that i don’t know which properties it exposes or how to be able to determine whether it is “active” (i mean motion detected) or not

**Comment by bwp91** [comment]
and i don’t particularly want to go down the “http” polling route like i did with the leak sensors because that was an absolutely failure

**Comment by bwp91** [comment]
can one purchase one of these motion sensors on its own and it can pair with the govee app? or does it require any bridge?

**Comment by livefeed** [comment]
Yes you can buy on its own and pairs right in the Govee app.

**Comment by bwp91** [comment]
i now have one coming from the USA (they dont seem to sell them in the UK) so should arrive some time next week!

**Comment by livefeed** [comment]
Thanks Ben, If you need a tester I am around.

**Comment by bwp91** [comment]
> Yes you can buy on its own and pairs right in the Govee app.

It arrived today, and I cannot add it to the app because I don't have another device that supports 'distributed gateway'?

😰
