### ISSUE TITLE
Add support for Heater Max H7134

### ISSUE THREAD

**Issue by inventor7777** [bwp91/homebridge-govee#561]
* **Please explain your feature request in a one or two sentences.**
Add compatibility for the new Space Heater with Fireplace Ambience (not released yet)

* **Is your feature request related to a problem? Please describe.**
The device is not supported.

* **Any particular Govee devices that this relates to?**
H7134 Heater

* **Anything else?**
{"device":"81:83:60:74:F4:1D:19:96","deviceName":"Heater Max","model":"H7134","httpInfo":{"groupId":9645165,"device":"81:83:60:74:F4:1D:19:96","sku":"H7134","spec":"","versionHard":"1.02.00","versionSoft":"1.00.17","deviceName":"Heater Max","deviceExt":{"deviceSettings":"{\"wifiName\":\"Govee Access Point\",\"address\":\"60:74:F4:1D:19:97\",\"bleName\":\"GVH71341997\",\"topic\":\"GD/9dd99d2bd81899effd18949870ef5822\",\"wifiMac\":\"60:74:F4:1D:19:96\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.17\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"XlMSdzP/Ego=\",\"dumpOnOff\":1,\"mcuSoftVersion\":\"1.00.07\\u0000\",\"mcuHardVersion\":\"1.00.06\\u0000\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H7134\",\"device\":\"81:83:60:74:F4:1D:19:96\",\"deviceName\":\"Heater Max\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.17\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/b985d8f3305eb98cb2ed3a24792bad53-add_list_type_device_7134.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":179}}
I am a tester for this item and wonder if there is a way to implement support.

**Comment by bwp91** [comment]
Hi @inventor7777 

You can try updating to the beta version of the plugin
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

The device should be added to homebridge and look like a heater, controlling it may or not work as I have initially based this device on similar heater models.

Let me know!

**Comment by inventor7777** [comment]
Thank you! Everything works perfectly! Even the fireplace light can be controlled!

**Comment by inventor7777** [comment]
One last question-is it possible to add oscillation support too?

**Comment by inventor7777** [comment]
@bwp91 Is it possible to add oscillation support?

**Comment by inventor7777** [comment]
Actually, found that separating the accessories in the Home app enabled the oscillation control.

**Comment by bwp91** [comment]
this _should_ work even when the services are combined into one accessory tile 🤨

**Comment by inventor7777** [comment]
![IMG_9439](https://github.com/bwp91/homebridge-govee/assets/142270525/34fe4447-78c3-4cb0-b3ad-ec851877d74f)
![IMG_9440](https://github.com/bwp91/homebridge-govee/assets/142270525/842
![IMG_9441](https://github.com/bwp91/homebridge-govee/assets/142270525/57b660c8-
![IMG_9442](https://github.com/bwp91/homebridge-govee/assets/142270525/e753eb52-2af8-41e5-b477-361b4ec564d5)
850f-4588-8403-75606f21f21b)
![IMG_9443](https://github.c
![IMG_9445](https://github.com/bwp91/homebridge-govee/assets/142270525/d1efa128-f170-4e53-8f26-141da90caf6c)
om/bwp91/homebridge-govee/assets/142270525/63c83ad3-2255-4b8f-88bd-23e2ca669040)

8aa2f-7c08-4eae-a820-3aa4b42ff51b)

Attached are photos of what I see. The photo of the oscillation toggle is only available if you actually open the specific heater accessory (the one with the temperature and heat settings) If you haver the tiles united, the toggle doesn't appear unless you navigate through the accessory settings, to the grouped accessories. it doesn't appear on the main accessory page.

**Comment by inventor7777** [comment]
Some of the photos dint seem to load.
![IMG_9441](https://github.com/bwp91/homebridge-govee/assets/142270525/df7f4522-d87d-4da0-a648-5efca23261ce)
![IMG_9442](https://github.com/bwp91/homebridge-govee/assets/142270525/a7a5ae2e-e9be-4f40-ba70-dedb506020b5)
![IMG_9443](https://github.com/bwp91/homebridge-govee/assets/142270525/6c6b0baf-b0be-44aa-bcfe-a65a23705f85)
