### ISSUE TITLE
H6609 (Gaming Light Strip G1) not supported

### ISSUE THREAD

**Issue by patters** [bwp91/homebridge-govee#563]
* **Please explain your feature request in a one or two sentences.**

When starting the plug-in it warns about this device with some JSON needed to support it. 

* **Any particular Govee devices that this relates to?**

H6609

* **Anything else?**

[8/16/2023, 6:45:21 PM] [Govee] [Govee Gaming Light Strip G1] is not currently supported, do create a Github issue with the following info:
{"ip":"192.168.4.106","device":"redacted…","sku":"H6609","bleVersionHard":"3.05.01","bleVersionSoft":"3.00.03","wifiVersionHard":"1.04.01","wifiVersionSoft":"1.00.12","httpInfo":{"groupId":0,"device":"redacted…","sku":"H6609","spec":"","versionHard":"3.05.01","versionSoft":"3.00.03","deviceName":"Govee Gaming Light Strip G1","deviceExt":{"deviceSettings":"{\"wifiName\":\"redacted\",\"address\":\"redacted\",\"bleName\":\"Govee_H6609_4830\",\"topic\":\"GD/redacted\",\"wifiMac\":\"redacted\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.12\",\"wifiHardVersion\":\"1.04.01\",\"ic\":36,\"secretCode\":\"redacted=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6609\",\"device\":\"redacted\",\"deviceName\":\"Govee Gaming Light Strip G1\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"3.00.03\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5963882c5df9d3fd13ec8e4504afc0c1-add_list_type_device_6609.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/528a92729e57a7eb44e373879280c1bd-new_light_title_605b_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/2db2b862b05eb850e700e76c748b8865-new_light_title_605b_off.png\",\"ext\":\"\",\"ic\":36}"},"pactType":1,"pactCode":1,"share":0,"goodsType":173},"model":"H6609","deviceName":"Govee Gaming Light Strip G1","isLANDevice":true}

**Comment by bwp91** [comment]
Hi @patters 

Please can you update to the beta version of the plugin?
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

The device will show as a light accessory in homekit - hopefully the commands to send to devices are the same as similar models.

Thanks!

**Comment by patters** [comment]
It works, thank you!
