### ISSUE TITLE
H705C Permanent Outdoor LIghts support

### ISSUE THREAD

**Issue by peterstylias** [bwp91/homebridge-govee#567]
* **Please explain your feature request in a one or two sentences.**
There is a new model H705C or maybe its not new but its not supported with the current plug-in.  right now it only supports H705 A and B.

* **Is your feature request related to a problem? Please describe.**
Govee plugin cannot see the device.  Im  not able to add it in homebridge

* **Any particular Govee devices that this relates to?**
H705C Permanent Outdoor Lights

* **Anything else?**

**Comment by bwp91** [comment]
Hi @peterstylias please try the new version of the plugin
