### ISSUE TITLE
H713A issue

### ISSUE THREAD

**Issue by oscar-pitts** [bwp91/homebridge-govee#568]
The H713A heater is showing as a light when using this plugin... Is this the intended behaviour.. How can I get around this?

**Comment by bwp91** [comment]
Hi @oscar-pitts apologies this was a mistake on my behalf! Please try v9.4.1 of the plugin

**Comment by oscar-pitts** [comment]
Excellent thank you so much!! I could NEVER do what you do!

**Comment by oscar-pitts** [comment]
However, I cant seem to get this to work now @bwp91 ... Not too sure if I'm just being stupid (cos I am doing all this with a very limited knowledge) ?

**Comment by bwp91** [comment]
This device should be appeating as a heater accessory in the home app now right?

What can't you get to work?

**Comment by oscar-pitts** [comment]
![IMG_1724](https://github.com/bwp91/homebridge-govee/assets/48858983/7663cac7-8e49-40ba-93c6-eccf0dbc98d0)

**Comment by oscar-pitts** [comment]
confused as to what this is all about - neither one seem to actually make an action happen
