### ISSUE TITLE
Support govee

### ISSUE THREAD

**Issue by Danieleeedldl** [bwp91/homebridge-govee#572]
Hey i just wanted to ask you if my Heater H713C is supported or will be supported any times, because i tryed everything to get it in my homebridge
Thanks guys

**Comment by bwp91** [comment]
Hi @Danieleeedldl 

Please try the beta version of the plugin:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by Danieleeedldl** [comment]
thanks a lot,  it works perfekt now!
