### ISSUE TITLE
Support H713C space heater

### ISSUE THREAD

**Issue by spensonshih** [bwp91/homebridge-govee#575]
* **Please explain your feature request in a one or two sentences.**
Please add support for Space Heater H713C

* **Is your feature request related to a problem? Please describe.**
Device is currently not supported by the plugin.

* **Any particular Govee devices that this relates to?**
Space Heater

* **Anything else?**

{"device":"23:13:D4:AD:FC:81:FD:07","deviceName":"Bathroom Space Heater","model":"H713C","httpInfo":{"groupId":0,"device":"23:13:D4:AD:FC:81:FD:07","sku":"H713C","spec":"","versionHard":"1.02.00","versionSoft":"1.00.06","deviceName":"Bathroom Space Heater","deviceExt":{"deviceSettings":"{\"wifiName\":\"*******\",\"address\":\"**********\",\"bleName\":\"ihoment_H713C_FD08\",\"topic\":\"GD/1f2ce83c8a65684a6e1124c13bd2d6cd\",\"wifiMac\":\"D4:AD:FC:81:FD:07\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.06\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"******",\"dumpOnOff\":1,\"mcuSoftVersion\":\"1.00.03\\u0000\",\"mcuHardVersion\":\"1.00.01\\u0000\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H713C\",\"device\":\"23:13:D4:AD:FC:81:FD:07\",\"deviceName\":\"Bathroom Space Heater\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.06\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":166}}

**Comment by Hendrix90** [comment]
also looking for support for device H713C. 😊

**Comment by Hendrix90** [comment]
works with latest beta! Great thank you!
