### ISSUE TITLE
Model not supported: H61BA

### ISSUE THREAD

**Issue by samthelamb** [bwp91/homebridge-govee#578]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
v1.6.1 (Homebridge A8E0)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Synology DSM; [v18.12.0](https://homebridge.io/w/JTKEF)

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v9.4.2; It works normally with my other LED Light strips, but This model just won't add on to my HomeKit.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H61BA

### Please paste any relevant logs below.

```
{"device":"7D:C8:C6:38:32:34:48:54","deviceName":"TV Strip","model":"H61BA","httpInfo":{"groupId":0,"device":"7D:C8:C6:38:32:34:48:54","sku":"H61BA","spec":"","versionHard":"3.05.00","versionSoft":"3.00.10","deviceName":"TV Strip","deviceExt":{"deviceSettings":"{\"wifiName\":\"The duck goes quack\",\"address\":\"C6:38:32:34:48:54\",\"bleName\":\"Govee_H61BA_4854\",\"topic\":\"GD/0c96388da4c5a54408ecc08ff3406e9b\",\"wifiMac\":\"60:74:F4:35:64:88\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"\",\"wifiHardVersion\":\"\",\"ic\":20,\"secretCode\":\"TDfGODI0SFQ=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H61BA\",\"device\":\"7D:C8:C6:38:32:34:48:54\",\"deviceName\":\"TV Strip\",\"versionHard\":\"3.05.00\",\"versionSoft\":\"3.00.10\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5c8525ab5509e3346cf8daacbfbc58ee-add_list_type_device_61ba.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/07c10ede03d01d3b8dca963414a16d64-h61ba_light_title_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/bba0c5d45c2f1c73dfbc2929d2bc5bb3-h61ba_light_title_off.png\",\"ext\":\"\",\"ic\":20}"},"pactType":1,"pactCode":1,"share":0,"goodsType":178}}
```

**Comment by bwp91** [comment]
Hi @samthelamb 

Please update to the beta version of the plugin:
https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by samthelamb** [comment]
@bwp91 That worked! Thank you :)
