### ISSUE TITLE
Ignored devices

### ISSUE THREAD

**Issue by AlanStout** [bwp91/homebridge-govee#58]
* **Please explain your feature request in a one or two sentences.**
When I add my MAC address it doesn't ignore the device in home , any ideas ? Thanks 

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

* **Anything else?**

**Comment by bwp91** [comment]
hi @AlanStout 
Please post your config so i can check the format for ignored devices is correct. Don’t forget to redact your api key!
