### ISSUE TITLE
H6010 Support

### ISSUE THREAD

**Issue by apb0703** [bwp91/homebridge-govee#582]
* **Please explain your feature request in a one or two sentences.**
Please add support for the new BR30 H6010 if possible

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

H6010

* **Anything else?**

**Comment by bwp91** [comment]
Hi @apb0703 

Please install the beta version of the plugin

This should get this device working :)
https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by apb0703** [comment]
Thank you!
