### ISSUE TITLE
Color is spelled wrong

### ISSUE THREAD

**Issue by TheBrettYT** [bwp91/homebridge-govee#583]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI

* Which version of Homebridge/HOOBS do you have?
v1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
The latest firmware

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6117 and H6125
Colors won't change very buggy from communicating with HomeKit etc

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @TheBrettYT 

Please try this first with regards to colour issues:

https://github.com/bwp91/homebridge-govee/wiki/Common-Errors#colour-issues

**Comment by TheBrettYT** [comment]
> 

No I'm saying is it supposed to be spelled colour or color I'm not sure.

**Comment by bwp91** [comment]
Oh I see - well i’m from the UK, so colour is correct for me 😄

**Comment by TheBrettYT** [comment]
> o

Oh haha Its ok I still understand what It means in the US

**Comment by TheBrettYT** [comment]
Also the color doesn't change is that a bug request as well.
