### ISSUE TITLE
Installing v9.4.2 and v9.4.3-beta.3 has caused my Govee devices to stop working on my Hoobs

### ISSUE THREAD

**Issue by wilky761** [bwp91/homebridge-govee#586]
### What issue do you have? Please be as thorough and explicit as possible.
None of my Govee devices are working on HOOBS

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
HOOBS 4.2.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
HOOBS Box

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
Issue started upgrading from v9.4.0 to 9.4.2

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
NONE of my Govee devices are working now.

### Please paste any relevant logs below.
11/09/2023, 14:44:12HoobsGoveeInitialising plugin v9.4.2 | System linux | Node v16.20.2 | HB v1.6.0 | HAPNodeJS v0.11.0...
11/09/2023, 14:44:12HoobsGoveeWARNINGConfig entry [apiRefreshTime] is unused and can be removed.
11/09/2023, 14:44:13HoobsGoveePlugin initialised. Setting up accessories....
11/09/2023, 14:44:17HoobsGovee[LAN] client enabled and found 0 device(s).
11/09/2023, 14:44:17HoobsGoveeWARNING[HTTP] could not use existing access token as no data received from Govee server whilst obtaining devices at default.getDevices (file:///var/lib/hoobs/hoobs/node_modules/homebridge-govee/lib/connection/http.js:162:15).
11/09/2023, 14:44:18HoobsGoveeWARNING[AWS] disabling client as requires HTTP client.
11/09/2023, 14:44:18HoobsGoveeWARNING[HTTP] disabling client as Incorrect password at default.login (file:///var/lib/hoobs/hoobs/node_modules/homebridge-govee/lib/connection/http.js:48:19).
11/09/2023, 14:44:18HoobsGovee[BLE] client enabled.
11/09/2023, 14:44:18HoobsGoveeWARNING***** Disabling plugin [v9.4.2]. *****
11/09/2023, 14:44:18HoobsGoveeWARNING***** No devices found to initialise. *****
11/09/2023, 14:45:01HoobsGoveeInitialising plugin v9.4.2 | System linux | Node v16.20.2 | HB v1.6.0 | HAPNodeJS v0.11.0...
11/09/2023, 14:45:01HoobsGoveeWARNINGConfig entry [apiRefreshTime] is unused and can be removed.
11/09/2023, 14:45:06HoobsGoveePlugin initialised. Setting up accessories....
11/09/2023, 14:45:09HoobsGovee[LAN] client enabled and found 0 device(s).
11/09/2023, 14:45:10HoobsGoveeWARNING[HTTP] could not use existing access token as no data received from Govee server whilst obtaining devices at default.getDevices (file:///var/lib/hoobs/hoobs/node_modules/homebridge-govee/lib/connection/http.js:162:15).
11/09/2023, 14:45:10HoobsGoveeWARNING[HTTP] disabling client as The number of consecutive failed logins for this account has reached the maximum. Please try again in 5 minutes. at default.login (file:///var/lib/hoobs/hoobs/node_modules/homebridge-govee/lib/connection/http.js:58:15).
11/09/2023, 14:45:10HoobsGoveeWARNING[AWS] disabling client as requires HTTP client.
11/09/2023, 14:45:11HoobsGovee[BLE] client enabled.
11/09/2023, 14:45:11HoobsGoveeWARNING***** Disabling plugin [v9.4.2]. *****
11/09/2023, 14:45:11HoobsGoveeWARNING***** No devices found to initialise. *****

**Comment by bwp91** [comment]
hi @wilky761 the logs say your govee password is wrong.

and this is the message from the govee server so please double check your password is correct

**Comment by wilky761** [comment]
Oh awesome, thanks. Not sure how that has happened.
