### ISSUE TITLE
[Ceiling Light] is not currently supported,

### ISSUE THREAD

**Issue by Jwat206** [bwp91/homebridge-govee#589]
* **Please explain your feature request in a one or two sentences.**
The new round panel ceiling light.

* **Is your feature request related to a problem? Please describe.**
It just doesn’t work yet. Log said to submit.

* **Any particular Govee devices that this relates to?**
Round panel ceiling light.

* **Anything else?**

[14/09/2023, 15:48:17] [Govee] [Ceiling Light] is not currently supported,
do create a Github
issue with the following info:
{"device":"06:EF:60:74:F4:66:E0 :EA"
, "deviceName
": "Ceiling Light", "model": "H60A0", "httpInfo": {" groupId": 0, "device" :"06:EF:60:74:F4:66:E0:EA" sku": "H60A0" ,"spec": "" , "deviceName": "Ceiling ight" , "deviceExt" : {"deviceSettings":"{\"wifinam el":\ "$7/“3!500000\",\ "address\":\ "60:74:F4:66:
E0 :EB\",\ "bleName\": \ "GVH60A0E0EB\", \ "topic\": \
"GD/b6e0ba2603b00599ee8378475c4cb7£7\",\ "wifiMa
c\":\"60:74:F4:66:E0:EAl",\"pactIype\" :1, \"pact
Code\":1,\ "wifisoftVersion\":\"1.00.171",\"wifi Hardversion\":\"1.02.00\",\"ic\" :13, \"boilwater
CompletedNotionoff\" ： 1， \"completionNotiOnoff\"：
1,\ "autoshutDownOnOff\" :1,\"sku\":\ "H60A0\"
, l"d
evice\" ："06:EF:60:74:F4:66:EO:EA\"
, \"deviceNam
el":\ "Ceiling Light\", \"versionHard)":\"1.02.00 ,\"versionSoft\":\"1.00.17\",\"playState\": fa
Ise}", "lastDeviceData":"{\"online\" :false}" , "ex tResources":"{\"skuUrl|":\"https://d1f2504ijhdy
jw.cloudfront.net/sku-img/d2addc9100bfd835bed56
0170011Id2a-add_list_type_device
60a0.png\"
‚l"h
eadOnImg\":\"\",\ "headoffImg\":\"\",\"ext\":\"\
,\"icl" :13}"},
, "pactIype" :1, "pactCode" :1, "share
":0, "goodsType" : 188}

**Comment by bwp91** [comment]
Hi @Jwat206 

Please install the beta version of the plugin. You should find this device starts to work:

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

Question - does this device support LAN mode - do you have the option for this in your govee app?

**Comment by Jwat206** [comment]
That worked! Thank you. It does not support LAN mode. At least not yet. I’m in one of the testing groups testing the light out right now. They’ve added that capability to other lights in the past after testing. I do push for it when I do reviews and feedback.Thanks again for your help! All my BestOn Sep 15, 2023, at 15:14, Ben ***@***.***> wrote:﻿
Hi @Jwat206
Please install the beta version of the plugin. You should find this device starts to work:
https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions
Question - does this device support LAN mode - do you have the option for this in your govee app?
