### ISSUE TITLE
H61BC

### ISSUE THREAD

**Issue by modernoutlaw** [bwp91/homebridge-govee#591]
Hi! I have a light strip, model number H61BC and I was wondering if the plugin supported that model? Thanks!!

**Comment by bwp91** [comment]
Hi, is this device wifi? bluetooth? both?

**Comment by modernoutlaw** [comment]
Hi Ben! Both wifi and bluetooth

From: Ben ***@***.***>
Date: Friday, September 15, 2023 at 12:44 PM
To: bwp91/homebridge-govee ***@***.***>
Cc: Jonathan Clark ***@***.***>, Author ***@***.***>
Subject: Re: [bwp91/homebridge-govee] H61BC (Issue #591)

Hi, is this device wifi? bluetooth? both?

**Comment by bwp91** [comment]
Also meant to ask, does this device support LAN mode? do you have the option for it in your govee app?

**Comment by bwp91** [comment]
Anyway - you can install the beta version of the plugin, and this model should be supported:

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by modernoutlaw** [comment]
Installing the beta brought it in as an accessory, thanks! To your earlier question, yes, it does have LAN mode available (and is enabled). Thanks!

From: Ben ***@***.***>
Date: Friday, September 15, 2023 at 1:48 PM
To: bwp91/homebridge-govee ***@***.***>
Cc: Jonathan Clark ***@***.***>, Author ***@***.***>
Subject: Re: [bwp91/homebridge-govee] H61BC (Issue #591)

Anyway - you can install the beta version of the plugin, and this model should be supported:

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by bwp91** [comment]
@modernoutlaw if you update to the newer beta version (same instructions) the plugin will utilise lan mode when it can 👍

**Comment by modernoutlaw** [comment]
[like]  Jonathan Clark reacted to your message:
________________________________
