### ISSUE TITLE
One of the temperatures is showing up as 0 degrees

### ISSUE THREAD

**Issue by philjones** [bwp91/homebridge-govee#592]
### What issue do you have? Please be as thorough and explicit as possible.

I have a set of 3 H5100 temperature and hygrometer - one of them is showing 0 degrees C according to the UI

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1) Homebridge UI-X primarily

* Which version of Homebridge/HOOBS do you have?

Homebridge v1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Homebridge on Raspberry Pi 3

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

homebridge-govee@9.4.3-beta.5 - it was happening on the latest published version as well

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H5100

### Please paste any relevant logs below.

```
[16/09/2023, 20:42:35] [homebridge-govee] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[16/09/2023, 20:42:35] [Govee] [Freezer] current temperature [NaN°C / NaN°F].
```

**Comment by bwp91** [comment]
Hi @philjones do you still have this issue if you try the newest beta?

I'm trying to work out at this point:

https://github.com/bwp91/homebridge-govee/blob/3202e3a44acf6a7b36e096652895624a765bb82a/lib/platform.js#L1141-L1149

why a value isn't being saved into the `accessory.context.offTemp`.

https://github.com/bwp91/homebridge-govee/pull/593/files

Thanks for taking the time to provide a PR, I appreciate this would indeed sort out the issue, but I would rather try and fix this at the 'source' if possible.

**Comment by philjones** [comment]
Oddly, the beta seems to work - yes

I don't really see how these are different - based on what I was observing with `temCali` being `undefined` I would have expected no tempMin / tempMax to show - or is that set somewhere else?

https://github.com/bwp91/homebridge-govee/commit/ad182b2843230ada9255df9d1e665129104de4ab#diff-69c8555fe1714c34d62f83b86f2040c16df16047cc5887d5b903ca7e610108c6R1144

Either way, thanks for the fix!

**Comment by bwp91** [comment]
The only way i can’t see my original code working is if the value of temMax is `0`, can this be the case for the sensor which wasn’t working?

**Comment by philjones** [comment]
Ah, good call!

Yes, this particular sensor is in the freezer lol so it's current temp is -15.9C so it seems plausible that the `temMax` would be `0`.
