### ISSUE TITLE
Smart Aroma Diffuser Support

### ISSUE THREAD

**Issue by anthonymkz** [bwp91/homebridge-govee#595]
* **Which model is this? Need the `Hxxxx` number.**
H7162

* **Which type of device is this? Light, heater, leak sensor, etc.**
Smart Aroma Diffuser

* **Which connection methods does this device have? Wifi? Bluetooth? Both?**
Both

* **Anything else?**
[22/09/2023, 21:23:52] [Govee] [Smart Aroma Diffuser] is not currently supported, do create a Github issue with the following info:
{"device":"16:8C:60:74:F4:3A:E6:22","deviceName":"Smart Aroma Diffuser","model":"H7162","httpInfo":{"groupId":0,"device":"16:8C:60:74:F4:3A:E6:22","sku":"H7162","spec":"","versionHard":"1.02.00","versionSoft":"1.00.04","deviceName":"Smart Aroma Diffuser","deviceExt":{"deviceSettings":"{\"wifiName\":\"MKZNetwork\",\"address\":\"60:74:F4:3A:E6:23\",\"bleName\":\"ihoment_H7162_E623\",\"topic\":\"GD/86bd4df0a7a750575e9c4d906d79f132\",\"wifiMac\":\"60:74:F4:3A:E6:22\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.04\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"SDaWMkthGE0=\",\"waterShortageOnOff\":1,\"mcuSoftVersion\":\"1.00.08\",\"mcuHardVersion\":\"1.00.01\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H7162\",\"device\":\"16:8C:60:74:F4:3A:E6:22\",\"deviceName\":\"Smart Aroma Diffuser\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.04\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/1cbe00f8a15fc7bc9e4950eed9009c0a-add_list_type_device_7162.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":189}}

**Comment by inventor7777** [comment]
Same-
My log-
[Diffuser] is not currently supported, do create a Github issue with the following info:
{"device":"20:15:60:74:F4:3C:71:F6","deviceName":"Diffuser","model":"H7162","httpInfo":{"groupId":9645165,"device":"20:15:60:74:F4:3C:71:F6","sku":"H7162","spec":"","versionHard":"1.02.00","versionSoft":"1.00.04","deviceName":"Diffuser","deviceExt":{"deviceSettings":"{\"wifiName\":\"Govee Access Point\",\"address\":\"60:74:F4:3C:71:F7\",\"bleName\":\"ihoment_H7162_71F7\",\"topic\":\"GD/b0164c8067439299aa0f6c82c8fbe44c\",\"wifiMac\":\"60:74:F4:3C:71:F6\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.04\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"sZKpDJXP3VQ=\",\"waterShortageOnOff\":1,\"mcuSoftVersion\":\"1.00.08\",\"mcuHardVersion\":\"1.00.01\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H7162\",\"device\":\"20:15:60:74:F4:3C:71:F6\",\"deviceName\":\"Diffuser\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.04\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/1cbe00f8a15fc7bc9e4950eed9009c0a-add_list_type_device_7162.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":18

**Comment by bwp91** [comment]
Hi @anthonymkz  /  @inventor7777 

The diffuser is not a device I have implemented before, so I will need some help with this, easiest on Discord if either of you are on there?

Either via the homebridge server at https://discord.gg/kqNCe2D
Or directly, my username is `bwp91`

Thanks!

**Comment by inventor7777** [comment]
Hey @bwp91! I don't use Discord, but the diffuser has an LED strip around the base, and a high/low setting for the diffusion. The Pro model has white noise built in, but I can't see that being added to the Home app.

Here's the link to Govee's website - https://us.govee.com/collections/new-release-smart-appliances/products/goveelife-smart-essential-oil-diffuser

**Comment by inventor7777** [comment]
Hey @bwp91! I'm on the latest beta version of the plugin and the diffuser shows as not supported. 
Is that supposed to happen? 
<img width="516" alt="BC020398-91CF-4718-A2D4-74C677901DDB" src="https://github.com/bwp91/homebridge-govee/assets/142270525/701d29d1-3ac5-4850-81d8-420ef030014f">

**Comment by claudiomorabito** [comment]
Also H7161 is a smart diffuser, I opened a dedicated issue for that model, however it should work the same way.

Thanks.
