### ISSUE TITLE
Issue with calling frequency on water leak sensors 

### ISSUE THREAD

**Issue by recoi1er** [bwp91/homebridge-govee#598]
### What issue do you have? Please be as thorough and explicit as possible.

In the Govee app 2 of my water sensors don’t work when I tap on them they say “Too many request, try again later”. I reached out to Govee and they said it’s the 3rd party plugin I’m using that made too many requests. They said they have no way of resetting that error but that the plugin dev would? Something about changing the frequency it calls on the devices to stop that alert in the app, but my question is how do I even stop the plugin from calling / reset currently so I can access the devices again. Govee didn’t have an answer for that, they had no clue.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
Hoobs V:4.3.0
Homebridge: 1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 3B+ 
Node: 16.20.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
9.4.2 has been going on for months

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
(Only 2 of these sensors have the error) Water sensor x5: H5054

(Not having any issues) Temp sensors x3: H5179

### Please paste any relevant logs below.

```
9/27/2023, 2:51:39 PMGovee BridgeERROR[Govee Bridge 6D55@Beer Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
9/27/2023, 2:51:39 PMGovee BridgeGovee[Beer Freezer] current temperature [NaN°C / NaN°F].
9/27/2023, 2:51:39 PMGovee BridgeGovee[Main Freezer] current battery [84%].
9/27/2023, 2:51:39 PMGovee BridgeGovee[Main Freezer] current temperature [NaN°C / NaN°F].
9/27/2023, 2:51:39 PMGovee BridgeERROR[Govee Bridge 6D55@Main Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
9/27/2023, 2:51:39 PMGovee BridgeERROR[Govee Bridge 6D55@Cabinet Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
9/27/2023, 2:51:39 PMGovee BridgeGovee[Cabinet Freezer] current temperature [NaN°C / NaN°F].
9/27/2023, 2:51:46 PMgoveebridge stopping
9/27/2023, 2:51:49 PMGovee Bridge starting
9/27/2023, 2:51:56 PMGovee BridgeLoaded plugin 'homebridge-govee'
9/27/2023, 2:51:56 PMGovee BridgeLoading 1 platforms...
9/27/2023, 2:51:56 PMGovee BridgeGoveeInitialising plugin v9.4.2 | System linux | Node v16.20.2 | HB v1.6.0 | HAPNodeJS v0.11.0...
9/27/2023, 2:51:56 PMGovee BridgeGoveeWARNINGConfig entry [apiKey] is unused and can be removed.
9/27/2023, 2:51:56 PMGovee BridgeGoveePlugin initialised. Setting up accessories....
9/27/2023, 2:51:56 PMGovee BridgeBridge is running on port 51896.
9/27/2023, 2:51:58 PMGovee BridgeGovee[LAN] client enabled and found 0 device(s).
9/27/2023, 2:51:59 PMGovee BridgeGovee[HTTP] client enabled and found 10 device(s).
9/27/2023, 2:51:59 PMGovee BridgeGovee[AWS] client enabled.
9/27/2023, 2:51:59 PMGovee BridgeGovee[BLE] client enabled.
9/27/2023, 2:51:59 PMGovee BridgeGovee[Beer Freezer] initialising with options {"lowBattThreshold":20}.
9/27/2023, 2:51:59 PMGovee BridgeGovee[Beer Freezer] initialised with id [D1:18:18:1F:69:51:04:F3] [H5179].
9/27/2023, 2:51:59 PMGovee BridgeGovee[Main Freezer] initialising with options {"lowBattThreshold":20}.
9/27/2023, 2:51:59 PMGovee BridgeGovee[Main Freezer] initialised with id [05:63:18:1F:69:51:C8:B2] [H5179].
9/27/2023, 2:51:59 PMGovee BridgeGovee[Cabinet Freezer] initialising with options {"lowBattThreshold":20}.
9/27/2023, 2:51:59 PMGovee BridgeGovee[Cabinet Freezer] initialised with id [43:FC:18:1F:69:90:FC:25] [H5179].
9/27/2023, 2:51:59 PMGovee BridgeGovee[Master Toilet Sensor] initialising with options {}.
9/27/2023, 2:51:59 PMGovee BridgeGovee[Master Toilet Sensor] initialised with id [4E75251FB34F00CB45] [H5054].
9/27/2023, 2:51:59 PMGovee BridgeGovee[Master Sink Sensor] initialising with options {}.
9/27/2023, 2:51:59 PMGovee BridgeGovee[Master Sink Sensor] initialised with id [4E75251FB34F00C0BE] [H5054].
9/27/2023, 2:52:00 PMGovee BridgeGovee[Guest Toilet Sensor] initialising with options {}.
9/27/2023, 2:52:00 PMGovee BridgeGovee[Guest Toilet Sensor] initialised with id [4E75251FB34F00C9E2] [H5054].
9/27/2023, 2:52:00 PMGovee BridgeGovee[Guest Sink Sensor] initialising with options {}.
9/27/2023, 2:52:00 PMGovee BridgeGovee[Guest Sink Sensor] initialised with id [4E75251FB34F00CB2E] [H5054].
9/27/2023, 2:52:00 PMGovee BridgeGovee[Kitchen Sink Sensor] initialising with options {}.
9/27/2023, 2:52:00 PMGovee BridgeGovee[Kitchen Sink Sensor] initialised with id [4E75251FB34F0001A3] [H5054].
9/27/2023, 2:52:00 PMGovee BridgeGovee[MudRoom Sensor] initialising with options {}.
9/27/2023, 2:52:00 PMGovee BridgeGovee[MudRoom Sensor] initialised with id [4E75251FB34F0002C2] [H5054].
9/27/2023, 2:52:00 PMGovee BridgeGovee[Water Heater Sensor] initialising with options {}.
9/27/2023, 2:52:00 PMGovee BridgeGovee[Water Heater Sensor] initialised with id [4E75251FB34F000136] [H5054].
9/27/2023, 2:52:01 PMGovee BridgeERROR[Govee Bridge 6D55@Beer Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
9/27/2023, 2:52:01 PMGovee BridgeGovee[Beer Freezer] current temperature [NaN°C / NaN°F].
9/27/2023, 2:52:01 PMGovee BridgeGovee[Beer Freezer] current humidity [81.7%].
9/27/2023, 2:52:01 PMGovee BridgeERROR[Govee Bridge 6D55@Main Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
9/27/2023, 2:52:01 PMGovee BridgeGovee[Main Freezer] current temperature [NaN°C / NaN°F].
9/27/2023, 2:52:01 PMGovee BridgeGovee[Main Freezer] current humidity [58.8%].
9/27/2023, 2:52:01 PMGovee BridgeERROR[Govee Bridge 6D55@Cabinet Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
9/27/2023, 2:52:01 PMGovee BridgeGovee[Cabinet Freezer] current temperature [NaN°C / NaN°F].
9/27/2023, 2:52:01 PMGovee BridgeGovee[Cabinet Freezer] current humidity [71.4%].
9/27/2023, 2:52:01 PMGovee BridgeGovee✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
```

**Comment by bwp91** [comment]
Hi @recoi1er 

In the plugin settings in the hoobs ui, you should see a setting called `HTTP Refresh Interval`.

Try putting this number to `300` (5 minutes) and leave this for ~24 hours. You should find this no longer leads to the Govee error message

**Comment by bwp91** [comment]
I see you're not really having a good time with the plugin in general, referring to these logs:

```
9/27/2023, 2:52:01 PMGovee BridgeERROR[Govee Bridge 6D55@Beer Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
9/27/2023, 2:52:01 PMGovee BridgeGovee[Beer Freezer] current temperature [NaN°C / NaN°F].
9/27/2023, 2:52:01 PMGovee BridgeGovee[Beer Freezer] current humidity [81.7%].
9/27/2023, 2:52:01 PMGovee BridgeERROR[Govee Bridge 6D55@Main Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
9/27/2023, 2:52:01 PMGovee BridgeGovee[Main Freezer] current temperature [NaN°C / NaN°F].
9/27/2023, 2:52:01 PMGovee BridgeGovee[Main Freezer] current humidity [58.8%].
9/27/2023, 2:52:01 PMGovee BridgeERROR[Govee Bridge 6D55@Cabinet Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
9/27/2023, 2:52:01 PMGovee BridgeGovee[Cabinet Freezer] current temperature [NaN°C / NaN°F].
9/27/2023, 2:52:01 PMGovee BridgeGovee[Cabinet Freezer] current humidity [71.4%].
```

**Comment by bwp91** [comment]
If you'd be happy to give a bit of time, I'd love to try and sort out these temperature log issues

**Comment by recoi1er** [comment]
Thank you so much for responding! I set the interval to 300 - I will let you know tomorrow how that looks then!

I am all for helping with the temp log issues - just let me know what needs to be done and I’ll do it!

**Comment by recoi1er** [comment]
> If you'd be happy to give a bit of time, I'd love to try and sort out these temperature log issues

Ok it’s been a few days and both devices’ status have not changed in the app at all


`10/1/2023, 7:37:40 AMGovee BridgeERROR[Govee Bridge 6D55@Beer Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
10/1/2023, 7:37:40 AMGovee BridgeGovee[Beer Freezer] current temperature [NaN°C / NaN°F].
10/1/2023, 7:37:40 AMGovee BridgeGovee[Main Freezer] current temperature [NaN°C / NaN°F].
10/1/2023, 7:37:40 AMGovee BridgeERROR[Govee Bridge 6D55@Main Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
10/1/2023, 7:37:40 AMGovee BridgeGovee[Cabinet Freezer] current temperature [NaN°C / NaN°F].
10/1/2023, 7:37:40 AMGovee BridgeERROR[Govee Bridge 6D55@Cabinet Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
10/1/2023, 7:37:40 AMGovee BridgeGovee[Cabinet Freezer] current humidity [37.5%].
10/1/2023, 7:37:41 AMgoveebridge stopping
10/1/2023, 7:37:44 AMGovee Bridge starting
10/1/2023, 7:37:50 AMGovee BridgeLoaded plugin 'homebridge-govee'
10/1/2023, 7:37:50 AMGovee BridgeLoading 1 platforms...
10/1/2023, 7:37:50 AMGovee BridgeGoveeInitialising plugin v9.4.2 | System linux | Node v16.20.2 | HB v1.6.0 | HAPNodeJS v0.11.0...
10/1/2023, 7:37:50 AMGovee BridgeGoveeWARNINGConfig entry [apiKey] is unused and can be removed.
10/1/2023, 7:37:50 AMGovee BridgeGoveePlugin initialised. Setting up accessories....
10/1/2023, 7:37:51 AMGovee BridgeBridge is running on port 51896.
10/1/2023, 7:37:53 AMGovee BridgeGovee[LAN] client enabled and found 0 device(s).
10/1/2023, 7:37:53 AMGovee BridgeGovee[HTTP] client enabled and found 10 device(s).
10/1/2023, 7:37:54 AMGovee BridgeGovee[AWS] client enabled.
10/1/2023, 7:37:54 AMGovee BridgeGovee[BLE] client enabled.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Beer Freezer] initialising with options {"lowBattThreshold":20}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Beer Freezer] initialised with id [D1:18:18:1F:69:51:04:F3] [H5179].
10/1/2023, 7:37:54 AMGovee BridgeGovee[Main Freezer] initialising with options {"lowBattThreshold":20}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Main Freezer] initialised with id [05:63:18:1F:69:51:C8:B2] [H5179].
10/1/2023, 7:37:54 AMGovee BridgeGovee[Cabinet Freezer] initialising with options {"lowBattThreshold":20}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Cabinet Freezer] initialised with id [43:FC:18:1F:69:90:FC:25] [H5179].
10/1/2023, 7:37:54 AMGovee BridgeGovee[Master Toilet Sensor] initialising with options {}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Master Toilet Sensor] initialised with id [4E75251FB34F00CB45] [H5054].
10/1/2023, 7:37:54 AMGovee BridgeGovee[Master Sink Sensor] initialising with options {}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Master Sink Sensor] initialised with id [4E75251FB34F00C0BE] [H5054].
10/1/2023, 7:37:54 AMGovee BridgeGovee[Guest Toilet Sensor] initialising with options {}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Guest Toilet Sensor] initialised with id [4E75251FB34F00C9E2] [H5054].
10/1/2023, 7:37:54 AMGovee BridgeGovee[Guest Sink Sensor] initialising with options {}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Guest Sink Sensor] initialised with id [4E75251FB34F00CB2E] [H5054].
10/1/2023, 7:37:54 AMGovee BridgeGovee[Kitchen Sink Sensor] initialising with options {}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Kitchen Sink Sensor] initialised with id [4E75251FB34F0001A3] [H5054].
10/1/2023, 7:37:54 AMGovee BridgeGovee[MudRoom Sensor] initialising with options {}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[MudRoom Sensor] initialised with id [4E75251FB34F0002C2] [H5054].
10/1/2023, 7:37:54 AMGovee BridgeGovee[Water Heater Sensor] initialising with options {}.
10/1/2023, 7:37:54 AMGovee BridgeGovee[Water Heater Sensor] initialised with id [4E75251FB34F000136] [H5054].
10/1/2023, 7:37:55 AMGovee BridgeERROR[Govee Bridge 6D55@Beer Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
10/1/2023, 7:37:55 AMGovee BridgeGovee[Beer Freezer] current temperature [NaN°C / NaN°F].
10/1/2023, 7:37:55 AMGovee BridgeGovee[Beer Freezer] current humidity [82.1%].
10/1/2023, 7:37:55 AMGovee BridgeERROR[Govee Bridge 6D55@Main Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
10/1/2023, 7:37:55 AMGovee BridgeGovee[Main Freezer] current temperature [NaN°C / NaN°F].
10/1/2023, 7:37:55 AMGovee BridgeGovee[Main Freezer] current humidity [67.7%].
10/1/2023, 7:37:55 AMGovee BridgeGovee[Cabinet Freezer] current temperature [NaN°C / NaN°F].
10/1/2023, 7:37:55 AMGovee BridgeGovee[Cabinet Freezer] current humidity [37.5%].
10/1/2023, 7:37:55 AMGovee BridgeERROR[Govee Bridge 6D55@Cabinet Freezer@@Current Temperature] characteristic value expected valid finite number and received "NaN" (number)
10/1/2023, 7:37:56 AMGovee BridgeGovee✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful! `

**Comment by recoi1er** [comment]
> If you'd be happy to give a bit of time, I'd love to try and sort out these temperature log issues

Checking in again with you on this - no change on my end still!
