### ISSUE TITLE
Device request for H601B

### ISSUE THREAD

**Issue by jbev79** [bwp91/homebridge-govee#599]
* **Please explain your feature request in a one or two sentences.**
I recently purchased the 4 inch ceiling lights, H601B, and received an error in this plugin stating they are not supported

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**
This relates specifically to the H601B ceiling lights

* **Anything else?**

27/09/2023, 17:38:38] [Govee] [Soffit Peak Left Bot] is not currently supported, do create a Github issue with the following info:
{"device":"FE:83:60:74:F4:2B:38:10","deviceName":"Soffit Peak Left Bot","model":"H601B","httpInfo":{"groupId":0,"device":"FE:83:60:74:F4:2B:38:10","sku":"H601B","spec":"","versionHard":"1.02.00","versionSoft":"1.00.04","deviceName":"Soffit Peak Left Bot","deviceExt":{"deviceSettings":"{\"address\":\"60:74:F4:2B:38:11\",\"bleName\":\"ihoment_H601B_3811\",\"topic\":\"GD/6af3a9562f4c76793f8dadc551b17578\",\"wifiMac\":\"60:74:F4:2B:38:10\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"\",\"wifiHardVersion\":\"\",\"ic\":0,\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H601B\",\"device\":\"FE:83:60:74:F4:2B:38:10\",\"deviceName\":\"Soffit Peak Left Bot\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.04\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/ebb32b4d1a5412299cfd99ee2a517993-add_list_type_device_601b.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/87b948e0f6d6da6a03dce2e8262fb288-new_light_title_601a_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/0ffd6e8b02c9a3756d1d57929773573b-new_light_title_601a_off.png\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":111}}
[27/09/2023, 17:38:38] [Govee] [Front Triangle Lights] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.

**Comment by bwp91** [comment]
Hi @jbev79 

Please install the beta version of the plugin:
https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by jbev79** [comment]
Thank You. That solved my issue.
