### ISSUE TITLE
H6102

### ISSUE THREAD

**Issue by thgibs** [bwp91/homebridge-govee#60]
* **Please explain your feature request in a one or two sentences.**

is it possible to add H6102 Lightstrip zo the supported devices

* **Is your feature request related to a problem? Please describe.**

* **Any particular ECOVACS devices that this relates to?**
H6102 Lightstrip

* **Anything else?**

**Comment by bwp91** [comment]
Hi @thgibs 

Unfortunately the models that are supported by this plugin are specifically stated by the Govee API, in other words, adding support for new models is impossible unless Govee specifically allows this.

The 'latest' supported models are always visible on the wiki page:
https://github.com/bwp91/homebridge-govee/wiki/Supported-Devices

In fact I think the H6102 does not support wifi (only bluetooth) so it is very unlikely this model will ever be supported :(
