### ISSUE TITLE
Support for H6088

### ISSUE THREAD

**Issue by TheBassfly** [bwp91/homebridge-govee#600]
Support for the unsupported Cube Wall Scones H6088

* **Any particular Govee devices that this relates to?**
H6088

* **Anything else?**
Homebridge output:
[Cube Wall Sconces] is not currently supported, do create a Github issue with the following info:
{"device":"24:C0:D7:38:32:34:56:79","deviceName":"Cube Wall Sconces","model":"H6088","httpInfo":{"groupId":0,"device":"24:C0:D7:38:32:34:56:79","sku":"H6088","spec":"","versionHard":"3.05.01","versionSoft":"3.00.13","deviceName":"Cube Wall Sconces","deviceExt":{"deviceSettings":"{\"wifiName\":\"WL'habitant\",\"address\":\"D7:38:32:34:56:79\",\"bleName\":\"Govee_H6088_5679\",\"topic\":\"GD/b9f5b7a86123943637281832727c0321\",\"wifiMac\":\"60:74:F4:1F:94:FA\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"\",\"wifiHardVersion\":\"\",\"ic\":6,\"secretCode\":\"jhXXODI0Vnk=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6088\",\"device\":\"24:C0:D7:38:32:34:56:79\",\"deviceName\":\"Cube Wall Sconces\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"3.00.13\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/516e83c0a68eee2cee7e95757659b359-add_list_type_device_6088.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/e2225b1d7579ecb3828bb5ce29ada86e-new_light_title_6088_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/784f767e0550df843a1d189b39b5d284-new_light_title_6088_off.png\",\"ext\":\"\",\"ic\":6}"},"pactType":1,"pactCode":1,"share":0,"goodsType":157}}

**Comment by bwp91** [comment]
Hi @TheBassfly 

Please try the beta version of the plugin

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by TheBassfly** [comment]
Works

Thank you!
