### ISSUE TITLE
H713A (Euro variant of H7130) AWS control not working

### ISSUE THREAD

**Issue by n13ldo** [bwp91/homebridge-govee#602]
* **Which model is this? Need the `Hxxxx` number.**
H713A

* **Which type of device is this? Light, heater, leak sensor, etc.**
Heater

* **Which connection methods does this device have? Wifi? Bluetooth? Both?**
Wifi

* **Anything else?**
H713A is the 220-240v version of the already supported H7130. Only difference I can tell is the mains voltage and the unit's temperature measurement is in Celcius, not Fahrenheit.

**Comment by n13ldo** [comment]
So after forking and looking through the project I spotted H713A in there. 

However, after adding this plugin to Homebride, entering my Govee credentials, plugin finds the device but then asking the Heater to turn on - nothing happens and the status in the log changes from ON to OFF after a short period (seconds)

**Comment by bwp91** [comment]
Hi @n13ldo 

Please try the beta version of the plugin

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by n13ldo** [comment]
Hi, I had already switched to version v9.4.3-beta.11 between my original post here and my reply. Overnight (Now Mon 2nd Oct) it has started working, without my intervention. This morning I can control the heater target heat and get current temp, in HA. Also current status is correctly reported through this plugin when I use the Govee app directly on my phone to interact with the heater.
