### ISSUE TITLE
Support For Smart Space Heater : H713C 

### ISSUE THREAD

**Issue by A3H1M4SA** [bwp91/homebridge-govee#603]
* **Which model is this? Need the `Hxxxx` number.**
Smart Space Heater : H713C

* **Which type of device is this? Light, heater, leak sensor, etc.**

Heater

* **Which connection methods does this device have? Wifi? Bluetooth? Both?**

Both Wifi and Bluetooth

**Comment by bwp91** [comment]
Hi @AhimsaGMS 

Please try the beta version of the plugin

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions
