### ISSUE TITLE
Support Request: Light H601B

### ISSUE THREAD

**Issue by robjschroeder** [bwp91/homebridge-govee#604]
* **Which model is this? Need the `Hxxxx` number.**
* 
H601B

* **Which type of device is this? Light, heater, leak sensor, etc.**
Light

* **Which connection methods does this device have? Wifi? Bluetooth? Both?**
Both

* **Anything else?**
* Thanks!

**Comment by bwp91** [comment]
Hi @robjschroeder 

Please try the beta version of the plugin

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by robjschroeder** [comment]
@bwp91 , devices were discovered with beta version of plugin.
