### ISSUE TITLE
Device Request: H61C5

### ISSUE THREAD

**Issue by DerElefant69** [bwp91/homebridge-govee#606]
* **Which model is this? Need the `Hxxxx` number.**
H61C5

* **Which type of device is this? Light, heater, leak sensor, etc.**
Light / RGBIC LED Strip

* **Which connection methods does this device have? Wifi? Bluetooth? Both?**
Both

* **Anything else?**
[RGBIC Neon Rope Lights] is not currently supported, do create a Github issue with the following info:
{"ip":"10.0.0.24","device":"59:CD:38:32:30:66:5C:FF","sku":"H61C5","bleVersionHard":"3.01.10","bleVersionSoft":"3.03.26","wifiVersionHard":"1.04.01","wifiVersionSoft":"1.00.12","httpInfo":{"groupId":0,"device":"59:CD:38:32:30:66:5C:FF","sku":"H61C5","spec":"","versionHard":"3.01.10","versionSoft":"3.03.26","deviceName":"RGBIC Neon Rope Lights","deviceExt":{"deviceSettings":"{\"wifiName\":\"( . )( . )?\",\"address\":\"CD:38:32:30:66:5C\",\"bleName\":\"Govee_H61C5_665C\",\"topic\":\"GD/9ade071adab0282385547e507b59b1a8\",\"wifiMac\":\"60:74:F4:24:41:3E\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.12\",\"wifiHardVersion\":\"1.04.01\",\"ic\":70,\"secretCode\":\"O7HNODIwZlw=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"supportBleBroadV3\":false,\"sku\":\"H61C5\",\"device\":\"59:CD:38:32:30:66:5C:FF\",\"deviceName\":\"RGBIC Neon Rope Lights\",\"versionHard\":\"3.01.10\",\"versionSoft\":\"3.03.26\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/f96c50e4f99613143967b8925ff8cf49-add_list_type_device_61c5.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/b57553350ecda1670fc890f11e0b578e-h61c5_light_title_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/2fdc3c15c1820d5c37cb5a6588bff4a7-h61c5_light_title_off.png\",\"ext\":\"\",\"ic\":70}"},"pactType":1,"pactCode":1,"share":0,"goodsType":141},"model":"H61C5","deviceName":"RGBIC Neon Rope Lights","isLANDevice":true}

**Comment by bwp91** [comment]
Hi @DerElefant69 

Please try the beta version of the plugin

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by DerElefant69** [comment]
Works perfectly. Thank you very much 👍
