### ISSUE TITLE
INSTALLATION OF PLUGIN FAILED

### ISSUE THREAD

**Issue by djfunkysara** [bwp91/homebridge-govee#61]
Hi I have tried to search plugin for GOVEE but it always fails. May I know is there anyway I can install for HOOBS?

**Comment by djfunkysara** [comment]
I mean I can't install the home bridge-govee plugin ... Hoobs keep saying failed

**Comment by bwp91** [comment]
Hi, which version of hoobs are you running?

**Comment by djfunkysara** [comment]
Hi hoobs version 3.3.5

**Comment by bwp91** [comment]
When you say "Hoobs keep saying failed" could you get the exact messages?

Where does this error display? In the logs?

**Comment by djfunkysara** [comment]
![image](https://user-images.githubusercontent.com/67842146/113679802-bfdb3b80-96f2-11eb-8447-527731654c75.jpeg)

**Comment by bwp91** [comment]
Which version of nodejs and npm are you running?

You can check via the hoobs terminal with these commands:

```
node -v
```

and

```
npm -v
```

**Comment by djfunkysara** [comment]
![image](https://user-images.githubusercontent.com/67842146/113683596-f7e47d80-96f6-11eb-9f05-b2a6c250180d.jpeg)

**Comment by bwp91** [comment]
Your version of npm is not at a recommended version... I would advise to downgrade it to 6.14.11. It might sort out the issue you are having with installing the govee plugin.

I am, however, not sure of a/the recommended way of downgrading the version of npm when running hoobs :/

**Comment by bwp91** [comment]
Scrap that, could I message you on my discord channel?
https://discord.gg/cMGhNtZ3tW

**Comment by djfunkysara** [comment]
It worked suddenly.... after trying updating which failed npm with error. So now I can use the on and off function on HomeKit

**Comment by bwp91** [comment]
Ah i'm glad you got it working!
Are you happy for this issue to be closed?

**Comment by djfunkysara** [comment]
Yes can close thanks
