### ISSUE TITLE
Govee Christmas Light Strand

### ISSUE THREAD

**Issue by Mattmaker95** [bwp91/homebridge-govee#610]
* **Which model is this? Need the `Hxxxx` number.**
H70C1

* **Which type of device is this? Light, heater, leak sensor, etc.**
Light, 33ft Christmas light strand

* **Which connection methods does this device have? Wifi? Bluetooth? Both?**
Wifi and Bluetooth

* **Anything else?**

I so appreciate the time and effort put into this plugin.  I am hopeful that I can get this light strand and effects into Homekit.  If it is possible I will definitely use it all the time and sponsor you!  Thanks!

**Comment by bwp91** [comment]
Hi @Mattmaker95 

Please try the beta version of the plugin

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by ssmoss** [comment]
There is a second longer version of this device with the model number H70C2

**Comment by Mattmaker95** [comment]
Yes that worked! Appreciate man.Thanks,
Matt Hatmaker
C: (714) 267-5431On Oct 12, 2023, at 8:12 PM, ssmoss ***@***.***> wrote:There is a second longer version of this device with the model number H70C2—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ssmoss** [comment]
FYI H70C2 was fixed with the version [10](https://github.com/bwp91/homebridge-govee/releases/tag/v10.0.0) release.
