### ISSUE TITLE
Enable Temp Reporting - Heater

### ISSUE THREAD

**Issue by OttoVonSkidmark** [bwp91/homebridge-govee#611]
I have a persistent warning on my logs : "10/12/2023, 9:12:04 AMGovee BridgeGoveeWARNING[Office Space Heater] you should enable `tempReporting` in the config for this device."

I am not sure where to enable this feature (I have temp reporting enabled in the Govee app - not sure where else to update this.

I am running v 9.4.2 on Hoobs

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by stwrz** [comment]
Same for me, too.
