### ISSUE TITLE
H70C2 String Light Not Supported

### ISSUE THREAD

**Issue by Banjo85** [bwp91/homebridge-govee#614]
* **Which model is this? Need the `Hxxxx` number.**
H70C2

* **Which type of device is this? Light, heater, leak sensor, etc.**
Light

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**

WIFI and BLE Yes, LAN unknown

* **Anything else?**
[String Light] is not currently supported, do create a Github issue with the following info:
{"device":"3C:18:E4:65:3D:80:80:52","deviceName":"String Light","model":"H70C2","httpInfo":{"groupId":0,"device":"3C:18:E4:65:3D:80:80:52","sku":"H70C2","spec":"","versionHard":"3.04.01","versionSoft":"1.00.07","deviceName":"String Light","deviceExt":{"deviceSettings":"{\"wifiName\":\"Loki\",\"address\":\"E4:65:3D:80:80:52\",\"bleName\":\"Govee_H70C2_8052\",\"topic\":\"GD/da140a1aaf079e411fe47f6b06853d43\",\"wifiMac\":\"60:74:F4:4F:DD:1C\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"2.05.08\",\"wifiHardVersion\":\"1.02.00\",\"ic\":200,\"secretCode\":\"d9LkZT2AgFI=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"dspVersionSoft\":13,\"sku\":\"H70C2\",\"device\":\"3C:18:E4:65:3D:80:80:52\",\"deviceName\":\"String Light\",\"versionHard\":\"3.04.01\",\"versionSoft\":\"1.00.07\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/d2c8daf6b9b07e2d610fd6a0884dca5d-add_list_type_device_70c2.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/865f75dd8518a240d3e68d8d904c7a85-h70c1_light_title_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/2c9b63bdb64f2422700e610ea17c5e29-h70c1_light_title_off.png\",\"ext\":\"\",\"ic\":200}"},"pactType":1,"pactCode":1,"share":0,"goodsType":181,"attributesId":71}}

**Comment by ssmoss** [comment]
I think this was fixed with the version [10](https://github.com/bwp91/homebridge-govee/releases/tag/v10.0.0) release.
