### ISSUE TITLE
H7130 Heater - thermostat device doesn't load and brief 'no response' message

### ISSUE THREAD

**Issue by tmur11** [bwp91/homebridge-govee#615]
Setup H7130 heater few days ago worked perfect. Now thermostat device doesn't load seems to display brief 'no response' after close device details where thermostat dial graphic is normally displayed.

Homebridge Docker Ubuntu
Homebridge v1.6.1

![Screenshot 2023-10-18 at 6 46 00 PM](https://github.com/bwp91/homebridge-govee/assets/21132832/01238f2c-03c1-484d-a2a1-d20048954b42)
![Screenshot 2023-10-18 at 6 45 57 PM](https://github.com/bwp91/homebridge-govee/assets/21132832/371ba6ef-0b66-49a1-bdf9-6272e223adcd)

**Comment by ramza007** [comment]
Same issue, i just updated to ios17.1 from ios16 and the dial was present before the upgrade, same thing on my ipad. Weirdly my watch displays the auto, heat, off toggles. Tried restarting phone, updating and restarting my HB server and the govee plugin still doesn't work

**Comment by tmur11** [comment]
I wonder if its iOS 17 related although when I installed and configured the Goove HB plugin I was already running iOS17 and it worked for about 24hrs. Talking to my other half she indicated she might have changed the display mode or something like from Fan display to Heater display within ios Home app but I couldn't find any settings to change back. Just like some smart plugs can be shown as lights or switches depending on what you select for device settings within homekit.

**Comment by omawhite** [comment]
I saw your comment in the issue I made. The other day I made an interesting discovery, this bug doesn't show up on my Mac running MacOS Ventura 13.6. So it might add credence to your idea that it's an iOS 17 problem, or at least an iOS issue. FWIW i didn't change any settings in home to display the heater as a fan or anything else, so I can't confirm or deny that has anything to do with it.

**Comment by BlueThunder93** [comment]
> Same issue, i just updated to ios17.1 from ios16 and the dial was present before the upgrade, same thing on my ipad. Weirdly my watch displays the auto, heat, off toggles. Tried restarting phone, updating and restarting my HB server and the govee plugin still doesn't work

Having this exact same issue with my Govee Heater (H7130).  I have no Thermostat option on the card and cannot turn the unit on/off from within IOS 17.1 or Sonoma 14.  I went to my Apple Watch and was able to go from Auto to Heat and then the Thermostat slider showed up on both the Mac and iPhone Home apps and let me control everything.  Even when I couldn't toggle the heater on/off from the Phone or Mac it would still show the proper status of the heater when I toggled it on/off from within the Govee app.  Hope this can be easily addressed and fixed as this is an awesome integration to have within Homekit - thank you for all the time/work/effort you have put into this plugin!

**Comment by tmur11** [comment]
Can confirm using macOS 13 (Ventura) was able to restore thermostat dial (and use of the device again via homekit) once I disabled "auto". I believe as others have mentioned using the Govee app and disabling the "thermostat mode" also fixes this issue. I tried the govee "auto stop" setting as well but this is toggled off my homekit when switching between off and heat modes on the thermostat dial.

Really would like to use the thermostat feature in homekit though.

**Comment by skydivedan** [comment]
This sounds like an iOS 17 / Mac Sonoma issue... does that mean that this can't get fixed? I've used this plugin for my heater for over a year, and it's worked great. It would be a shame if I need to use the Govee app again, instead of just using this through HomeKit/HomeBridge.

**Comment by quasistoic** [comment]
As a workaround for those experiencing this problem: if you go into the Govee app and turn off "thermostat mode" for the device in question, it should start correctly displaying thermostat controls in HomeKit. Unintuitive, but this is how I was able to regain control of the heater through HomeKit.

**Comment by skydivedan** [comment]
> As a workaround for those experiencing this problem: if you go into the Govee app and turn off "thermostat mode" for the device in question, it should start correctly displaying thermostat controls in HomeKit. Unintuitive, but this is how I was able to regain control of the heater through HomeKit.

Wow! Just tried this, and can confirm that this works! Thanks for this.

**Comment by skydivedan** [comment]
@quasistoic - followup. This solution _kinda_ works. I spoke a little too soon on this. 
Here's what happened... I followed your advice, and then I was able to see the heater as I wanted, with a thermostat dial, and the ability to turn to "off" "auto" or "heater" mode (not sure on the third choice there). I did this by turning off "thermostat mode" in the Govee app. 
But then at some time later, it stopped working again. And when I looked at the Govee app, I could see that "thermostat mode" was ON again. So, I turned it off again, and then it worked again... until it didn't. Again, somehow over time it got reset to having "thermostat mode" turned back on.

I don't have any empirical data to explain _why_ this happened, or how long until it flipped back. But that's what happens.

**Comment by BlueThunder93** [comment]
> @quasistoic - followup. This solution _kinda_ works. I spoke a little too soon on this. 
> 
> Here's what happened... I followed your advice, and then I was able to see the heater as I wanted, with a thermostat dial, and the ability to turn to "off" "auto" or "heater" mode (not sure on the third choice there). I did this by turning off "thermostat mode" in the Govee app. 
> 
> But then at some time later, it stopped working again. And when I looked at the Govee app, I could see that "thermostat mode" was ON again. So, I turned it off again, and then it worked again... until it didn't. Again, somehow over time it got reset to having "thermostat mode" turned back on.
> 
> 
> 
> I don't have any empirical data to explain _why_ this happened, or how long until it flipped back. But that's what happens. 

I am seeing something very similar with this - where Thermostat mode reenables itself over time.  However, it has become less frequent on this occurrence happening.  Still holding out hope for some permanent fix to the issue overall.  Thanks to everyone that supports this plugin!

**Comment by drosenberg-gh** [comment]
Would it be possible to open this issue as I'm experiencing the exact same problem and I just installed the latest version of the plugin

**Comment by quasistoic** [comment]
> @quasistoic - followup. This solution _kinda_ works. I spoke a little too soon on this. Here's what happened... I followed your advice, and then I was able to see the heater as I wanted, with a thermostat dial, and the ability to turn to "off" "auto" or "heater" mode (not sure on the third choice there). I did this by turning off "thermostat mode" in the Govee app. But then at some time later, it stopped working again. And when I looked at the Govee app, I could see that "thermostat mode" was ON again. So, I turned it off again, and then it worked again... until it didn't. Again, somehow over time it got reset to having "thermostat mode" turned back on.
> 
> I don't have any empirical data to explain _why_ this happened, or how long until it flipped back. But that's what happens.

Apologies, I wasn't paying attention to this thread. In January, I also found times when my Govee heater would switch back into "thermostat mode" and disable the Homekit controls - this seemed to most often happen when I had accidentally fat-fingered the Homekit UI and moved the device from "Off" to "Auto" rather than "Heat". When this happened, the heater would cease to be controllable as a thermostat in HomeKit until I went into the Govee app and turned Thermostat Mode off again.

In late Jan/Feb, I switched from using HomeBridge to using HomeAssistant for smart home integration (and passing along relevant entities to HomeKit for Siri control) and all of this has ceased to be an issue for me. My switch to HA was for unrelated reasons, but as a side benefit, this issue became irrelevant.

**Comment by omawhite** [comment]
@quasistoic I was wondering if home assistant might fix work better with the govee stuff, but I wasn't if or how well home assistant hooked in with homekit. Good to know, thanks for the info.
