### ISSUE TITLE
H70C2 not supported 

### ISSUE THREAD

**Issue by Tony8444** [bwp91/homebridge-govee#617]
* **Which model is this? Need the `Hxxxx` number.**

H70C2

* **Which type of device is this? Light, heater, leak sensor, etc.**

Light

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**
wifi bluetooth 

* **Anything else?**

**Comment by ssmoss** [comment]
I think this was fixed with the version [10](https://github.com/bwp91/homebridge-govee/releases/tag/v10.0.0) release.

**Comment by Tony8444** [comment]
tried the beta...not at home right now so I can't see what version it is.

**Comment by ssmoss** [comment]
Version 10 came out today. I just updated and see it being added in the logs.

**Comment by Tony8444** [comment]
nice ill try it tonight...thank you
