### ISSUE TITLE
H7131 toggling heater to auto makes thermostat control disappear.

### ISSUE THREAD

**Issue by omawhite** [bwp91/homebridge-govee#618]
### What issue do you have? Please be as thorough and explicit as possible.
In the home app, the thermostat controls for my heater don't display, this seems to happen when the heater is in auto mode? Turning the fan on seems to switch the heater back to heat mode, which makes the thermostat controls reappear. 
![IMG_4428](https://github.com/bwp91/homebridge-govee/assets/10691377/53f03779-063b-4f68-9d01-83081b23c83c)
![IMG_4429](https://github.com/bwp91/homebridge-govee/assets/10691377/2a04e071-2211-43a8-a498-52bbbed0ce4d)

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
homebridge-config-ui-x v4.50.6

* Which version of Homebridge/HOOBS do you have?
homebridge 1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

home bridge is running on an ubuntu(22.10) container
node: 18.13.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v9.4.3-beta.13, I didn't use to have this issue, but I'm not sure which version introduced it. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
heater: H7131

### Please paste any relevant logs below.

```

```

**Comment by ramza007** [comment]
Have the same issue, where the temp dial disappears on auto. when I try tuning on just fan and turning off the heater with the spin wheel it crashes my home app

**Comment by tmur11** [comment]
I think this is related to my issue #615

**Comment by Sn0wT1g3R** [comment]
Same issues here
