### ISSUE TITLE
Support Request: H608A

### ISSUE THREAD

**Issue by spo86** [bwp91/homebridge-govee#623]
* **Which model is this? Need the `Hxxxx` number.**

H608A (RGBIC String Downlights 16.4 ft)

* **Which type of device is this? Light, heater, leak sensor, etc.**

Light

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**

All

* **Anything else?**

Thank you! :)

**Comment by tjridge** [comment]
Would like this integration as well. Let me know what info I can provide to help.
