### ISSUE TITLE
Issues with brightness not matching on update

### ISSUE THREAD

**Issue by AlphaDog01** [bwp91/homebridge-govee#630]
### What issue do you have? Please be as thorough and explicit as possible.

After updating home ridge to newest gui and node.js to 20.9.0 my h6003 lights all now have messed up light settings
Brightness is now 39% = actual 100% per light and 100% is 39% actual. All other variable percentages seem normal.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge up-x 4.52.1

* Which version of Homebridge/HOOBS do you have?

1.7.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Docker container on a Ubuntu virtual machine.

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

10.0.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

All my h6003 lights my newest h6009 work fine

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @AlphaDog01 

Please see this:
- https://github.com/bwp91/homebridge-govee/wiki/Common-Errors#brightness-issues

**Comment by AlphaDog01** [comment]
Thank you so much not sure how I couldn't find that but that cleared this issue up thanks again
