### ISSUE TITLE
[Govee] [Heater] you should enable `tempReporting` in the config for this device.

### ISSUE THREAD

**Issue by Mightyred81** [bwp91/homebridge-govee#631]
### What issue do you have? Please be as thorough and explicit as possible.

Hi, I did try joining the hombebridge page to post a question but it says link invalid. My issue is Ive installed a Heater in the Govee plugin and now get the following error:

[Govee] [Heater] you should enable `tempReporting` in the config for this device.

In HomeKit the Heater can now be switched on and off only but the temperature reading is not available

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Ive added the following code but it appears this is invalid?

                    "tempReporting": "True"

* Which version of Homebridge/HOOBS do you have?

V1.7.0 (Homebridge)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Ubuntu Focal Fossa (20.04.5 LTS)
Node.js Version | v20.9.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

v10.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

Govee H713A
Firmware 1.00.10
Hardware Version 1.02.01

### Please paste any relevant logs below.

```

```

**Comment by troypressley** [comment]
I have Govee Smart Heater and have same issue.

Latest Firmware and Latest Homebridge and plugin

[11/15/2023, 12:43:50 PM] [Govee] [Govee Smart Heater] you should enable `tempReporting` in the config for this device.


CONFIG:
{
    "bridge": {
        "name": "Homebridge 7C88",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51258,
        "pin": "XXX-XXX-XXX",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "refreshToken": "eyJydCI6ImV5SmhiR2NpT2lKU1V6STFOaUlzSW1wcmRTSTZJaTl2WVhWMGFDOXBiblJsY201aGJDOXFkMnR6SWl3aWEybGtJam9pTkdSak9EUXlaR0lpTENKMGVYQWlPaUpLVjFRaWZRLmV5SnBZWFFpT2pFM01EQXdOek00TWpjc0ltbHpjeUk2SWxKcGJtZFBZWFYwYUZObGNuWnBZMlV0Y0hKdlpEcDFjeTFsWVhOMExURTZZVGc1T0daa1pEa2lMQ0p5WldaeVpYTm9YMk5wWkNJNkluSnBibWRmYjJabWFXTnBZV3hmWVc1a2NtOXBaQ0lzSW5KbFpuSmxjMmhmYzJOdmNHVnpJanBiSW1Oc2FXVnVkQ0pkTENKeVpXWnlaWE5vWDNWelpYSmZhV1FpT2pFeU9UYzROelV4TENKeWJtUWlPaUptVEZKV1ExbDFlRE14SWl3aWMyVnpjMmx2Ymw5cFpDSTZJalprWkRGallUVmlMVGN4T1dFdE5HRXpNQzFpWkRVMUxUY3hZMkpoT0RrNVpqWTJZaUlzSW5SNWNHVWlPaUp5WldaeVpYTm9MWFJ2YTJWdUluMC5RRGJkRVNwckc1ZWQ4Nm5kdFZiS2NybkZ1NkpWSElld05ucXRFQTBWNG5qWlNJNU9iNXA4dHRqOFNKZEV6ZXZmN3l3aklpYVViUm1LOHlLNnpudGJ5TXVkZVBDNndfT0hnV0w5M0JlUzJ3eXQtTzRmTFBld0VNY1g1WTNuc0psMThiVUlXdWlMNUtNRnZvcExrbnBHeFJiV2pxd2FTbkFVbnF6RkhkV0xTaHB4cTJXUkllT0FVZE9WZVVzOEJaVlY0dHdva0pzN0xXVWNuTGpjdTFJWEhPSEotX0tLSEJUUUVrMDM3b0xFWGo3SVdCeUJsaVZBQVlpZHMzczVmeVhoZlVWRHlienhPcUdBRUR2NTVfb2QzWUxPWEdCX1Z0TkNrcGEtRm1IY1E4WnU2NEtva1JyUWE3SThDTVFHSG9hVlBVZ3hvTWtReV82djc4Y0Z6eGw1elEiLCJoaWQiOiIzOTk1Y2Q0MS0wZTczLTUwYTMtODYwZi1hM2NhZTg3NzZlOTEiLCJwbmMiOnsiZ2NtIjp7InRva2VuIjoiZEdWbGRuWEhlNWM6QVBBOTFiSFA2bXQyQjhGU3o1dVlCRTgzZWUza3ZsMDFNdlZfTHl0UWthWUMtdFV2eTRVeF9BVVhlZG9FR3c0QVczbnphLUdwX01Tc0ZiUnBWNVdTWkRQTnNvb2hQaFRYaHA3LTNGeUpuemRuT3JqTnZxQ3VKOFFQdGdrMU5xV1pjUUZLV2wwVVhjNXoiLCJhbmRyb2lkSWQiOiI0OTc0NTg4NDQ5MDUzNTg4NjM5Iiwic2VjdXJpdHlUb2tlbiI6IjUwMjIyNDc3NDk1OTM5MTkwOSIsImFwcElkIjoid3A6cmVjZWl2ZXIucHVzaC5jb20jMjljZmQ5ODYtNzhlZC00Y2ViLTk3ZGUtMjMxMDAxNDZiZDgwIn0sImtleXMiOnsicHJpdmF0ZUtleSI6InJiZmtsOWxvWmJ0U3ZUU01sbXN6RXJEc2NpaFlJUm43RktMbF9XUjVXVEkiLCJwdWJsaWNLZXkiOiJCRnh5ZnI3T21rSjh0d0RGMEM2SWVxZmtZY3BMdERvZkhvem9rYThVTm41Wkw5UVRMb3l3MGdaV2VQZi1jUVlKaEV1MEtxZEZqS3JZWFlacmd0R29sV00iLCJhdXRoU2VjcmV0Ijoickl0dGI2RFhaWDhnWks5YWtQUGlFUSJ9LCJmY20iOnsidG9rZW4iOiJlZ01LVFRpVjlCODpBUEE5MWJFczZxZkcwVkZaalFQZHNmNF9mNkowT05MbTBDRzNBRV8xVUZRXzQ5M1FUcFltNzZySnlKTVJzX041TmtJd2lkcy1JYmpIaVdWVTNPaVhfQVFBWEJRNUFjSVlicEROSHNzYzJiWWZPSUIwNm1OWDJhY080Yy1VYUxOUEgzcmtHb0thc3gybiIsInB1c2hTZXQiOiJlMURMTi1LY1NSZzpBUEE5MWJIaERaeHlHeEFXQlVOZnc2XzB3ZHdZeE9VQzhiYko1bTFnZE9mVkVzc3BoMXBPMHVReUxDQ2VjLXB3UnRaMG9nYjc3Vk9DY2RYbDdrN1lra3FOVHVnWkpZVHllaFJtY0lkN2FleU5uQlZOakZZSUxqNWxNOGRIZUxZd2tOR1gxSUNEYkVleiJ9fX0=",
            "unbridgeCameras": false,
            "platform": "Ring"
        },
        {
            "name": "Govee",
            "username": "Username",
            "password": "Password",
            "bleDisable": true,
            "heaterDevices": [
                {
                    "label": "Govee Smart Heater",
                    "deviceId": "XX:XX:XX:XX:XX:XX",
                    "tempReporting": "true"
                }
            ],
            "platform": "Govee"
        }
    ]
}

**Comment by eBarazi** [comment]
Hi, 
I Have Govee smart heater H713A, and have the same problem:

"[Govee] [Samrt Heater] you should enable 'tempReporting' in the config for this device."

It is enabled in HB config:
        {
            "name": "Govee",
            "username": "Username",
            "password": "Password",
            "bleDisable": false,
            "heaterDevices": [
                {
                    "label": "H713A",
                    "deviceId": "xxxxxxxxxxxxxxxx",
                    "tempReporting": true
                }
            ],
            "platform": "Govee"
        }
    ]
}

Homebridge version: 1.7.0
Platform: Linux Debian 12
Node.js version:  20.9.0
Goove plugin version: 10.0.0 

Device:
Govee H713A
Firmware: 1.00.10
Hardware Version: 1.02.01

Any idea, please?

**Comment by bwp91** [comment]
Hi @Mightyred81 @troypressley @eBarazi 

It is best to use the Homebridge UI to configure the plugin. Please check the device ID @troypressley it looks like in your case the device id is not the 23 characters it is meant to be.

**Comment by smclean117** [comment]
Hi I am having a similar issue,

mine differs slightly in that when I change the config using the correct ID and enable temp reporting on Homebridge UI config it then correctly shows temp on HomeKit but does not respond to any commands, on/off does not do anything.

turning off temp reporting then allows the device to function correctly again.

**Comment by phillwall72** [comment]
doesn't appear in my interface 
<img width="746" alt="Screenshot 2023-12-25 at 17 12 56" src="https://github.com/bwp91/homebridge-govee/assets/79764865/f4fe616f-70e0-4fb5-84fb-18f630e3e26d">

**Comment by calsonicgtr** [comment]
Has anyone found a solution to this? Does not prevent anything from working but would like to know how to correct.

**Comment by jmjamesjr** [comment]
this worked for me

{
   "name": "Govee",
   "username": "",
   "password": "",
   "debug": false,
   "heaterDevices": [
     {
       "label": "My Heater (this can be anything)",
       "deviceId": "11:22:33:44:55:66:77:88",
       "tempReporting": true
      }
   ],
   "platform": "Govee"
}
