### ISSUE TITLE
H7133 Heater

### ISSUE THREAD

**Issue by iceonu2** [bwp91/homebridge-govee#637]
* **Please explain your feature request in a one or two sentences.**

Support for Govee Heater model H7133

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

* **Anything else?**

**Comment by iceonu2** [comment]
[Space Heater Pro] is not currently supported, do create a Github issue with the following info:
{"device":"C5:2C:60:74:F4:41:EA:A0","deviceName":"Space Heater Pro","model":"H7133","httpInfo":{"groupId":0,"device":"C5:2C:60:74:F4:41:EA:A0","sku":"H7133","spec":"","versionHard":"1.02.00","versionSoft":"1.00.20","deviceName":"Space Heater Pro","deviceExt":{"deviceSettings":"{\"wifiName\":\xxxxxxx\",\"address\":\"11:22:33:44:55:66\",\"bleName\":\"GVH7133EAA1\",\"topic\":\"GD/c18c6fe8014d6e4ce1363924ee87801c\",\"wifiMac\":\"xx:xx:xx:xx:xx:xx\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.20\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"bRS3O7lTQx0=\",\"dumpOnOff\":1,\"mcuSoftVersion\":\"1.00.13\\u0000\",\"mcuHardVersion\":\"1.00.12\\u0000\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":0,\"sku\":\"H7133\",\"device\":\"C5:2C:60:74:F4:41:EA:A0\",\"deviceName\":\"Space Heater Pro\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.20\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/2eb9ff0b5a4d5b17a85d725f54442b1c-add_list_type_device_7133.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"goodsType":174,"attributesId":68,"supportScene":0}}

**Comment by occammd** [comment]
I installed the beta on home bridge. H7133 works for me now!

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions
