### ISSUE TITLE
New TV Backlight 3 Lite 

### ISSUE THREAD

**Issue by DJMMC** [bwp91/homebridge-govee#644]
* **Which model is this? Need the `Hxxxx` number.**
H6099

https://eu.govee.com/collections/tv-gaming-lights/products/govee-tv-backlight-3-lite

* **Which type of device is this? Light, heater, leak sensor, etc.**
TV Backlight Lightstrip

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**
Wifi, Bluetooth

* **Anything else?**

[RGBIC TV Backlight 3 Lite] is not currently supported, do create a Github issue with the following info:
{"device":"18:54:D9:38:32:34:3D:17","deviceName":"RGBIC TV Backlight 3 Lite","model":"H6099","httpInfo":{"groupId":0,"device":"18:54:D9:38:32:34:3D:17","sku":"H6099","spec":"","versionHard":"3.05.01","versionSoft":"1.00.05","deviceName":"RGBIC TV Backlight 3 Lite","deviceExt":{"deviceSettings":"{\"wifiName\":\"MYWIFI\",\"address\":\"D9:38:32:34:3D:17\",\"bleName\":\"Govee_H6099_3D17\",\"topic\":\"GD/c5593a1e476795e2064cb65cf29f36bd\",\"wifiMac\":\"D4:AD:FC:B4:67:94\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.10\",\"wifiHardVersion\":\"1.06.00\",\"ic\":36,\"secretCode\":\"gZTZODI0PRc=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6099\",\"device\":\"18:54:D9:38:32:34:3D:17\",\"deviceName\":\"RGBIC TV Backlight 3 Lite\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"1.00.05\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/784ef9170ab66ccdaf137d29963f5476-add_list_type_device_6099.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/42d0585f82d3c6c93b50534f9e9b3804-new_light_title_h6104_alexa_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5098709790bf157447ed1f8e0b65c2ad-new_light_title_6104_alexa_off.png\",\"ext\":\"\",\"ic\":50}"},"pactType":1,"pactCode":1,"share":0,"goodsType":191,"attributesId":1,"supportScene":1}}

**Comment by Semir333** [comment]
+1 for this

[RGBIC TV Backlight 3 Lite] is not currently supported, do create a Github issue with the following info:
{"device":"1E:80:CC:38:32:34:55:73","deviceName":"RGBIC TV Backlight 3 Lite","model":"H6099","httpInfo":{"groupId":8635317,"device":"1E:80:CC:38:32:34:55:73","sku":"H6099","spec":"","versionHard":"3.05.01","versionSoft":"1.00.05","deviceName":"RGBIC TV Backlight 3 Lite","deviceExt":{"deviceSettings":"{\"wifiName\":\"DIGI-PDE-N\",\"address\":\"CC:38:32:34:55:73\",\"bleName\":\"Govee_H6099_5573\",\"topic\":\"GD/feb9b2df499195ed517106561ba92259\",\"wifiMac\":\"D4:AD:FC:B4:6B:94\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.07\",\"wifiHardVersion\":\"1.06.00\",\"ic\":36,\"secretCode\":\"96XMODI0VXM=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6099\",\"device\":\"1E:80:CC:38:32:34:55:73\",\"deviceName\":\"RGBIC TV Backlight 3 Lite\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"1.00.05\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/784ef9170ab66ccdaf137d29963f5476-add_list_type_device_6099.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/42d0585f82d3c6c93b50534f9e9b3804-new_light_title_h6104_alexa_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5098709790bf157447ed1f8e0b65c2ad-new_light_title_6104_alexa_off.png\",\"ext\":\"\",\"ic\":50}"},"pactType":1,"pactCode":1,"share":0,"goodsType":191,"attributesId":1,"supportScene":1}}
