### ISSUE TITLE
segment control?

### ISSUE THREAD

**Issue by grizzalorian** [bwp91/homebridge-govee#645]
* **Please explain your feature request in a one or two sentences.**

wondering if it would be possible to add segment control for the RGBIC devices. Love that option in the Govee app. but within HomeKit it if you touch any of the color options it just lights up the device as that one color etc.

* **Is your feature request related to a problem? Please describe.**

* **Any particular Govee devices that this relates to?**

H702C, H6076, H6046

* **Anything else?**

**Comment by bwp91** [comment]
hi @grizzalorian 
you’re not the only one to have requested this!
the issue is that the home app does not have any way of showing some interface for setting different parts of a light strip to different colours

**Comment by grizzalorian** [comment]
ah fair enough.  I saw another plugin (Govee ultimate) but I could never get it to work. (yours works flawlessly) 
Guess I'll continue to use the Govee app to set those for now.

**Comment by bwp91** [comment]
https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

Could be useful for using the home app to turn into scenes that you have **already** made in the govee app?

Appreciate it's not quite what this issue was aimed at, but perhaps some kind of alternative?

**Comment by hanakin** [comment]
what about splitting each segment up into individual home lights? it could be used to at least add some more control? for example, I have the govee desk light strip and have each side of my desk a different color based on the color of light on that slide for better ambiance. It would be handy to be able to do this in homekit if each segment could be set as its own light? I know it's tedious, but the best thing is we have given homekits limitations.
