### ISSUE TITLE
Add support for Permanent Lights Pro [H706C]

### ISSUE THREAD

**Issue by pctony** [bwp91/homebridge-govee#648]
* **Which model is this? Need the `Hxxxx` number.**

H706C

* **Which type of device is this? Light, heater, leak sensor, etc.**

Light - permanent outdoor

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**

WiFi. BLE. LAN. 

* **Anything else?**

A copy of the output from HomeBridge 

{"ip":"192.168.198.140","device":"1E:D2:FD:1E:17:A2:16:57","sku":"H706C","bleVersionHard":"3.04.01","bleVersionSoft":"1.00.14","wifiVersionHard":"1.04.01","wifiVersionSoft":"1.01.11","httpInfo":{"groupId":0,"device":"1E:D2:FD:1E:17:A2:16:57","sku":"H706C","spec":"","versionHard":"3.04.01","versionSoft":"1.00.14","deviceName":"Lower Pro String","deviceExt":{"deviceSettings":"{\"wifiName\":\"CB23\",\"address\":\"FD:1E:17:A2:16:57\",\"bleName\":\"Govee_H706C_1657\",\"topic\":\"GD/0c52436ad840108b0475c1024fbc5565\",\"wifiMac\":\"60:74:F4:8C:FC:A6\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.01.11\",\"wifiHardVersion\":\"1.04.01\",\"ic\":30,\"secretCode\":\"dMb9HheiFlc=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"dspVersionSoft\":\"13\",\"segmentCount\":24,\"sku\":\"H706C\",\"device\":\"1E:D2:FD:1E:17:A2:16:57\",\"deviceName\":\"Lower Pro String\",\"versionHard\":\"3.04.01\",\"versionSoft\":\"1.00.14\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/798230d5d5982ba58b8c796c523c3ecd-add_list_type_device_706c.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/dc58b1f4592275085d753a11342f7748-706c_light_title_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/2f2589a1d94d8d0c369c8d360384b859-706c_light_title_off.png\",\"ext\":\"\",\"ic\":120}"},"pactType":1,"pactCode":1,"share":0,"goodsType":180,"attributesId":49,"supportScene":0},"model":"H706C","deviceName":"Lower Pro String","isLANDevice":true}

**Comment by Route105** [comment]
Can you add support for the H706A too

[Front LED Lights] is not currently supported, do create a Github issue with the following info:
{"ip":"192.168.1.210","device":"36:99:F1:F1:A7:4B:D6:80","sku":"H706A","bleVersionHard":"3.04.01","bleVersionSoft":"1.00.14","wifiVersionHard":"1.04.01","wifiVersionSoft":"1.01.17","httpInfo":{"groupId":0,"device":"36:99:F1:F1:A7:4B:D6:80","sku":"H706A","spec":"","versionHard":"3.04.01","versionSoft":"1.00.14","deviceName":"Front LED Lights","deviceExt":{"deviceSettings":"{\"wifiName\":\"DMB #41 (2G)\",\"address\":\"F1:F1:A7:4B:D6:80\",\"bleName\":\"Govee_H706A_D680\",\"topic\":\"GD/8d0e8155b27869a8bb1c047b29c69a5b\",\"wifiMac\":\"60:74:F4:7D:72:CD\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.01.17\",\"wifiHardVersion\":\"1.04.01\",\"ic\":60,\"secretCode\":\"f2Hx8adL1oA=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"dspVersionSoft\":\"13\",\"segmentCount\":9,\"sku\":\"H706A\",\"device\":\"36:99:F1:F1:A7:4B:D6:80\",\"deviceName\":\"Front LED Lights\",\"versionHard\":\"3.04.01\",\"versionSoft\":\"1.00.14\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/110c816f749f75640260511c333a1065-add_list_type_device_706a.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/8e57eab8d1c8c6d9f280be7e4460b0d2-706a_light_title_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/a4e9d925c3c788fc25adde52e44349a8-706a_light_title_off.png\",\"ext\":\"\",\"ic\":120}"},"pactType":1,"pactCode":1,"share":0,"goodsType":180,"attributesId":49,"supportScene":0},"model":"H706A","deviceName":"Front LED Lights","isLANDevice":true}

**Comment by pctony** [comment]
Thank you for adding support in 10.2.0
