### ISSUE TITLE
Govee Smart Kettle H7173

### ISSUE THREAD

**Issue by adambomb1011** [bwp91/homebridge-govee#649]
* **Which model is this? Need the `Hxxxx` number.**
H7173

* **Which type of device is this? Light, heater, leak sensor, etc.**
Govee Smart Kettle

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**
All

* **Anything else?**
does not support this model

**Comment by seerocode** [comment]
Bumping this same request with additional details for the same model:

* skuUrl:"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7ee4ef2469e8bfec6401ff933f80f10b-add_list_type_device_7173.png
"versionHard":"1.02.00",
"versionSoft":"1.00.12"
mcuSoftVersion":"1.00.10
mcuHardVersion":"999.999
wifiSoftVersion":"1.00.12
bleName":"GVH71733863
"topic":"GD/46337d254a70c73e9633490ae34717e9

**Comment by tradel** [comment]
Full output from the plugin logs:

``` json
{
  "device": "21:65:60:74:F4:5E:5A:74",
  "deviceName": "Smart Kettle",
  "model": "H7173",
  "httpInfo": {
    "groupId": 0,
    "device": "21:65:60:74:F4:5E:5A:74",
    "sku": "H7173",
    "spec": "",
    "versionHard": "1.02.00",
    "versionSoft": "1.00.15",
    "deviceName": "Smart Kettle",
    "deviceExt": {
      "deviceSettings": "{\"wifiName\":\"2625VirginiaLane-PRO\",\"address\":\"60:74:F4:5E:5A:75\",\"bleName\":\"GVH71735A75\",\"topic\":\"GD/215761a2735a60fd5f0fef9e93eb090c\",\"wifiMac\":\"60:74:F4:5E:5A:74\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.15\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"PpAWL+oKEFY=\",\"boilWaterExceptionNotiOnOff\":1,\"mcuSoftVersion\":\"1.00.10\",\"mcuHardVersion\":\"1.00.01\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H7173\",\"device\":\"21:65:60:74:F4:5E:5A:74\",\"deviceName\":\"Smart Kettle\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.15\",\"playState\":false}",
      "lastDeviceData": "{\"online\":false}",
      "extResources": "{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7ee4ef2469e8bfec6401ff933f80f10b-add_list_type_device_7173.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"
    },
    "pactType": 1,
    "pactCode": 1,
    "share": 0,
    "goodsType": 177,
    "attributesId": 0,
    "supportScene": 0
  }
}
```

**Comment by bwp91** [comment]
Hi @adambomb1011 @seerocode @tradel 

Apologies this github issue completely slipped me.

Some support for this model should be available in the beta version of the plugin.

The commands are based off other kettle models, so Im not sure how well it will work at this point.

Let me know how it goes!

**Comment by Valdorama** [comment]
Can confirm that the H7173 kettle appears to be working. I installed this plugin yesterday (for use with Home Assistant) and the kettle was correctly discovered. You could probably add it to the supported devices list.

Thanks for your work on this plugin!
