### ISSUE TITLE
Please add Govee Glide Hexa Ultra (H606A) support

### ISSUE THREAD

**Issue by BadToxic** [bwp91/homebridge-govee#654]
* **Which model is this? Need the `Hxxxx` number.**
Govee Glide Hexa Ultra
sku: H606A
bleBane: Govee_H606A_8223

* **Which type of device is this? Light, heater, leak sensor, etc.**
3D cube **light** panels

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**
Bluetooth
Wifi

* **Anything else?**
dspVersionSoft:12
shapes: CgZABkAGAAAGGQb8BQAABkAGuAUAAAaPBkAGAAAGtwb8BQAABt4GuAUAAAa3BnMFAAAG3gYvBQAABi0HLwUAAAZVB+sEAAABAAAGARQgCAEAAggBCAEEIAgBEAIIAQA=
versionHard: 3.04.01
versionSoft: 1.00.15
skuUrl: https://d1f2504ijhdyjw.cloudfront.net/sku-img/5d84bf48453d3911792e756f3b7efd4b-add_list_type_device_606a.png

**Comment by BadToxic** [comment]
I updated to v10.4.0 and now the "Glide Hexa Ultra" got listed, but they can't be controlled. In the HomeBridge UI and in Apple Home it got an entry, but turning it on/off or changing the brightness doesn't do anything.
Also tried:
- Updating NodeJS to the newest.
- Uninstall & Reinstall the Govee Plugin.
- Restarting Homebridge several times.
(The console acts like everything is working.)

**Comment by KyDenZ** [comment]
I’m experiencing the same issue with the latest version 11.10.0.
No errors in the logs, I can clearly see:

```
[22/08/2025, 15:02:08] [Govee] [Glide Hexa Ultra] current state [off].
[22/08/2025, 15:02:09] [Govee] [Glide Hexa Ultra] current state [on].
```

But nothing happens, the light does not turn on
