### ISSUE TITLE
Support for H6099 - RGBIC TV Backlight 3 Lite

### ISSUE THREAD

**Issue by fauxchet** [bwp91/homebridge-govee#659]
* **Which model is this? Need the `Hxxxx` number.**
H6099

* **Which type of device is this? Light, heater, leak sensor, etc.**
TV Lights

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**
WiFi & Bluetooth

* **Anything else?**
I created this GitHub account just to submit this request! So far very impressed with homebridge. Thanks

**Comment by saschakue** [comment]
I've got this in my log:

[01/12/2023, 11:41:11] [Govee] [RGBIC TV Backlight 3 Lite] is not currently supported, do create a Github issue with the following info:
{"device":"1B:18:D9:38:32:34:54:17","deviceName":"RGBIC TV Backlight 3 Lite","model":"H6099","httpInfo":{"groupId":0,"device":"1B:18:D9:38:32:34:54:17","sku":"H6099","spec":"","versionHard":"3.05.01","versionSoft":"1.00.05","deviceName":"RGBIC TV Backlight 3 Lite","deviceExt":{"deviceSettings":"{\"wifiName\":\"Bikini Bottom 2\",\"address\":\"D9:38:32:34:54:17\",\"bleName\":\"Govee_H6099_5417\",\"topic\":\"GD/8dfa70881526de8fd686392fb10b188c\",\"wifiMac\":\"D4:AD:FC:B4:6C:2B\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.12\",\"wifiHardVersion\":\"1.06.00\",\"ic\":36,\"secretCode\":\"y5zZODI0VBc=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6099\",\"device\":\"1B:18:D9:38:32:34:54:17\",\"deviceName\":\"RGBIC TV Backlight 3 Lite\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"1.00.05\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/784ef9170ab66ccdaf137d29963f5476-add_list_type_device_6099.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/42d0585f82d3c6c93b50534f9e9b3804-new_light_title_h6104_alexa_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5098709790bf157447ed1f8e0b65c2ad-new_light_title_6104_alexa_off.png\",\"ext\":\"\",\"ic\":50}"},"pactType":1,"pactCode":1,"share":0,"goodsType":191,"attributesId":1,"supportScene":1}}

**Comment by Sylanorr** [comment]
Me too

[Govee TV] is not currently supported, do create a Github issue with the following info:
{"device":"7A:75:CD:39:32:35:76:47","deviceName":"Govee TV","model":"H6099","httpInfo":{"groupId":0,"device":"7A:75:CD:39:32:35:76:47","sku":"H6099","spec":"","versionHard":"3.05.01","versionSoft":"1.00.05","deviceName":"Govee TV","deviceExt":{"deviceSettings":"{\"wifiName\":\"NSFW\",\"address\":\"CD:39:32:35:76:47\",\"bleName\":\"Govee_H6099_7647\",\"topic\":\"GD/95f5e35bb72f5e07751301ac7bc32a7c\",\"wifiMac\":\"60:74:F4:8F:D7:EB\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.12\",\"wifiHardVersion\":\"1.06.00\",\"ic\":36,\"secretCode\":\"kJjNOTI1dkc=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6099\",\"device\":\"7A:75:CD:39:32:35:76:47\",\"deviceName\":\"Govee TV\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"1.00.05\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/784ef9170ab66ccdaf137d29963f5476-add_list_type_device_6099.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/42d0585f82d3c6c93b50534f9e9b3804-new_light_title_h6104_alexa_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5098709790bf157447ed1f8e0b65c2ad-new_light_title_6104_alexa_off.png\",\"ext\":\"\",\"ic\":50}"},"pactType":1,"pactCode":1,"share":0,"goodsType":191,"attributesId":1,"supportScene":1}}

**Comment by Robothaler** [comment]
It would be great to get a working plugin for my new Govee T3 Backlite:

{"device":"18:C3:CF:38:32:34:14:48","deviceName":"RGBIC TV Backlight 3 Lite","model":"H6099","httpInfo":{"groupId":0,"device":"18:C3:CF:38:32:34:14:48","sku":"H6099","spec":"","versionHard":"3.05.01","versionSoft":"1.00.05","deviceName":"RGBIC TV Backlight 3 Lite","deviceExt":{"deviceSettings":"{\"wifiName\":\"FRITZ!Box 7490\",\"address\":\"CF:38:32:34:14:48\",\"bleName\":\"Govee_H6099_1448\",\"topic\":\"GD/c95d709814fc6c3c28ed213021dfa3a7\",\"wifiMac\":\"D4:AD:FC:DF:A1:74\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.13\",\"wifiHardVersion\":\"1.06.00\",\"ic\":36,\"secretCode\":\"B4DPODI0FEg=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6099\",\"device\":\"18:C3:CF:38:32:34:14:48\",\"deviceName\":\"RGBIC TV Backlight 3 Lite\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"1.00.05\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/784ef9170ab66ccdaf137d29963f5476-add_list_type_device_6099.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/42d0585f82d3c6c93b50534f9e9b3804-new_light_title_h6104_alexa_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5098709790bf157447ed1f8e0b65c2ad-new_light_title_6104_alexa_off.png\",\"ext\":\"\",\"ic\":50}"},"pactType":1,"pactCode":1,"share":0,"goodsType":191,"attributesId":1,"supportScene":1}}

**Comment by Semir333** [comment]
+1 for plugin support! @bwp91 

[RGBIC TV Backlight 3 Lite] is not currently supported, do create a Github issue with the following info:
{"device":"1E:80:CC:38:32:34:55:73","deviceName":"RGBIC TV Backlight 3 Lite","model":"H6099","httpInfo":{"groupId":8635317,"device":"1E:80:CC:38:32:34:55:73","sku":"H6099","spec":"","versionHard":"3.05.01","versionSoft":"1.00.05","deviceName":"RGBIC TV Backlight 3 Lite","deviceExt":{"deviceSettings":"{\"wifiName\":\"DIGI-PDE-N\",\"address\":\"CC:38:32:34:55:73\",\"bleName\":\"Govee_H6099_5573\",\"topic\":\"GD/feb9b2df499195ed517106561ba92259\",\"wifiMac\":\"D4:AD:FC:B4:6B:94\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.13\",\"wifiHardVersion\":\"1.06.00\",\"ic\":36,\"secretCode\":\"96XMODI0VXM=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6099\",\"device\":\"1E:80:CC:38:32:34:55:73\",\"deviceName\":\"RGBIC TV Backlight 3 Lite\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"1.00.05\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/784ef9170ab66ccdaf137d29963f5476-add_list_type_device_6099.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/42d0585f82d3c6c93b50534f9e9b3804-new_light_title_h6104_alexa_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5098709790bf157447ed1f8e0b65c2ad-new_light_title_6104_alexa_off.png\",\"ext\":\"\",\"ic\":50}"},"pactType":1,"pactCode":1,"share":0,"goodsType":191,"attributesId":1,"supportScene":1}}

**Comment by carlosrfernandez** [comment]
Would really appreciate support for this light!

**Comment by siimdev** [comment]
Looking forward for the support as well, until Matter support is added by Govee.

**Comment by bwp91** [comment]
Hey guys, sorry for delay on this, please check the beta version of the plugin :)

**Comment by Semir333** [comment]
> Hey guys, sorry for delay on this, please check the beta version of the plugin :) @bwp91 

Thank you for your work!

I've setted up.
-Settings fine (AWS not tested)
-Homekit shown perfectly
-Colour mode/adaptive mode work perfectly.
-Turn on/off work perfectly.

*One note only, i notice a little bit of lag when change anything. Used with BLE.

**Comment by dkkrause** [comment]
Thank you! Beta is working well for me too, using AWS. Seems quite responsive.
