### ISSUE TITLE
H7133 Heater Turns on Randomly 🔥⚠️

### ISSUE THREAD

**Issue by danglez83** [bwp91/homebridge-govee#674]
### What issue do you have? Please be as thorough and explicit as possible.
Ever since adding the plugin, I have noticed that my H7133 Heater has been turning on randomly. I just disabled the plugin to verify that it is in fact the plugin, but since the issue occurred randomly, I will take some time to confirm. Obviously this is very dangerous, so I wanted to notify you as soon as possible in case there is something you noticed in the plugin code. I had one automation setup in homekit to turn the heater OFF if no one was home (just as a precaution in case someone forgot to turn off before leaving). No other automations setup in HK or Govee app.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1

* Which version of Homebridge/HOOBS do you have?
v1.7.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspbian GNU/Linux Bullseye (node v18.18.2)

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v10.2.0 - first version I have installed

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H7133 Heater 

### Please paste any relevant logs below.

[12/16/2023, 8:14:39 AM] [Govee] [Office Heater] current temperature [26°C].
[12/16/2023, 8:15:30 AM] [Govee] [Office Heater] current state [off].
[12/16/2023, 8:15:30 AM] [Govee] [Office Heater] current temperature [25°C].
[12/16/2023, 8:15:30 AM] [Govee] [Office Heater] current light [off].
[12/16/2023, 8:16:02 AM] [Govee] [Office Heater] current mode [fan-only].
[12/16/2023, 8:16:03 AM] [Govee] [Office Heater] current state [on].
[12/16/2023, 8:16:03 AM] [Govee] [Office Heater] current light [on].
[12/16/2023, 8:16:08 AM] [Govee] [Office Heater] current state [off].
[12/16/2023, 8:16:09 AM] [Govee] [Office Heater] current light [off].
[12/16/2023, 8:16:39 AM] [Govee] [Office Heater] current temperature [24°C].
```

```

**Comment by danglez83** [comment]
Since disabling the plugin, the heater has not turned on randomly, so it does in fact appear to be the plugin that is causing the issue. I would love to get this back into HomeKit, so hopefully this safety hazard can be addressed asap.

**Comment by bwp91** [comment]
Hi @danglez83 

the plugin is reactive to changes that are made to the device "by govee" i mean any automations that are made in the govee app.

but the plugin does not send commands to the device unless explicitly configured ie by

- controlling directly in homebridge/homekit
- as part of some homekit automation

So I wonder if for example some converse of this was occurring

>  I had one automation setup in homekit to turn the heater OFF if no one was home (just as a precaution in case someone forgot to turn off before leaving)

so that if homekit detected you _were_ home then it would try and turn it on.

Have you tried re-enabling the plugin, but deleting this automation?

Obviously I am interested in the result of this to make sure that nothing that I don't even know about is happening with the plugin!

Thanks

**Comment by danglez83** [comment]
Hey @bwp91 thanks for getting back to me. Good to know that the plugin does not send any commands unless configured to do so. 

> so that if homekit detected you were home then it would try and turn it on.

I would find this really strange behavior, BUT to be sure, I re-enabled the plugin and made sure that NO automations were set. I will keep an eye on it (and the logs) over the next couple of days.

Stay tuned!
