### ISSUE TITLE
HTTP not working - "Status Code 503 at settle"

### ISSUE THREAD

**Issue by mitul216** [bwp91/homebridge-govee#676]
### What issue do you have? Please be as thorough and explicit as possible.

I moved my HomeBridge installation from my PC to another PC. All of my plugins no longer show up except for one of my TV lightstrips. I get this error code on my log:

[12/16/2023, 2:55:18 PM] [Govee] [HTTP] disabling client as Request failed with status code 503 at settle (file:///C:/Users/mitul/AppData/Roaming/npm/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).
[12/16/2023, 2:55:18 PM] [Govee] [AWS] disabling client as requires HTTP client.
[12/16/2023, 2:55:18 PM] [Govee] [BLE] disabling client as Cannot find package '@abandonware/bluetooth-hci-socket' imported from C:\Users\mitul\AppData\Roaming\npm\node_modules\homebridge-govee\lib\platform.js at packageResolve (node:internal/modules/esm/resolve:844:9).

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have? *
Latest

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Windows 10 HOME

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v10.2.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
3 H7013 lights
1 H6110 strip light

### Please paste any relevant logs below.
[12/16/2023, 2:55:18 PM] [Govee] [HTTP] disabling client as Request failed with status code 503 at settle (file:///C:/Users/mitul/AppData/Roaming/npm/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).
[12/16/2023, 2:55:18 PM] [Govee] [AWS] disabling client as requires HTTP client.
[12/16/2023, 2:55:18 PM] [Govee] [BLE] disabling client as Cannot find package '@abandonware/bluetooth-hci-socket' imported from C:\Users\mitul\AppData\Roaming\npm\node_modules\homebridge-govee\lib\platform.js at packageResolve (node:internal/modules/esm/resolve:844:9).

**Comment by Vader20** [comment]
I got the same, I didnt make any changes either. 

`[Govee] [HTTP] disabling client as Request failed with status code 503 at settle (file:///C:/Users/mitul/AppData/Roaming/npm/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).`

**Comment by Vinanonymous** [comment]
Same

[HTTP] disabling client as Request failed with status code 503 at settle (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12)

I tried to reset everything but no luck. I lost my heater device ID in the process and can't figure out how to find it. Any tips?

**Comment by neoalarrode** [comment]
I have the same problem, in my case I have stopped seeing a DreamView T1 H6199 and three H6008 bulbs.

So it seems it's going to be a general problem of the devices that pass through AWS

**Comment by Teagan42** [comment]
This isn't related to the repo - I author the other govee plugin and getting the same issues.

**Comment by Teagan42** [comment]
> Same
> 
> [HTTP] disabling client as Request failed with status code 503 at settle (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12)
> 
> I tried to reset everything but no luck. I lost my heater device ID in the process and can't figure out how to find it. Any tips?

Check the configuration directory under `accessories/.cachedAccessories.ABC1234.bk` - you should be able to find the device ID listed under the accessory's context. It's a lot of JSON, you can use the application `jq` (JSON query) to search for it. A simple query to find all device id's is `cat .cachedAccessories.ABC123.bk | jq '.. | .deviceId?'` (there will need to scroll up as there will be a lot of null lines)

**Comment by Vinanonymous** [comment]
> > Same
> > [HTTP] disabling client as Request failed with status code 503 at settle (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12)
> > I tried to reset everything but no luck. I lost my heater device ID in the process and can't figure out how to find it. Any tips?
> 
> Check the configuration directory under `accessories/.cachedAccessories.ABC1234.bk` - you should be able to find the device ID listed under the accessory's context. It's a lot of JSON, you can use the application `jq` (JSON query) to search for it. A simple query to find all device id's is `cat .cachedAccessories.ABC123.bk | jq '.. | .deviceId?'` (there will need to scroll up as there will be a lot of null lines)

Hmm, pretend I know nothing about coding lol! I have no idea how to do that tbh. I also see you can add an Govee API Key, not sure if I can use that or not.

**Comment by neoalarrode** [comment]
> This isn't related to the repo - I author the other govee plugin and getting the same issues.

It may be that they have the AWS servers under maintenance since error code 503 means that the service is down or saturated.

**Comment by Teagan42** [comment]
> > > Same
> > > [HTTP] disabling client as Request failed with status code 503 at settle (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12)
> > > I tried to reset everything but no luck. I lost my heater device ID in the process and can't figure out how to find it. Any tips?
> > 
> > 
> > Check the configuration directory under `accessories/.cachedAccessories.ABC1234.bk` - you should be able to find the device ID listed under the accessory's context. It's a lot of JSON, you can use the application `jq` (JSON query) to search for it. A simple query to find all device id's is `cat .cachedAccessories.ABC123.bk | jq '.. | .deviceId?'` (there will need to scroll up as there will be a lot of null lines)
> 
> Hmm, pretend I know nothing about coding lol! I have no idea how to do that tbh. I also see you can add an Govee API Key, not sure if I can use that or not.

No coding required, simply locate the directory where the configuration lives - depending on how you run HomeBridge, that could be a few different places.

Based on your comment:
> [HTTP] disabling client as Request failed with status code 503 at settle (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12)

I would guess the configuration directory is under one of the following:
`/var/lib/homebridge`
`/usr/local/share`
`/home/homebridge`
`/etc/homebridge`
For MacOS:
https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#understanding-where-your-files-are-macos

Anyway, your configuration directory will have the following files/folders:
```
accessories/
- .cachedAccessories.ABCD1234.bk
- cachedAccessories.ABCD1234.json
auth.json
backups/
config.json
persist/
```

The files under `accessories` are most likely to have your Device ID - you can open them with whatever editor you are familar with. If you can't find it there, check the backups directory.

**Comment by neoalarrode** [comment]
It has already worked again.
