### ISSUE TITLE
H6143 Color is unable to be controlled

### ISSUE THREAD

**Issue by kv1296** [bwp91/homebridge-govee#68]
Hey there, love the plug-in, you do an amazing job of keeping it updated, just having an issue with a specific device that I could use your help with.

### What issue do you have? Please be as thorough and explicit as possible.
My H6143 light is not responding to commands properly. Brightness seems to be incorrectly reported in the app, 39% brightness seems to correspond with 100% brightness on the light. If I got to 40% or higher I get a "no response error" in the home app.

The log file then posts the following error:

> [4/18/2021, 10:06:46 PM] [Govee] [H6143_C51A] could not be updated as Request failed with status code 400 at createError (/usr/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).

Additionally, color settings are unable to be applied through the home app. Whenever the color is changed, the light just flashes and displays a white color at the proper brightness. The adaptive lighting feature also does not work, which I believe is due to this color changing problem.

The log file posts the following error in the color case (H6143 is the device that is erroring, "LED Strip" is my H6159 which is working appropriately):

> [4/18/2021, 10:17:59 PM] [Govee] [H6143_C51A] sending update {"name":"color","value":{"r":255,"g":0,"b":0}}.
[4/18/2021, 10:18:00 PM] [Govee] [H6143_C51A] current colour [rgb 255 0 0].
[4/18/2021, 10:18:05 PM] [Govee] [LED Strip] received update [{"online":"true","powerState":"off","brightness":36,"color":{"r":255,"b":14,"g":137}}].
[4/18/2021, 10:18:05 PM] [Govee] [H6143_C51A] ignoring update [{"online":true,"powerState":"on","brightness":100,"colorTemInKelvin":305,"colorTem":305}].

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Config-ui, running on Raspberry Pi 4

* Which version of Homebridge/HOOBS do you have?
1.3.4

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
3.1.2, I have not yet tried downgrading to a previous version.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6143 is the device that I am having issues with. My H6159 is responding appropriately.

### Please paste any relevant logs below.

For the color issue (H6143 is the device that is erroring, "LED Strip" is my H6159 which is working appropriately): 
[4/18/2021, 10:17:59 PM] [Govee] [H6143_C51A] sending update {"name":"color","value":{"r":255,"g":0,"b":0}}.
[4/18/2021, 10:18:00 PM] [Govee] [H6143_C51A] current colour [rgb 255 0 0].
[4/18/2021, 10:18:05 PM] [Govee] [LED Strip] received update [{"online":"true","powerState":"off","brightness":36,"color":{"r":255,"b":14,"g":137}}].
[4/18/2021, 10:18:05 PM] [Govee] [H6143_C51A] ignoring update [{"online":true,"powerState":"on","brightness":100,"colorTemInKelvin":305,"colorTem":305}].
[4/18/2021, 10:18:20 PM] [Govee] [H6143_C51A] ignoring update [{"online":true,"powerState":"on","brightness":100,"colorTemInKelvin":305,"colorTem":305}].
```

```
For the brightness issue:
[4/18/2021, 10:20:05 PM] [Govee] [H6143_C51A] current brightness [38%].
[4/18/2021, 10:20:05 PM] [Govee] [H6143_C51A] sending update {"name":"brightness","value":91}.
[4/18/2021, 10:20:05 PM] [Govee] [H6143_C51A] current brightness [36%].
[4/18/2021, 10:20:09 PM] [Govee] [H6143_C51A] sending update {"name":"brightness","value":97}.
[4/18/2021, 10:20:10 PM] [Govee] [H6143_C51A] current brightness [38%].
[4/18/2021, 10:20:10 PM] [Govee] [H6143_C51A] sending update {"name":"brightness","value":99}.
[4/18/2021, 10:20:10 PM] [Govee] [H6143_C51A] current brightness [39%].
**This is when I instruct the app to set brightness ~40%** [4/18/2021, 10:20:11 PM] [Govee] [H6143_C51A] sending update {"name":"brightness","value":102}.
[4/18/2021, 10:20:11 PM] [Govee] [H6143_C51A] could not be updated as Request failed with status code 400 at createError (/usr/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[4/18/2021, 10:20:18 PM] [Govee] [H6143_C51A] sending update {"name":"brightness","value":114}.
[4/18/2021, 10:20:19 PM] [Govee] [H6143_C51A] could not be updated as Request failed with status code 400 at createError (/usr/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).

**Comment by bwp91** [comment]
Hi @kv1296 

If you can update to the beta version 3.1.3-beta.1, this should fix the brightness issue you are receiving.

Hopefully in turn this will fix the colour issue?

If not, let me know and I will look into this further.

Thanks

**Comment by kv1296** [comment]
Yes, brightness issue is properly mapped and fixed now!

The color issue still seems to be persisting with the device still "ignoring" the update. The device still flashes and displays white whenever the color is changed. 

> [4/19/2021, 10:01:20 AM] [Govee] [H6143_C51A] sending update {"name":"color","value":{"r":255,"g":0,"b":0}}.
> [4/19/2021, 10:01:20 AM] [Govee] [H6143_C51A] current colour [rgb 255 0 0].
> [4/19/2021, 10:01:27 AM] [Govee] [H6143_C51A] ignoring update [{"online":true,"powerState":"on","brightness":60,"colorTemInKelvin":305,"colorTem":305}].
> [4/19/2021, 10:01:27 AM] [Govee] [LED Strip] received update [{"online":"true","powerState":"off","brightness":36,"color":{"r":255,"b":14,"g":137}}].
> [4/19/2021, 10:01:35 AM] [Govee] [H6143_C51A] sending update {"name":"color","value":{"r":30,"g":0,"b":255}}.
> [4/19/2021, 10:01:36 AM] [Govee] [H6143_C51A] current colour [rgb 30 0 255].
> [4/19/2021, 10:01:42 AM] [Govee] [H6143_C51A] ignoring update [{"online":true,"powerState":"on","brightness":60,"colorTemInKelvin":305,"colorTem":305}].
> [4/19/2021, 10:01:42 AM] [Govee] [LED Strip] received update [{"online":"true","powerState":"off","brightness":36,"color":{"r":255,"b":14,"g":137}}].
> [4/19/2021, 10:01:57 AM] [Govee] [H6143_C51A] ignoring update [{"online":true,"powerState":"on","brightness":60,"colorTemInKelvin":305,"colorTem":305}].

**Comment by bwp91** [comment]
In the Homebridge UI in the govee plugin settings page on the 'My Devices' tab, what does it say for the 'Supported Commands' for the H6143 strip?

**Comment by kv1296** [comment]
Supported commands are: turn, brightness, color, colorTem

Device cloud status is online and is retrievable and controllable

**Comment by bwp91** [comment]
The problem from my perspective, is that the plugin is sending the correct command to the device, and since the no problems with the request are shown in the logs, the 'reply' from Govee is successful too.

So I am a little clueless as to why your device isn't actually accepting the command :/

**Comment by bwp91** [comment]
The other thing I noticed is your device's state that is reported to the plugin

```
{"online":true,"powerState":"on","brightness":60,"colorTemInKelvin":305,"colorTem":305}
```

In the Govee API it explicitly states that the `colorTem` (colour temperature) should be between 2000 and 9000. So I am utterly confused!

**Comment by kv1296** [comment]
Ah yes I do see what you mean. Is there are reason the H6159 is not also reporting the `colorTem` in the same way? I see it reports `color` instead. 

I agree that it's a bit strange, hopefully this isn't some kind of weird thing Govee is doing with their newer products. These are the newer RGBIC lights which were first listed on Amazon on April 6th.

**Comment by bwp91** [comment]
The H6159 is the device I have, and it reports all of the supported commands,

<img alt="Screenshot 2021-04-19 at 19 21 08" src="https://user-images.githubusercontent.com/43026681/115284476-a26f8e00-a144-11eb-804c-935ffa3442cd.png">

So it's strange that your device doesn't have `colorTem` in the list...

**Comment by kv1296** [comment]
Yes, I see the `colorTem` in the supported commands as well, I wonder why the logs don't reflect that.

<img width="973" alt="Screen Shot 2021-04-19 at 2 25 20 PM" src="https://user-images.githubusercontent.com/45614017/115284849-2f9ded00-a11b-11eb-90c8-d88a6a1bdb58.png">

**Comment by bwp91** [comment]
> Ah yes I do see what you mean. Is there are reason the H6159 is not also reporting the colorTem in the same way? I see it reports color instead.

Oh I see what you mean now. Normally:

* If a device is in 'colour' mode (ie a colour is chosen from the govee app) then the device will report to the plugin the RGB current colour, eg

    ```
    [4/19/2021, 10:01:27 AM] [Govee] [LED Strip] received update [{"online":"true","powerState":"off","brightness":36,"color":{"r":255,"b":14,"g":137}}].
    ```

* If a device is in colour temperature mode (ie a colour temperature is chosen from the govee app) then the device will report to the plugin the kelvin value (between 2000 and 9000)

    ```
    [4/19/2021, 10:01:57 AM] [Govee] [H6143_C51A] ignoring update [{"online":true,"powerState":"on","brightness":60,"colorTemInKelvin":305,"colorTem":305}]
    ```

When selecting a colour from the home app, the plugin will send the rgb values to the device to put it in 'colour' mode. When selecing a colour temperature from the home app, the plugin will check to see if the device supports `colorTem`, and if the device does then the kelvin value will be sent (between 2000 and 9000). If the device doesn't support `colorTem` then the colour temperature will be converted to rgb and send as if it were an rgb value

**Comment by kv1296** [comment]
Ah okay I understand, thanks for the explanation. In that case, strange that the H6143 continues to report `colorTem` despite an RGB color being chosen in the Govee App. Sounds like you're thinking this may be a Govee API problem rather than something going on with the plugin?

**Comment by bwp91** [comment]
There have been a few users (including myself) who have been having problems with the API the last few days/couple of weeks, with regards to the API reporting old state information about the devices.

This seems to have been fixed now - it could be that the API has been incorrectly reporting the `colorTem` for your device. How does it seem now?

**Comment by kv1296** [comment]
Unfortunately not, the logs look exactly the same as before. Still a `colorTem` of 305 no matter what the actual state of the device is.

**Comment by kv1296** [comment]
In case you are curious, the last update seems to have fixed the problem. Not sure if you did something, or if Govee changed the API. Thanks!
