### ISSUE TITLE
Change Color or Brightness

### ISSUE THREAD

**Issue by gelberlemmy** [bwp91/homebridge-govee#69]
Hello,
i have installed the homebridge adapter on IOBroker with you Plugin. Cool i can use the Govee LED Stripes in IOBroker directly.
I have the H6163. But i can only use the datapoint "on" no brightness or so on. And who can i change the color of the stripe ?
When i change the color in the Govee App i can see it on the Hue datapoint. When i change it on IOBroker nothing happend.

Have i do some configuartion ? I have the API in placed in the Plugin.

Can you give me a little tip ?

Regards Andre

![2021-04-20 20_50_06-objects - ioBroker](https://user-images.githubusercontent.com/20154913/115448634-319aa580-a21a-11eb-93e2-8b77dfe7d8aa.png)

**Comment by bwp91** [comment]
Hi @gelberlemmy 

I have never used ioBroker so my support for this is limited.

The only thing I noticed on the [ioBroker docs](https://www.iobroker.net/#en/documentation/dev/stateroles.md) with regards to the 'roles' is that:

* the brightness should be `level.dimmer` not level.brightness
* you haven't set a role for `level.color.hue`

**Comment by gelberlemmy** [comment]
Hi, thanks for your quick answer. I will test it. Thanks

**Comment by gelberlemmy** [comment]
OK. The level.dimmer didnt work. I can´t write the Datapoints. When i change it in the Govee App, i can see the change on my Datapoints...... One Point "ON" i can use for on / off.
I use the Version 3.1.2
Here is a log from the Adapter

  |   |   |  
-- | -- | -- | --
ham.0 | 2021-04-21 10:10:27.171 | info | (26959) stateChange ham.0.Kanal-Büro.Lightbulb.Brightness {"val":100,"ack":true,"ts":1618992627168,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1618992627159}

**Comment by bwp91** [comment]
Have you checked this post?
While I don’t understand the language, there a couple of posts about Govee within the most recent posts:

https://forum.iobroker.net/topic/13540/homebridge-adapter-funktionierende-plugins-und-beispiele/108

I’m honestly not sure what the issue is, as i said before i have never used ioBroker so can’t really help except find things that could be useful
