### ISSUE TITLE
Unpaired and Not connected light strip keeps coning back

### ISSUE THREAD

**Issue by tjenvy** [bwp91/homebridge-govee#693]
### What issue do you have? Please be as thorough and explicit as possible.
I have multiple Govee devices in the house under two different people myself and my roommate.

I have 2 heaters and an RGBIC backlight.
He has a light strip, and RGBIC monitor light and hexapanels. 

When signing into my username in the plugin, I get my 3 devices AND his light strip. Whats strange is the name is always the long hex name every time. 
I sign into my Govee app, its not there so its pulling it from somewhere.

troubleshooting 
delete plugin 
clean json 
remove cached accessories
restart hbservice

Nothing seems to get rid of this light off my system. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI

* Which version of Homebridge/HOOBS do you have?
1.7.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
macOS 
Node js 18.18.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
10.2.0
This has been going on for over a year. Until recently it wasn't a big deal but I accidentally turn his light on while hes asleep and it's becoming a problem. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Govee RGBIC LED Neon Rope Lights for Desks
H61C3
firmware 1.2

### Please paste any relevant logs below.

```
Not really sure any logs you need here. 
Plugin in json is literally just username and password and govee as platform no other devices in json under that heading.

```

**Comment by bwp91** [comment]
Hi @tjenvy its probably a device which supports lan mode that is on the same network as your homebridge.

the lan scanner will pick up any govee device.

if you don’t use the lan functionality for your own devices then you could just disable the lan option in the plugin config

**Comment by tjenvy** [comment]
Thats the thing though we have 6 total devices in the home all on the network. The one that keeps showing up on mine is actually on his govee account not mine.  If it were scanning the LANthen his other devices would show up as well, they never have.  :(

**Comment by bwp91** [comment]
But not all devices support LAN mode, only some more recent light models

**Comment by tjenvy** [comment]
So whats different about "lan" mode then? and I would think  Hexa lights are the newest and would support this.

**Comment by bwp91** [comment]
could you provide a list of all models on your network? the 4 digit Hxxxx number ?

**Comment by tjenvy** [comment]
Well IDK why but disabling lan mode dropped that one. Doesnt make any sense but I’ll take it!!!

**Comment by bwp91** [comment]
It does make sense (at least to me!)

- the homebridge plugin will of course get your devices using the username and password
- the plugin will also scan the local network for devices**, and try and match these to the ones from your account
- in your case it is also detecting a device** not from your account (from your roommates account)

**not all devices support lan mode, and only the ones which do would be detected from the lan scanning.

There are some docs here about lan mode, plus a list of supported devices:

https://app-h5.govee.com/user-manual/wlan-guide

**Comment by tjenvy** [comment]
Yeah the hexa are H6061 which is lan supported
 The Dreamview G1 H604B is not. 
So I would expect the panels to also show up. 

The docs do show that it appears each device has a lan option switch per device so maybe that got turned on? Who knows. At least theres an explanation and I can search his device later to ensure that is turned off on all devices.  Stops cross talk on the system.
