### ISSUE TITLE
H5105

### ISSUE THREAD

**Issue by SieraEchoHotel** [bwp91/homebridge-govee#697]
* **Please explain your feature request in a one or two sentences.**

Please add support.

* **Is your feature request related to a problem? Please describe.**

No.

* **Any particular Govee devices that this relates to?**

H5105 thermometer device

* **Anything else?**

{"device":"19:36:D0:35:33:33:22:37","deviceName":"Govee Thermometer","model":"H5105","httpInfo":{"groupId":0,"device":"19:36:D0:35:33:33:22:37","sku":"H5105","spec":"","versionHard":"3.01.00","versionSoft":"1.00.10","deviceName":"Govee Thermometer","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":false,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":false,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":100,\"wifiLevel\":0,\"bleName\":\"GVH5105_2237\",\"address\":\"D0:35:33:33:22:37\",\"secretCode\":\"NyIzMzXQAAA=\",\"sku\":\"H5105\",\"device\":\"19:36:D0:35:33:33:22:37\",\"deviceName\":\"Govee Thermometer\",\"versionHard\":\"3.01.00\",\"versionSoft\":\"1.00.10\"}","lastDeviceData":"{\"online\":false,\"tem\":1810,\"hum\":3930,\"lastTime\":1704219300000,\"avgDayTem\":1810,\"avgDayHum\":3930}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/76e45906024e913ded9cdc0f943d87c3-add_list_type_device_5105.png\",\"headOnImg\":\"\",\"headOnImgNew\":\"\",\"headOffImg\":\"\",\"headOffImgNew\":\"\",\"ext\":\"\",\"ic\":0}"},"share":0,"deviceId":18079583,"goodsType":190,"attributesId":0,"supportScene":0}}

**Comment by bvjustin** [comment]
I also have this device, here is my diagnostic information:

`
{"device":"A5:67:D6:30:38:35:57:4A","deviceName":"Upstairs Thermometer","model":"H5105","httpInfo":{"groupId":0,"device":"A5:67:D6:30:38:35:57:4A","sku":"H5105","spec":"","versionHard":"3.01.00","versionSoft":"1.00.10","deviceName":"Upstairs Thermometer","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":false,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":false,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":100,\"wifiLevel\":0,\"bleName\":\"GVH5105_574A\",\"address\":\"D6:30:38:35:57:4A\",\"sku\":\"H5105\",\"device\":\"A5:67:D6:30:38:35:57:4A\",\"deviceName\":\"Upstairs Thermometer\",\"versionHard\":\"3.01.00\",\"versionSoft\":\"1.00.10\"}","lastDeviceData":"{\"online\":true}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/76e45906024e913ded9cdc0f943d87c3-add_list_type_device_5105.png\",\"headOnImg\":\"\",\"headOnImgNew\":\"\",\"headOffImg\":\"\",\"headOffImgNew\":\"\",\"ext\":\"\",\"ic\":0}"},"share":0,"deviceId":19029332,"goodsType":190,"attributesId":0,"supportScene":0}}
`
