### ISSUE TITLE
H6163 Brightness issue (39%)

### ISSUE THREAD

**Issue by jeanofthedead** [bwp91/homebridge-govee#7]
Hey again - my H6163 model has the same issue with being 'stuck' at the 39% brightness (and delays/failures when setting colors). Thought I'd pass that info along - thanks!

**Comment by bwp91** [comment]
just released v2.0.3 to fix this. Please update and restart Homebridge.
thanks for letting me know.
obviously i can't own *every* model of govee devices so I have to rely on people telling me on a per-device basis!

**Comment by jeanofthedead** [comment]
So fast! Thanks. I'll have to wait until it trickles down the HOOBS repo to update, but I'll report back when I can update.
