### ISSUE TITLE
Controlling color of lights via phillips hue switch

### ISSUE THREAD

**Issue by rohanbhangui** [bwp91/homebridge-govee#702]
Not sure if this is a bug so feel free to close accordingly.

I love that this plugin exists, makes it super easy to use.

I do have phillips hue lights in my homekit system. I use a phillips hue switch (remote with buttons) to control the lights in my office. I have a newly set up govee product (Floor Wall Lamp H6076). I use the buttons on the phillips hue switch to turn on/off the lights as well as the color.

I can control the on/off state easily but if I change the color of my govee light (to say green), and then I press the one of the phillips hue buttons (should turn on all the lights and make it a yellow), the phillips hue lights will turn the correct color (yellow), the govee will stay green.

Is there anything I can do to fix this? I would expect if the color and on/off state is set in my switch that the light would turn on and the light would turn to the color I set. Seems only way to trigger color change is to hit the same button second time (first one to turn on the light)

I updated the firmware of govee light, homebridge and plugins are up to date

**Comment by bwp91** [comment]
could you do this, and grab logs from these actions:

- use the govee app to change the colour to BLUE
- then use the govee app to change the temperature to YELLOWER (doesnt matter which)
- use the HOME app to change the colour to BLUE
- then use the HOME app to change the temperature to something similar to what was chosen above ^

**Comment by rohanbhangui** [comment]
[homebridge.log_1.txt](https://github.com/bwp91/homebridge-govee/files/13847144/homebridge.log_1.txt)

**Comment by rohanbhangui** [comment]
Temporary Solution: 

I was using color temperature with my phillips hue lights and thought this would work with the Govee. Instead in homekit use the color tab instead of temperature and it should work fine.
