### ISSUE TITLE
Govee air purifiers H7121 and H7126 no controls in Home assistant

### ISSUE THREAD

**Issue by adambomb1011** [bwp91/homebridge-govee#705]
* **Please explain your feature request in a one or two sentences.**
Govee air purifiers H7121 and H7126 are being added to home assistant through the homebridge plugin, but there is no device control for them. I can only "Identify" and Lock controls. I would like to turn them off and on.

* **Is your feature request related to a problem? Please describe.**
There is no off/on entity in home assistant

* **Any particular Govee devices that this relates to?**
H7121 and H7126

* **Anything else?**

**Comment by jeepin95** [comment]
I am seeing the same results, only an "Identify" option in Home Assistant. Initially I was not able to control my H7126 through Homebridge either. Looking at #577 which is old but got me to look at the beta. Once I updated to v10.3.1-beta.0 and restart I can now simply turn it on or off through Homebridge, but in Home Assistant I still only see the identify button even after deleting the devices, rebooting and detecting and configuring them again.
