### ISSUE TITLE
[BLE] disabling client as ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by mickolas9** [bwp91/homebridge-govee#707]
### What issue do you have? Please be as thorough and explicit as possible.

I cannot enable bluetooth on my Govee LED H6181

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

RPi Node.js V20

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Latest beta

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6181

### Please paste any relevant logs below.

```

```

**Comment by MGSTL** [comment]
I am also having this issue as well.
