### ISSUE TITLE
H6195 Leds won't change color

### ISSUE THREAD

**Issue by 89c4vette** [bwp91/homebridge-govee#709]
### What issue do you have? Please be as thorough and explicit as possible.
I can turn the strips on/off, and change brightness. But when changing colors homekit says they have changed but no change on the lights themselves. 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge 

* Which version of Homebridge/HOOBS do you have?
1.7.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
Currently have 10.3.0, the color changing hasn't been working

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6195

### Please paste any relevant logs below.
In the log it will switch to the blue (when i click) and then 30 seconds later switch back

```
[16/01/2024, 16:41:28] [Govee] [Bedroom lights] current colour [7143K / 140M].
[16/01/2024, 16:45:41] [Govee] [Bedroom lights] current colour [rgb 0 0 255].
[16/01/2024, 16:45:54] [Govee] [Bedroom lights] current colour [7143K / 140M].
[16/01/2024, 16:46:07] [Govee] [Bedroom lights] current colour [rgb 0 0 255].
[16/01/2024, 16:46:19] [Govee] [Bedroom lights] current colour [7143K / 140M].
```

**Comment by mofirouz** [comment]
To add to this issue, I have 3x H6159 and they don't change colour either. The firmware version on them is 1.07.02 (no new versions) and hardware version is 1.00.02.

**Comment by joshsb9662** [comment]
Reference this wiki to see if this fixes the issue. https://github.com/bwp91/homebridge-govee/wiki/Common-Errors

**Comment by mofirouz** [comment]
Tried all the combos, nothing worked sadly.
