### ISSUE TITLE
H6078 39% Brightness 

### ISSUE THREAD

**Issue by SmetcH1302** [bwp91/homebridge-govee#710]
### What issue do you have? Please be as thorough and explicit as possible.
When I set 100% brightness on my H6078 lamp in Govee app, Homekit says 39% via Hoobs Log.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Hoobs
* Which version of Homebridge/HOOBS do you have?
Hoobs 4.3.0
Homebridge 1.6.0
* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Hoobs box
* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
10.3.0
* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6078

### Please paste any relevant logs below.

```
1/17/2024, 5:20:19 PMHue Bridge NewGovee[Floor Lamp] current colour [4600K / 217M].
1/17/2024, 5:20:25 PMHue Bridge NewGovee[Floor Lamp] current brightness [20%].
1/17/2024, 5:20:30 PMHue Bridge NewGovee[Floor Lamp] current brightness [39%].
```

**Comment by traviscole** [comment]
[https://github.com/bwp91/homebridge-govee/wiki/Common-Errors#brightness-issues](https://github.com/bwp91/homebridge-govee/wiki/Common-Errors#brightness-issues)

Brightness Issues
For some Govee light models, they may be a scaling issue with the brightness. You may find that turning the brightness to 100% shows as 39% in the Home app. To fix:

In the plugin settings in the 'Light Devices' section, enter the device ID and label for the device (this can be found in the Homebridge log when the plugin starts (this can be found in the Homebridge log when the plugin starts (skip this step if you already have an entry for your light configured)
Check the 'AWS Brightness No Scale' option (note this option will not appear until the step above has been completed)
Restart the plugin (or Homebridge)

**Comment by SmetcH1302** [comment]
Thank you. Problem solved.
