### ISSUE TITLE
H61810A2FR Compatibility

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-govee#72]
Hi Ben, any chance to introduce compatibility for H61810A2FR ?
Please see below:

https://www.amazon.it/dp/B07WNQXGC1/ref=cm_sw_r_cp_api_glt_i_17BZ4DPA5WVJQF0NJYK1

Thanks
Stefano

**Comment by bwp91** [comment]
In the new version of the plugin it will log an entry if someone has a model that could be potentially be supported.

But the plugin is limited to the models that are supported by the govee API which can be seen on the wiki page on 'Supported Devices'.

Also, not sure if the H6181 is wifi or bluetooth or both, but it would need wifi if it were every to be supported by the API

**Comment by Stetocasa** [comment]
> In the new version of the plugin it will log an entry if someone has a model that could be potentially be supported.
> 
> 
> 
> But the plugin is limited to the models that are supported by the govee API which can be seen on the wiki page on 'Supported Devices'.
> 
> 
> 
> Also, not sure if the H6181 is wifi or bluetooth or both, but it would need wifi if it were every to be supported by the API

Tomorrow Amazon will deliver this model in my home.
I know that is totally supported from Govee app

**Comment by bwp91** [comment]
> I know that is totally supported from Govee app

The Govee app, obviously, will work will all Govee models - the app works with both bluetooth and wifi devices. 

The Govee API, on the other hand, only works with a select number of wifi models. There is nothing I can do about this except be able to support more models as and when the API is updated by Govee themselves.

**Comment by Stetocasa** [comment]
@bwp91 I sent a note to Govee support asking if they are planned to add H61810A2FR in official API
