### ISSUE TITLE
H601A Stuck at 39%

### ISSUE THREAD

**Issue by cmb991** [bwp91/homebridge-govee#720]
### What issue do you have? Please be as thorough and explicit as possible.

Same issue that others have reported. My H601A is having the 0-39% brightness bug, showing no response trying to set higher than that. 39% represents 100%. Everything is up to date, and I have tried the beta as well without success. I see that you have been able to fix this for other models.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

1.7.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Docker

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

10.3.0 has never worked past 39% since I got the lights a month ago. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H601A

### Please paste any relevant logs below.

```

```

**Comment by joshsb9662** [comment]
You tried this fix?

https://github.com/bwp91/homebridge-govee/wiki/Common-Errors

**Comment by cmb991** [comment]
Looks like the first option fixes it.  Same issue happened on the newer Govee bulbs I bought. Thanks. On Feb 3, 2024, at 21:02, joshsb9662 ***@***.***> wrote:﻿
You tried this fix?
https://github.com/bwp91/homebridge-govee/wiki/Common-Errors
