### ISSUE TITLE
RGBIC TV Backlight 3 Lite (model:H6099)

### ISSUE THREAD

**Issue by kenwkcheung** [bwp91/homebridge-govee#723]
{"device":"26:23:D4:39:32:35:32:0A","deviceName":"RGBIC TV Backlight 3 Lite","model":"H6099","httpInfo":{"groupId":0,"device":"26:23:D4:39:32:35:32:0A","sku":"H6099","spec":"","versionHard":"3.05.01","versionSoft":"1.00.05","deviceName":"RGBIC TV Backlight 3 Lite","deviceExt":{"deviceSettings":"{\"wifiName\":\"private-g\",\"address\":\"D4:39:32:35:32:0A\",\"bleName\":\"Govee_H6099_320A\",\"topic\":\"GD/737eb37b6085263acd9de0e274010c73\",\"wifiMac\":\"60:74:F4:8F:CF:AE\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.13\",\"wifiHardVersion\":\"1.06.00\",\"ic\":36,\"secretCode\":\"Nc/UOTI1Mgo=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6099\",\"device\":\"26:23:D4:39:32:35:32:0A\",\"deviceName\":\"RGBIC TV Backlight 3 Lite\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"1.00.05\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/784ef9170ab66ccdaf137d29963f5476-add_list_type_device_6099.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/42d0585f82d3c6c93b50534f9e9b3804-new_light_title_h6104_alexa_on.png\",\"headOnImgNew\":\"\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5098709790bf157447ed1f8e0b65c2ad-new_light_title_6104_alexa_off.png\",\"headOffImgNew\":\"\",\"ext\":\"\",\"ic\":50}"},"pactType":1,"pactCode":1,"share":0,"deviceId":19000560,"goodsType":191,"attributesId":1,"supportScene":1}}

**Comment by quorea** [comment]
Hello bwp91,
just installed H6099 but the app says not supported. here is the code 
TV Backlight 3 Lite] is not currently supported, do create a Github issue with the following info:
{"device":"51:CA:C9:F0:82:C6:59:94","deviceName":"TV Backlight 3 Lite","model":"H6099"


Any help?
