### ISSUE TITLE
H6008 lights fully bright only at 39% not 100%

### ISSUE THREAD

**Issue by cbhfan88** [bwp91/homebridge-govee#724]
### What issue do you have? Please be as thorough and explicit as possible.

My Govee lights are on at 100% but in homekit they show as 39%. When I set them at 100% in HomeKit they get really dim.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
V1.7.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 4B

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

V10.3.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Lights, H6008

### Please paste any relevant logs below.

```

```

**Comment by joshsb9662** [comment]
Take a look at this wiki, should fix the issue. I had the same problem before. 

https://github.com/bwp91/homebridge-govee/wiki/Common-Errors

**Comment by inventor7777** [comment]
https://github.com/bwp91/homebridge-govee/wiki/Common-Errors
