### ISSUE TITLE
Thermometer","model":"H5105"

### ISSUE THREAD

**Issue by Ebinette** [bwp91/homebridge-govee#725]
* **Which model is this? Need the `Hxxxx` number.**

model":"H5105"

* **Which type of device is this? Light, heater, leak sensor, etc.**

Thermometer Hygrometer

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**

LAN

* **Anything else?**

[Indoor Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"B5:DF:D6:35:33:33:5F:52","deviceName":"Indoor Thermometer","model":"H5105","httpInfo":{"groupId":0,"device":"B5:DF:D6:35:33:33:5F:52","sku":"H5105","spec":"","versionHard":"3.01.00","versionSoft":"1.00.10","deviceName":"Indoor Thermometer","deviceExt":{"deviceSettings":"{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":false,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":false,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":100,\"wifiLevel\":0,\"bleName\":\"GVH5105_5F52\",\"address\":\"D6:35:33:33:5F:52\",\"secretCode\":\"Ul8zMzXWAAA=\",\"sku\":\"H5105\",\"device\":\"B5:DF:D6:35:33:33:5F:52\",\"deviceName\":\"Indoor Thermometer\",\"versionHard\":\"3.01.00\",\"versionSoft\":\"1.00.10\"}","lastDeviceData":"{\"online\":true,\"tem\":2740,\"hum\":3240,\"lastTime\":1706932980000,\"avgDayTem\":2740,\"avgDayHum\":3240}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/76e45906024e913ded9cdc0f943d87c3-add_list_type_device_5105.png\",\"headOnImg\":\"\",\"headOnImgNew\":\"\",\"headOffImg\":\"\",\"headOffImgNew\":\"\",\"ext\":\"\",\"ic\":0}"},"share":0,"deviceId":19094568,"goodsType":190,"attributesId":0,"supportScene":0}}

**Comment by floringae** [comment]
Support added in following PR #727

**Comment by Ebinette** [comment]
> Support added in following PR #727

You are Great! Thank you !
