### ISSUE TITLE
LAN Support for H70A1

### ISSUE THREAD

**Issue by cmfrazier** [bwp91/homebridge-govee#729]
* H70A1

* Light Strip

* Bluetooth, WiFi, LAN

* AWS currently supported, but would like to see LAN support.

**Comment by bwp91** [comment]
Hi @cmfrazier 

please update to beta version 10.3.1-beta.4 this should start the LAN mode working for this model!

**Comment by cmfrazier** [comment]
Indeed, works great!

**Comment by bwp91** [comment]
Thanks @cmfrazier 😌

**Comment by cmfrazier** [comment]
@bwp91 Let me know if I should make a new issue, but I'm seeing where brightness in home.app keeps resetting to 39% brightness. This would also happen when using AWS too.

**Comment by cmfrazier** [comment]
> @bwp91 Let me know if I should make a new issue, but I'm seeing where brightness in home.app keeps resetting to 39% brightness. This would also happen when using AWS too. 

Sigh... https://github.com/bwp91/homebridge-govee/wiki/Common-Errors#brightness-issues

**Comment by bwp91** [comment]
you got it!
