### ISSUE TITLE
createError on poll in version 3.1.4

### ISSUE THREAD

**Issue by sidjohn1** [bwp91/homebridge-govee#73]
### What issue do you have? Please be as thorough and explicit as possible.

At regular intervals i get the following error, i assume it’s during polls because on/off works fine. I only see the error on 3.1.4, if i roll back to 3.1.3 the error clears

[5/6/2021, 1:03:38 PM] [Govee] [Den TV Light] could not be refreshed as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).

### Details of your setup.
(1) Homebridge + config-ui

* Which version of Homebridge/HOOBS do you have?
* 1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
OS | macOS
v14.16.1
v6.14.12

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
* 3.1.4

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6104

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @sidjohn1 

In v3.1.3 if you turn on debug mode in the plugin settings, are there any messages that appear in the logs about skipping the sync (in place of these messages that are appearing in v3.1.4)?

**Comment by sidjohn1** [comment]
Even with debugging turned on, that is all it says… over and over again

**Comment by bwp91** [comment]
On v3.1.3?

**Comment by sidjohn1** [comment]
Yes i do,
[5/7/2021, 2:23:38 PM] [Govee] [Den TV Light] skipping sync as device status not retrievable.

**Comment by bwp91** [comment]
If you update to the latest beta version do you still get any ` Request failed with status code 400` error in the log?
The `skipping sync as device status not retrievable` message is 'normal' (can only be seen in debug mode).

**Comment by bwp91** [comment]
I am confident that this issue has been fixed in the latest version of the plugin so will close this issue.
If you are still having problems then please feel free to reopen.
Thanks!
