### ISSUE TITLE
39%

### ISSUE THREAD

**Issue by Lezomaj** [bwp91/homebridge-govee#74]
Hey, Im trying to use HomeKit with all of my govee devices but it always says my devices are at 39% brightens and when I go and change it says "No response" Ive updated everything but its still doing it.

**Comment by bwp91** [comment]
hi @Lezomaj 
what is the model of the device that is causing this?

**Comment by Lezomaj** [comment]
> hi @Lezomaj
> what is the model of the device that is causing this?

Hey, my aura table lamp H6052 is with the 39% problem, and also my new model H6143 just isn't working at all with HomeKit, its in the app but they nothing.

**Comment by bwp91** [comment]
the latest beta version should fix the brightness issues for the H6052.
What issues are you facing with the H6143?
