### ISSUE TITLE
Status Code 400

### ISSUE THREAD

**Issue by geekseanlin** [bwp91/homebridge-govee#75]
I keep getting the following code in my homebridge though the led is still working.

[Living Room TV LED] could not be refreshed as Request failed with status code 400 at createError (/homebridge/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).

**Comment by bwp91** [comment]
Hi @geekseanlin 
If you update to the beta version of the plugin do you still get this message?

**Comment by thechris1992** [comment]
no, it's gone

**Comment by bwp91** [comment]
I am confident that this issue has been fixed in the latest version of the plugin so will close this issue.
If you are still having problems then please feel free to reopen.
Thanks!
