### ISSUE TITLE
New Govee App Update

### ISSUE THREAD

**Issue by Superduperduu04** [bwp91/homebridge-govee#78]
Hey, in the new App Update it's now possible to use Siri Shortcuts with the Bluetooth Models. 
Is this maybe somehow a way to integrate the Bluetooth Models in the plugin to? ￼
I don't have any programmer skills - I was only asking myself if this is a way to do so?🤔

**Comment by bwp91** [comment]
Hi @Superduperduu04 

Bluetooth control is not something I plan on adding to the plugin. This is for a number of reasons:

* This would require extra software packages to be installed outside of Homebridge, and this can differ per platform, so it wouldn't be just a one-click install for the plugin
* The current state of any device could not be retrieved, meaning, if the device was controlled via the govee app then it would not update in Homebridge
* The devices can only connect to one bluetooth device at a time, meaning, it simply would not connect if the led strip is connected to the govee app via bluetooth, and vice versa if homebridge was connected to the device then the govee app could not connect

There are simply too many limitations.

**Comment by bwp91** [comment]
@Superduperduu04  

Initial support for bluetooth is now available in the beta version of the plugin… happy to walk you through the steps to test if you’re interested!

**Comment by Superduperduu04** [comment]
@bwp91 
That's great. I will try to test it, but how can i get the device id from my led stripe?
My Model is H6127 and not supported yet. Can you add this model too?

**Comment by bwp91** [comment]
I'd be happy to help you (it's a bit easier messaging there) on Discord?
https://discord.gg/cMGhNtZ3tW
