### ISSUE TITLE
Support Request for H5086 Smart Plug

### ISSUE THREAD

**Issue by sterlingpelzel** [bwp91/homebridge-govee#780]
**Model:** H5086

**Device Type:** Smart plug

**Connection Methods:** WiFi & Bluetooth. Unsure about LAN mode

**Comment by PhracturedBlue** [comment]
I don't use this project, but I needed to communicate with my H5086.
I have documented the changes in the protocol here (note that AA01 uses 01/00 to trun on/off the device)
https://github.com/egold555/Govee-Reverse-Engineering/pull/13

Hopefully it will help
