### ISSUE TITLE
Please add Unsupported Fan - H7106 - Smart Tower Fan

### ISSUE THREAD

**Issue by CobWebbs** [bwp91/homebridge-govee#784]
* **Which model is this? Need the `Hxxxx` number.**

H7106 - Smart Tower Fan

* **Which type of device is this? Light, heater, leak sensor, etc.**

Fan

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**

Wifi (and Maybe Bluetooth - Sorry only had it an hour)

* **Anything else?**

{"device":"1F:DA:D0:C9:07:00:65:6E","deviceName":"Smart Tower Fan","model":"H7106","httpInfo":{"groupId":0,"device":"1F:DA:D0:C9:07:00:65:6E","sku":"H7106","spec":"","versionHard":"1.02.00","versionSoft":"1.00.10","deviceName":"Smart Tower Fan","deviceExt":{"deviceSettings":"{\"wifiName\":\"XXXXXX-XX\",\"address\":\"D0:C9:07:00:65:6F\",\"bleName\":\"GVH7106656F\",\"topic\":\"GD/a746aa7123cf506155a48aa868ba8b5f\",\"wifiMac\":\"D0:C9:07:00:65:6E\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.10\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"L29lfLK10Ns=\",\"mcuSoftVersion\":\"1.00.09\\u0000\",\"mcuHardVersion\":\"1.01.10\\u0000\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H7106\",\"device\":\"1F:DA:D0:C9:07:00:65:6E\",\"deviceName\":\"Smart Tower Fan\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.10\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/9c9f19f3f00806e9160a024c3659ba89-add_list_type_device_7106.png\",\"headOnImg\":\"\",\"headOnImgNew\":\"\",\"headOffImg\":\"\",\"headOffImgNew\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"deviceId":21129580,"gidConfirmed":false,"goodsType":200,"attributesId":0,"supportScene":0}}

**Comment by gizbug** [comment]
Also waiting for support
