### ISSUE TITLE
Bluetooth LE capabilities

### ISSUE THREAD

**Issue by pintapass** [bwp91/homebridge-govee#80]
Is there any way that Bluetooth LE support could be added for Govee's non-WiFi LED light strips?  I'm thinking specifically of the [H6181](https://www.amazon.com/dp/B07V4CY9GZ/ref=emc_b_5_t).

It seems that there are other Homebridge Govee plugins (e.g., Homebridge Plugin Govee, Homebridge Govee Water Detectors) that manage to control the Bluetooth thermometer/hygrometer devices. Could their functionality be leveraged somehow to integrate Bluetooth LE support into Homebridge Govee?

Running `hcitool lescan` via the Homebrige terminal on my Pi4 sees and identifies the MAC of my H6181. But inserting that MAC into the corresponding field of Homebridge Govee (I know, it was a Hail Mary) did not provide any measure of control.

I'd be thrilled with just simple on/off functions, but some measure of RGB control (even basic color changing) would be the icing on the cake.

Thanks!

**Comment by bwp91** [comment]
Hi @pintapass 

Would be happy to message you on Discord about this...
https://discord.gg/cMGhNtZ3tW

I've been recoding the plugin to allow for the opportunity of bluetooth control of devices.
