### ISSUE TITLE
Third Device Not Showing up

### ISSUE THREAD

**Issue by davewehr** [bwp91/homebridge-govee#81]
I have two H6052 units and one H6072. The 6072 doesn’t appear in the plugin even though I entered the MAC address. What’s even more strange is only one of the two 6052 units are present in the config, yet they both show up on the my devices tab and work in HomeKit.

**Comment by bwp91** [comment]
Hi @davewehr 

The plugin will use the API key to download a device list from your Govee account. This has nothing to do with any device ids that are in the config - this is used to apply optional configuration to each device. This is why you have both H6052s that appear, even though only one is in the configuration.

It's strange that the H6072 is not appearing. It's definitely not in the ignore list setting? It might be worth applying for a new API key from Govee. Try this, and if it doesn't work I can look into this further.

**Comment by davewehr** [comment]
That worked, thank you so much
