### ISSUE TITLE
TV Backlight Kit is not currently supported

### ISSUE THREAD

**Issue by adnix42** [bwp91/homebridge-govee#816]
### What issue do you have? Please be as thorough and explicit as possible.
When adding the plugin I get the following error:

[TV Backlight Kit] is not currently supported, do create a Github issue with the following info:

### Details of your setup.
Home Bridge Docker 

* Which version of Homebridge/HOOBS do you have?
1.8.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Docker

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
10.8.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
TV Backlight Kit model : H605A

### Please paste any relevant logs below.
[TV Backlight Kit] is not currently supported, do create a Github issue with the following info:
{"device":"74:95:C9:F0:83:46:5E:84","deviceName":"TV Backlight Kit","model":"H605A","httpInfo":{"groupId":0,"device":"74:95:C9:F0:83:46:5E:84","sku":"H605A","spec":"","versionHard":"3.05.01","versionSoft":"1.00.05","deviceName":"TV Backlight Kit","deviceExt":{"deviceSettings":"{\"wifiName\":\"xxxxxxxx\",\"address\":\"C9:F0:83:46:5E:84\",\"bleName\":\"Govee_H605A_5E84\",\"topic\":\"GD/4472fdff517181d138acfbca76ce6c40\",\"wifiMac\":\"60:74:F4:EA:22:D1\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.14\",\"wifiHardVersion\":\"1.06.00\",\"ic\":56,\"secretCode\":\"xxxxxxxx",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H605A\",\"device\":\"74:95:C9:F0:83:46:5E:84\",\"deviceName\":\"TV Backlight Kit\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"1.00.05\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/b0fb924ba87ea0c3950888c3ec1bc42b-add_list_type_device_605a.png\",\"headOnImg\":\"\",\"headOnImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/44465ea19aacbbd800a158e4058ca489-new_light_title_605a_on.png\",\"headOffImg\":\"\",\"headOffImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/9cdc37821a2cb09e7197e23c8ffb28e8-new_light_title_605a_off.png\",\"ext\":\"\",\"ic\":56}"},"pactType":1,"pactCode":1,"share":0,"deviceId":21705046,"gidConfirmed":false,"goodsType":253,"attributesId":33,"supportScene":0}}

**Comment by benwebbbenwebb** [comment]
Hi @adnix42  

FYI looks like it should be supported now

https://github.com/bwp91/homebridge-govee/blob/fa245b4e0e04a325f74aea6837128dfa9d5acc7d/CHANGELOG.md?plain=1#L30-L38
