### ISSUE TITLE
Govee Smart TV Backlight 3S (H6098)

### ISSUE THREAD

**Issue by CyderEyesX** [bwp91/homebridge-govee#819]
* **Which model is this? Need the `Hxxxx` number.**
H6098

* **Which type of device is this? Light, heater, leak sensor, etc.**
Govee Smart TV Backlight 3S

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**
Wifi & Bluetooth 

* **Anything else?**

[RGBIC TV Backlight 3S] is not currently supported, do create a Github issue with the following info:
{"device":"3A:5A:D6:39:32:35:26:35","deviceName":"RGBIC TV Backlight 3S","model":"H6098","httpInfo":{"groupId":0,"device":"3A:5A:D6:39:32:35:26:35","sku":"H6098","spec":"","versionHard":"3.05.01","versionSoft":"1.00.04","deviceName":"RGBIC TV Backlight 3S","deviceExt":{"deviceSettings":"{\"wifiName\":\"CyderEyesXs Wi-Fi Network\",\"address\":\"D6:39:32:35:26:35\",\"bleName\":\"Govee_H6098_2635\",\"topic\":\"GD/0077c0e26d63b1b3a298838cfcb97058\",\"wifiMac\":\"60:74:F4:E1:F5:33\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.10\",\"wifiHardVersion\":\"1.06.00\",\"ic\":36,\"secretCode\":\"2BXWOTI1JjU=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H6098\",\"device\":\"3A:5A:D6:39:32:35:26:35\",\"deviceName\":\"RGBIC TV Backlight 3S\",\"versionHard\":\"3.05.01\",\"versionSoft\":\"1.00.04\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/1b48be0324bc20c591184505ac24b427-add_list_type_device_6098.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/42d0585f82d3c6c93b50534f9e9b3804-new_light_title_h6104_alexa_on.png\",\"headOnImgNew\":\"\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5098709790bf157447ed1f8e0b65c2ad-new_light_title_6104_alexa_off.png\",\"headOffImgNew\":\"\",\"ext\":\"\",\"ic\":50}"},"pactType":1,"pactCode":1,"share":0,"deviceId":21774824,"gidConfirmed":false,"goodsType":203,"attributesId":1,"supportScene":1}}

**Comment by benwebbbenwebb** [comment]
FYI @CyderEyesX looks like @bwp91 added support for H6098 under v10.9.0 a week or so ago...

https://github.com/bwp91/homebridge-govee/blob/fa245b4e0e04a325f74aea6837128dfa9d5acc7d/CHANGELOG.md?plain=1#L30-L38
