### ISSUE TITLE
H6054 Brightness slider issue

### ISSUE THREAD

**Issue by Cramster** [bwp91/homebridge-govee#82]
### What issue do you have? Please be as thorough and explicit as possible.

The brightness adjust slider for H6054 appears to be inaccurate- the slider doesn’t seem to go above the 40% mark, but that is actually 100% on the actual light. In other words I can control 100% of the light but only using the bottom 40% of the brightness slider in HomeKit. I have another light, a different model, and the slider works fine.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

(1) Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 3B+
Node.js 14.17.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Latest 3.3.0 but it was also present in the previous version (I started using this on the version prior to 3.3.0 - big thanks, it’s a fantastic plug-in and works really well even despite this minor UI issue on this particular model - thank you!!)

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6054

### Please paste any relevant logs below.

```
06/07/2021, 23:29:59] [Govee] [TV Lights] current brightness [39%].
[06/07/2021, 23:30:14] [Govee] [TV Lights] current brightness [39%].
[06/07/2021, 23:30:29] [Govee] [TV Lights] current brightness [39%].
[06/07/2021, 23:30:32] [Homebridge UI] [homebridge-govee] Terminating child process...
[06/07/2021, 23:30:32] [Homebridge UI] [homebridge-govee] Child process ended
[06/07/2021, 23:30:44] [Govee] [TV Lights] current brightness [39%].
[06/07/2021, 23:30:59] [Govee] [TV Lights] current brightness [39%].
[06/07/2021, 23:31:13] [Homebridge UI] [homebridge-govee] Terminating child process...
[06/07/2021, 23:31:13] [Homebridge UI] [homebridge-govee] Child process ended
[06/07/2021, 23:31:14] [Govee] [TV Lights] current brightness [39%].
[06/07/2021, 23:31:29] [Govee] [TV Lights] current brightness [39%].
[06/07/2021, 23:31:36] [Govee] [TV Lights] could not be updated as Request failed with status code 400 at createError (/usr/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
```

**Comment by bwp91** [comment]
Hi @Cramster 

Can you install the beta version of the plugin I have just pushed, v3.3.1-beta.0, to see if this brightness issue is resolved?

Thanks!

**Comment by Cramster** [comment]
Trying to update to beta but it's telling me my node is not up to update (to 14.17.3) but when I try to update it thinks it's on the latest version at 14.17.2 similar to the issue this person has:

https://github.com/homebridge/homebridge/issues/2951

I will try their work around to install to 14.17.3 and then update to beta when I get a chance today. Thank you!!

**Comment by bwp91** [comment]
You can ignore the node version warning, the plugin will still work on node 14.17.2

**Comment by Cramster** [comment]
Ah okay I see now - got it! After playing around with it for just 20 seconds so far the brightness solider appears to be working properly! Awesome, friend.

**Comment by DarkKent00** [comment]
I’m not to sure this is an issue as I just installed the plugin today. All is running well but my light strip has considerable lag. Running HB on and M1 Mac mini. 22 wyze color bulbs, 4 wyze outlets, and 4 wyze cams connected. All running smooth. I have the cams unbridged. Only thing taking long to respond is the govee strip. 8 to 10 secs. Maybe more. But sometimes a lil less. No error warnings. Shows it’s happening instantly on the HBUI. Anything else I can help with just let me know.

**Comment by bwp91** [comment]
hi @DarkKent00 

This plugin can appear to have quite a lot of issues (!) but it’s actually normally down to the connection between the govee server and the device strip itself.

The plugin sends update commands to the govee server, and these requests always get a “success” response from govee (unless there are internet issues either on your network or with the govee server). However it can sometimes take some time for the device to get the update from the govee server to the device - sometimes pretty instant, sometimes with a delay, and even sometimes not at all. The plugin cannot determine whether these commands are received by the device. I think these govee devices regularly drop wifi connection which I think is the main cause of these delays.

You can turn on plugin debug logging in the plugin settings to see exactly when the commands are being sent to govee server (they appear as `sending update…`) in the logs. This can be useful to see when the command is sent vs when the command is received by the device (when the device itself responds to the command).

But I do appreciate this plugin doesn’t feel quick and snappy like other plugins 😅

**Comment by DarkKent00** [comment]
You are absolutely right in everything you said. Seems it's govee side. Everything is running smooth on HB. Thanks for the great work. Oh don't know if this means anything but I have 2 strips. The other I haven't plugged in in a while but it is on my account. HB shows that strip as on 100%.

**Comment by bwp91** [comment]
Chances are it was ON when you unplugged it, so the govee api is still reporting it as on!

**Comment by bwp91** [comment]
You can use the “ignore devices” plugin setting to remove it if it’s cluttering the home app!

**Comment by bwp91** [comment]
Closing this as original issue re `H6054` model has been fixed in the current version of the plugin!
Thanks
