### ISSUE TITLE
H6641 Support

### ISSUE THREAD

**Issue by allkindsofralph** [bwp91/homebridge-govee#825]
* **Which model is this? Need the `Hxxxx` number.**
H6641

* **Which type of device is this? Light, heater, leak sensor, etc.**
Light, Neon Rope for Wall Lining

* **Which connection methods does this device have? Wifi? Bluetooth? LAN mode? All?**
All, Bluetooth WiFi LAN Matter

* **Anything else?**
It’s a RGBICWW neon rope similar to Neon Rope 2

is there anything else I can provide to aid in adding support. I know it has Matter support, this is the first Matter support device I have gotten from Govee but after I setup in Govee app it seems like I can’t add it to HomeKit via Matter code.

**Comment by benwebbbenwebb** [comment]
Hi @allkindsofralph 

FYI looks like it should be supported now

https://github.com/bwp91/homebridge-govee/blob/fa245b4e0e04a325f74aea6837128dfa9d5acc7d/CHANGELOG.md?plain=1#L30-L38
