### ISSUE TITLE
Limited Color Management 

### ISSUE THREAD

**Issue by michaelromero2020** [bwp91/homebridge-govee#83]
I just wanted to make sure I'm not missing anything. The color control through the home app is pretty limited; for instance, even with the Govee RBGIC versions, your only option is to pick one color and the 6 options are predetermined. There are not any additional controls that I haven't enabled, are there?

**Comment by bwp91** [comment]
Hi @michaelromero2020 

The home app doesn’t have the ui to be able to control the leds individually, so it’s indeed limited to choosing one colour for the whole strip.

however apart from the 6 determined colour icons, you should be able to click on any colour on the RGB/colour temperature wheel to choose any colour?

**Comment by michaelromero2020** [comment]
Ah thanks for that. The color wheel is helpful! 

Do you know the logic for color selection when you set up an automation? Does it turn to the color profile that was active when the automation was set up? 

Example: I've had them on with Gradient color "A" and the automation is set for 7 pm. When 7 pm hits, it turns the color to an entirely different gradient color scheme.

**Comment by bwp91** [comment]
An automation setup by the home app will define the:

- state to set to (on/off)
- brightness to set to
- colour to set to

there is no way to just define one characteristic (for example JUST turn on, and leave the brightness and colour as it were before).

You can see (and change) the brightness and colour that the device will change to by long pressing the light on the automation screen.

If you are looking to JUST turn on the light (and for it to not change brightness and colour) then you may want to consider using the Eve HomeKit app (it's free) which let's you create scenes defining **just** state (on/off) and/or brightness and/or colour. It gives more control with defining scenes than the Home app does.

You can then use the Home app to implement this scene within the automation, so hopefully achieving what you're aiming to do.

**Comment by cumanzor** [comment]
Is it possible to have the plug in select Video Mode settings (Part/All, Game,Movie, Saturation)?

**Comment by bwp91** [comment]
> Is it possible to have the plug in select Video Mode settings (Part/All, Game,Movie, Saturation)?

Is this for a TV LED strip?

The plugin can’t select different values that different modes offer. But it might be able to mimic a pre-set mode using the AWS connection, is this something you have exploded?

My strip doesn’t have this feature so video modes is something i haven’t checked.

**Comment by cumanzor** [comment]
Yeah it's for the Govee Immersion TV Lights, I haven't used the AWS connection mode yet, I'll explore that and let you know, thanks!

**Comment by bwp91** [comment]
You may find these instructions (follow them for the AWS code) work just as well for video modes:

https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes
