### ISSUE TITLE
Feedback - wiki not up to date with latest supported devices

### ISSUE THREAD

**Issue by benwebbbenwebb** [bwp91/homebridge-govee#839]
Hi @bwp91 

Love the plugin, thanks so much.

Quick feedback, looks like the wiki [Supported Devices](https://github.com/bwp91/homebridge-govee/wiki/Supported-Devices) page isn't up to date with the list of devices you have in [constants.js](https://github.com/bwp91/homebridge-govee/blob/latest/lib/utils/constants.js).

I was going to offer to try and update the wiki, but looks like PRs on Github wiki pages aren't possible. 😞 Maybe a note on the top of the wiki page to say it's not exhaustive, that the page isn't updated as often as the plugin and even if your device isn't listed to give it a go (and raise a Model Request only if it doesn't work?).

Example: H6099 isn't listed on the wiki but is supported, e.g. #659 / fe9e368

Thanks again!

**Comment by bwp91** [comment]
phew that was crazy to update 😅

but all done: https://github.com/bwp91/homebridge-govee/wiki/Supported-Devices

**Comment by benwebbbenwebb** [comment]
Nice one, thanks @bwp91!

Great work
