### ISSUE TITLE
Is Homebridge v2 Supported?

### ISSUE THREAD

**Issue by moshevayner** [bwp91/homebridge-govee#841]
Hey there!

I just noticed this popup on my HB UI prepping for the upcoming v2 release. 
It appears that there are some breaking changes, so I just wanted to make sure that we shouldn't expect any issues with the plugin after upgrading to the new release? 
They have more info [here](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2).

Thanks!!

**Comment by bwp91** [comment]
Yep it is from plugin v10.8.1 onwards 👍
