### ISSUE TITLE
sync failed as no data received from Govee server

### ISSUE THREAD

**Issue by wheeler01** [bwp91/homebridge-govee#846]
I have 2 Govee devices which until the last 72 hours were working fine with my installation of Homebridge UX ver [v1.8.4] · [UI v4.56.4].

I started receiving the following error:

 [HTTP] sync failed as no data received from Govee server whilst obtaining devices at default.getDevices (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:162:15).

I am running version 10.9.2 of the plugin.

I am running NodeJS ver 20.16.0

Any help would be appreciated. Thank you.

**Comment by bwp91** [comment]
it might have just been the govee server having a moment, have you tried restarting the plugin,

**Comment by wheeler01** [comment]
I had tried restarting the plug-in a couple of times. The problem persisted. I restarted HomeBridge today. The issue does not seem to be repeating itself. Thank you for the assistance.
