### ISSUE TITLE
Error when updating: npm ERR! Invalid or unexpected token

### ISSUE THREAD

**Issue by d2ustin** [bwp91/homebridge-govee#85]
### What issue do you have? Please be as thorough and explicit as possible.
When updating via the update button I'm getting "npm ERR! Invalid or unexpected token"

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi
Node.js Version | v14.17.3
NPM Version | v6.14.13

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v3.3.1 trying to upgrade 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
n/a

### Please paste any relevant logs below.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-govee@latest'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose stack /usr/local/lib/node_modules/npm/node_modules/flush-write-stream/node_modules/readable-stream/readable.js:2
4 verbose stack ^Dtzid"�u
4 verbose stack ^
4 verbose stack
4 verbose stack SyntaxError: Invalid or unexpected token
4 verbose stack     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:1049:27)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:950:32)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:974:19)
4 verbose stack     at require (internal/modules/cjs/helpers.js:92:18)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/flush-write-stream/index.js:1:14)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:1085:14)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:950:32)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:974:19)
4 verbose stack     at require (internal/modules/cjs/helpers.js:92:18)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/mississippi/index.js:9:21)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:1085:14)
5 verbose cwd /usr/local
6 verbose Linux 5.4.79-v7+
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-govee@latest"
8 verbose node v14.17.3
9 verbose npm  v6.14.13
10 error Invalid or unexpected token
11 verbose exit [ 1, true ]
(END)
```

**Comment by bwp91** [comment]
Hi @d2ustin 

Can you try running this in the homebridge terminal:

`sudo npm cache clean --force`

then try the update again?

**Comment by d2ustin** [comment]
Hey there, so I'm actually getting the same error? Is this not plugin related or is it something with home bridge itself?  here's the log: 

..
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'cache',
1 verbose cli   'clean',
1 verbose cli   '--force'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 warn using --force I sure hope you know what you are doing.
5 verbose stack /usr/local/lib/node_modules/npm/node_modules/flush-write-stream/node_modules/readable-stream/readable.js:2
5 verbose stack ^Dtzid"�u
5 verbose stack ^
5 verbose stack
5 verbose stack SyntaxError: Invalid or unexpected token
5 verbose stack     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
5 verbose stack     at Module._compile (internal/modules/cjs/loader.js:1049:27)
5 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
5 verbose stack     at Module.load (internal/modules/cjs/loader.js:950:32)
5 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
5 verbose stack     at Module.require (internal/modules/cjs/loader.js:974:19)
5 verbose stack     at require (internal/modules/cjs/helpers.js:92:18)
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/flush-write-stream/index.js:1:14)
5 verbose stack     at Module._compile (internal/modules/cjs/loader.js:1085:14)
5 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
5 verbose stack     at Module.load (internal/modules/cjs/loader.js:950:32)
5 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
5 verbose stack     at Module.require (internal/modules/cjs/loader.js:974:19)
5 verbose stack     at require (internal/modules/cjs/helpers.js:92:18)
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/mississippi/index.js:9:21)
5 verbose stack     at Module._compile (internal/modules/cjs/loader.js:1085:14)
6 verbose cwd /var/lib/homebridge
7 verbose Linux 5.4.79-v7+
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "cache" "clean" "--force"
9 verbose node v14.17.3
10 verbose npm  v6.14.13
11 error Invalid or unexpected token
12 verbose exit [ 1, true ]
(END)
,,

**Comment by bwp91** [comment]
It’s neither the plugin nor homebridge. it’s to do with npm, the software that installs and maintains the plugins and homebridge package too.

I think it has messed up saving a file from one of the dependencies of govee plugin.

Happy to try and solve this with you, are you on the homebridge discord server at all?

**Comment by d2ustin** [comment]
I just joined @dclt

**Comment by bwp91** [comment]
For future reference. was an npm issue.

Solved by reinstalling npm (using hb-service update-node)
