### ISSUE TITLE
Unable to connect to Govee Immersion (H6199) via Homebridge (accessory.setCharacteristic is not a function at GoveePlatform.addAccessory)

### ISSUE THREAD

**Issue by henry-bettany** [bwp91/homebridge-govee#86]
### What issue do you have? Please be as thorough and explicit as possible.
I can't get Homebridge to see/connect to my Govee Immersion (H6199) lights. I've got a fresh install of Homebridge and this plugin, but when I restart Homebridge having installed your plugin, I get an error (see the logs at the end of this issue).

If I try to get the status of my Govee lights using a Postman request (via https://developer-api.govee.com/v1/devices/state?device=<REDACTED>&model=H6199, using the device ID I've entered in Homebridge), I get the properties of the device as expected.

The name of the device in the logs matches the name I've set in the app, so it is able to get "something". 

### Details of your setup.
* **Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?** 
Homebridge UI-X

* **Which version of Homebridge/HOOBS do you have?**
Homebridge v1.3.4

* **Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.**
Raspberry Pi 3B+
Node v14.17.2
npm v6.14.13

* **Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?**
v3.5.0 (2021-07-14) - fresh install/first time use.

* **Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.**
N/A

### Please paste any relevant logs below.

```
[14/07/2021, 16:22:53] Homebridge v1.3.4 (Govee) is running on port 53274.
[14/07/2021, 16:22:55] [Govee] Disabling BLE client as no enabled devices configured at GoveePlatform.pluginSetup (/usr/lib/node_modules/homebridge-govee/lib/index.js:310:17).
[14/07/2021, 16:22:55] [Govee] {
  device: '<REDACTED>',
  sku: 'H6199',
  spec: '',
  versionHard: '3.02.01',
  versionSoft: '1.01.07',
  deviceName: 'TV Lights',
  deviceExt: {
    deviceSettings: '{"wifiName":"<REDACTED>","address":"<REDACTED>","bleName":"Govee_H6199_7A54","topic":"GD/<REDACTED>","wifiMac":"<REDACTED>","pactType":2,"pactCode":1,"wifiSoftVersion":"1.00.17","wifiHardVersion":"1.03.00","ic":0,"sku":"H6199","device":"<REDACTED>","deviceName":"TV Lights","versionHard":"3.02.01","versionSoft":"1.01.07"}',
    lastDeviceData: '{"online":false}',
    extResources: '{"skuUrl":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/c7c85fa99c8ac95399bc192f1058d684-add_list_type_device_6199.png","headOnImg":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/0c4a991d6c7be105fd5e0c2ffeee482f-new_light_title_6104_alexa_on.png","headOffImg":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/693e1b2cd0f89e39b4601dba37d23098-new_light_title_6104_alexa_off.png","ext":"","ic":0}'
  },
  pactType: 2,
  pactCode: 1,
  goodsType: 24
}
[14/07/2021, 16:22:55] [Govee] [TV Lights] could not be added to Homebridge as accessory.setCharacteristic is not a function at GoveePlatform.addAccessory (/usr/lib/node_modules/homebridge-govee/lib/index.js:628:17).
[14/07/2021, 16:22:55] [Govee] [TV Lights] could not be initialised as accessory not found at GoveePlatform.initialiseDevice (/usr/lib/node_modules/homebridge-govee/lib/index.js:472:15).
```

**Comment by bwp91** [comment]
Please try v3.5.1 I have just released it!

**Comment by henry-bettany** [comment]
Thanks for the quick response and fix, that works now!
