### ISSUE TITLE
Support for new Bluetooth device - H5075

### ISSUE THREAD

**Issue by andreinanu** [bwp91/homebridge-govee#88]
Hi there, 

As described in the logs, I'm opening an issue with the following (not supported) devices (I have two of them):

```
[20/07/2021, 16:40:25] [Govee] [Kitchen Thermometer] is not currently supported, do create a Github issue with the following info:
[20/07/2021, 16:40:25] [Govee] {
  device: '72:60:A4:C1:38:49:1B:79',
  deviceName: 'Kitchen Thermometer',
  model: 'H5075',
  httpInfo: {
    device: '72:60:A4:C1:38:49:1B:79',
    sku: 'H5075',
    spec: '',
    versionHard: '1.00.02',
    versionSoft: '1.00.02',
    deviceName: 'Kitchen Thermometer',
    deviceExt: {
      deviceSettings: '{"temMin":2100,"temMax":2400,"temWarning":true,"fahOpen":false,"temCali":0,"humMin":3500,"humMax":6000,"humWarning":true,"humCali":0,"netWaring":true,"uploadRate":10,"battery":41,"wifiLevel":0,"bleName":"GVH5075_1B79","address":"A4:C1:38:49:1B:79","sku":"H5075","device":"72:60:A4:C1:38:49:1B:79","deviceName":"Kitchen Thermometer","versionHard":"1.00.02","versionSoft":"1.00.02"}',
      lastDeviceData: '{"online":false,"tem":2180,"hum":4890,"lastTime":1620041520000,"avgDayTem":2180,"avgDayHum":4890}',
      extResources: '{"skuUrl":"","headOnImg":"","headOffImg":"","ext":"","ic":0}'
    },
    goodsType: 0
  },
  isAPIDevice: false
} 
```

```
[20/07/2021, 16:40:25] [Govee] [Bedroom Thermometer] is not currently supported, do create a Github issue with the following info:
[20/07/2021, 16:40:25] [Govee] {
  device: 'BF:D0:A4:C1:38:77:0A:CB',
  deviceName: 'Bedroom Thermometer',
  model: 'H5075',
  httpInfo: {
    device: 'BF:D0:A4:C1:38:77:0A:CB',
    sku: 'H5075',
    spec: '',
    versionHard: '1.00.02',
    versionSoft: '1.00.02',
    deviceName: 'Bedroom Thermometer',
    deviceExt: {
      deviceSettings: '{"temMin":-2000,"temMax":6000,"temWarning":false,"fahOpen":false,"temCali":0,"humMin":0,"humMax":10000,"humWarning":false,"humCali":0,"netWaring":true,"uploadRate":10,"battery":87,"wifiLevel":0,"bleName":"GVH5075_0ACB","address":"A4:C1:38:77:0A:CB","sku":"H5075","device":"BF:D0:A4:C1:38:77:0A:CB","deviceName":"Bedroom Thermometer","versionHard":"1.00.02","versionSoft":"1.00.02"}',
      lastDeviceData: '{"online":false,"tem":1740,"hum":6690,"lastTime":1620041520000,"avgDayTem":1740,"avgDayHum":6690}',
      extResources: '{"skuUrl":"","headOnImg":"","headOffImg":"","ext":"","ic":0}'
    },
    goodsType: 0
  },
  isAPIDevice: false
}
```

Cheers!
Andrei

**Comment by bwp91** [comment]
It was under my impression that the H5075 was bluetooth only!

But from the data here it looks like I can use these values for a temperature sensor and a humidity sensor. The plugin will poll every 15 seconds for new data but not sure how 'up to date' this will be from the device.

Please install beta version 3.6.1-beta.0 to check it is working well

**Comment by andreinanu** [comment]
@bwp91 thanks for the quick response! I've installed the beta version and the devices are exposed to HomeKit as designed.
The only issue that I see for now, is that the readings are not accurate (neither temp or humidity).
I appreciate seeing the battery level though, it's a nice touch!

Let me know please if I can help with additional feedback for these devices along the way.

In case it helps for future development & adjustments - I normally use this plugin to connect to them - https://github.com/asednev/homebridge-plugin-govee.

**Comment by bwp91** [comment]
Ah, it's a shame the temperature and humidity don't seem accurate... makes me wonder how accurate the battery reading is 😛 

Do these devices have a wifi connection at all? Do they upload their historical reading data straight to the cloud or like via bluetooth to a phone to the cloud...

I wonder if the measurements available that the plugin obtains via the cloud are only 'updated' when the phone is connected to the device via bluetooth.

Who knows!

Well if these extra accessories get in the way you can use the config to get them removed and ignored from homebridge.

**Comment by andreinanu** [comment]
@bwp91 I believe that the data is polled only by the phone via BT. Nevertheless, thanks for the interest and the hard work, much appreciated.

Cheers!
