### ISSUE TITLE
H6159 Brightness 70%

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-govee#9]
Hi Ben, with the last release again issue with Brightness 
Now not yet at 39% but goes to 70% @bwp91

**Comment by bwp91** [comment]
Hiya, so just to confirm, which "direction" are we talking about, ie,
* if you set the brightness via homebridge/home app to 100% is shows as 70% in govee app?
* Or if you set the brightness in govee to 100% in govee it shows as 70% in home app?
Thanks

**Comment by Stetocasa** [comment]
> Hiya, so just to confirm, which "direction" are we talking about, ie,
> * if you set the brightness via homebridge/home app to 100% is shows as 70% in govee app?
> * Or if you set the brightness in govee to 100% in govee it shows as 70% in home app?
> Thanks 

Second one
I set 100% on hk and when the automation run the brightness go to 70

**Comment by bwp91** [comment]
> when the automation run

A HomeKit automation?

**Comment by Stetocasa** [comment]
> > when the automation run
> 
> 
> 
> A HomeKit automation? 

Yes, when door sensor triggered, light on

**Comment by bwp91** [comment]
And definitely the automation isn't setting the light to 70%?

Could you do me a favour:

1. In the plugin settings in the optional section, turn on "Debug Logging" and "Request & Response Logging"
2. Restart Homebridge
3. Start copying the Homebridge logs whilst you:
  * Through the home app turn the brightness to 100%
  * Then run the automation
4. End copying the Homebridge logs at this point

And post the logs here?
