### ISSUE TITLE
H6141 Bluetooth Support - able to test

### ISSUE THREAD

**Issue by ThisIsNoahEvans** [bwp91/homebridge-govee#90]
Hey there, I have two of the `H6141` LED strips from Govee. As your wiki says [here](https://github.com/bwp91/homebridge-govee/wiki/Supported-Devices#lights-bluetooth), they're not currently able to be controlled through Bluetooth but can be tested and added.

**I'm more than happy to attempt to test these with Bluetooth functionality so they can be added to the list.** I'm running Homebridge on a Raspberry Pi 3A+, and it's just a few metres from my lights so Bluetooth should work a charm :)

**Comment by bwp91** [comment]
Just published 3.7.1-beta.1, could you update to this? It has the H6141 added to list of bt-only devices.

Don't forget to add an entry for your light in the configuration and explicitly enable bluetooth.

If things don't work well at first then having plugin debug logging can help too.

It seems the raspberry pi has been the most successful platform for users to get the bluetooth working :)

Good luck and let me know!

**Comment by ThisIsNoahEvans** [comment]
It works wonderfully! Much much faster, through the Home app and through my HomePod. 
```
[27/07/2021, 12:54:10] [Govee] [Light Strip Left] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"enableAWS":"disabled","enableBT":"disabled","logging":"debug"}.
[27/07/2021, 12:54:10] [Govee] [Light Strip Left] initialised with id [2A:3E:A4:C1:38:E0:7F:A7].
[27/07/2021, 12:54:10] [Govee] [Light Strip Right] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"enableAWS":"disabled","enableBT":"disabled","logging":"debug"}.
[27/07/2021, 12:54:10] [Govee] [Light Strip Right] initialised with id [03:1C:A4:C1:38:23:A2:B5].
```

**Thank you! Love the plugin :)**

**Comment by bwp91** [comment]
Nice to hear it’s actually working for someone 🤣

You could look into scene support with bluetooth codes:

https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

**Comment by ThisIsNoahEvans** [comment]
Actually trying to sort out scenes with AWS codes now, but the Govee app won't connect to my lights over WiFi (everything else incl. Homebridge works fine. Could be an iOS 15 beta thing.)
I'll have a look into Bluetooth codes and hope for better luck there, haha

**Comment by bwp91** [comment]
I've just realises the H6141 is wifi too, so I didn't actually need to make changes to the plugin for you to get it to work, only to enable bluetooth control via the settings!

Sometimes I can get my lights to connect to wifi by first opening govee app with bluetooth on so it connects via bluetooth, then with the govee app open, use the control centre to turn phone bluetooth off.

> but the Govee app won't connect to my lights over WiFi

I think it's more an issue with the wifi connection of the lights, they can sometimes seem a bit lazy!

**Comment by ThisIsNoahEvans** [comment]
Probably me missing something obvious...but shouldn't I see the six different options after expanding `Custom Scenes/Modes`? 
![image](https://user-images.githubusercontent.com/35865874/127159189-3eea9201-b822-40f6-930b-18de59ebb062.png)

I don't have any options for Bluetooth or AWS above - as the custom scenes description says - though, which further confuses me 😂
![image](https://user-images.githubusercontent.com/35865874/127203712-83e1b079-ddab-462f-a46a-4aa3d1f969c3.png)

**Comment by bwp91** [comment]
Have you entered the device id correctly? Options will show and hide depending on whether the initial values are correct.
The options for lights appear when the device id is 23 characters long, eg `2A:3E:A4:C1:38:E0:7F:A7`
