### ISSUE TITLE
H6171 - Device is not currently supported.

### ISSUE THREAD

**Issue by rlabiak** [bwp91/homebridge-govee#91]
Hello,

I am using Homebridge version 4.41.1, Node.js version 14.17.3, Npm version 7.20.2, Homebridge Govee Plugin version 3.8.0 (Homebridge is running on an Ubuntu 20.04 vm). Logs are posted below. Please let me know if there is anything I can do to help (while I am not a programmer I am more than happy to test or provide more logs etc).

[Govee] [Deck Lights - East] is not currently supported, do create a Github issue with the following info:
[2021-07-28, 4:42:33 p.m.] [Govee] {
  device: 'F7:A4:A4:C1:38:AE:D6:FB',
  deviceName: 'Deck Lights - East',
  model: 'H6171',
  httpInfo: {
    device: 'F7:A4:A4:C1:38:AE:D6:FB',
    sku: 'H6171',
    spec: '',
    versionHard: '1.00.01',
    versionSoft: '1.06.03',
    deviceName: 'Deck Lights - East',
    deviceExt: {
      deviceSettings: '{"address":"A4:C1:38:AE:D6:FB","bleName":"ihoment_H6171_D6FB","pactType":1,"pactCode":1,"ic":60,"sku":"H6171","device":"F7:A4:A4:C1:38:AE:D6:FB","deviceName":"Deck Lights - East","versionHard":"1.00.01","versionSoft":"1.06.03"}',
      lastDeviceData: '{"online":false}',
      extResources: '{"skuUrl":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/03139f2d7f7485795456cf0912179a6c-add_list_type_device_6171.png","headOnImg":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/046746fb6a9e6e302f315d8d19f99e07-new_light_title_eaves_rgbic_on.png","headOffImg":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/4b1a91316faebe523e645a0a895c476e-new_light_title_eaves_off.png","ext":"","ic":60}'
    },
    pactType: 1,
    pactCode: 1,
    goodsType: 13
  },
  isAPIDevice: false
}

**Comment by bwp91** [comment]
Hi @rlabiak 
Is bluetooth support something that you think might work from your homebridge instance?

**Comment by rlabiak** [comment]
I actually have a bluetooth receiver coming today, that I plan on passing through to the vm, so after some testing on my end it should work. The worst case scenario would be me just migrating my homebridge instance to a raspberry pi or something similar.

**Comment by bwp91** [comment]
I have just released a beta version of the plugin, 3.8.1-beta.0, which has the H6171 added to the bluetooth only supported model list.

you'll need to add a config entry with your device id `F7:A4:A4:C1:38:AE:D6:FB` and ticking the 'enable bluetooth' option.

Also for reference, the plugin uses this package:, for bluetooth control and there may be some extra steps to get it to work on your machine.
https://github.com/abandonware/noble#installation

Good luck and let me know how you get on :)

**Comment by rlabiak** [comment]
awesome, I will test it out shortly. Thanks so much :), hopefully the bluetooth receiver has enough of a range.

**Comment by rlabiak** [comment]
so bluetooth is working on my ubuntu 20.04 homebridge vm, it can see the light strip but currently working out how to force it to pair.

**Comment by bwp91** [comment]
Do you have the 'Device Safety' option turned on in the govee app?

In all the cases I have known so far... the homebridge instance _just_ pairs with the device... never known it to not pair 'out of the box'

**Comment by bwp91** [comment]
Also make sure you don’t have the govee app open on your phone so the light isn’t connected to your phone. i would test disabling bluetooth on your phone

**Comment by rlabiak** [comment]
Nope, device safety is off, the app was closed but I never "force closed the app" so I can try just disabling bluetooth.

**Comment by rlabiak** [comment]
still no dice.

**Comment by bwp91** [comment]
Can you post some logs with debug mode on trying to control the device?

**Comment by rlabiak** [comment]
let me see if I can figure out how to get logs for bluetooth on ubuntu

**Comment by bwp91** [comment]
I did mean homebridge logs!

**Comment by rlabiak** [comment]
let me see if the device shows up in homebridge.

**Comment by rlabiak** [comment]
so i see the lights in homebridge, but not in homekit. working on getting debug mode turned on

**Comment by rlabiak** [comment]
ok light strip is registering in homekit.. now for the debug logs.

**Comment by bwp91** [comment]
in the plugin settings -> optional settings -> Debug Logging.

**Comment by bwp91** [comment]
I’ve just realised what you might have been doing.
You don’t need to pair the device with your homebridge— the plugin will do it on the go

**Comment by rlabiak** [comment]
so the device doesnt necessarily need to pair with the vm then?

**Comment by rlabiak** [comment]
[2021-07-29, 3:52:42 p.m.] [Govee] [noble] scanning started.
[2021-07-29, 3:52:42 p.m.] [Govee] [noble] scanning stopped.
[2021-07-29, 3:52:42 p.m.] [Govee] [Deck Lights - East] has been reported [discoverable] via BLE.
[2021-07-29, 3:52:43 p.m.] [Govee] [Deck Lights - East] has been reported [connected] via BLE.
[2021-07-29, 3:52:44 p.m.] [Govee] [Deck Lights - East] [BLE] sending update {5: [2,255,230,210]}.
[2021-07-29, 3:52:44 p.m.] [Govee] [Deck Lights - East] current colour [5100K / 198M] via adaptive lighting.
[2021-07-29, 3:52:46 p.m.] [Govee] [noble] scanning started.
[2021-07-29, 3:52:54 p.m.] [Govee] [Deck Lights - East] not sending AWS update as not available or enabled at /usr/lib/node_modules/homebridge-govee/lib/index.js:972:19.
[2021-07-29, 3:52:54 p.m.] [Govee] [Deck Lights - East] [BLE] sending update {1: 0}.
[2021-07-29, 3:52:54 p.m.] [Govee] [noble] scanning started.
[2021-07-29, 3:52:55 p.m.] [Govee] [Deck Lights - East] current state [off].
[2021-07-29, 3:53:07 p.m.] [Govee] [Deck Lights - East] has been reported [disconnected] via BLE.
[2021-07-29, 3:53:12 p.m.] [Govee] [noble] scanning stopped.
[2021-07-29, 3:53:22 p.m.] [Govee] [noble] scanning stopped.
[2021-07-29, 3:53:33 p.m.] [Govee] [noble] scanning stopped.
[2021-07-29, 3:53:42 p.m.] [Govee] [Deck Lights - East] skipping adaptive lighting update as device is off or kelvin is same as before [5100K / 198M].
[2021-07-29, 3:53:44 p.m.] [Govee] [noble] scanning stopped.

**Comment by rlabiak** [comment]
apparently it is working :D.. disabled bluetooth on my phone and it is still turning off / on.. this makes me very happy :)

**Comment by bwp91** [comment]
That looks to me like it's working?

With each command, the plugin will search...connect...send...disconnect. You don't need to manually pair the device with your ¡homebridge machine'

**Comment by rlabiak** [comment]
that being said, cpu usage for the vm is now consistently high even while running it as a child bridge.. that may change after I turn debugging off.

**Comment by rlabiak** [comment]
thank you, I appreciate the changes you made for me very much!

**Comment by rlabiak** [comment]
there shouldnt be an issue pairing a second light strip via this method correct?

**Comment by bwp91** [comment]
> there shouldnt be an issue pairing a second light strip via this method correct?

should be no issue at all, since the plugin is designed to connect... send command and disconnect... multiple light strips are fine.

The plugin uses a queue to send device updates one at a time, so there will never be a time that the plugin tries to connect to two devices at the same time.

> thank you, I appreciate the changes you made for me very much!

glad it's useful!

**Comment by rlabiak** [comment]
now im just trying to remember how I got the device id the first time.. govee home app leaves a lot to be desired....

**Comment by bwp91** [comment]
restart the plugin and check the homebridge logs. all your devices (in your govee account) will be listed with device id

**Comment by rlabiak** [comment]
thanks :)
