### ISSUE TITLE
Device Request: H61E5 - COB Strip Light

### ISSUE THREAD

**Issue by guildo-h0rn** [bwp91/homebridge-govee#914]
Hi,

is support for COB Strip Light planed from your site? Looking foward!

[COB Strip Light] is not currently supported, do create a Github issue with the following info:
{"device":"1C:59:D4:0F:46:06:10:66","deviceName":"COB Strip Light","model":"H61E5","httpInfo":{"groupId":0,"device":"1C:59:D4:0F:46:06:10:66","sku":"H61E5","spec":"","versionHard":"3.05.00","versionSoft":"1.00.10","deviceName":"COB Strip Light","deviceExt":{"deviceSettings":"{\"wifiName\":\"GAP\",\"address\":\"D4:0F:46:06:10:66\",\"bleName\":\"Govee_H61E5_1066\",\"topic\":\"GD/8dbe16c4ffd7359715bf35fab0497249\",\"wifiMac\":\"D0:C9:07:9A:E3:A8\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.01.17\",\"wifiHardVersion\":\"1.04.01\",\"ic\":36,\"secretCode\":\"k64j+LHx55E=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H61E5\",\"device\":\"1C:59:D4:0F:46:06:10:66\",\"deviceName\":\"COB Strip Light\",\"versionHard\":\"3.05.00\",\"versionSoft\":\"1.00.10\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/decf978a0df472abc82b7ac8aa8b9a47-add_list_type_device_61e5.png\",\"headOnImg\":\"\",\"headOnImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/363f43f15b4a541b4008d85c6a2c4a64-light_pics_61e5e6_on.png\",\"headOffImg\":\"\",\"headOffImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/22bf9eb6791678e031f4653059ed5e87-light_pics_61e5e6_off.png\",\"ext\":\"\",\"ic\":36}"},"pactType":1,"pactCode":1,"share":0,"deviceId":24400208,"gidConfirmed":true,"goodsType":239,"attributesId":103,"supportScene":0}}

**Comment by Dontodtod** [comment]
Hi,

Same issue here:

{"device":"0A:DF:D0:C8:02:06:0F:57","deviceName":"COB Strip Light","model":"H61E5","httpInfo":{"groupId":0,"device":"0A:DF:D0:C8:02:06:0F:57","sku":"H61E5","spec":"","versionHard":"3.05.00","versionSoft":"1.00.10","deviceName":"COB Strip Light","deviceExt":{"deviceSettings":"{\"wifiName\":\"YOUGHAL5G\",\"address\":\"D0:C8:02:06:0F:57\",\"bleName\":\"Govee_H61E5_0F57\",\"topic\":\"GD/b63f44998de5611f4234fc8ebe5cec5c\",\"wifiMac\":\"D0:C9:07:75:6F:98\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.01.17\",\"wifiHardVersion\":\"1.04.01\",\"ic\":36,\"secretCode\":\"FHB/Z62poPg=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H61E5\",\"device\":\"0A:DF:D0:C8:02:06:0F:57\",\"deviceName\":\"COB Strip Light\",\"versionHard\":\"3.05.00\",\"versionSoft\":\"1.00.10\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/decf978a0df472abc82b7ac8aa8b9a47-add_list_type_device_61e5.png\",\"headOnImg\":\"\",\"headOnImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/363f43f15b4a541b4008d85c6a2c4a64-light_pics_61e5e6_on.png\",\"headOffImg\":\"\",\"headOffImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/22bf9eb6791678e031f4653059ed5e87-light_pics_61e5e6_off.png\",\"ext\":\"\",\"ic\":36}"},"pactType":1,"pactCode":1,"share":0,"deviceId":24501860,"gidConfirmed":true,"goodsType":239,"attributesId":103,"supportScene":0}}

Many thanks,

**Comment by guildo-h0rn** [comment]
With the new Update on v10.10.0 is it working, tanks you a lot!
