### ISSUE TITLE
H6127 not currently supported. Details as requested in log

### ISSUE THREAD

**Issue by Subivan1** [bwp91/homebridge-govee#92]
[Govee] [Study Led] is not currently supported, do create a Github issue with the following info:
[29/07/2021, 11:33:29] [Govee] {
  device: 'abee96bd0fe2dc98',
  deviceName: 'Study Led',
  model: 'H6127',
  httpInfo: {
    device: 'abee96bd0fe2dc98',
    sku: 'H6127',
    spec: '',
    versionHard: '1.00.03',
    versionSoft: '1.06.10',
    deviceName: 'Study Led',
    deviceExt: {
      deviceSettings: '{"address":"A4:C1:38:00:7F:D9","bleName":"ihoment_H6127_7FD9","pactType":1,"pactCode":1,"ic":50,"sku":"H6127","device":"abee96bd0fe2dc98","deviceName":"Study Led","versionHard":"1.00.03","versionSoft":"1.06.10"}',
      lastDeviceData: '{"online":false}',
      extResources: '{"skuUrl":"","headOnImg":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png","headOffImg":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png","ext":"","ic":50}'
    },
    pactType: 1,
    pactCode: 1,
    goodsType: 0
  },
  isAPIDevice: false
}

**Comment by bwp91** [comment]
Hi @Subivan1 

Thanks for this. What platform are you running homebridge on? Would you be interested in the bluetooth control (it can sometimes take a bit of extra manual setup)?

**Comment by Subivan1** [comment]
Hi,  
I am using a raspberry pi 3+  Homebridge UI, And I think I am up to date on Node etc.
Yes I would be interested in Bluetooth control and I am happy to give the extra setup a go and play around with things.

Cheers
Mike

Cheers

**Comment by bwp91** [comment]
Can you update to beta version of the plugin, v3.8.1-beta.1 and then use the plugin settings screen to add an entry for your lights in the 'Light Devices' section.

Use device ID `AB:EE:96:BD:0F:E2:DC:98`.

And tick the "Enable BLE" box.

It might also be worth ticking the 'Debug Logging' box in the optional settings just until you get it to work.

Restart the plugin and the device should be added to homebridge. You can try to control it from the home app, if it doesn't work then the homebridge log should offer a reason why not.

There may be a couple of commands you need to run in the homebridge terminal, try this if it doesn't initially work:

https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control

Let me know how you get on!

**Comment by Subivan1** [comment]
I will give that a go this evening. I will let you know how I get on.

**Comment by Subivan1** [comment]
everything worked on the Beta and have now updated to latest release and everything is still fine. Thanks very much.

**Comment by Subivan1** [comment]
Brilliant response and update works fine.
