### ISSUE TITLE
H6125 Support

### ISSUE THREAD

**Issue by nealbuff** [bwp91/homebridge-govee#93]
* **Please explain your feature request in a one or two sentences.**

Hello, I've just tried to add a device but it seems Govee H6125 is not currently supported. Would it be possible to add please?

Thanks.

device: 'redacted',
  deviceName: 'RBIC Light strip',
  model: 'H6125',
  httpInfo: {
    device: 'redacted',
    sku: 'H6125',
    spec: '',
    versionHard: '1.00.04',
    versionSoft: '1.07.01',
    deviceName: 'RBIC Light strip',
    deviceExt: {
      deviceSettings: '{"address":"redacted","bleName":"ihoment_H6125_FAF3","pactType":1,"pactCode":1,"ic":50,"sku":"H6125","device":"BD:redacted","deviceName":"RBIC Light strip","versionHard":"1.00.04","versionSoft":"1.07.01"}',
      lastDeviceData: '{"online":false}',
      extResources: '{"skuUrl":"","headOnImg":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/7497e9e37fb1d7461581173195ffcf3e-new_light_title_home_on.png","headOffImg":"https://d1f2504ijhdyjw.cloudfront.net/sku-img/871d58cc47b99af39dead92abd2acd01-new_light_title_home_off.png","ext":"","ic":50}'
    },
    pactType: 1,
    pactCode: 1,
    goodsType: 0
  },
  isAPIDevice: false
}

**Comment by nealbuff** [comment]
Thanks - the device is now showing up, but I'm getting a log when the plugin starts saying "Disabling BLE client as required packages not available", but I've gone through the notes and I think I have all the required packages installed. Anything you think I might be missing?

**Comment by bwp91** [comment]
it seems that a package that is installed with the plugin hasn't been installed properly,

From the homebridge terminal, can you run this command and copy and paste all the output here? It might be quite a few lines.

```
sudo npm i -g homebridge-govee@beta
```

**Comment by nealbuff** [comment]
yep:

pi@raspberrypi:~ $ sudo npm i -g homebridge-govee@beta
npm WARN deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

added 6 packages, removed 7 packages, changed 128 packages, and audited 135 packages in 52s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by nealbuff** [comment]
In fact - it's just started working! Thanks for your quick responses!

**Comment by bwp91** [comment]
Excellent! enjoy!
