### ISSUE TITLE
H5080 not being detected

### ISSUE THREAD

**Issue by timmeade** [bwp91/homebridge-govee#95]
### What issue do you have? Please be as thorough and explicit as possible.
Just installed an H5080.  Works fine from the Govee App.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge 1

* Which version of Homebridge/HOOBS do you have?
8095

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Mac Mini

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v4.2.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H5080

### Please paste any relevant logs below.

I see this in the logs:   Says please open a github issue:

```
[8/4/2021, 3:31:23 PM] [Govee] Disabling API client as API key not provided.
[8/4/2021, 3:31:23 PM] [Govee] Disabling BLE client as no enabled devices configured.
[8/4/2021, 3:31:23 PM] [Govee] [Desk Plug] could not be initialised as Cannot read property '59:EF:7C:A6:B0:66:A4:3D' of undefined at GoveePlatform.initialiseDevice (/Users/tim/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-govee/lib/index.js:483:29).
[8/4/2021, 3:31:23 PM] [Govee] [Temp Office] is not currently supported, do create a Github issue with the following info:
```

```
{
   "device":"53:20:A4:C1:38:17:D7:66",
   "deviceName":"Temp Office",
   "model":"H5101",
   "httpInfo":{
      "device":"53:20:A4:C1:38:17:D7:66",
      "sku":"H5101",
      "spec":"",
      "versionHard":"1.00.01",
      "versionSoft":"1.00.02",
      "deviceName":"Temp Office",
      "deviceExt":{
         "lastDeviceData":"{}",
         "deviceSettings":"{\"ic\":0,\"device\":\"53:20:A4:C1:38:17:D7:66\",\"address\":\"A4:C1:38:17:D7:66\",\"temWarning\":false,\"wifiLevel\":0,\"humMax\":10000,\"groupOrder\":0,\"fahOpen\":false,\"humMin\":0,\"pactCode\":0,\"netWarning\":false,\"groupRole\":0,\"sku\":\"H5101\",\"battery\":100,\"temMax\":6000,\"humWarning\":false,\"temMin\":-2000,\"deviceName\":\"Temp Office\",\"pactType\":0,\"temCali\":0,\"bleName\":\"GVH5101_D766\",\"header\":0,\"humCali\":0,\"uploadRate\":0}",
         "extResources":"{\"skuUrl\":\"http://s3.amazonaws.com/govee-public/sku-img/8323e495f4d414fb3d113fac0df0bb4a-add_list_type_device_h5101.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"
      },
      "goodsType":8
   },
   "isAPIDevice":false
}
```

The [Desk Plug] is the name and mac address of the H5080.

I have no idea what Temp Office and the other mac address is.   I wont swear there isnt something on the network that may trigger that, but i dont know of it.   We have a LOT of devices.

Thanks

**Comment by bwp91** [comment]
Hi @timmeade 

Could you install the beta version of the plugin? currently 4.2.1-beta.3.

I have fixed the issue which prevented the plug from initialising.

I've also added H5080 to the supported models list, so will now appear in Homebridge. But aren't reliable as the plugin uses the cloud to retrieve information (doesn't use bluetooth for latest values).

**Comment by bwp91** [comment]
>  I wont swear there isnt something on the network that may trigger that, but i dont know of it. We have a LOT of devices.

The plugin gets a device list from your govee account (no network scanning), do you have a temperature/humidity sensor added to your govee account?

**Comment by timmeade** [comment]
Thanks for the fast turn around.

I had added a second plug and it did not work either with release version.

After adding new beta version;

Now both DO show in homebridge.   But i cannot control them.   

These are WIFI units btw.    Not sure if that makes a difference. bluetooth seems to be only used for setup.

**Comment by bwp91** [comment]
I don't own any of the wemo outlets, neither have I known someone to have them... so the implementation has never really been tested.

Are there any messages/errors in the homebridge log when you try to control one of them?

**Comment by timmeade** [comment]
i have not received the API key from them yet.   Its been 2 days.   But here is what is in the logs:

```
[8/5/2021, 7:58:03 AM] [Govee] [Desk Plug] has been reported [offline] via API, so update may or may not be successful.
[8/5/2021, 7:58:03 AM] [Govee] [Desk Plug] not sending AWS update as not connected to AWS at connectionAWS.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/aws.js:106:13).
[8/5/2021, 7:58:03 AM] [Govee] [Desk Plug] reverting to API as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1020:17.
[8/5/2021, 7:58:03 AM] [Govee] [Desk Plug] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1020:17.
```

**Comment by bwp91** [comment]
Try requesting another API key through the govee app. It's normally instant that you get a key emailed to you.

The API connection is the 'failsafe' method if bluetooth control (for bluetooth devices) or AWS control (for AWS enabled devices) fails. I would recommend getting your (hopefully received) API key into the plugin config.

I wasn't aware of this before but the plugin seems to be detecting that these outlets are possibly controllable by AWS too. Do any messages appear in the logs if you turn it on/off with the govee app? If it is possible to control via bluetooth from the govee app, then turn bluetooth off, as we want the device to be connected to wifi for any message to appear in the homebridge log

**Comment by timmeade** [comment]
I resent for API key.  Still nothing.  

Nothing logs during the event itself:   but i did see this.

```
[8/5/2021, 8:10:55 AM] [Govee] [Desk Plug] [AWS] message event [GD/2dba031a66315678f2ddbe7a634c806a {"msg":{"transaction":"y_1628165455008681","accountTopic":"GA\/f01c3ef82c017e2d44932784cdd83854","type":0,"cmdVersion":0,"cmd":"status"}}].
[8/5/2021, 8:11:01 AM] [Govee] [Sony 4600] [AWS] reconnect event
[8/5/2021, 8:11:01 AM] [Govee] [Desk Plug] [AWS] offline event.
[8/5/2021, 8:11:01 AM] [Govee] [Desk Plug] [AWS] close event.
[8/5/2021, 8:11:01 AM] [Govee] [Sony 4600] [AWS] connected event.
```

**Comment by timmeade** [comment]
This may be event:

```
[8/5/2021, 8:12:28 AM] [Govee] [Sony 4600] has been reported [offline] via API, so update may or may not be successful.
[8/5/2021, 8:12:28 AM] [Govee] [Sony 4600] not sending AWS update as not connected to AWS at connectionAWS.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/aws.js:106:13).
[8/5/2021, 8:12:28 AM] [Govee] [Sony 4600] reverting to API as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1020:17.
[8/5/2021, 8:12:28 AM] [Govee] [Sony 4600] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1020:17.
```

**Comment by timmeade** [comment]
OK i got the API key and they are now working.  

I assume this means they will not work if the internet is offline?  Not direct?

**Comment by bwp91** [comment]
The **govee** outlets work over the cloud, this is one of the drawbacks of them compared to other brands. So yes, if you have internet problems/wifi problems or there is a govee cloud problem then the devices will not function through Homebridge (and I assume via the govee app too).

Are they controllable via bluetooth from the govee app?

**Comment by timmeade** [comment]
The app has nothing about bluetooth.   Just wifi. 

I had thought since homebridge had the ip and macaddress it could reach out direct...   I will have to look further.   

Also;  currently they are not showing up in homekit.   Might be me.  I'm new to homebridge.

**Comment by bwp91** [comment]
The device id is slightly longer than a mac address, its only use is to match any user configuration with a particular device.

> Also; currently they are not showing up in homekit. Might be me. I'm new to homebridge.

Have you used 'Add Accessory' in the home app to add the homebridge bridge into homekit?

**Comment by timmeade** [comment]
I found it..  Was not in default room was somewheres else.

**Comment by bwp91** [comment]
Ah good. i hope you get some use from the plugin!

I don't know much about the outlets, how well they stay connected to wifi, if you ever try to control it through homekit and it doesn't work, it's most likely due to the device not being connected to wifi at the time that the command was sent.

I am pretty sure these devices don't have a way of being controlled locally... but if you find a way do let me know!

🙏

**Comment by timmeade** [comment]
Will do.  these appear to work better than wemo but we shall see.

I have some phillips hue plugs coming today.   They are thread so very interested in testing them.

Good work.

Much thanks

**Comment by bwp91** [comment]
Do you use the wemo plugin?

**Comment by timmeade** [comment]
Yes.   also have the wemo bridge.  Neither seems to keep the plugs online in homekit.    They go in and out constantly

**Comment by bwp91** [comment]
Are your wemo devices on the same network /vlan as your homebridge instance?

**Comment by timmeade** [comment]
Solid question.  I had not really considered.    But we do run multiple wifi networks and vlans.  i will have to dig further.  I think they were setup on same but not 100% certain.

**Comment by bwp91** [comment]
I'm ironically just working on an update for wemo plugin now.
trying to get the connections a little bit more stable

**Comment by timmeade** [comment]
More than happy to test.   I have multiple light switches and plugs.    Even if on different networks. they are all reachable from each other.  So should work.

Question?  should i unplug the wemo hub?   As i am getting duplicates in a lot of rooms.

**Comment by timmeade** [comment]
Just checked and i did remove the bridge.  Looks like homekit is hitting them direct.   And homebridge is adding a second of the same item.

**Comment by bwp91** [comment]
Some users have said the plugin is more reliable then the wemo hub. Try it i guess.

The connection method that both the plugin and the hub use can be unreliable when devices are on different sub networks.

You can install the beta of the homebridge-wemo plugin, create entries for your devices in the settings and set the “Listener Type” to “HTTP” (not UPnP).

You should find this works better for devices if on different networks

**Comment by timmeade** [comment]
OK I'll try that later.    Really not sure on the create entries.  Any way to automate that at a later time?  I dont mind trying for testing sakes,  but we have a lot of devices.

**Comment by timmeade** [comment]
Well could not resist. updatd to new beta and put my worst problem child in http mode.

Would be fantastic if you could just make that change from the my devices tab instead of having to copy/paste serial number.  

I'll let you know on results.  Should i open new issue?  We are very off topic on this one now.

**Comment by bwp91** [comment]
> We are very off topic on this one now.

Probably for the better. I have been thinking this too!

**Comment by devins-07** [comment]
> This may be event:
> 
> ```
> [8/5/2021, 8:12:28 AM] [Govee] [Sony 4600] has been reported [offline] via API, so update may or may not be successful.
> [8/5/2021, 8:12:28 AM] [Govee] [Sony 4600] not sending AWS update as not connected to AWS at connectionAWS.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/aws.js:106:13).
> [8/5/2021, 8:12:28 AM] [Govee] [Sony 4600] reverting to API as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1020:17.
> [8/5/2021, 8:12:28 AM] [Govee] [Sony 4600] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1020:17.
> ```

I'm not sure if this is related to my issue right here, [https://github.com/bwp91/homebridge-govee/issues/94](url)
but I'm having the same issue where it says 
[8/5/2021, 8:11:01 AM] [Govee] [Sony 4600] [AWS] reconnect event
[8/5/2021, 8:11:01 AM] [Govee] [Desk Plug] [AWS] offline event.
[8/5/2021, 8:11:01 AM] [Govee] [Desk Plug] [AWS] close event.
[8/5/2021, 8:11:01 AM] [Govee] [Sony 4600] [AWS] connected event.
I'm sure its due to the wifi but I'm confused as to why because i have the router no further than 10 feet away from the govee lights and the raspberrypi connected over Ethernet.
