### ISSUE TITLE
Issue with H5075 temp/humidity readings

### ISSUE THREAD

**Issue by chadderwick** [bwp91/homebridge-govee#958]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?
* Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
1.85

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
* Raspberry Pi
* Node.js 22.11.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
I'm a new user and using version 10.12.1

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
* H5075

### Please paste any relevant logs below.

There are no errors, but the temperature and humidity readings are incorrect
```

```

**Comment by chadderwick** [comment]
The below plugin does pull the temp/humidity correctly, but hoping to have a single plugin

homebridge-plugin-govee
asednev

**Comment by DasHutch** [comment]
I’m seeing similar issues with homebridge not sending the updated temp/humidity to HomeKit. In Govee app it’s working as intended but my automations are failing as it has an outdated humidity value

**Comment by chadderwick** [comment]
I actually think the issue may have been that I had govee app opened....I closed app to disconnect from bluetooth and seems fine now
