### ISSUE TITLE
Plugin not working after 4.3.0 update

### ISSUE THREAD

**Issue by nylonshah** [bwp91/homebridge-govee#97]
### What issue do you have? Please be as thorough and explicit as possible.
After the 2021-08-05 (v4.3.0) update, the plugin is unable to install. Also when trying to update, the plugin uninstalls. The log cites "ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-govee' -> '/usr/local/lib/node_modules/.homebridge-govee-4xHIsKEi'".

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

(1) Homebridge UI-X 

* Which version of Homebridge/HOOBS do you have?
v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 3. Node.js v14.17.4. NPM v7.20.3

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

v4.3.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6159

### Please paste any relevant logs below.

```
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-govee
npm ERR! dest /usr/local/lib/node_modules/.homebridge-govee-4xHIsKEi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-govee' -> '/usr/local/lib/node_modules/.homebridge-govee-4xHIsKEi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-08-08T03_07_47_856Z-debug.log
```

**Comment by bwp91** [comment]
Hi, looks like some npm error, you may need to delete the plugin files manually and reinstall.

Try these commands in the terminal;

```
sudo rm -rf /usr/local/lib/node_modules/homebridge-govee
```

```
sudo npm i -g homebridge-govee
```
