### ISSUE TITLE
H5051 not being detected

### ISSUE THREAD

**Issue by Dekryptid** [bwp91/homebridge-govee#98]
What issue do you have? Please be as thorough and explicit as possible.
Just installed an H5051. Works fine from the Govee App.

Details of your setup.
Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?
HOOBS

Which version of Homebridge/HOOBS do you have?
HOOBS v4

Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 4B+

Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v4.3.0

Which Govee devices do you have that are causing issues? Please include product models if applicable.
H5051

Please paste any relevant logs below.
I see this in the logs: Says please open a github issue:
`
8/8/2021, 4:47:33 PMGovee Bridge starting
8/8/2021, 4:47:35 PMGovee BridgeLoaded plugin 'homebridge-govee'
8/8/2021, 4:47:35 PMGovee BridgeLoading 1 platforms...
8/8/2021, 4:47:35 PMGovee BridgeGoveeInitialising plugin v4.3.0 | Node v14.17.4 | HB v1.3.4 | HOOBS v4...
8/8/2021, 4:47:35 PMGovee BridgeGoveePlugin initialised. Setting up accessories....
8/8/2021, 4:47:36 PMGovee BridgeBridge is running on port 52826.
8/8/2021, 4:47:36 PMGovee BridgeGoveeWARNINGDisabling BLE client as no enabled devices configured.
8/8/2021, 4:47:36 PMGovee BridgeGoveeWARNING[Kitchen] is not currently supported, do create a Github issue with the following info:
`
`{
    "device": "84:B0:E3:60:59:42:68:18",
    "deviceName": "Kitchen",
    "model": "H5051",
    "httpInfo": {
        "device": "84:B0:E3:60:59:42:68:18",
        "sku": "H5051",
        "spec": "",
        "versionHard": "1.03.00",
        "versionSoft": "1.04.04",
        "deviceName": "Kitchen",
        "deviceExt": {
            "deviceSettings": "{\"temMin\":-2000,\"temMax\":6000,\"temWarning\":false,\"fahOpen\":false,\"temCali\":0,\"humMin\":0,\"humMax\":10000,\"humWarning\":false,\"humCali\":0,\"netWaring\":true,\"uploadRate\":10,\"battery\":91,\"wifiLevel\":0,\"bleName\":\"Govee_H5051_6818\",\"address\":\"E3:60:59:42:68:18\",\"secretCode\":\"D973D711D5AFD34D\",\"sku\":\"H5051\",\"device\":\"84:B0:E3:60:59:42:68:18\",\"deviceName\":\"Kitchen\",\"versionHard\":\"1.03.00\",\"versionSoft\":\"1.04.04\"}",
            "lastDeviceData": "{\"online\":true,\"tem\":2179,\"hum\":4573,\"lastTime\":1628455080000,\"avgDayTem\":2179,\"avgDayHum\":4573}",
            "extResources": "{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/f8f5045355d933ef5d66ca39b3d43e06-add_list_type_device_5051.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"
        },
        "goodsType": 0
    },
    "isAPIDevice": false
}`

**Comment by bwp91** [comment]
Hi @Dekryptid 

Please update to v4.4.0 of the plugin, this device should then appear in your homebridge/hoobs!

Thanks
