### ISSUE TITLE
H6144 39% Brightness

### ISSUE THREAD

**Issue by gradyg21** [bwp91/homebridge-govee#99]
### What issue do you have? Please be as thorough and explicit as possible.

Same issue that others have reported. My H6144 is having the 0-39% brightness bug, showing no response trying to set higher than that. 39% represents 100%. Everything is up to date, and I have tried the beta as well without success. I see in the issues that you have been able to fix this for other models, including the H6054 (which I have, and brightness works properly).

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

I'm using Homebridge with the UI.

* Which version of Homebridge/HOOBS do you have?

Reporting Up to Date, 1.3.4.

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Homebridge is running off my 2014 Mac Mini. Node.js is the latest 14.17.4m and Npm is 6.14.14.

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

Tried both 4.4.0, and 4.4.1 beta, both with the same problem. This has been the cause since I got the lights a few weeks ago.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

The 2*5m RGBIC strip, which is the H6144.

### Please paste any relevant logs below.

```
[8/9/2021, 2:25:45 PM] [Govee] [H6144_A009] not sending AWS update as not available or enabled.
[8/9/2021, 2:25:45 PM] [Govee] [H6144_A009] reverting to API as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1020:17.
[8/9/2021, 2:25:45 PM] [Govee] [H6144_A009] [API] sending update {"name":"brightness","value":229}.
[8/9/2021, 2:25:45 PM] [Govee] [H6144_A009] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15)
```

Thank you for all the great work. You've saved me a lot of cash I would have had to give to Philips if this plugin didn't exist.

**Comment by bwp91** [comment]
Can you try 4.4.1-beta.0 of the plugin?

The H6144 was already in a sub-list of models that seem to report brightness [0, 254] rather than [0, 100]. I have removed it from the list to see if it works properly again. I can't seem to find the issue/reason why it was in this list. Perhaps it doesn't need to be there anymore.

**Comment by gradyg21** [comment]
Yep, all working properly. I ordered the H6143 that arrived today, so I can confirm those work properly too. It's pretty cool how things show up in Homebridge and Homekit automatically after adding them to the Govee app. Thank you for this great plugin!

**Comment by bwp91** [comment]
Ah glad it’s working 🙂
